### ISSUE TITLE
Add agency to SR popup

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#1012]
# Description

If an SR has a handling agency assigned, add agency to SR popup window with link to agency website.

## Action Items

- [x] Fetch agencies from `/agencies` on pageload.
- [x] Add agency name/website link to SR popup window.
- [x] Add source to SR popup.

## Resources
response from `/requests/1174673`

{
"requestId": 1174673,
"srnumber": "1-1584096961",
"councilId": 58,
"councilName": "Mid City West",
"typeId": 6,
"typeName": "Illegal Dumping",
"agencyId": 2,
"agencyName": "Sanitation Bureau",
"createdDate": "2020-03-25",
"closedDate": null,
"address": "8670 W BURTON WAY, 90048",
"latitude": 34.0720201513,
"longitude": -118.381076886
}

**Comment by mattyweb** [comment]
Should probably have source in there too. Might want to do it in this ticket while you're working on agency.
