### ISSUE TITLE
[BUG] Sticky footer on reports page (Chrome)

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#1018]
**Describe the bug**
Footer sticks to bottom of iframe after scrolling to bottom of reports dashboard.

**To Reproduce**
1. Go to dev.311-data.org
2. Click on Reports
3. Choose any report
4. Scroll to bottom of page
5. Scroll up

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mattyweb** [comment]
This is semi-fixed. Removing the min-height and the absolute positioning seemed to have fixed it in most places. However, the map currently doesn't show the footer at all.
