### ISSUE TITLE
Create reports out of API endpoints 

### ISSUE THREAD

**Issue by captain-nimo** [hackforla/311-data#1030]
### Overview
We need to ideate and create reports for UX testing with 311-data customers to determine value of specific kinds of data analysis.

### Action Items
- [ ] Grab data from API endpoints 
- [ ] Wrangle (cleaning and reorganizing) the data
- [ ] Generate report

### Resources
[Includes all the useful endpoints to extract the data](https://dev-api.311-data.org/docs#/default/get_all_service_requests_requests_get)

**Comment by captain-nimo** [comment]
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by AdelSadro** [comment]
Some new dashboards are created here:
https://colab.research.google.com/drive/1u3yhuYCiAJ6Vw4c4B7D9sdw7ObF7hAbC

**Comment by AdelSadro** [comment]
Hi @pras4u - The latest version of the reports and dashboards are shared here:
https://drive.google.com/drive/folders/1bUmwMWG8Im_S8__wIpIScT8q6D5Wf4Vz?usp=sharing
I appreciate it if you give me feedback on this. Thank you.

**Comment by KarinaLopez19** [comment]
Google Colab ([installation tutorial linked here](https://docs.google.com/document/d/1r3hM4eEWvckeX1qk5n_LVwGIEi5S3X_6oz2tenn5jus/edit?usp=sharing)) that can be used to view and share feedback on reports

**Comment by pras4u** [comment]
@AdelSadro Refer our review couple of weeks back & my comments on the sheet. Please let me know in case of questions.

**Comment by EchoProject** [comment]
@pras4u can you provide insights into whether this Issue was completed or if we still need to move this into development?

**Comment by nichhk** [comment]
I'm not quite sure how this is different from our existing dashboards, which already get their data from the API endpoints.

I'm closing this for now.
