### ISSUE TITLE
Recruiting New UI Designers 

### ISSUE THREAD

**Issue by danarchen** [hackforla/311-data#1031]
### Overview
The 311 Data project is in need of one or more UI designers.

### Action Items

- [x] Attend UX/UI meeting to recruit UI designers
- [x] Walk them through current UX/UI issues on Github

**Comment by danarchen** [comment]
Attended 03/22's UXUI meeting and recruited a new UI designer. She will be onboarded tomorrow with @kevindperez. We will attend again next Monday's to see if we can recruit more, if not attend Tuesday's onboarding around 7 to recruit directly!

**Comment by danarchen** [comment]
UX/UI designers: Dhwani and Sim were successfully onboarded.

**Comment by danarchen** [comment]
Will be onboarding Elizabeth either tonight (3/31) or tomorrow.
New UX team: Nina, Sim, Dhwani, Liah, and Sharifa.

**Comment by kevindperez** [comment]
Everyone has been onboarded as of 4/4/21.
