### ISSUE TITLE
[Planning] Look at refreshes to data access stack

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#1035]
None of this is especially urgent but there are a few things to track with out data access stack. Using this ticket as a way to keep an eye on them.

The biggest issue is probably with async access to Redis. The maintainer of aioredis seems to have been replaced and that project is taking a new architecture direction. These are probably good changes, but who knows how long they will take to play out. In the meantime, we are pinned to Python 3.7 and Redis 5 due to the caching libraries. Not a big deal at the moment, but eventually this could become a problem.

At some point, we'll likely want to replace GINO for async PostgreSql access. It looks like encode/databases is gaining traction and that should be an easy swap given both use SQL Alchemy Core for queries. I don't expect any improvements as a result but encode/databases is likely to be better supported. BTW, SQL Alchemy itself is supposedly getting async support in version 14, but my gut tells me that won't be our best choice.

Lastly, we should look at whether a new ORM like ormar or Tortoise ORM could be helpful.

**Comment by EchoProject** [comment]
@adamkendis  Are the technologies APIs to build the product? How should label this Issue?
