### ISSUE TITLE
Style Contact Us form

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#1048]
# Description

The webform on the Contact Us page has transitioned to a hosted Formspree form. Following new Contact Us page mockup (#962), the form will need to be styled.

## Action Items

- [ ] Confirm new Contact Us page design.
- [ ] Style form to match new design.

**Comment by Rishabhraghwendra18** [comment]
Hi @adamkendis  May I work on this issue ? 😃

**Comment by adamkendis** [comment]
Hi @Rishabhraghwendra18 ! It looks like the new design for the `Contact Us` page (#962) is in progress and not ready for frontend yet. If you're looking for some frontend tickets to work on, message me on Slack (@ Adam Kendis) and we can connect to get you started. Thanks!

**Comment by Rishabhraghwendra18** [comment]
@adamkendis ok..no problem

**Comment by ExperimentsInHonesty** [comment]
@ezhou0  Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@ezhou0 Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by edwinjue** [comment]
Contact form has been redesigned per  “Finalized Designs as of 9/20” at the very bottom of “[Version 2_Iterations](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1009%3A1004)”
