### ISSUE TITLE
List all the inactive `311-data` slack channels and archive them

### ISSUE THREAD

**Issue by captain-nimo** [hackforla/311-data#1055]
### Overview

There are so many `311-data` channels in slack. We don't use most of them anymore. We need to list all the inactive channels and archive them.

### Action Items
- [x] List all the 311 slack channels
- [x] check off all the inactive (`311-data`) slack channels on the list below - Mahmudul
- [x] Save the list of people on the channels to a spreadsheet - bonnie
- [x] Archive the inactive slack channels - bonnie

### Resources

<details>
<summary>List of 311 slack channels</summary>

311-data
311-data-uiux
311-data-backend
311-data-environment-prod
311-data-analysis
311-data-outreach
311-data-dev
311-data-qa
311-data-ml
311-data-devops
311-data-performance
311-data-architecture
311-data-product
311-data-reports
311-data-team-leads
</details>

<details>
<summary>List of 311 inactive slack channels</summary>

inactive channels are marked with checks
- [ ] 311-data
- [ ] 311-data-uiux
- [x] 311-data-backend
- [x] 311-data-environment-prod
- [ ] 311-data-analysis
- [x] 311-data-outreach
- [ ] 311-data-dev
- [x] 311-data-qa
- [x] 311-data-ml
- [x] 311-data-devops
- [x] 311-data-performance
- [x] 311-data-architecture
- [x] 311-data-product 
- [x] 311-data-reports
- [ ] 311-data-team-leads 

</details>

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2021-03-25 at 6 37 01 PM](https://user-images.githubusercontent.com/37763229/112571214-d5706d00-8da4-11eb-943c-8f4ff106e0c3.png)

**Comment by captain-nimo** [comment]
@ExperimentsInHonesty, I've checked out all the inactive channels in the description.

**Comment by captain-nimo** [comment]
@captain-nimo will give draft message.

**Comment by captain-nimo** [comment]
Please find the list of all people in the inactive channels are in following spreadsheet.

https://docs.google.com/spreadsheets/d/1ytzXsoGrZJ76-AR-I8opZf3P7sI6ExK6VLkiF_lx3AA/edit?usp=sharing

**Comment by captain-nimo** [comment]
The draft message could be `Since the this channel is inactive, we're archiving the channel. Please let us know if the channel is needed in future.`
