### ISSUE TITLE
Update the Wiki 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/311-data#1056]
### Dependency
- Wiki updating can begin once #1132 Google Drive Migration is complete and Onboarding documents have been confirmed with Team Leads. 
   - While #1132 is complete enough to begin processing current documents for completeness  

### Description
We need to update the Wiki, so that new team members can have all the necessary information to get started as soon as they can. 

### Action Items
- [x] Identify/Align on what areas of the wiki need to be updated/refreshed & set deadlines. 
- [x] Complete the first pass of proposed changes.
- [ ] Get Bonnie to sign off on proposed changes and update the Wiki. 

### Resources
- #1407 
- [Current Wiki ](https://github.com/hackforla/311-data/wiki)

**Comment by ahdithebomb** [comment]
@ExperimentsInHonesty will share links to the example wikis here.

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/.github is where the new default wiki is
Some good examples are: 
[Civic Tech Index](https://github.com/civictechindex/CTI-website-frontend/wiki)
[100 Automations](https://github.com/100Automations/website/wiki)

**Comment by ahdithebomb** [comment]
Update: Nothing to share at this point
Blockers: Work, hackathon last week 
ETA: I will ping relevant stakeholders this week and circle back with a list of areas that need to be refreshed  for the next meeting

**Comment by ahdithebomb** [comment]
Update: Nothing to share at this point
Blockers:  End of Quarter Work/Interviews 
ETA: I need to follow up with some key stakeholders to see what needs to be updated for the wiki by end of next week.

**Comment by captain-nimo** [comment]
@ahdithebomb,
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by EchoProject** [comment]
Making a note to include Peer Review process: 
1. Two devs to PR a pull request before Sr. Dev review. 
2. A dev may submit a review if they have completed an issue of the same size (i.e. size pt1 can be reviewed by any dev, pt2 can be reviewed by devs that have completed at least a pt2, once completing pt8 can review all others). 
3. Add screenshots and videos to pull request comments.

**Comment by EchoProject** [comment]
I'll be creating a Sheet to list current Wiki title pages with their descriptions to narrow or widen the scope from which to begin processing relevant material.

**Comment by EchoProject** [comment]
Completed compiling page tree and description to [this Google Sheet] (https://docs.google.com/spreadsheets/d/1kKnTjLAlVe6fJ0QxvhqcaY5s2JIihn5asc6o7PZbGr4/edit#gid=0).

**Comment by EchoProject** [comment]
Use this [Wiki page](https://github.com/hackforla/guides/wiki/Joining-the-Team) as a guide.

**Comment by EchoProject** [comment]
Reviving this issue. 
Next steps: 
- [ ] Delete blank pages from Wiki
- [ ] Inventory broken links 
- [ ] Draft topology of relevant pages and note information we'll need to provide successful onboarding

**Comment by EchoProject** [comment]
Met with Elizabeth and Melissa to discuss design onboarding improvements [tied to this issue](https://github.com/hackforla/311-data/issues/1201).
