### ISSUE TITLE
Consolidate Data analysis branch and merge to dev

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#106]
### Overview
Take a look through the dataAnalysis branch and remove all non-essentials
Also consolidate existing functions/scripts into one unified class 

This will support bringing the cleaning script into the backend server

**Comment by ryanmswan** [comment]
I think we've got this one closed now, yeah?

**Comment by sellnat77** [comment]
This is done @sellnat77 Should have closed this!!!! Dangit @sellnat77 !!
