### ISSUE TITLE
Use Type colors in Dash reports

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#1064]
# Description

There are colors specified for Types in the 311 Data API. Currently, there is a standard palate used for all Dash reports.

The goal is to use the color for each Type in Dash reports so this is consistent everywhere.

**Comment by captain-nimo** [comment]
@mattyweb, if you think this issue still needs to be addressed. Could you please confirm whether it's UI/UX or Frontend?

**Comment by mattyweb** [comment]
It's mine. I'm not sure how to assign colors to a series but I'm sure there's a way to do it. The colors are already in the API. I just need to pull them and assign them to the charts.

**Comment by chelseybeck** [comment]
I agree that this should be updated, so I'm keeping it open and assigning it to myself for now.

**Comment by EchoProject** [comment]
@chelseybeck 
Please update: 
1. Progress:
2. Blockers: 
3. Availability:
4. ETA:

**Comment by EchoProject** [comment]
@joshuayhwu, when you have time, can you look into this Issue?

**Comment by joshuayhwu** [comment]
Below are the color mappings based on the request types listed on the API (note that Multiple Streetlights and WaterWaste has same color), which I define as DISCRETE_COLORS_MAP dictionary in the design.py file. For all visualizations that involve requestTypes, simply add the color_discrete_map=DISCRETE_COLORS_MAP argument in the plotly express visualizations.

DISCRETE_COLORS_MAP = {
    "Graffiti":"#BF82BA",
    "Homeless Encampment":"#11975F",
    "Animal Remains":"#267370",
    "Bulky Items": "#D05F4E",
    "Electronic Waste": "#AE3D51",
    "Illegal Dumping": "#685DB1",
    "Metal/Appliances": "#8B508B",
    "Single Streetlight": "#79B74E",
    "Multiple Streetlights": "#EDAD08",
    "Water Waste": "#EDAD08",
     "Other": "#1D6996",
     "Feedback":  "#E17C05"
}

# TODO: 
- Add additional discrete color to differentiate Multiple Streetlights with Water Waste
-Add color_discrete_map to all visualizations involving request types
