### ISSUE TITLE
Create Google Form for identifying onboarding pain points

### ISSUE THREAD

**Issue by dplem** [hackforla/311-data#1070]
### Overview
Create Google Form for identifying onboarding pain points in relation to the data analyst and data scientist journey

### Action Items
Submit for Bonnie to review.

**Comment by dplem** [comment]
Here is the first draft of the Google form to identify onboarding pain points: https://docs.google.com/forms/d/e/1FAIpQLSexa0ZZ6UihIN95cxzcIYcggsig6YBidW79cVlJ3aHJq5FPuw/viewform

**Comment by dplem** [comment]
@bonnie @mattyweb thoughts on the google form?

**Comment by captain-nimo** [comment]
Form will need to have 311 look and feel.
Here's the figma link: https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A5

**Comment by pras4u** [comment]
Reassigning to @dplem ; please review & close if complete
