### ISSUE TITLE
Setup 311Data Arcgis account & support Echo Park

### ISSUE THREAD

**Issue by pras4u** [hackforla/311-data#1092]
Echo Park Illegal Dumping for 2019

Last comment - 'shoot, it says the data set is too large to import into arcgis free version and that i'd have to upgrade.'

**Comment by pras4u** [comment]
Worked with Admin to create a 311Data Arcgis account
Created a pwd & added credentials to 1password
Next Steps - Test large imports into arcgis & communicate to NC

**Comment by dplem** [comment]
Uploaded 2019 and 2020 Echo Park Illegal dumping files to arcgis.com.

2019: https://lahubcom.maps.arcgis.com/home/item.html?id=95b900cec72d4da1b64290d81ecd3d9c
2020: https://lahubcom.maps.arcgis.com/home/item.html?id=11b54d0089594c75baad36ae8e881bcb

**Comment by ExperimentsInHonesty** [comment]
Follow up with everyone involved to find out if this was helpful for them.

**Comment by EchoProject** [comment]
Next steps:
1. Interview Pras 
2. Write up a history of this service delivery
3. Make a research plan
