### ISSUE TITLE
[FUTURE] [FEAT] Add a "stuck" service request indicator for things that have been open a long time

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#1094]
### Dependency
This Issue can be addressed post v2 for feasibility if the SR resolutions are still over due. 

### Overview
Browsing through the pins I'm seeing a few SRs that have been open for more than a year(!). I think it would be helpful to have some kind of indicator to highlight these issues for council members so they can follow up with the city on them.

For instance, the "stuck" pin could have a solid border around it. Maybe even a red one. We could also have an indicator in the popup.

![image](https://user-images.githubusercontent.com/10199792/117083476-a3ceb800-acf9-11eb-8733-1c639b17481b.png)

Alternatively or in addition we could add a report for these "stuck" items.

### Resources
There are a few options for styling the circles programmatically. Border color, width are some. Also the circle size could change.
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-stroke-color

**Comment by EchoProject** [comment]
Adding this Issue to items for review for the product roadmap.
