### ISSUE TITLE
ArcGis Data Exploration and Report

### ISSUE THREAD

**Issue by dplem** [hackforla/311-data#1097]
# Description

Use Illegal dumping, homeless encampments, elementary schools location data in Echo Park to perform data exploration, visualization and provide a report to stakeholders.

## Action Items

1. Import csv datasets
2. Data Exploration
3. Data Visualization
4. Build report in Storymap (arcgis)

**Comment by dplem** [comment]
Created ArcGis folder in 311-data Google Drive: [link](https://drive.google.com/drive/folders/11-mShAm8zVeQtJWcFeEGCv_39YbTW6OX?usp=sharing)

**Comment by dplem** [comment]
Storymap Report: [link](https://drive.google.com/file/d/1HED0fTM4FKiNS906_RM5DFJC-tZvT0ky/view?usp=sharing)

**Comment by pras4u** [comment]
@dplem please share the PDF in 311-data slack channel & request feedback

**Comment by pras4u** [comment]
@dplem @pras4u  Continue to work on developing additional data insights.

**Comment by pras4u** [comment]
The report created by Derek will be used for any future custom data requests from NCs as a reference.
