### ISSUE TITLE
Update screenshots in FAQ

### ISSUE THREAD

**Issue by elizabeth-ux** [hackforla/311-data#1112]
### Dependencies:
Dependency: v2 needs to be completed before FAQ can be completed.

https://github.com/hackforla/311-data/projects/10?card_filter_query=milestone%3A%22initial+v2+launch%22

Update screenshots for "How do I search for 311 requests in my Neighborhood Council?" in FAQ once filter look is finalized. 

**Special note**
When this page is live in the development environment take new screenshots and do another mockup of the drop downs and any questions... this will also be informed by the UX research comments. #848

**Resources**
https://311-data.org/faq

**Comment by edwinjue** [comment]
@elizabeth-ux hope all is well! Here is the latest FAQ in dev. The search functionality is still being implemented but we have the UI design implemented according to the v2 design. Please let me know if there is anything else you need from us to resume your work. Thanks!

![image](https://user-images.githubusercontent.com/1448719/220056705-ea070aa4-d31d-4d04-a2c2-07d27fb51924.png)
