### ISSUE TITLE
Routing, shareable URL

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#1115]
# Description

- [x] Add Submit control (modal on filter change)
- [x] Add query string to url on query submit. 
`?ncid=1&rid=1,2,3,4,5&open=true&closed=false`
- [x] Add 'share' icon to map page for copying shareable url.
- [x] Fix routing for charts dashboards to allow direct linking to each dashboard.

**Comment by adamkendis** [comment]
Status: Working on query string builder for shareable url.
ETA: Saturday 6/18
Blockers: None

**Comment by adamkendis** [comment]
Status: Completed all except dashboards routes.
Blockers: Was in Yosemite all last week, started new fulltime job this week.
ETA: Will 100% be completed over the weekend.

**Comment by adamkendis** [comment]
Completed all except routing for charts dashboards. Per meeting with @dhwanirparekh and @elizabeth-ux , reports dashboards/charts will be reviewed to determine which (if any) should be eliminated, re-ordering the charts on page and possibly moving some around to different dashboards. Since the dashboard urls are currently hardcoded, the reports routing will be done after finalizing reports UI/UX work.

**Comment by ExperimentsInHonesty** [comment]
@adamkendis Is is possible to create a markdown or YAML file where we list out all the routes and the application looks to that file?

**Comment by adamkendis** [comment]
I have an in progress branch. Will push it up and pull in another dev to complete if I'm not able to in the next week or two.

**Comment by adamkendis** [comment]
Update: Going to hold on to this ticket for now. My in-progress branch would need a ton of cleanup for a new dev to easily pick it up. Will be able to finish and push this feature before Christmas.

**Comment by adamkendis** [comment]
Update: same as last week!

**Comment by ExperimentsInHonesty** [comment]
@adamkendis Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@adamkendis Please provide update
Progress
Blockers
Availability
ETA
