### ISSUE TITLE
311-data report improvements

### ISSUE THREAD

**Issue by KarinaLopez19** [hackforla/311-data#1117]
# Description
Improving existing data reports to make them more accessible and meaningful to users.

## Action Items
- [ ] Review existing reports and identify pain-points for users less comfortable with data (e.g., Add plot descriptions)
- [ ] Identify points of improvements to make plots more meaningful to different audiences (e.g., features helpful for neighborhood council members, neighbor, activist)
- [ ] Prototype Plotly reports following these suggestions
- [ ] Review final reports and publish on website

## Resources
- [Slide deck offering quick improvement suggestions](https://docs.google.com/presentation/d/1kMykDmM4MDj_7sSyJg1R5VUyKoI3l-HFFJgLTBpYQSg/edit?usp=sharing)
- [Brainstorming notes](https://docs.google.com/document/d/14WBvmiXpCVuLPYd6OSFnuqgDtRyzfafNMc7GlqRELJk/edit?usp=sharing)
- [Existing Plotly reports](https://drive.google.com/drive/folders/1P-uID8FpnqwvYlUmzWsmgU4pxRSeb72z?usp=sharing)
- [Plotly gallery](https://dash-gallery.plotly.host/Portal/)
- [Storage for Matt Recordings](https://drive.google.com/drive/folders/1ZjNujQX0v6EHljiyuoHbWirKv6ImDtxN)

**Comment by KarinaLopez19** [comment]
Assigned issue to @chelseybeck. [Here](https://docs.google.com/document/d/1fNIxKJl91YZ_b6PRvKMdyd7tXJwWbfGIAJ5VTfe8Jow/edit?usp=sharing) is the onboarding data science document for the 311 project. Under the resources section of this issue, you will also find a slide deck and notes that may be helpful to review.

**Comment by chelseybeck** [comment]
Reaching out to Matt Webster to review prototypes and will update when more info becomes available.

**Comment by captain-nimo** [comment]
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by chelseybeck** [comment]
Still in research phase and am improving documentation of the process so that entry level data analysts can easily onboard to this project.

**Comment by captain-nimo** [comment]
@chelseybeck, can you please add the size of the ticket?
https://github.com/hackforla/311-data/labels?q=size

**Comment by chelseybeck** [comment]
Working w/ @KarinaLopez19 to update documentation

**Comment by chelseybeck** [comment]
Review existing reports and identify pain points for users less comfortable with data.

# Recommendations

- [ ] include a high-level description for each report page (e.g., The below charts represent 311 requests over the past 30 days. Charts are interactive. Hover over the data points for more information. Select or deselect request types by clicking on them in the legend.
- [ ] include a high-level description for each figure (e.g., This visualization represents the volume of 311-requests per neighborhood from 2016-2020.)

## Pages

### [Overview](https://dev.311-data.org/reports/dashboards/overview)
- [ ] Remove bottom graph of total requests by neighborhood until we can add population/housing data. Empower LA has [data on housing units](https://empowerla.org/data/) that would probably work well. We should explore tapping into that. The issue with leaving the bar graph up without population data is that the number of housing units per neighborhood council varies from around 6k to more than 20k.

**Comment by chelseybeck** [comment]
# Identify points of improvements to make plots more meaningful to different audiences

**Comment by chelseybeck** [comment]
@ExperimentsInHonesty - no. I'm breaking this down into multiple issues for the data science team so I need to move everything over before I close. Will be done tonight.
