### ISSUE TITLE
User Testing Feedback

### ISSUE THREAD

**Issue by dhwanirparekh** [hackforla/311-data#1120]
### Overview
We need to create issues for front end and UI/UX from the user feedback

### Action Items
- [ ]  Issues that need to be made front end
   - [ ] Make Selector responsive
      - [ ] The selector box was clipped for me on my 13" screen and there was no way to scroll down the page or the selector box, so I had to resize in my browser to get the full controls.
   - [ ] Change selection default and options
      - [ ] Would also be nice to have the ability to select one request type or deselect all (or start uninitialized with a select all option) since I know users like to look at one specific request type at a time more often than all requests simultaneously.
<img width="503" alt="Point_2" src="https://user-images.githubusercontent.com/38696871/125009325-f8f4b600-e029-11eb-95eb-6f52e6ecf939.png">

- [ ] When I try to select a "date range" with the calendar feature, it overlaps with the "request type" and makes it hard to read and navigate.
![Point_3](https://user-images.githubusercontent.com/38696871/125009344-027e1e00-e02a-11eb-82c4-3343ab6ce9dc.png)

- [ ]  Issues that need to be made UI/UX
4) I'm not entirely sure about requirements for a muted text that is not highlighted, but I believe FILTERS needs greater contrast to meet tier 2 standards, as does the Council tab! Most of the text seems okay but I'd still run it past a color contrast checker to make sure since there are a lot of greys used. Medium grey tones are often tricky as a backdrop to text!
5) When hovering over the navigation bar on top of the page, it is difficult to see the hover color when the mouse hovers over the text due to the lack of color contrast.
<img width="581" alt="Point_5" src="https://user-images.githubusercontent.com/38696871/125009362-0a3dc280-e02a-11eb-945b-940874bcf75f.png">
6) The chartreuse single is indistinguishable from the mint green background on the safari iPhone 7. There's little difference between the homeless green and the single chartreuse. I would suggest using indigo instead. Or heliotrope or bright blue to distinguish it from the animal turquoise. The 10 freeway & Los Angeles icons are covering important data. You could put them in the ocean and further east, respectively. Clipped as shown w no scrolling. Cite which court determined the illegal dumping designation.

![Point_6](https://user-images.githubusercontent.com/38696871/125009379-1164d080-e02a-11eb-9b3e-d8d5f8e5577e.jpg)

**Comment by dhwanirparekh** [comment]
Points 4 & 6 needs action from UI/UX team - has to figure out colors to meet the contrast requirements, rest are for the frontend team

**Comment by EchoProject** [comment]
UX team made issues: 
#1126 
#1128 
#1127

**Comment by EchoProject** [comment]
Hi @adamkendis . Do you need us to make the dev tickets from this issue?
