### ISSUE TITLE
Project Cleanup of extra boards

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/311-data#1125]
### Description
We need to clean up the project management so its easy to understand where we are and what needs to be done next

### Action Items
- [ ] Sort vision board into done and undone columns
   - [ ] review each item in the undone 
      - [ ] determine if there is any related issues
        - [ ] If yes, should we keep the current undone issue or close it
           - [ ] if closing, close with comment to indicate why closing and potentially link to other issue
        - [ ] if no, determine if we want to keep the issue open and flesh it out, or close it.
- [ ] Review all the issues on the NC workshop board with Adam Kendis to learn what happened
   - [ ] decide what to do next 

### Resources
[20200414 - NC Workshop Board](https://github.com/hackforla/311-data/projects/6)
[vision board](https://github.com/hackforla/311-data/projects/8)

**Comment by pras4u** [comment]
Vision board cleaned up; Moved issues to project board; Need to work on the product requirements of individual items when prioritized for a milestone.
