### ISSUE TITLE
Create Current Version Features vs Next Iteration Features

### ISSUE THREAD

**Issue by pras4u** [hackforla/311-data#1131]
List current version features
Compare against next iteration features

WIP Link below

https://docs.google.com/spreadsheets/d/1KWPIoo0skY4I_Xi7bFTPbyjQ6QiyVq4RML_t3IViAqs/edit#gid=0

**Comment by EchoProject** [comment]
Next steps as discussed in meeting: 
"Yes" to any feature already in v2
The issue number if it hasn't been added to v2 
If it's not there and there's no number, then add missing 
If it's in v2 but not in v1 add it to the list of features

**Comment by pras4u** [comment]
Update 1/6/2022 

Progress - WIP
Blockers - None
Availability - No change
ETA - ~2 -3 weeks

**Comment by pras4u** [comment]
Update 1/13/2022

Progress - WIP
Blockers - None
Availability - No change
ETA - ~2 -3 weeks

**Comment by pras4u** [comment]
@EchoProject This is complete. We can review today.

**Comment by pras4u** [comment]
All issues emanating from the v1 & v2 analysis have been created in Project board. Closing this issue.
