### ISSUE TITLE
311-Data Drive Migration

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1132]
### Overview 
We need to move files from My Drive system to the new 311 Shared Drive so we do not lose files when team members leave the project.  

### Action Items 

- [x] Recreate folder structure in new Shared Drive 
- [ ] Reach out to existing PM team (Pras & Bonnie) 
- [x] Add column to roster and add check box to those with files 
- [x] Add column to roster to indicate files have been moved 

### Resources
[311 Roster](https://docs.google.com/spreadsheets/d/1c4pYPX8YgSzkZ4iE8fOG98py56n4umUmlq5FQ40yniI/edit#gid=0) 
[Folder Owner Contact Sheet](https://docs.google.com/spreadsheets/d/1T-B6IVZ0pBrM42ooDrHvCqevF80vt1itiX2vP8aGsI4/edit#gid=0)
[Contact Email Template](https://docs.google.com/document/d/1hyM1MzOoDIJlodjF6FgRTmFedvx6Ou8eA7Ros7c9maA/edit)

**Comment by EchoProject** [comment]
Initial folder recreation has been completed. Get confirmation that all folders exist.

**Comment by EchoProject** [comment]
Columns [Has File Ownership in Google Drive | Google Drive Files Have Been Moved] have been added to the 311-Data team roster and those with files have a checkmark in their cell.

**Comment by EchoProject** [comment]
During folder check with Bonnie, discovered following missing folders:
1. Data Analysis - Users (Adel, Adrianna), Working Files (ArcGis),  
2. UI/UX - Interviews (Past), UX Research (Recordings of Interviews)  
Eric will add folders to new Drive.
https://drive.google.com/drive/folders/1ObUz4mTQmSCwND_WQcOXAuCeKpCwNzmz

**Comment by EchoProject** [comment]
Completed adding missing folders to the [New Shared Google Drive](https://drive.google.com/drive/folders/1ObUz4mTQmSCwND_WQcOXAuCeKpCwNzmz). 
Count of total folders == 34 (as of 2021-09-28). 

Next steps: Reach out to active and inactive team members to move files from the [Old Shared Google Drive](https://drive.google.com/drive/u/2/folders/10_KYe3pbZqiq6reeLA8zDDeIlz-4PxWM) to the new one.

**Comment by ExperimentsInHonesty** [comment]
@EchoProject where is the spreadsheet that details our progress on this?

**Comment by EchoProject** [comment]
[Here is the link](https://docs.google.com/spreadsheets/d/1T-B6IVZ0pBrM42ooDrHvCqevF80vt1itiX2vP8aGsI4/edit#gid=0) to the Google sheet with contact details of file holders. I've also included the link under Resources.

**Comment by EchoProject** [comment]
Bonnie has sent out an email to the remaining contacts that have not completed the file transfer during today's PM meeting.

**Comment by ExperimentsInHonesty** [comment]
I sent this to all today

> Hi.  
> 
> I am sending you this message on behalf of the 311 project.  We need your help moving some files you own.  It will take 5 min or less.  I would be happy to connect with you, and help you do it.   Plus it would just be nice to know what you are up to.
> 
> Bonnie

**Comment by ExperimentsInHonesty** [comment]
Worked with Karina.

**Comment by ExperimentsInHonesty** [comment]
Mon, Jan 10, 3:58 PM
Hi Bonnie,

Thanks for the reminder. I tried to move the file when someone else contacted me about previously, I got an error that said I don’t have access to the file in question. Figured action wasn’t needed after all, but I’ve just requested access. Hope that helps. 

I’m a product designer at Madewell, working remotely from Silver Lake while my team is based in NYC.  

How’s everything with Hack For LA? Hope you’re all doing well!

Rose

**Comment by ExperimentsInHonesty** [comment]
Tue, Jan 11, 8:41 AM 
Hi Bonnie,

Let me know how I can help to move files.

Thank you,
Roberta

**Comment by ExperimentsInHonesty** [comment]
Fri, Jan 14, 4:40 PM
Hey Bonnie,

Happy New Years!

I'd be happy to touch base with you for a couple of minutes sometime next week.

Would Wednesday at 1 pm or 2 pm work for you?

**Comment by ExperimentsInHonesty** [comment]
Next steps are for me to respond and send calendar inivites 
And for us to figure out why rose can't access he own files

**Comment by EchoProject** [comment]
Please update @ExperimentsInHonesty : 
1. Progress:
2. Blockers: 
3. Availability:
4. ETA:

**Comment by EchoProject** [comment]
Closing this issue as the migration has been completed.
