### ISSUE TITLE
Project Issues: Clean Up, Sorting, and Prioritization (311-Data Team or Data Science Team)

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1137]
### Dependency
Dependent on confirming that all required v2 feature issues are in the prioritized backlog and well documented. 

### Description
We need to sort all issues on the Project Board to be within the scope of either the 311-Data team or the Data Science team so we can drive lingering issues that have no current outlet and focus on the prioritization of clearing issues on the Project Board. 

### Action Items 

- [ ] Label issues with "role: data science" for issues within the scope of the Data Science team
- [ ] Confirm with Data Science team the transferred issues list 
- [ ] Confirm sorting label for issues within the scope of the 311-Data team 
- [ ] Prioritize issues within the scope of the 311-Data team and assign task takeovers 

### Resources
https://github.com/hackforla/311-data/projects/10

**Comment by EchoProject** [comment]
Adam will look through Ice Box column and label/ move appropriate Issues.

**Comment by EchoProject** [comment]
- We are tracking missing labels for issues on the project at issue #1134. We need to drive this number down weekly. 
- Issues in the Icebox have dependencies added to them.
- We need to get updates for In Progress column issues weekly.

**Comment by ExperimentsInHonesty** [comment]
next steps
- [ ] review the issues related to plotly dash that might be on the data science repo now
- [ ] find any that are on our repo
- [ ] talk to Chelsey to figure out her status on each and where she has put the documentation

**Comment by ExperimentsInHonesty** [comment]
@alexulven Were you able to reach Chelsey? Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by alexulven** [comment]
Chelsey told me that her other project has taken up a lot of her time. She said she would comment on #699 to answer the question, but she didn't find a way to add a legend to chart exports in plotly. Chelsey think #1064 could be done by updating the plotly configurations, but she doesn't have the time to do it right now.

**Comment by ExperimentsInHonesty** [comment]
@alexulven following up with Chelsey to find out what documentation she has added to project.

**Comment by alexulven** [comment]
The documentation is in this issue in the data science project: https://github.com/hackforla/data-science/issues/126

**Comment by ExperimentsInHonesty** [comment]
We need to take a look at our wiki and the resources Chelsey has provided in issue https://github.com/hackforla/data-science/issues/126 and figure out how we are going to onboard new people 

Dependency on this is if we are going to continue to use plotly
see chelsey resources for this - to help us build out the plotly dash
