### ISSUE TITLE
 Make Selector responsive

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/311-data#1139]
### Overview
We need all selector box feature to be responsive on the website.

### Details
 The selector box was clipped for me on my 13" screen and there was no way to scroll down the page or the selector box, so I had to resize in my browser to get the full controls.

### Action Items
- [ ] Replicate issue
- [ ] Figure out why it not responsive
- [ ] Propose changes
- [ ] Get Approval for Proposed Changes
- [ ] Submit PR

**Comment by EchoProject** [comment]
@nichhk while this specific issue may not be super pressing, we should definitely take screen responsiveness into account during dev. I'm going to close this issue, and I'll make a note to bring this up at the next team meeting to be kept in mind across frontend issues.

**Comment by nichhk** [comment]
Tagging @edwinjue for visibility.
