### ISSUE TITLE
Reports drop down menu

### ISSUE THREAD

**Issue by elizabeth-ux** [hackforla/311-data#1147]
### Overview
We need to update the navigation color scheme to match the rest of the site so that we have consistency.

#### Details
- The dev site at the time of this comment is using the wrong color palette. [This comment](https://github.com/hackforla/311-data/issues/1147#issuecomment-962811934) indicates the correct "dark" color and yellow hover color. The information is also located in Figma. 

### Action Items
Design:
- [x] Change drop down background 
- [x] Change hover colors
- [x] Add screen shot to issue

Development:
- [ ] update the current website with the colors specified in figma

### Resources/Instructions
- https://github.com/hackforla/311-data/issues/1380
- [DesignStudio ](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=2775%3A7702)

**Comment by elizabeth-ux** [comment]
Change the background color on menu dropdown to #0F181F and change hover to yellow underline #FFB100
![Reports Menu](https://user-images.githubusercontent.com/20293568/140686273-88ab4f7c-adea-4713-b916-d045ad5e8ded.png)

**Comment by EchoProject** [comment]
@elizabeth-ux can you provide a link to the Figma where this was worked on? We were trying to see the inconsistency between this and the current state of the dev-site. 

To us, it seems the above background color is more black and the yellow is slightly more orange here.

**Comment by EchoProject** [comment]
The dev site at the time of this comment is using the wrong color palette. The above comment is using the correct "dark" color and yellow hover color and is located in Figma.

**Comment by EchoProject** [comment]
@melissahermes99 can you look into this and double-check we have the correct color information above? Please add in the exact color requirements into the requirements text.

**Comment by EchoProject** [comment]
@melissahermes99 is this issue waiting for dev support? Let @nichhk and I know if this still needs to be implemented or if we can close this issue. I'm adding it to the Design Epic for Map page for now.

**Comment by melissahermes99** [comment]
@EchoProject Yes! This issue still needs to be implemented. We need to change the background color on the reports menu dropdown to #0F181F and change the yellow underline #FFB100. Should I go ahead and make a separate issue for dev? 

![image](https://user-images.githubusercontent.com/97048386/194690095-0dd87721-62c6-4577-a007-e6aebe6601ee.png)
![image](https://user-images.githubusercontent.com/97048386/194690104-f0ebc040-81d4-489e-8860-e1031faede76.png)

**Comment by nichhk** [comment]
Yes, @melissahermes99, please make an issue for dev! Thanks! I will close this issue since the design portion is complete.
