### ISSUE TITLE
NC boundaries not rendering on dev site

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#1154]
### Overview
When visiting dev.311-data.org, the boundaries do not render and the following error is logged in the console. 
`Error {message: 'Input data is not a valid GeoJSON object.'}`

### Action Items
 - Update with valid geojson.

**Comment by EchoProject** [comment]
Hi @adamkendis should we keep this issue in the Icebox, or can we do an issue approval?

**Comment by nichhk** [comment]
This might be related to #1155--in order to do address searching, it seems like we need to be able to get the NC using the latitude and longitude of the address. I will try to fix this first before #1155.

**Comment by nichhk** [comment]
I've checked some of the GeoJSON files in client/v1/data, and they are indeed not valid GeoJSON files. geojsonlint.com points out several issues; however, even after using https://mapstertech.github.io/mapster-right-hand-rule-fixer/ to fix the issues (and now passing the linter), `Error {message: 'Input data is not a valid GeoJSON object.'}` persists.

**Comment by nichhk** [comment]
I see now that the GeoJSON files might be getting [pulled](https://github.com/hackforla/311-data/pull/917) from the server? It is confusing because the client still references GeoJSON files from client/v1/data, but maybe we also need to update the GeoJSON files on the server-side.
