### ISSUE TITLE
Address searching crashes app

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#1155]
### Overview
Address searching crashes app

### How to reproduce bug:
1. Visit dev.311-data.org
2. Enter `1025` in the address search input
3. Select `1025 Venice Blvd`
4. App crashes - see errors in console

### Action Items
- [ ] Reproduce bug
- [ ] Inspect runtime to see what errors it might be throwing, and troubleshoot from there
- [ ] While working on this ticket, also limit the address search just to Los Angeles.

### Resources
https://dev.311-data.org/map

**Comment by adamkendis** [comment]
While working on this ticket, also limit the address search just to Los Angeles.

**Comment by EchoProject** [comment]
@nichhk This is the issue for the search request not working and an additional comment about limiting search parameters to Los Angeles. We may want to consider leaving this open for US address searches in the event we want to expand service request data to other metros.
