### ISSUE TITLE
Update copyright message

### ISSUE THREAD

**Issue by alexulven** [hackforla/311-data#1156]
### Overview
We need to update the copyright message at the bottom of the map to better explain how the map can be used and link to the license.

### Action Items

- [x] Change the copyright message in the footer to the following: "311Data License | Privacy Policy | Powered by volunteers from Hack For LA" 
- [ ] The text 311Data License should link to the license on the wiki: https://github.com/hackforla/311-data/blob/dev/LICENSE. The links for the privacy policy should remain the same.

### Resources/Instructions

**Comment by amnak1284** [comment]
Hi, I would like to work on this.
