### ISSUE TITLE
[FUTURE] Footer tooltip for "Data updated through"

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1160]
### Overview
We need to provide a tooltip for the "Data updated: [date]" item in the footer to provide further explanation of what the date represents to mitigate friction. 

### Action Items
- [x] Write a brief explanation of what the "Data Updated Through" date/time in the footer represent. Specifically we get data from LA City Data Portal automatically and that is when we last refreshed the data.  See FAQ for link to the LA City portal
- [x] Design  tooltip or popup with the explanation text that appears when the user hovers or clicks the date in the footer.

### Resources/Instructions
![Screen Shot 2020-05-19 at 8 12 16 PM](https://user-images.githubusercontent.com/40484278/82400817-11aca180-9a0d-11ea-8b2a-f261321e02af.png)

**Comment by ExperimentsInHonesty** [comment]
@melissahermes99 welcome to the project.  Please specify what your probable ETA is for completion of this issue

**Comment by melissahermes99** [comment]
> @melissahermes99 welcome to the project. Please specify what your probable ETA is for completion of this issue

Thank you! I'm glad to be here! My estimated time of completion is Monday, March 28th. I would like to take some time to look through the project to get a feel for how things are formatted and to gain some understanding of the style guide so I can incorporate this addition well :)

**Comment by melissahermes99** [comment]
![tooltip](https://user-images.githubusercontent.com/97048386/160465626-33251e77-e3fb-4422-94b3-329d4f5cf268.PNG)
This is the tooltip I've come up with for the "Data updated through" footer. It follows the design guidelines and the formatting that Selena has been using. I opted to not include an "x" to close out of the tooltip, rather, it should disappear when a cursor stops hovering.

**Comment by EchoProject** [comment]
I'll create an issue for a front-end ticket to be in the prioritized backlog.

**Comment by EchoProject** [comment]
@nichhk here's another issue that can move to eng for development.  Let us know if you have any questions.

**Comment by nichhk** [comment]
@funbunch, here's another one for you if you're interested!

**Comment by funbunch** [comment]
Got it!

**Comment by mc759** [comment]
Hey @melissahermes99 and @edwinjue! Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by edwinjue** [comment]
@funbunch Hi Shannon, hope all's well. Is this something you're still interested in? Please let @mc759 know at your earliest convenience. Thanks

**Comment by mc759** [comment]
@funbunch I see that the updated date is included on the dev site, can this issue be closed or are there more changes necessary?
