### ISSUE TITLE
Create FAQ page design

### ISSUE THREAD

**Issue by pras4u** [hackforla/311-data#1167]
### Overview
We need the FAQ on the new site to be at least as good as the old FAQ, so that we don't disappoint users by taking away features.

### Action Items
- [x] Refer to the current site FAQ page & understand features
- [x] Review figma to see if there is a design for v2 FAQ 
   - [x] If yes, add link to the figma page below under resources
     - [x] review design and see if you are signing off on it, or it needs changes.  
     - [x] Inform team
   - [ ] If no, Design / update the FAQ page for v2

### Resources/Instructions
[current website FAQ page](https://311-data.org/faq) - also called ```help center``` on menu
[new site under development FAQ page](https://dev.311-data.org/faqs)

[311 Figma](https://www.figma.com/file/VjmU0TCcJf3rPq30bnF17Y/311-Data-Project's-team-library?node-id=0%3A1
)

#### Special note
The new site has an s on the end of the URL, recommend removing that when we go to production so that peoples previous bookmarks still work

**Comment by yibarra15** [comment]
Hi Team, there's a design for [the V2 FAQ page](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=3461%3A0) 

It doesn't need any changes
