### ISSUE TITLE
[CLOSE THIS] Create Accessibility Icon/ Button

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1170]
### Overview
We need to create an Accessibility icon/ button that provides Map, Visualization, Keyboard information so that users have a source to refer to while navigating the website. 

The below images are from the v1 site. As of 2022-02-10, this feature does not exist on v2. 

### Action Items
UI/UX - Design, please provide actions: 
- [ ] 

### Resources/Instructions 
![Snip20220210_19](https://user-images.githubusercontent.com/20729686/153525449-3259d8d5-af2c-4b77-a738-33945dda1999.png)
![Snip20220210_20](https://user-images.githubusercontent.com/20729686/153525666-749f92ae-015b-4a24-afcc-cc835b4aa993.png)

**Comment by melissahermes99** [comment]
The accessibility icon and instruction sheet have been added to the [Version 2_Design Studio on Figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/?node-id=2775%3A7702).

**Comment by EchoProject** [comment]
@nichhk this issue is available for one of the devs to work on when they have time. I imagine this is a quick build. Let us know if there's something you need.

**Comment by nichhk** [comment]
Sweet! @funbunch , does this look interesting to you?

**Comment by funbunch** [comment]
Yes, I think so. Thanks!

**Comment by EchoProject** [comment]
Hey @funbunch! Do you have an update for us on this issue? 
Please update: 
1. Progress:
2. Blockers: 
3. Availability:
4. ETA: 

Thanks!

**Comment by funbunch** [comment]
Hi @EchoProject @melissahermes99 
Just looking back at this now. I do have a few questions if we could discuss! For one the nav menu here in the new design looks different than what I have on dev. I'm not sure if there is a navbar update as well.

**Comment by mc759** [comment]
@melissahermes99 can you [please address @funbunch's questions? Thanks!
