### ISSUE TITLE
Pin Header Navigation For All Pages

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1171]
### Overview
We need to pin the Header Navigation for all pages so that menu options remain visible as a user scrolls down the site. 

### Details
As of 2022-02-10, the Header Nav is only pinned on the Map and Reports (including sub-pages) pages.  And is not pinned on FAQ, Blog, Privacy and Contact pages 

### Action Items
- [ ] Review code and identify the coding differences between the pages where menu is pinned and where it is not
- [ ] Identify a global fix, so that when we add new pages we will not have this issue again.
- [ ] Apply fix
- [ ] Document how it works in the wiki

### Resources/Instructions
![Snip20220210_21](https://user-images.githubusercontent.com/20729686/153526457-34b71326-5a1f-4470-af89-63e89d2a9410.png)
![Snip20220210_22](https://user-images.githubusercontent.com/20729686/153526460-9c7e2b63-9cb1-430f-92cf-13942ee06be0.png)
that helps with this issue provide the link(s) here.

**Comment by EchoProject** [comment]
Need clarification on the following statement that was taken from the [Feature Comparison Sheet found here](https://docs.google.com/spreadsheets/d/1KWPIoo0skY4I_Xi7bFTPbyjQ6QiyVq4RML_t3IViAqs/edit#gid=0): 

"Additonally there is no hamburger menu for the top nav, menu items just start disappearing" 

Clarify and add to the Issue Description.

**Comment by ExperimentsInHonesty** [comment]
@EchoProject I reviewed the comment copied here:

> Need clarification on the following statement that was taken from the [Feature Comparison Sheet found here](https://docs.google.com/spreadsheets/d/1KWPIoo0skY4I_Xi7bFTPbyjQ6QiyVq4RML_t3IViAqs/edit#gid=0):

>  "Additionally there is no hamburger menu for the top nav, menu items just start disappearing"

> Clarify and add to the Issue Description.


I think that it needs to be on a separate issue where we address the fact that the menu and page is not responsive at all, on phone it does not fit the screen.  You can hide this comment and the one above when you move it to another issue
