### ISSUE TITLE
NEEDS WORK: No Submit Button? 

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1172]
### Dependency 
Dependent on getting the below compeleted. 
- #1155 
- #1165 (complete for 2022)

### Overview
Create a submit button when requesting searches on the filtering menu so that users can explicitly take action on their query. 

Auto requesting after each selection is made requires many API calls. We should reduce this burden. 

### Resources/Instructions
![Snip20220210_24](https://user-images.githubusercontent.com/20729686/153530047-f744bf44-d21d-4de3-9ddc-4947131fcc6e.png)

**Comment by EchoProject** [comment]
Need to get clarification on the issue request from the [Feature Comparison Sheet found here](https://docs.google.com/spreadsheets/d/1KWPIoo0skY4I_Xi7bFTPbyjQ6QiyVq4RML_t3IViAqs/edit#gid=0).

**Comment by nichhk** [comment]
This blocked by #1252 and #1253.

**Comment by nichhk** [comment]
I think this is obsolete with our new design, so I will close it out.
