### ISSUE TITLE
Tech Lead Onboarding 

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1180]
### Overview
Provide first steps for the new Tech Lead to ramp up on the v2 project so they have context on immediate priorities. 

### Resources/Instructions
[Hack for LA/ Engineering Open Roles board](https://github.com/hackforla/engineering/projects/2#card-54125928)

<details>
<summary>open role listing</summary>

<img src="https://www.hackforla.org/assets/images/projects/311_data.png" />

**Project Name:** 311 Data

**Volunteer Opportunity:** Full stack React, Mapbox GL JS.

We are very close to launching V2. We need your help to meet the finish line. The `311-data.org` website has a permanent placement on the LA Department of Neighbourhood Empowerment website.  

**Duration:** Open-ended

**Who to communicate your interest to**

  - Slack channel link: [#311-data](https://hackforla.slack.com/archives/CJY4R382X)
  - Slack name of person to contact in the channel:  Eric Cho

[Read more about the project](https://www.hackforla.org/projects/311-data)
</details>

**Comment by ExperimentsInHonesty** [comment]
Immediate need for Tech Lead.  

Responsibilities will include:
Decoding how we have our data pipeline between the 311 city data
Fixing the gap in our data from when it was down earlier in the year
identifying how to keep it working from year to year, when they move to the new dataset
