### ISSUE TITLE
Change all Actions filenames to be lowercase

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1192]
### Overview
Most code style guides suggest to use all lowercase characters for filenames (e.g., see [Google style guide](https://developers.google.com/style/filenames)). The actions in .github/workflows/ do not follow this.

### Action Items
Simply change the filenames to be lowercase. Some of these files also contain the filename within the file itself, so make sure to check for/update that as well.

**Comment by EchoProject** [comment]
Hey @nichhk, is this issue ongoing, or have all the filenames been changed?
