### ISSUE TITLE
[FUTURE] UI/UX Onboarding Documentation Improvement

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1201]
### Overview
We need to improve the onboarding experience for new designers joining the program so that they have a baseline understanding of design guidelines, Figma tool, current state, and design decisions. 

The goal is to have a new designer functional (1 Issue completed, and 1 Issue in Progress) within the first full week. 

### Action Items
- [x] Onboarding Docs - Create a step-by-step plan for new design volunteers to follow in the first weeks - Melissa 
- [x] Design Guide - Update the guide to include additional assets - [INSERT]
- [x] Figma - Include blurb/ descriptions to each page to identify assets and lifecycle - [INSERT]
- [ ] Video Tutorial - Create video tutorials on using Figma for new volunteers not familiar with the software - Melissa  
- [ ] Project Wiki - Include project background, current state, and final design decisions - Eric 

### Resources/Instructions
[Project Wiki](https://github.com/hackforla/311-data/wiki/Resources-Home)
[Figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=4649%3A9363) 
[Design Google Drive](https://drive.google.com/drive/folders/1d5GVgigqNZEE63b-ZZP_O_mfJnJUhvoD)
[Design Onboarding Doc](https://docs.google.com/document/d/1_fBJPTea0i_j1FWs6p24EXj0qo60RmGqnKiLkBw1hts/edit)

**Comment by mc759** [comment]
@EchoProject This issue ties in with the 2023H1 roadmap. Should we ping the designers for an update or include it in a different conversation?

**Comment by mc759** [comment]
@melissahermes99 and @elizabeth-ux We are moving this issue to the backlog given everything else at the moment, but please update when you can get back this!

**Comment by Graemo27** [comment]
We could add some cover pages, history pages, and flow charts to familiarize new designers on Figma for 311.
