### ISSUE TITLE
v2 Add About Page

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1202]
### Overview
We need to add an about page to the v2 site to provide background and context of the 311-Data project. 

### Action Items
- [x] Add page 
- [ ] Use design panel in Figma as content 
- [ ] Ensure all hyperlinks are used 
- [x] Add "About Us" to header navigation 

### Resources/Instructions
Design work was completed [here](https://github.com/hackforla/311-data/issues/960).

Page design found in [Figma Design Studio](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=2775%3A7702) under Sim -> farthest right. 
![Snip20220513_36](https://user-images.githubusercontent.com/20729686/168396680-842dabea-764c-4cd0-b682-f5d0f397100b.png)

**Comment by EchoProject** [comment]
@funbunch checking to see if this issue can be closed. It looks like the changes have been pushed.

**Comment by funbunch** [comment]
Yes! Good to close.
