### ISSUE TITLE
Add District Type Selection to Map Menu [INCOMPLETE]

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1203]
### Overview
We need to add a selection feature for choosing a district type so that users can search queries beyond neighborhood councils.

### Action Items
- [ ] [Design Team INSERT]
- [ ] [Design Team INSERT]
- [ ] [Design Team INSERT]

**Comment by elizabeth-ux** [comment]
@EchoProject Is this what you were looking for to add District type to the menu?

![Filter Menu with Districts](https://user-images.githubusercontent.com/20293568/172281733-8c07c9f6-7ccf-4e3f-9bd1-d4cc48085064.png)

**Comment by EchoProject** [comment]
Let's sync up on this during the meeting tonight.

**Comment by elizabeth-ux** [comment]
@EchoProject. Can probably close this issue as this subject matter was added to issue [Menu redesign #1157](https://github.com/hackforla/311-data/issues/1157). Any further menu updates will be posted to issue #1157
