### ISSUE TITLE
Identify points of improvements to make 311-data dashboards more meaningful to different audiences

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/311-data#1232]
### Overview
The 311-data dashboards display data about 311 requests but right they aren't answering key questions that neighborhood council members might have or need to answer to make informed decisions. Here are some examples of interesting questions that might produce more meaningful dashboards:

- How does my neighborhood council compare to another council in terms of the type of request or days to close?
- Are requests higher in certain months? When there is a higher number of requests, how does that impact days to close?
- How have requests changed for my council over time?

### Action Items

- [ ] Explore 311-data and make recommendations for report improvements

### Resources/Instructions
[311-data development site](https://dev.311-data.org/map) -under Reports

[311-data project onboarding](https://docs.google.com/document/d/1fNIxKJl91YZ_b6PRvKMdyd7tXJwWbfGIAJ5VTfe8Jow/edit?pli=1#heading=h.c8tc614ce3iu)

Refer to the documentation in the [311-data dashboards directory](https://github.com/hackforla/311-data/tree/dev/server/dash/dashboards) for creating or modifying dashboards

[Dash Python User Guide](https://dash.plotly.com/)

Optional: prototype reports in Jupyter Notebooks -examples found [here](https://drive.google.com/drive/u/3/folders/1P-uID8FpnqwvYlUmzWsmgU4pxRSeb72z). 

### Issues Created From People Reviewing Dashboard
- https://github.com/hackforla/311-data/issues/1231 
- https://github.com/hackforla/311-data/issues/1229
- https://github.com/hackforla/311-data/issues/1234
- https://github.com/hackforla/311-data/issues/1228

**Comment by joshuayhwu** [comment]
Combined dashboard answer first two bullets, #1228 covers last bullet.
