### ISSUE TITLE
Replace column chart with stacked bar chart on the reports overview page

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/311-data#1234]
### Overview
Replace column chart with stacked bar chart to improve visualization

### Action Items

- [ ] Edit existing dashboard - [overview](https://dev.311-data.org/reports/dashboards/overview) to replace column chart w/ stacked bar chart

### Resources/Instructions

[311-data project onboarding](https://docs.google.com/document/d/1fNIxKJl91YZ_b6PRvKMdyd7tXJwWbfGIAJ5VTfe8Jow/edit?pli=1#heading=h.c8tc614ce3iu)

Refer to the documentation in the [311-data dashboards directory](https://github.com/hackforla/311-data/tree/dev/server/dash/dashboards) for creating or modifying dashboards

[Dash Python User Guide](https://dash.plotly.com/)

[Plotly Dash Tutorial - specific to stacked bar charts](https://pbpython.com/plotly-dash-intro.html)

Optional: prototype reports in Jupyter Notebooks -examples found [here](https://drive.google.com/drive/u/3/folders/1P-uID8FpnqwvYlUmzWsmgU4pxRSeb72z). Make a copy and edit the code to see changes in real-time.

- #1378

**Comment by nichhk** [comment]
Let's hold off on this issue until Josh checks in PR #1288. We are getting rid of the Overview dashboard there.

**Comment by joshuayhwu** [comment]
Deprecated overview dashboard. No longer relevant.
