### ISSUE TITLE
Plotly Dash Versioning Issue 

### ISSUE THREAD

**Issue by joshuayhwu** [hackforla/311-data#1246]
### Overview
Existing plotly dashboards versions are from v1.x while the current plotly dash is on v2.x. There is no longerr any documentation available for older versions of Dash and an upgrade is necessary. 

Currently, I have succesfully upgrade the code and tested in a separate directory with new dashboard incorporated in there. However, then repeating the process in 311 Code base, none of the callback functions get triggered (i.e. no interactivity possible), while the static visuals still get render. I suspect this is something to do with gunicorn interfering with the callbacks being fire, as everything works perfectly without gunicorn. One thing worth mentioning is that this sometimes occur prior to upgrade as well, but the issue will resolve after reloading a few times.

### Action Items
- [ ] Determine which existing dashboards we want to keep
- [x] Upgrade desired dashboards to newest version to work with docker
- [x] Ensure new vesrions of dashboards are compatible with gunicorn 
- [ ] Integrate new dashboards with existing code base

### Resources/Instructions
- See [here](https://github.com/joshuayhwu/311-Data-Dashboard) for Upgraded Dashboards with New Dash Version with Docker 
- https://dash.plotly.com/dash-2-0-migration
- #1378

**Comment by nichhk** [comment]
In the next team meeting, can you and the team try to figure out which of the existing dashboards we want to maintain, and which we can get rid of? Independent of that, I think we can merge the "long" and "recent" versions of each dashboard into a single dashboard.

Then, we can start to perform the upgrade.

**Comment by joshuayhwu** [comment]
Sounds good. We will get a vote on those and see which ones we could combine.

**Comment by joshuayhwu** [comment]
Fixed with #1249
