### ISSUE TITLE
311 request types with no council (councilId=0) assigned to it

### ISSUE THREAD

**Issue by priyakalyan** [hackforla/311-data#1250]
### Overview
We need to take a look at all the 311 request type data with no council id or council name assigned to it. In the 311 data server, the councilId has been assigned as 0 and the councilName as 'No Council' for such request types. 

### Action Items

- [x] Determine if all of the 'No Council' request types fall outside of the NC boundary. 
- [x] Check the pattern for the other years.
- [x] Plot a histogram of all such request types.  

### Resources/Instructions

- Here is an interactive plot of 311 request with no council id for the year 2021- [noCouncil](https://spontaneous-kashata-dce0b6.netlify.app/). The 311 data is obtained by making an API call to [LA 311 Data API](https://dev-api.311-data.org/docs), fetching all rows of data for the year 2021. 
- The link to the neighborhood council shape file is [here](https://geohub.lacity.org/datasets/9c8639737e3a457a8c0f6a93f9c36974_18/about).
- The link to the metro rail stops shape file is [here](https://geohub.lacity.org/datasets/lahub::metro-rail-lines-stops/about)
- tools: google colab, geopandas, pandas, folium

**Comment by EchoProject** [comment]
Hi @priyakalyan, is this issue still relevant? If so, could you provide an update?

**Comment by priyakalyan** [comment]
Hi @EchoProject, sorry for a late reply. Last time I checked, Zak was working on this issue. I have slacked him asking for an update. This issue was created to make sure that all the no council data were falling outside the NC boundary. If Zak is not working on it anymore, then I will look at it and close the issue.

**Comment by zaklang123** [comment]
Hi @EchoProject, I'm currently working on this issue. I'm making slow, but steady progress. I've just figured out how to use Geopandas and Folium, so I think I'm ready to start going through the action items.

**Comment by mc759** [comment]
@zaklang123 Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by zaklang123** [comment]
Hi, 

I'm almost done with this issue. I just have the histogram part left to complete. I did try to contact EmpowerLA to understand why there are certain gaps in the neighborhood councils, but I have not heard back from them. I plan on having the project done early next year.

Thanks

**Comment by akhaleghi** [comment]
@zaklang123 is there any work left to be done on this issue?

**Comment by ExperimentsInHonesty** [comment]
Where is the histogram this issue was supposed to create?
