### ISSUE TITLE
Frontend is not compatible with Redux Devtools

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1255]
### Overview
Redux Devtools makes debugging and viewing redux state much simpler. We should make our frontend compatible with this extension. See this [post](https://codeburst.io/redux-devtools-for-dummies-74566c597d7) for instructions.

It looks like we've installed and activated Redux Devtools two years ago (PR #289), but the extension is greyed out when I'm on the dev site.

### Action Items:
- [ ] We should rename "webpack.dev.js" to "webpack.local.js", and create a new "webpack.dev.js" file that is the same as "webpack.prod.js", but it specifies mode as "development". See context in comment below.

**Comment by mc759** [comment]
Hey @edwinjue can you help us update this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by edwinjue** [comment]
Redux devtools should already be working on local development environment as I already have it installed
