### ISSUE TITLE
Make 311 Data's request data easily accessible for data scientists

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1259]
### Overview
Currently, we have no way of providing our clean request data to our data scientists. @priyakalyan is working on PR #1257, but this script takes a long time to execute to get all the data.

I see two solutions to this:
1. Make our SQL DB accessible to data scientists + create Python methods that read from the DB and produce dataframes.
2. During our nightly Prefect runs, add a step that also writes the request data out as a csv file to S3. 

I'm leaning towards (1) right now, since it will use less disk space and has fewer moving parts. (1) will take longer to implement, however, since we currently don't have access to make infrastructure changes (waiting for SSH keys or Terraform configs from @mattyweb).

### Action Items
- [ ] Get SSH key passphrase for DB access
- [ ] Make our SQL DB accessible to data scientists + create Python methods that read from the DB and produce dataframes

**Comment by nichhk** [comment]
@joshuayhwu , who might be interested in working on this.

**Comment by joshuayhwu** [comment]
I was taking a look at the lacity API [config](https://github.com/hackforla/311-data/blob/6e2c070285ff729a8ca7d9ec8e663db7aa7583ab/server/api/code/lacity_data_api/config.py#L5) and attempting to connect to postgres locally. I was wondering what's the passcode for the database, if any? (the code said it defaults to none but psycopg2 said db refused connection)

**Comment by nichhk** [comment]
Please take a look at this [section](https://github.com/hackforla/311-data/blob/dev/server/terraform/README.md#developer-access-with-ssh-and-bastion-server) of the Terraform README. Basically, we cannot directly access our DB right now because it's in a virtual private network (or cloud?). It can only be access through the bastion server, but we don't have the SSH key from Matt yet :(

**Comment by joshuayhwu** [comment]
Interesting. What are your thoughts on directly accessing the Socrata API and building a separate db?

**Comment by nichhk** [comment]
Hmm I think that would help us get a solution faster, but we'd have to maintain another component in an already too-complicated system.

If we think that this task is highest priority, I would go with option 2 listed in the first comment.

**Comment by joshuayhwu** [comment]
Sounds good. We can discuss more tonight.

**Comment by mc759** [comment]
Hey @joshuayhwu Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!
