### ISSUE TITLE
Prefect nightly task regularly times out waiting for dashboard to say it's reloading

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1261]
### Overview
See prior [context](https://github.com/hackforla/311-data/issues/1258#issuecomment-1167911599) here. This isn't high priority now that we are aware of this bug, but we'd like to have confidence in our error reporting (i.e., if our logs indicate an error, it's actually an error).

[Here](https://github.com/hackforla/311-data/blob/456d03754c169b1ecae5f0bb1683db871e311299/server/dash/index.py#L53) is where the dashboard handles a reload request.

[Here](https://github.com/hackforla/311-data/blob/456d03754c169b1ecae5f0bb1683db871e311299/server/prefect/tasks/cache.py#L61) is where the nightly task issues the reload request and [waits](https://github.com/hackforla/311-data/blob/456d03754c169b1ecae5f0bb1683db871e311299/server/prefect/tasks/cache.py#L54) for the dashboard to indicate that it's reloading.

### Action Items
- [ ] Try increasing the timeout to 2min

**Comment by nichhk** [comment]
I took a closer look at this. When you manually tell the dashboard server to reload (i.e., visit `dashboard_url/reload`), it happens almost instantaneously, and we get the result that we're expecting.

So I'm less confident that extending the timeout will solve our issue here. There is probably a bug in the way that we are verifying the reload's success. Currently, prefect opens a browser and navigates to `dashboard_url/reload`, and then it waits for an HTML component with a specific ID to show up on the page. This seems quite overengineered.

I think making a simple web request will be less complicated and work more reliably since we won't need to rely on a browser automation library, so I'll try that.

**Comment by nichhk** [comment]
Actually, according to #1028, we need to run a browser. There is very little detail in the bug. But apparently they tried using my approach in the previous comment first, but it didn't work. So I will continue investigating the existing solution.

**Comment by nichhk** [comment]
It doesn't seem to be timing out anymore, probably thanks to #1379. But Prefect still says the reloading is failing, probably because it [can't find](https://github.com/hackforla/311-data/blob/b0717ad25eab4ef25a2f26da187d9d8905ab5f77/server/prefect/tasks/cache.py#L73) the reloading message in the page content. I checked the lightsail logs, and the report server is indeed being reloaded, so I'm going to add a print statement to the Prefect task to see what content it's getting from the reload page.

**Comment by nichhk** [comment]
It timed out again for last night's run. We might need to add a call to `waitForNavigation`? https://stackoverflow.com/a/58298172

**Comment by mc759** [comment]
Hey @edwinjue Just added you as a replacement for Nich! Can you help us update this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!
