### ISSUE TITLE
Dev site says its data hasn't been updated in ~10 days

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1262]
### Overview
We are successfully pulling data every night according to the nightly pull logging. But the dev site says "Data updated: 06/15/22", which is almost 10 days ago.

The frontend code to display the date is [here](https://github.com/hackforla/311-data/blob/7cbb445aae2053b68168e36a460294c0d0e5d9ab/client/components/Footer.jsx#L66).

The backend code to retrieve the lastPulledLocal timestamp is [here](https://github.com/hackforla/311-data/blob/b0717ad25eab4ef25a2f26da187d9d8905ab5f77/server/api/code/lacity_data_api/routers/status.py#L37). 

### Action Items
- [x] Investigate relationship between "Data updated" and Prefect run success.
- [ ] Fix #1261

**Comment by nichhk** [comment]
This seems very related to #1261. We finally had a successful nightly Prefect run on 06/28, including waiting for the dashboard to say it's reloading, and now the dev site says its data was updated on 06/28. Today is 06/29, and the 06/29 Prefect run failed, so the dev site doesn't say it was updated on 06/28.

**Comment by piotrsan** [comment]
Hi Nich, here is a screenshot of the missing data, week of 6/12 is the most affected one.

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/15342705/179672263-8c61417c-914c-4c42-9495-c68b1b6be1f1.png">

**Comment by EchoProject** [comment]
@nichhk it looks like we can close this item since there's another issue under the fix action. Is that correct?

**Comment by nichhk** [comment]
Yup that's right. Closing this out.
