### ISSUE TITLE
Map should display a loading modal when it's retrieving new data

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1284]
### Overview
Currently, it can take up to 25s for the dev site to pull data for the past month. We should display a loading modal in these situations.

### Action Items
- [ ] Design a loading indicator.
- [ ] Display it when the client is retrieving data, and hide it when the client finishes retrieving data

### Resources 
- https://github.com/hackforla/311-data/issues/1380
- https://github.com/hackforla/311-data/issues/1396

**Comment by nichhk** [comment]
@elizabeth-ux and @melissahermes99, could you design a loading indicator for the map?

On the eng side, I've gotten a material-ui [CircularProgress](https://mui.com/material-ui/react-progress/#circular-indeterminate) component to load, but it doesn't look good.

![bad-loading-modal](https://user-images.githubusercontent.com/6537426/182221771-a49605b7-a627-4a7b-ab88-7e182f4233d7.png)

**Comment by melissahermes99** [comment]
I've come up with two test loading indicators for the map. The first indicator utilizes the logo and the second is just a simple loading bar. If neither of these is what we're looking for I can keep experimenting to find something that works. For now, you can find the UI for both indicators under the [Map Loading Screen Test](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=2375%3A0) page. 

I've gone ahead and created a quick prototype for both indicators as well. 
https://www.figma.com/proto/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5106%3A17198&scaling=contain&page-id=2375%3A0&starting-point-node-id=5106%3A17185&show-proto-sidebar=1

![image](https://user-images.githubusercontent.com/97048386/182714880-41f8a5bc-4059-428a-8129-95ad8cc8f0a9.png)
![image](https://user-images.githubusercontent.com/97048386/182714928-3eb2329f-c47a-411b-9c36-d6ed8b07b274.png)

**Comment by nichhk** [comment]
Thanks Melissa! They look great. I prefer the first one, but would appreciate feedback from others! @elizabeth-ux @EchoProject any thoughts?

**Comment by EchoProject** [comment]
I also like the first. @melissahermes99 Is it possible to have the shimmer go in the other direction (from left to right)? 

@nichhk The darkened state of the page while loading isn't currently a feature, correct? Are we building this in? 
So every time the screen is loading it darkens? Makes sense for predictably long loads, but I feel like it'll be eye straining if the load happens quickly and possible more than once. 

I think it'll look weird if the screen isn't darkened given the colors.

**Comment by melissahermes99** [comment]
> I also like the first. @melissahermes99 Is it possible to have the shimmer go in the other direction (from left to right)?
> 
> @nichhk The darkened state of the page while loading isn't currently a feature, correct? Are we building this in? So every time the screen is loading it darkens? Makes sense for predictably long loads, but I feel like it'll be eye straining if the load happens quickly and possible more than once.
> 
> I think it'll look weird if the screen isn't darkened given the colors.

**Comment by melissahermes99** [comment]
> I also like the first. @melissahermes99 Is it possible to have the shimmer go in the other direction (from left to right)?

I've updated the first loading indicator to move to the left. 
![image](https://user-images.githubusercontent.com/97048386/182982858-19baa15e-b598-4997-8772-94864bc475a0.png)

**Comment by melissahermes99** [comment]
I have created a progress bar. I am not sure if looping it is a good idea, so I've slowed down the speed of it's progression. You can view it [**here.**](https://www.figma.com/proto/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5166%3A23042&scaling=min-zoom&page-id=2375%3A0&starting-point-node-id=5166%3A21377)

![image](https://user-images.githubusercontent.com/97048386/184259547-969ec32d-af6e-4b0d-8417-99deb49b588b.png)

**Comment by nichhk** [comment]
Thanks Melissa, this looks good to me! Was there any discussion last night about which loading indicator to go with?

**Comment by EchoProject** [comment]
I think we landed with the bar at the top, below the nav, would prompt as orange and then turn teal during the loading. The color change would not loop, and the background would not darken. @melissahermes99 am I missing anything?

**Comment by melissahermes99** [comment]
Sounds good! I did have to make a slight adjustment to the canvas to lower to bar just a bit. I had previously had it overlapping the header on accident. I've updated the color transitions as well to make the flow of the loading bar more smooth.

**Comment by nichhk** [comment]
Update for Killen: we already have an ugly loading indicator on the dev site, but we want to upgrade it to the one that Melissa [designed](https://github.com/hackforla/311-data/issues/1284#issuecomment-1212591656). You can see how I added the ugly loading indicator [here](https://github.com/hackforla/311-data/pull/1304).

**Comment by mc759** [comment]
Hey @jekijo Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by jekijo** [comment]
Hey @mc759, I actually finished this issue a while ago and submitted a pull request (#1412 ). I didn't know the issue hadn't been closed yet, but I'll go ahead and do that now
