### ISSUE TITLE
Connect with Someone in the City of LA 

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1287]
### Overview
We need to connect with someone in the City of LA to build a relationship with their data engineers in order to keep up to date with changes to data collection/ distribution and to build more robust products. 

### Action Items

- [x] Provide, in writing, why we want to speak with someone at the City of LA 
- [ ] Bonnie will forward the message to her contact 
- [ ] Her contact will connect us with the appropriate person 

### Resources/Instructions
- #1407

**Comment by EchoProject** [comment]
Here is a short paragraph on why we're looking to connect with someone at the City of LA. 

We would like to connect with someone at the City of Los Angeles that manages data. As a partner of EmpowerLA, we use the City's 311 service request data to provide data visualization and analytic dashbaords for local gonverments and community members. We would like to build a relationship with the City's data department to stay current on the City's data collection process and storage as it affects downstream usage. We would like to keep our web tool up-to-date along side any changes made at the aggregation level. Also, if possible, we would like access to population data to normalize our research as we investigate the nuances of Los Angeles communities. 

We look forward to working with the city to make the City of Los Angeles even better. 

All the best,
Eric Cho 
Product Manager - 311-Data.org

**Comment by EchoProject** [comment]
Hey @nichhk, can you take a look at the comment above and see if there's anything you would like to change before I send to Bonnie to forward? This is regarding connecting with a data manager at the City of LA.

**Comment by nichhk** [comment]
Looks great, thanks Eric!

A couple comments:
- There is a typo--"gonverments".
- might help to specify that we're looking for per-NC population data.
- not sure what "aggregation level" means, maybe that can be clarified.
