### ISSUE TITLE
Errors in onboarding document

### ISSUE THREAD

**Issue by hbrumley** [hackforla/311-data#129]
The link in the sentence _"Run docker compose-up using the yml file included in the repo."_ should link to Orchestration/docker-compose-default.yml. In addition, the command should be ```docker-compose up```

I also had to rename the above file to docker-compose.yml in order to get it to build. If there is another way to make the command work it should probably be mentioned in the document.

**Comment by ryanmswan** [comment]
Thanks for the fix. I'll make sure to push this in the next draft of the onboarding document.

**Comment by ryanmswan** [comment]
Added info to the onboarding doc.
