### ISSUE TITLE
[EPIC] Data Science Insight Discovery using 311 Data (Research) H1 2023

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1291]
## This is the Epic for all Data Science Research Projects
All data science team members may feel free to add your projects to the ongoing task list, below! If you have a project repo or public link you'd like to use to share your project work, make sure that link is referenced in your project's issue. 

### Overview

To generate impact, I (Nich) think there are a two main ways of thinking about these **Data Science Deep Dives (DSDDs)**:
* investigation/justice-oriented: is the city treating and serving Los Angelenos with equal treatment?
* Efficiency-oriented: how can we make city services and processes more efficient?

(If anyone has other ideas on how to frame our DSDDs, please comment below.)

We've already created other issues to track specific DSDDs, with 1-2 data scientists working on a particular DSDD. So this issue just serves to track our overall progress and work towards the main goal of producing at least one interesting, actionable insight--the more the better!

#### Investigation/Justice

- [x] #1278
- [x] #1277
- [x] #1294
- [x] #1098

#### Efficiency

- [x] #1279 
- [x] #1289
- [x] #1229 

#### Both

- [x] #1250
- [x] #1432

#### Backlog

- [ ]  #1292 
- [ ]  #1293 

### Resources/Instructions
- [Get your 311 datasets here](https://github.com/hackforla/311-data/tree/dev/server/utils) with the API. A data range may be entered using the CLI. If you need help with this ask a Lead or a Peer! This may generate a large dataset so be prepared. For example, one year may have 1M+ data points (individual 311 requests). 

- [City of LA 311 data resources](https://data.lacity.org/City-Infrastructure-Service-Requests/MyLA311-Service-Request-Data-2022/i5ke-k6by)

- [Shape files for Neighborhood Council here](https://geohub.lacity.org/datasets/9c8639737e3a457a8c0f6a93f9c36974/explore)

- [Census city block shape files here (tabblock20)](https://www2.census.gov/geo/tiger/TIGER2020PL/STATE/06_CALIFORNIA/06037/)

- If you want to do an analysis using Census blocks, [use this script on the CLI to do a spatial join with Census block IDs](https://github.com/ajmachado42/Hack-for-LA-311-Data/tree/master/I-1279/get_nc_blk_req) and your API dataset from above. 

- Here is a list of [Data Sources](https://github.com/hackforla/311-data/blob/dev/misc/DataSources.md) to generate some ideas for projects.

- Staying informed about what's going on in LA is also helpful--knowing the pain points for Los Angelenos will help us to know which problems to solve.

**Comment by nichhk** [comment]
Tagging all our data scientists: @joshuayhwu @susanklm @piotrsan @priyakalyan @Michaeldavidng @JACKIEKWON @lgewirtz @yn2191

**Comment by ajmachado42** [comment]
Doing some hygiene here and closing this one out. The [forecasting task was completed](https://github.com/hackforla/311-data/issues/1289). See task for conclusions.

**Comment by ajmachado42** [comment]
Other research projects exist that weren't included in the backlog section of this issue. See Data Science role tag for those other projects.

**Comment by ajmachado42** [comment]
Reopening since this is an ongoing Epic.
