### ISSUE TITLE
Identify the regions to set up LA Metros Bike Share Stations to help mitigate "First/Last Mile Problem" 

### ISSUE THREAD

**Issue by joshuayhwu** [hackforla/311-data#1292]
### Overview
LA is notorious for its traffic volume and public transport is one way to mitigate the issue. However, the lack of adequate city planning means that citizens often face the "First Mile / Last Mile Problem" when trying to access the public transit - it is often difficult to reach/exit the public transport system without first driving to/from the transportation system because LA is not as dense as a city say NYC. The LA Metro system have tried utilizing a variety of bus, lightrail, and bike system to help mitigate the problem but I believe there is more targeted work to be done. As data scientists, we can utilize some of the 311 request and public data available to identify regions to set up LA Metro Bike Share for relatively dense areas and Bus Stops for relatively sparse areas.

### Action Items

- [ ] Reaching out to domain experts in the City Planning team to understand whether the issue still exist, what are some ongoing effort to mitigate the issue, and how can we best help
- [ ] Reaching out / potentially collaborating with LA Metro / Lyft / Uber / Lime to drive impact with business intervention
- [ ] Define the problem and update the issue 
- [ ] (Prelim) Identify and define northstar metric for evaluating location for placing share bikes/bus stops depending on density fo region (e.g. weighted average for the number of 5-star restaurants, shopping malls, desserts, company offices based on Yelp Data, risk of bike being stolen with 311 Request data )
- [ ] (Prelim) Test and validate our northstar metric based on existing sales / utilization data if possible (from companies)
- [ ] (Prelim) Finding the optimal bike share routes / bus routes for city (e.g. based on how wide the road is, existing bike lanes, and distance/time it takes to reach target from destination) and receive feedback from City Planning domain experts 
- [ ] (Prelim) A/B Testing with existing domain exprts of utilizing our project plan

### Resources/Instructions
- [Article from LA's City Planning and Development Report ](https://www.cp-dr.com/articles/node-3748)
- [Stolen Bikes Listing](https://bikinginla.com/stolen-bike-listings/)
- [Bike Share & Bike Lane Data from list of Data Sources](https://github.com/hackforla/311-data/blob/dev/misc/DataSources.md)

**Comment by Michaeldavidng** [comment]
here:
https://public.tableau.com/app/profile/michael.david.ng/viz/2021LosAngelesbicycleshare/Sheet1
10/12/2022

**Comment by Michaeldavidng** [comment]
From what I understood from our previous meeting, you mentioned that you wanted to look at my tableau and give pointers about next steps.

So, I'll wait on standby until you give your recommendation or what not.

I was hoping to pit a 3rd dimension regarding distance in the last tab of the workbook but if that doesn't sit right with you than I don't really know what you would have me do next.

Lastly, I'm might be leaving hack for LA in the near future; well that or I might just take an extended break like Elizabeth did previously.

**Comment by joshuayhwu** [comment]
@Michaeldavidng Thanks for the updates! 

Please correct me if my observations of the tableau are wrong:
1. Standard bicycles are used the most
2. Monthly pass holders and Walk-up are the most common users of bike shares
3. Trip-route is generally one-way
4. The highest use of bike share is likely in tourist areas like beach and metro areas

For the last tab, I'd reccomend just plotting average duration against distance to see the correlation. I'm more interested in exploring the following:
1. Does the higher average duration translate to lower usage?
2. Aside from tourist areas, what are the areas with the highest metro usuage?
3. what are the stations with the highest walk-up usuage? what about monthly pass?
