### ISSUE TITLE
Redesign FAQ page to include color legend and category explanations.

### ISSUE THREAD

**Issue by melissahermes99** [hackforla/311-data#1297]
### Overview
We need to reformat the FAQ page to include a section dedicated to a detailed color legend. In previous versions of the map menu, we included an information pop-up that provided more details on the categories used for the map. In order to use our space more efficiently, we will need to relocate this information to the FAQ page.

### Action Items
UI/UX - Design, please provide actions: 
- [x] On the menu, create a map information button that will link to the FAQ page
- [x] Relocate the map information legend to the FAQ page
- [x] Format legend information to fit nicely in the FAQ page.

### Resources/Instructions
![image](https://user-images.githubusercontent.com/97048386/181095404-20e75a9f-e5e0-41f1-8679-fa793c2def40.png)
![image](https://user-images.githubusercontent.com/97048386/181095155-a2a92439-4b2f-412e-990e-36ebc840d230.png)

**Comment by melissahermes99** [comment]
![image](https://user-images.githubusercontent.com/97048386/184258805-c3d63feb-d91b-4a1a-a3b1-69569f88ab7f.png)
![image](https://user-images.githubusercontent.com/97048386/184258931-28f35cd6-6e1e-447e-b580-1b96254f948a.png)


Elizabeth and I have decided one of these methods can work for redirecting the user to the FAQ page. The first option is more broad for all questions and concerns and the second is more specific to the categories. It might not be a bad idea to include both features since they don't overlap on the screen.

**Comment by melissahermes99** [comment]
Elizabeth has added a section in the FAQ to include information about each category in the map key. You can find this change on the Version 2_Design Studio page. 
![image](https://user-images.githubusercontent.com/97048386/184259284-1ebbfc73-1ddf-4f77-90fc-0ce0bf7acd95.png)

**Comment by EchoProject** [comment]
@melissahermes99 per last weeks discussion, we can call the design work for this issue complete and pass off to engineering for development. @nichhk let us know if you require further specs to help write the user story. If not, you can close with comment. Thanks, all!

**Comment by melissahermes99** [comment]
I've gone ahead and added this to the EPIC as a completed issue for just documentation. This issue is complete on our end!
