### ISSUE TITLE
Implement caching for get_filtered_requests

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1307]
### Overview
[`get_filtered_requests`](https://github.com/hackforla/311-data/blob/ecf4ce422dbf1d8389e3b0e2586533d9c92eb104/server/api/code/lacity_data_api/models/service_request.py#L165) is the API that we use to get requests on the map, and it's very slow right now, probably because we're not caching the results.

You can play around with the API [here](https://dev-api.311-data.org/docs#/default/get_all_service_requests_requests_get).

### Action Items
- [x] Measure current API latency (see this [stackoverflow](https://stackoverflow.com/questions/18215389/how-do-i-measure-request-and-response-times-at-once-using-curl#:~:text=You%20can%20use%20curl%20%2Dv,trace%20mode%20to%20do%20anything) question on ways to measure latency). For the API arguments, please make the date range one day and limit the response to 10k requests. 
- [x] Implement caching by adding a `@cached(alias="default")` decorator on `get_filtered_requests`.
- [x] For each day in the past week, call `get_filtered_requests` in [`build_cache`](https://github.com/hackforla/311-data/blob/b0717ad25eab4ef25a2f26da187d9d8905ab5f77/server/api/code/lacity_data_api/services/utilities.py#L12). We're doing this so that the cache is primed for the API calls from the frontend. You can see how the frontend makes the requests for the past week [here](https://github.com/hackforla/311-data/blob/dev/client/components/Map/index.js#L220).
- [x] Check that the cache is caching the results for `get_filtered_requests` by checking the result of [/status/cache](https://dev-api.311-data.org/docs#/default/check_status_type_status__status_type__get)
- [x] Remeasure the API latency after adding caching.

**Comment by nichhk** [comment]
Killen will work on this. I'll assign it to him explicitly once he gets added to the repo.

**Comment by nichhk** [comment]
Hey @jekijo, please open a PR linking this issue and add me as a reviewer. Thanks!

Also, please share the stats for latency here in a comment.

**Comment by jekijo** [comment]
@nichhk here are the stats for latency I recorded for six days:

08/06/22: 0.0783 - 0.0472 
08/07/22: 0.1887 - 0.1089
08/08/22: 0.2802 - 0.2302
08/09/22: 0.3380 - 0.2867
08/10/22: 0.4722 - 0.4167
08/11/22: 0.7949 - 0.5709

the time reduction ranged from about 12% to up to about 40%

**Comment by nichhk** [comment]
Thanks Killen! Could you note the method that you used to measure latency here in the comments?

Let's see how the caching affects performance on the dev site after merging your PR.

**Comment by jekijo** [comment]
For measuring latency I used a curl-format.txt file and curl -w "@curl-format.txt" -o /dev/null -s "localhost" to show the time of each request. I had also used curl -v --trace-time. Both of these were from the stackoverflow link in the issue card.
