### ISSUE TITLE
Run unit tests for Prefect

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1309]
### Overview
We need to be able to run unit tests for Prefect. Currently, `docker-compose run prefect pytest` is failing.

We can follow the unit test infra setup that the `api` is using. Prefect does seem to have a few unit tests, but we cannot use docker to run them right now.

### Action Items
- [x] Add `pytest` to Prefect's requirements.txt file. `pytest` is already in the Pipfile, but we are using requirements.txt in the Dockerfile.
- [x] See if `docker-compose run prefect pytest` works after that

**Comment by edwinjue** [comment]
added `pytest==7.1.2` to the end of /server/prefect/requirements.txt
ran `docker compose build` to rebuild
then `docker compose run prefect pytest` works and returns the following:

[+] Running 2/2

 ⠿ Network 311_data_default  Created                                                            0.1s

 ⠿ Container 311-postgres    Created                                                            0.2s

[+] Running 1/1

 ⠿ Container 311-postgres  Started                                                              0.4s

======================================== test session starts ========================================

platform linux -- Python 3.7.13, pytest-7.1.2, pluggy-1.0.0

rootdir: /app, configfile: setup.cfg, testpaths: tests

collected 6 items                                                                                   



tests/test_tasks.py F.....                                                                    [100%]



============================================= FAILURES ==============================================

_________________________________________ test_last_updated _________________________________________



    def test_last_updated():

>       runner = TaskRunner(task=postgres.get_last_updated)

E       AttributeError: module 'tasks.postgres' has no attribute 'get_last_updated'



tests/test_tasks.py:14: AttributeError

========================================= warnings summary ==========================================

../usr/local/lib/python3.7/site-packages/marshmallow/fields.py:198: 11 warnings

  /usr/local/lib/python3.7/site-packages/marshmallow/fields.py:198: RemovedInMarshmallow4Warning: Passing field metadata as a keyword arg is deprecated. Use the explicit `metadata=...` argument instead.

    RemovedInMarshmallow4Warning,



-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

====================================== short test summary info ======================================

FAILED tests/test_tasks.py::test_last_updated - AttributeError: module 'tasks.postgres' has no att...

============================= 1 failed, 5 passed, 11 warnings in 54.96s =============================

**Comment by nichhk** [comment]
Thanks for taking a look at this @edwinjue!

Could you make a PR with your changes? You can delete `test_last_updated`-- it looks like `get_last_updated` is not a function anymore.
