### ISSUE TITLE
Deprecate requirements.txt in favor of Pipfile

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1310]
### Overview
Currently, we are maintaining both requirements.txt and Pipfile for each of our Python packages. We should use [Pipfile only](https://jonathanmeier.io/advantages-of-pipfile-lock-over-requirements-txt/) so that we don't need to maintain two separate dependency specs.

### Action Items
- [ ] Make sure that each Pipfile is in sync with the requirements.txt file
- [ ] In our Dockerfiles, we should install dependencies using Pipfile instead of requirements.txt
- [ ] Delete the requirements.txt files

**Comment by mc759** [comment]
@edwinjue designated you as the assignee for this issue to replace Nich. 

Can you help us update the issue?

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!
