### ISSUE TITLE
Write up system design doc

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1311]
### Overview
We need to write up a system design doc so that we can explain our current architecture to the DevOps team. Currently, 311 Data infra is running on its own private AWS account, but it should be moved under the H4LA AWS account. We cannot even modify the existing infra on our private AWS account since we don't have the Terraform configs.

Hopefully, once this is all written up, we can find ways to simplify the architecture as we migrate to a different account.

### Action Items
- [x] Do write up [here](https://docs.google.com/document/d/1hgJyxs45aZv1mVOPnbBm783KBiHVjI0zWIX1jOxz-3s/edit)
- [x] Think about potential simplifications

**Comment by nichhk** [comment]
I wrote up the architecture section in the doc, and I will work on the core processes later. @EchoProject and @joshuayhwu, please take a look and let me know if there's anything to add re: architecture!

**Comment by nichhk** [comment]
Josh and I added the core processes. There are a couple small fixes to make, but we can get the ball rolling with DevOps folks now. @EchoProject could you start that conversation?

**Comment by EchoProject** [comment]
I'll reach out to the DevOps Team (Dean Church and Jason Ebung) regarding the next steps. Is it preferred to make the switch before or after launching v2? 

Also, great job on this document, @nichhk and @joshuayhwu !

**Comment by joshuayhwu** [comment]
@nichhk Updated with your feedback. Super grateful for the comprehensive overview!

**Comment by EchoProject** [comment]
Closing this issue as the work has been completed. [Here is a link to the document. ](https://docs.google.com/document/d/1hgJyxs45aZv1mVOPnbBm783KBiHVjI0zWIX1jOxz-3s/edit)
