### ISSUE TITLE
Set up Sentry to monitor API performance

### ISSUE THREAD

**Issue by nichhk** [hackforla/311-data#1312]
### Overview
We need to monitor API performance since our website is quite slow, and we want to track how well our improvements are working. See #1307 for example.

We already use Sentry on the [front](https://github.com/hackforla/311-data/blob/b0717ad25eab4ef25a2f26da187d9d8905ab5f77/client/index.js#L16) and [backend](https://github.com/hackforla/311-data/blob/b0717ad25eab4ef25a2f26da187d9d8905ab5f77/server/api/code/lacity_data_api/asgi.py#L14), but it's only set up to trace errors right now.

### Action Items
- [ ] Ensure that we can continue to use Sentry for free. If not, determine its cost and weigh against competitors.
- [ ] Set up performance monitoring

### Resources/Instructions
Log into our Sentry account with the credentials in 1Password

**Comment by edwinjue** [comment]
Hi @EchoProject @mc759 @SophAm1 is it possible to provide @bryantran04 with the sentry credentials in 1password so he can look into this? Thanks in advance!

**Comment by EchoProject** [comment]
Bryan should have access to the Sentry account and 1password 311-data dev. Let me know if this is not the case.

**Comment by edwinjue** [comment]
I believe @bryantran04 still does not have access

**Comment by EchoProject** [comment]
@bryantran04 do you have access to the 311-data dev 1passord? Karen should have contacted you last week regarding this. Also, did the login information for Sentry I provided in Slack not work? If that's the case, then we don't have access to the Sentry account and will need to create a new one and connect to our site.

**Comment by bryantran04** [comment]
@EchoProject I have access to sentry
