### ISSUE TITLE
[FUTURE] Mobile Menu Tooltips

### ISSUE THREAD

**Issue by melissahermes99** [hackforla/311-data#1319]
### Overview
We need to look into using tooltips for the mobile map menu. In order to aid the use of the map and filters on the mobile site, we have discussed using tooltips as a guide. 

### Action Items
- [x] Create brief instructions that appear upon loading the map
- [x] Use the tooltip format from the design system to create the tooltip instructions.

### Resources/Instructions
Information on this issue can be found on the [Menu Usability Test](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=3266%3A10) page and on the[ Design System ](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=3266%3A11)page.

**Comment by melissahermes99** [comment]
I've created a four-step tutorial for the mobile menu which includes the following :
- Start by entering an address
- Tap here to adjust filters and settings
- To adjust distance and location, swipe, pinch, or tap your screen
- Tap points to see details

[Click here to view prototype](https://www.figma.com/proto/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5024%3A14165&scaling=scale-down&page-id=3266%3A10&starting-point-node-id=5024%3A14165&show-proto-sidebar=1)

![image](https://user-images.githubusercontent.com/97048386/181658574-6e2f5e0a-0b1d-4581-803d-5f42b40895f3.png)

**Comment by mc759** [comment]
Hey @melissahermes99! Do you have an update for us on this issue?
Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by mc759** [comment]
Is this issue still relevant? Notice no tasks left in the initial comment. If active:

Hey @melissahermes99! Do you have an update for us on this issue?
Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by Graemo27** [comment]
Considering current state, it may be best to hold off on mobile site and move this to V3. Also, do we have research supporting user need for a mobile version of 311 (Is this a priority?)?
