### ISSUE TITLE
[EPIC] User Research H1 2023 Plan

### ISSUE THREAD

**Issue by EchoProject** [hackforla/311-data#1332]
### Summary 
This is Epic will keep track of all Issues related to User Research for the H2 2023 Roadmap that needs to be completed.   

### Required Issues
- [x] #1333
- [x] #1173
- [x] #1421 

### Resources/Instructions
[H2 2022 Product Roadmap](https://docs.google.com/spreadsheets/d/1H5KMz4pgKCalLSnPIHqDqkW0_viVzLnt3OgYklpoadk/edit#gid=0)
[H2 2022 UX Research Planning Slide Deck](https://docs.google.com/presentation/d/1UQA2tvO6Gx4GRGnvFouoT0Ypi8YMDmjHJVvH8o_HPu0/edit#slide=id.p) 
[Research Roadmap 311 Data
](https://docs.google.com/document/d/1dmtwTkiNj1pSycZqpn7S_Uk6vStUlS1-n_-rSq9IoEU/edit)

**Comment by EchoProject** [comment]
Hi Team! Here is the Epic we'll use to track all the Issues related to our roadmap research. We may not get to all of these issues, but we should work down the list. 

The first Issue needs to be created; however, the actual slide deck frame is already created. The link is in the resource section and can also be found [here](https://docs.google.com/presentation/d/1UQA2tvO6Gx4GRGnvFouoT0Ypi8YMDmjHJVvH8o_HPu0/edit#slide=id.p). 

I recommend everyone collaborate on the first Issue creation as well as fill in the initial information on the document. It doesn't need to be a final draft, so a brain dump will probably be helpful in building our research plan. 

Once the issues are created, please link them back to this Epic. We can review this Epic together in a couple of weeks.

**Comment by sanjumv** [comment]
@ryanfchase @hworthen  Closing this epic and moving its issues to functionality based epics
