### ISSUE TITLE
H2 2022 Research Plan Document

### ISSUE THREAD

**Issue by hworthen** [hackforla/311-data#1333]
### Overview 
We need to do X so that Y ...

### Action Items
To-do's for research plan document:

- [ ] -Background section
- [ ] -Methodology
- [ ] -Define participants
- [ ] -Create script and tasks

### Resources 
[311-Data Research Roadmap](https://docs.google.com/document/d/1dmtwTkiNj1pSycZqpn7S_Uk6vStUlS1-n_-rSq9IoEU/edit)
[TDM Calculator - Usability Testing Overview](https://github.com/hackforla/tdm-calculator/wiki/Usability-Testing-Overview)

**Comment by EchoProject** [comment]
I went ahead and updated the Labels. Let's get this added to the project board via the options on the right. Let me know if you're stuck.

**Comment by EchoProject** [comment]
Adding Ying to the issue. I've added the research roadmap link to the resources section of this issue.

**Comment by hworthen** [comment]
This is a repetitive issue and not currently needing to be addressed, so I am closing this.
