### ISSUE TITLE
TyperError: Cannot read properties of undefined (reading 'status') in action GET_METADATA_FAILURE

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1337]
**Describe the bug**
The error appears in the browser console:
  `TyperError: Cannot read properties of undefined (reading 'status')`

**To Reproduce**
1. Turn off your network connection (or place in airplane mode)
2. Start the client locally (per [instructions)](https://github.com/hackforla/311-data/blob/dev/client/README.md)
3. Open the site in Google Chrome and open the inspect window (F12 or Right-click > Inspect)
4. Go to the `Console` tab of the inspect window
5. Notice the error message ([image of console error](https://imgur.com/a/tI0bg0m))

**Expected behavior**
No error message

**Screenshots**
![Selection_999(2400)](https://user-images.githubusercontent.com/1448719/188284387-581f6e58-aa98-4bea-bb9a-57b167169947.jpg)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 105.0.5195.52 (Official Build) (64-bit)

**Additional context**

**Comment by edwinjue** [comment]
after doing some research, this can be corrected with [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) of the status property like this `response?.status`

**Comment by mc759** [comment]
Hey @edwinjue Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!
