### ISSUE TITLE
Reports Dropdown Menu inconsistent with existing summary dashboards

### ISSUE THREAD

**Issue by joshuayhwu** [hackforla/311-data#1350]
### Overview
The current dropdown menu of "Reports" is outdated as we combined our previous dashboards. Expected behavior is to have two items on the dropdown (Overview, Neighborhood), which links to the two new dashboards (overview_combined, nc_summary_comparison) respectively.
![Dev Website](https://user-images.githubusercontent.com/77765986/189200455-62f689a6-1971-4658-91ad-49c99981d7a7.PNG)

Currently, clicking on any of the dropdown would first bring to an index page (see screenshot), and clicking them in turn will bring one to the actual dashboards. @nichhk I would need some help from the engineering team to implement this change. 

### Action Items
- [ ] Remove the old reports dropdown [here](https://github.com/hackforla/311-data/blob/dev/client/components/Header.jsx#L84-L108) and replace with new links for the two new reports. The two new reports are the python files [here](https://github.com/hackforla/311-data/tree/dev/server/dash/dashboards). So the two new `Links` in Header.jsx would link to "/reports/dashboards/nc_summary_comparison" and "/reports/dashboards/overview"

### Resources/Instructions
[Code for summary dashboards](https://github.com/hackforla/311-data/tree/dev/server/dash/dashboards)

**Comment by nichhk** [comment]
@jekijo @edwinjue This should be a pretty straightforward task if either of you wants to take it on!

**Comment by edwinjue** [comment]
sure, sign me up

**Comment by nichhk** [comment]
No worries I am happy to do this now then.
