### ISSUE TITLE
Establish Typography, Margins, and Padding

### ISSUE THREAD

**Issue by melissahermes99** [hackforla/311-data#1357]
### Overview
It has been brought to attention, that throughout the creation of version two, not all text or spacing has followed the guidelines in the design system. This has made it more challenging to develop consistent pages. We need to adjust the most recent versions of each page in the file to follow the guidelines laid out in the design system. 
### Action Items
- [x] On each page, ensure the text follows the text styles as stated in the design system.
- [x] [ Use grids](https://www.figma.com/best-practices/everything-you-need-to-know-about-layout-grids/layout-grid-basics/) on each page to ensure that there are consistent margins and padding throughout the website. 
### Resources/Instructions
https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A5

**Comment by EchoProject** [comment]
Hi @melissahermes99 and @elizabeth-ux - Has this issue been completed? If so let's close. Thanks!
