### ISSUE TITLE
Selecting an ending date on map calendar date picker before a starting date results in a backwards range and no results

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1364]
### Overview
Selecting an ending date on map calendar date picker before a starting date results in a backwards range and no results

### Action Items

1. Open the calendar date picker on the map
2. Select Sept 17 as starting date
3. Select Sept 10 as the ending date
4. Notice the `Date Range` shows `9/17/2022 - 9/10/2022` and results on map are empty

![image](https://user-images.githubusercontent.com/1448719/190868810-8fa84e61-4c77-497a-8af5-10bff9fdba59.png)

### Resources/Instructions
- https://github.com/hackforla/311-data/issues/1396

**Comment by nichhk** [comment]
@jekijo, could you take this on? It should be familiar to you since you worked on disabling some of the dates in the calendar.

**Comment by jekijo** [comment]
Yeah I'll give it a go :thumbsup:

**Comment by mc759** [comment]
@jekijo Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!
