### ISSUE TITLE
Request Status: Open still displays "Closed" requests

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1365]
### Overview
Request Status: Open still displays "Closed" requests

### Action Items

1. Open `https://dev.311-data.org/map` in chrome
2. Press Ctrl + Shift + J to open developer tools (or right-click > Inspect)
3. Go to the `Network` Tab and clear
![image](https://user-images.githubusercontent.com/1448719/190869062-221bd1ef-20d2-4344-9664-0c639ac678ac.png)
4. Keep the `Network` Tab open and go to the Map calendar date picker and select:
- starting date: 8/1/2022 
- ending date: 8/1/2022
- confirm request status: open
![image](https://user-images.githubusercontent.com/1448719/190869293-688ca041-f5d2-4c3c-99e0-6bfba3d833fe.png)
6. Evaluate the response to the API call and click into it 
![image](https://user-images.githubusercontent.com/1448719/190869143-bcc53642-9890-4445-95de-c2f1669ebe36.png)
7. On the right-hand side, open the `Preview` pane
8. Drill down into entry `0` and notice the entry has a closedDate associated 
![image](https://user-images.githubusercontent.com/1448719/190869257-e55a187d-72c1-4a15-a6dd-458d6cec9bc1.png)

Since we are filtering for `open` requests, shouldn't any request with a `closed` date be excluded from the results?

**Comment by nichhk** [comment]
Edwin, does this still need to be open?

**Comment by edwinjue** [comment]
Yes, we can close
