### ISSUE TITLE
Need to update `contentful.com` to mirror the content in figma (e.g. - remove the `Privacy Policy` heading from the content area)

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1383]

**Comment by funbunch** [comment]
@edwinjue  @melissahermes99 @SophAm1 
Sorry for the delay. Could someone clarify again what this is? I do have access to Contentful.

**Comment by edwinjue** [comment]
Hi @funbunch, thanks for looking into this. I think we wanted to remove the redundant `Privacy Policy` heading in the content and move the paragraph up to that line (screenshot below). @melissahermes99 @SophAm1 are there are any other inconsistencies with the verbiage in the `Privacy Policy` that you would like Shannan to look into? Thanks

![image](https://user-images.githubusercontent.com/1448719/221380619-24bd0a0b-157f-4ff9-80f3-ca01642ec415.png)

**Comment by funbunch** [comment]
@edwinjue  
Oh I see. So in Contentful that is considered the 'title' and the field is required. It won't let us remove it. Open to any other suggestions or thoughts. @melissahermes99
