### ISSUE TITLE
Need to add the search feature to header of FAQs page (refer to v2 figma design - FAQs)

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1384]
### Resources ###
https://www.contentful.com/help/content-search/

**Comment by edwinjue** [comment]
We currently have a placeholder of the search input implemented. 

However, @tinazarb needs access to contentful.com to be able to implement the actual search functionality. 

@mc759 @EchoProject @SophAm1 @pras4u please advise on how to best provide her with the credentials

**Comment by tinazarb** [comment]
@melissahermes99 could I please ask for clarification on how we want this search to perform? In the Figma, it looks like the search is filtered by keywords in the search box, but I am not seeing keywords in Contenful. Feel free to let me know your direction on this!

**Comment by melissahermes99** [comment]
@tinazarb @edwinjue After discussing it tonight with Tina and @elizabeth-ux , we'd like to have to search be based off of keywords. For example, terms like funds, money, pay, and funded would prompt the question "How are Neighborhood Councils funded" to be suggested below the search bar. Is this what you were looking for? If not I'd be happy to clarify further!

**Comment by edwinjue** [comment]
As per @Graemo27, v2 iteration will not have a search feature
