### ISSUE TITLE
Selected information box on map has really large font

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1397]
### Overview
@ajmachado42 reported:

- [ ] I'm using Firefox and the formatting in the selected information box has really large font.

![image](https://user-images.githubusercontent.com/1448719/195465702-8c4675a6-d05a-4e77-8881-c5cd7e320fab.png)

### Resources
- https://github.com/hackforla/311-data/issues/1396

**Comment by edwinjue** [comment]
Hi @melissahermes99, do we have any specifications on the font sizes that should be used in the Location Details screen per the screenshot above? I wasn't able to find anything in the v2 finalized design in [figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=5153%3A18361). Thanks in advance!

**Comment by edwinjue** [comment]
How does the `INFORMATION` heading and `Council Name` look set at `24px`? 
This is the same size we're currently using for the `Filters & Settings` heading.

This is just an idea and will wait until you confirm. Thanks

![image](https://user-images.githubusercontent.com/1448719/195469436-bcd3c5a9-ed94-4121-941d-67279cf2cc6e.png)

**Comment by melissahermes99** [comment]
I think we might've decided to do away with the information box and opt for leaving the location in the address input area. Do you know if that's possible? That being said 24px looks perfect for all the menu headers! Thanks!

**Comment by edwinjue** [comment]
ok, 18px Oswald noted for menu headers. 

we'll have to see how leaving the location in the address input area will work out but i've noted this as well.

thanks!

**Comment by melissahermes99** [comment]
@edwinjue we just discussed and we want to be able to take away the information box in the future, but for now leave it as is. We're coming up with a solution to provide the information without cluttering the map.

**Comment by edwinjue** [comment]
@melissahermes99 sounds good. Please leave comment once you decide on what you would like to see.
