### ISSUE TITLE
Update Color of Reports Dropdown And The Page Selection Underline.

### ISSUE THREAD

**Issue by melissahermes99** [hackforla/311-data#1401]
### Overview
We need to change the background color on the reports menu dropdown to #0F181F and change the yellow underline #FFB100. Currently, the dropdown is #FFFFFF and the underline is #FFFF00. These need to be updated.

### Action Items
- [x] Update background color of the reports menu dropdown to #29404F
- [x] Update the yellow underlines for page selection to #FFB100
### Resources/Instructions
![image](https://user-images.githubusercontent.com/97048386/195474529-bc1ab77e-0764-44f7-9a78-69e62e3ddb1b.png)
![image](https://user-images.githubusercontent.com/97048386/195474549-7a8fa4ee-5bd8-4e27-8744-c6ccf6e182df.png)

**Comment by edwinjue** [comment]
@melissahermes99 marking this as closed because the requested changes have been merged to dev. Please take a look and let me know if this is what was expected. If you require any further customizations, please do so as a new issue. Thanks!

**Comment by nichhk** [comment]
![reports-dd-bg](https://user-images.githubusercontent.com/6537426/197882916-e5dcb9b9-bcde-4be7-b424-a156bdfd90d3.png)

I'm finding that there's not enough contrast between the text and the background. @melissahermes99 , do you have any suggestions? Thanks!

**Comment by melissahermes99** [comment]
Could we make the text and outlines #FFFFFF to look something like this? 
![image](https://user-images.githubusercontent.com/97048386/198117914-898b7491-e6da-40b2-8da2-d532b10aa856.png)

**Comment by edwinjue** [comment]
Hi @melissahermes99, thought I'd let you know I went ahead and implemented this locally just now. 

You can expect to see the change along with rest of the v2 Desktop Filter updates once they get approved

![image](https://user-images.githubusercontent.com/1448719/199867609-2d2dd55a-14bd-42df-a81c-e6066b76872b.png)

**Comment by edwinjue** [comment]
Perhaps, I should ask whether you would like the underline to always appear or only when the link is highlighted like this:

![image](https://user-images.githubusercontent.com/1448719/199868610-a2e3272a-78a5-41d9-a171-06f0202ecf0a.png)

Please let me know thanks!

**Comment by melissahermes99** [comment]
> rhaps, I should ask whether you would like the underline to always appear or only when the link is highlighted like this:

Sorry for the late reply, I was going through my missed notifications! Yes, we would like the underlines to only appear when an item is being hovered over. Also, would it be possible to remove the purple underline?

**Comment by melissahermes99** [comment]
Update as of 2/22/23 Color of drop downs should now be #29404F.
