### ISSUE TITLE
Discuss content & design of `Research` area

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1420]
### Overview
A `Research` tab was added to the v2 version of the dev site in #1411.

This issue was created to discuss the `Research` tab in terms of:
- [ ] Content
- [ ] Layout & Design

Therefore I have assigned @EchoProject @joshuayhwu @melissahermes99 and myself as initial collaborators

### Action Items
- [ ] Obtain access to `contentful` account (1Password)
- [ ] Decide what content to display  (DS Research? Updates?)
- [ ] Assign and provide a convenient means for content managers to update content
- [ ] Create Figma design for page
- [ ] Front-end implementation as per Figma

### Resources/Instructions
https://www.contentful.com/

![image](https://user-images.githubusercontent.com/1448719/201829475-5b77dc9b-c55f-4499-96c2-c75f62caa318.png)

**Comment by mc759** [comment]
Hey @edwinjue Do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by edwinjue** [comment]
Hi Michael, this is something that was communicated to me briefly before the end of H222.

Progress: Discussion still needs to take place among interested participants (i.e. whoever is interested in the Research area of our 311 page which includes a representative from PM, UI/UX and Engineering
Blockers: n/a
Availability: per @EchoProject/@mc759
ETA: n/a

**Comment by elizabeth-ux** [comment]
@edwinjue @ryanfchase - Per previous discussions with Melissa, Research page can be deleted for now as there is not enough content for the page. OK to close.
