### ISSUE TITLE
Alpha testing/ Bug Bashing 

### ISSUE THREAD

**Issue by yingli731** [hackforla/311-data#1421]
### Overview
We need to do Alpha testing to identify usability issues for the 311-data v.2. 

### Action Items

- [x] Create spreadsheet for Alpha Testing log
- [x] Have 311 team members look at the website and fill out the log
- [x] Analyze the log and present results

### Resources/Instructions
Link to the Alpha testing spreadsheet: https://docs.google.com/spreadsheets/d/1evIPBjzFBb32mCbeh3sGd3zWrx5qWVarpVN0ZN-QJCI/edit?usp=sharing

**Comment by SophAm1** [comment]
Congrats on successfully conducting alpha testing and help the team navigate bug bashing
