### ISSUE TITLE
[WHERE IS THIS???] Creating a new landing page with email collection

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1445]
### Overview
We need to replace the temporary landing page with a landing page that collects the emails of site visitors. The fastest way is to design a new website similar to 100 Automation. 100 Automation created a similar landing page with Mail Chimp so we can use their process and code. In the resources, I have linked the example Mail Chimp Page as well as the link to their notes and code for the page.  

### Action Items
- [x] Design a landing page that directs visitors to an email entry option within mail chimp 
- [x] Use the code from the 100 email automation and format it for 311 data
- [x] See if the ticketing link is necessary (check google analytics per Bonnie's recommendation)
- [x] Replace the original landing page with the new email entry option

### Resources/Instructions
Example of the 100 Automations [mail collection landing page ](https://100automations.github.io/landingpage/)

The [exact directions](https://github.com/hackforla/product-management/issues/132#issuecomment-913726964) for the new site using 100 Automation's process

Example message: "The 311 Data Site is temporarily down while we prepare for a new release. Check back again soon for an improved version of our original analytics tool. Please drop your email in the given box to get an update on the release of our product: [insert example email here]"  

Example message: "If you are looking to place a 311 ticket, please visit [Los Angeles's 311 System]"
Insert hyperlink with "Los Angeles's 311 System" to https://myla311.lacity.org/

**Comment by elizabeth-ux** [comment]
Here's the text for the email landing page. Background photo is fine.  [https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=6631%3A23007&t=dn0cM3JKUbY5fk5F-0
![Landing page](https://user-images.githubusercontent.com/20293568/220811965-f0d7c543-b3a6-43de-ae35-e06f64377946.png)

**Comment by edwinjue** [comment]
Thank you @elizabeth-ux. @melissahermes99 is this something you could help implement on Mail Chimp?

**Comment by melissahermes99** [comment]
@edwinjue Absolutely! I'll need to get connected to the 1Password first, just sent out a message to Bonnie about this! :)

**Comment by SophAm1** [comment]
Hi Everyone! @melissahermes99 created an email landing page within Mail Chimp under the campaigns tab. Whoever needs mail chimp access can reach out to me
