### ISSUE TITLE
Update FAQ with wording provided

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1467]
### Overview
Update FAQ with wording provided

### Action Items
- [ ] Log into Contentful and update FAQ with the following https://docs.google.com/document/d/1-ZvkaX6itAUTKvWQ6HjZc4Orkh6wQW-1ILFpkMAcAeE/edit

### Resources/Instructions
https://docs.google.com/document/d/1-ZvkaX6itAUTKvWQ6HjZc4Orkh6wQW-1ILFpkMAcAeE/edit

**Comment by chencc33** [comment]
Thanks for creating the issue. I have self-assigned this task. @edwinjue

**Comment by chencc33** [comment]
I have logged into Contentful and updated the FAQ content. The issue can be closed.
