### ISSUE TITLE
Usability Testing 

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1469]
Create a research plan to test out the product with members of the organization. This would complement the beta testing done with outside users and organizations 

- [ ] Create research plan
- [ ] Survey the 311 data team 
- [ ] Create an analysis of key team concerns 
- [ ] Create a research plan for usability testing 
- [ ] Conduct usability testing 

Dependency: V2 up and running, with new data dashboard ready for testing

**Comment by hworthen** [comment]
Closed because this is a repeat of issues we already have going.
