### ISSUE TITLE
Survey 311 data members on feature feedback

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1472]
We are hoping to create a survey that collects data on what features individual members of the 311 data would like feedback on when conducting future research studies.  

- [x] Create a plan for the survey
- [x] Write out questions for the survey 
- [x] Disperse survey in 311 data group
- [x] Remind members of survey during in-person meeting
- [ ] Analyze results from the survey to inform future testing

----
It might be helpful to incorporate demographics into the testing (ex/ engineering, background, time on the project, role, gender, etc) to get an understanding of where the survey results are coming from.

**Comment by hworthen** [comment]
I guess we did this but I don't really see how it is useful at this time. Will close.
