### ISSUE TITLE
Text Error with Metal Appliances Search Filter

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1473]
**Describe the bug**
When clicking on the "Metal Appliances Request", you receive results on the map with "Metal/Appliances" text not fitting within the given box. The "Metal/Appliances" text continues outside the box and onto the actual map. 

Also, the resulting text on the map is "Metal/Appliances" rather than matching the "Metal Appliances" text in the search filter. 

**To Reproduce**
1. Go to requests
2. Click on "Select/Deselect All" and then click on the "Metal Appliances" request filter
3. Scroll to the map
4. See "Metal/Appliances" text extending over the box 

**Expected behavior**
You expect to see the "Metal Appliances" fitting within the parameters of the address text box. 

**Screenshots**
<img width="1018" alt="Screen Shot 2023-02-23 at 4 01 58 PM" src="https://user-images.githubusercontent.com/121915799/221029462-122768a0-242d-49f7-ad06-24ccdf76b7b4.png">

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [safari]

**Additional context**

**Comment by edwinjue** [comment]
Thanks for looking into this @funbunch !
