### ISSUE TITLE
Update Wiki with Website Malfunction Postmortem

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1475]
The error that occurred this year with the website going down is cyclical and very likely to reoccur next year if we continue down the same course. We are hoping to create a postmortem that outlines the issues with the website so we can prevent the same loss from occurring again.

### Project Management
- [x] Create a google document for the project on google docs
- [x] Choose the post-mortem report template for the given issue
- [x] Populate the issue with the given headlines 
- [x] Populate the google document with matching headlines
- [x] Create a dedicated name for the project/issue 
- [x] Identify the people who were involved in the project 

### Report Substance
- [x] Identify the dates the problem occurred and when it was solved (dates the project was live, the site was down, the temporary landing page was down)
- [x] Incorporate the example post-mortem into the google document
- [x] Share the project with those individuals 
- [ ] Get analytics from data science team about the effects of the site malfunction

### Sharing Results
- [ ] Add the actual document to the Wiki
---
[Good Post-Mortem Template for this issue 
](https://tonylixu.medium.com/sre-a-good-postmortem-template-ed0c1901d096)
[Postmortem Google Doc](https://docs.google.com/document/d/1xK3-YfpsKfWBd4hPg9m512gS3nuYiN8p7o18cNx4DT4/edit)
[Website Wiki
](https://github.com/hackforla/311-data/wiki)

**Comment by edwinjue** [comment]
All the info for the write up is summed up in the first comment see "Overview": https://github.com/hackforla/311-data/issues/1436#issue-1531345716

**Comment by ryanfchase** [comment]
Deliverables were provided, but post-mortem was not uploaded to wiki. Closing as completed with a new ticket to publish this to the wiki: 
- https://github.com/hackforla/311-data/issues/1911
