### ISSUE TITLE
Data Asset Inventory

### ISSUE THREAD

**Issue by mc759** [hackforla/311-data#1490]
### Overview
To better organize and strategize around the Dashboard service of 311-data.org, the product team feels like it would be helpful to have an "inventory" of all the various assets the Data team has developed. Assets is broadly defined to include specific visualizations used on the dashboard to research reports that can be included in the Research/Blog section of the site. This inventory is meant to compliment the comparative analysis work being done to influence future changes. 

### To Do List

- [ ] Identify preferred tool to keep inventory (GitHub Issue? Google Sheets? Etc.)
- [ ] Document current assets by title, link to asset, date created, date updated, published (?) and anything else useful to the team
- [ ] Regularly add new assets to inventory as they are created

**Comment by joshuayhwu** [comment]
https://docs.google.com/spreadsheets/d/1H30i-oPhe1__Ih9MI76xbf533bnmvNhn_HPONEVIAe8/edit?usp=sharing
