### ISSUE TITLE
Agencies Involved Chart

### ISSUE THREAD

**Issue by melissahermes99** [hackforla/311-data#1517]
### Overview
We want to design a graph that tells the agencies involved in ticket resolution. This should ideally be a pie chart or bar graph. Data isn't currently available so work with plausible (but fake) numbers.

### Details
We want to have clear labels, titles and captions allowing the user to understand the meaning of the data clearly. We want to make the data accessible to readers without confusion.

### Action Items
- [ ] Create a pie chart or bar graph on Figma that tells the agencies involved in ticket resolution.
- [ ] Post a link to your graph in the comments
- [ ] Release dependency on #1506 

### Resources/Instructions
[Example Charts](https://docs.google.com/presentation/d/1Go9L5p_aIlZh-AJ3G0kPwGAeZapiyr4TBF-IdfHa33k/edit#slide=id.p)

**Comment by Y0shiPan** [comment]
https://www.figma.com/file/KuW8n0gSaMkwmFxzTce4Dz/311-Data-Personal-Workspace?type=design&node-id=0%3A1&t=UAFZiTs44DgZEsO3-1
