### ISSUE TITLE
311 Data Competitive Audit

### ISSUE THREAD

**Issue by SophAm1** [hackforla/311-data#1520]
### Overview
This is an issue to track progress on the competitive audit of the "311 Data Site". The issue serves as a checklist to be completed as you work on the analysis of the assigned site on Google Sheets. 

### Action Items
- [ ] Copy URL for project
- [ ] Insert Mission or Purpose from Site
- [ ] List users targeted 
- [ ] Answer the following questions on Data Displays:  
    - [ ] What data is being displayed?
    - [ ] And how is it being displayed?
    - [ ] What are the mechanisms to select the data to be displayed? (ex/ static or something users can choose)
- [ ] Questions about Map: 
   - [ ] Do they have a map?
   - [ ] How is the data related to the map?
- [ ] Questions about Stories: 
  - [ ] What types of stories are they telling with their data?
  - [ ] Do the stories tell a coherent message?
  - [ ] Does the data seem to be displayed randomly?
  - [ ] How does this relate to the website's overall goal or mission?
- [ ] Maps 
  - [ ] What are the pros of the map feature?
  - [ ] What are the cons of the map feature?
- [ ] Help Text or Explanations for Users
  - [ ] What text is offered to help support users?
- [ ] Release dependency on #1483

**Comment by hworthen** [comment]
Done. See EPIC https://github.com/hackforla/311-data/issues/1483 for links to deliverables.
