### ISSUE TITLE
Create bare containers to establish general layout

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#153]
### Overview
Itll be best to clear out all the nonsense we've created thus far and start fresh. This ticket will establish the bare layout components that more specific components can be built into.

## Status
Progress: Header is complete. Body and Footer 50%
Blocks: None
Availability: 
ETA: Complete on 1/28

### Action Items
- [x] Clear out old stuff
- [x] Start with the new stuff
- [x] Get clear base layout
  - [x] Header
  - [ ] Sticky left nav/filters
  - [ ] Body
### Resources/Instructions
See this mock for reference https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=42%3A787

**Comment by ExperimentsInHonesty** [comment]
@adamkendis will reach out to @brodly to find out status and see if he need to take the ticket over.
