### ISSUE TITLE
Set up a cron job via github actions to update data nightly 

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1535]
### Overview
Basically port over this workflow to the new tech stack:
https://github.com/edwinjue/311-data-v2-gh-pages/blob/main/.github/workflows/hfUpdate.yml

### Resources/Instructions
https://github.com/edwinjue/311-data-v2-gh-pages/blob/main/.github/workflows/hfUpdate.yml

**Comment by Girishbari** [comment]
didnt understand the statement "Are you expecting a change in main.yml from hfUpdate.yml (from the link you mentioned)"

**Comment by bberhane** [comment]
@mru-hub Howdy! Is this job still being worked on?

**Comment by ryanfchase** [comment]
I think this ticket is actually done, we are getting 2024 data nightly.

Worth noting, I don't think our updateHfDataset.py previous year data -- @Skydodle does that sound correct? I guess the caveat is that only 2024 data is expected to change, but I suppose we can't know that for certain. 

I'm still going to close this ticket, but I'll be bringing this ticket up in discussion on the next engineering meeting.

**Comment by Skydodle** [comment]
> I think this ticket is actually done, we are getting 2024 data nightly.
> 
> Worth noting, I don't think our updateHfDataset.py previous year data -- @Skydodle does that sound correct? I guess the caveat is that only 2024 data is expected to change, but I suppose we can't know that for certain.
> 
> I'm still going to close this ticket, but I'll be bringing this ticket up in discussion on the next engineering meeting.

Yes correct, the cron job only updates 2024 or current year data. The prior years data are completed and therefore does not need to update daily.
