### ISSUE TITLE
Spike: Fix contact form to use frontend-only service

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1536]
### Overview
We need to fix entire workflow from when submit button gets clicked on the contact form to having the submission appear in a github issue, so that we can know when to process requests.

### Action Items

- [x] Review the original code from 311-data:
- [x] Identify if any of it is reusable
- [x] define plan for how we will restructure to account for no backend
- [x] get plan sign-off from dev lead and product
- [x] document findings and create an issue to implement

#### Original code locations
- https://github.com/edwinjue/311-data-v2/blob/6ea06bc6c5a0dbee18cd6a19a10661e4db5bb05c/redux/sagas/data.js#L68
- [API endpoint code](https://github.com/hackforla/311-data/blob/a129468e9d6e9fa170b81174d007e813b31dcfd1/server/api/code/lacity_data_api/routers/shim.py#L123)
-  [github code](https://github.com/hackforla/311-data/blob/dev/server/api/code/lacity_data_api/services/github.py)
   - await github.create_issue(feedback.title, feedback.body)
   - await github.add_issue_to_project(id)	  
- [email code](https://github.com/hackforla/311-data/blob/dev/server/api/code/lacity_data_api/services/email.py) 
   - await email.respond_to_feedback(feedback.body, number)

**Comment by edwinjue** [comment]
@alexlaw528 Thank you so much for being so proactive on this! I will take a look when I have some time in the evening. In the meanwhile, feel free to fork our main branch into your own personal github repo to get started. Once we have something working on your own personal repo, we can work together to port it over to 311-data. I really appreciate it and will follow up later!

**Comment by ryanfchase** [comment]
@traycn 's suggestions (she will expand on these in her work)
- https://docs.github.com/en/rest/issues?apiVersion=2022-11-28
- https://www.emailjs.com/

**Comment by traycn** [comment]
Availability: 
2/2 - 2/5: 4AM - 9AM PT

**Comment by Skydodle** [comment]
@traycn thank you so much for picking up this issue! Just a gentle reminder to move this issue to 'in progress' on the Project Board as soon as you assign yourself so that this issue will no longer be on the 'priortized backlog' for other devs to pick up. Thanks again!

**Comment by traycn** [comment]
## Solution Proposal:
Add 2 events after the existing form is submitted. For reference to the data we are using, the values we are collecting on the forms submit are below.
```
// Contact Form field values:
{
     FirstName,
     LastName,
     Email,
     Association (optional),
     Message
}
```

### Event 1: Create a new Github Issue:
Create a Github Issue using [Octokit/Core.js](https://github.com/octokit/core.js#readme). Documentation for the Create an issue POST [here](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue).
- Set contact form field values into the POST request body as follows:
```
// Octokit - Create a Github Issue POST 
{
    owner: 'hackforla',
    repo: '311-data',
    title: 'Contact Form - {FirstName, LastName Association}',
    body: '{FirstName, ` `, LastName,` `, Association} <br>
             Email - {Email} <br>
             Message - {Message}
          ',
    assignees: [
      '[insert default assignee here]'
    ],
    milestone: [insert default milestone here],
    labels: [
      'bug'
    ],
    headers: {
      'X-GitHub-Api-Version': '2022-11-28'
    }
}
```
On **success** trigger to send an email. Refer to Event 2.

### Event 2: Send an email using EmailJS
Documentation for the sendForm() function [here](https://www.emailjs.com/docs/tutorial/creating-contact-form/). 

-----
### Development work:
Loc: 311-data.components.contact.ContactForm.jsx

### Event 1:
- Create a personal access token for HackForLA github account, docs [here](https://github.com/settings/tokens/new?scopes=repo).

#### For the 311-Data repo
- Install octokit/core.js package [here](https://www.npmjs.com/package/@octokit/core).
- Create octokit instance w/access token (do not make this token public)
  - Write a octokit.request POST function with the previous mentioned code snippet of the data model.
  - Execute the octokit.request POST function on the contact form submit.

### Event 2:
- Create a EmailJS account using HackForLA, sign up [here](https://dashboard.emailjs.com/sign-up).
  - Create an email service. 
  - Create an email template.
  - Gather the email service and email template ID.

#### For the 311-Data repo
- Create the sendForm() function, doc [here](https://www.emailjs.com/docs/tutorial/creating-contact-form/) with the email service and template ID.
  - Define values of request body based on `Contact Form field values` and `Email template values`.
  - Execute the sendForm() function after receiving a 201 code response from Octokit.

--
Let me know your thoughts on this proposal @ryanfchase @edwinjue

**Comment by traycn** [comment]
Created new issue for the Spike item: https://github.com/hackforla/311-data/issues/1682
