### ISSUE TITLE
Once MVP, we need to add test cases and implement automated tests

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1541]
### Overview
Once we have a minimum viable product (MVP), we should implement some automated tests to account for any bugs/regression when developing features post MVP

This should be done preferably using Jest + RTL

### Resources/Instructions
- https://github.com/hackforla/311-data/issues/1334

**Comment by ExperimentsInHonesty** [comment]
- Closing because its a Duplicate issue to #1334
