### ISSUE TITLE
Update 311-data README HuggingFace Link

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1544]
### Overview
We need to change the Readme's  Huggingface link to point to our 311 Data HuggingFace repo because it is pointing to Edwin's repo and it needs to point to 311's repo instead.

### Action Items

- [x] Update the Resource labeled "CSV and parquet datasets are also available here at huggingface.co" to link to https://huggingface.co/311-data

### Resources/Instructions

- [README Resources section](https://github.com/hackforla/311-data?tab=readme-ov-file#resources)
- [311 Data HuggingFace repo URL](https://huggingface.co/311-data)

--------

> Overview (Old)
Need a volunteer to review the README file in our current 311-data repo, remove all references to the old tech stack as well as any outdated links.  This person should collaborate with the individual working on #1543 to leverage their work and to update the README with relevant technical documentation and links wherever appropriate 

> Action Items (Old)
Remove old tech stack references/documentation/links
Add new tech stack documentation/links

**Comment by ryanfchase** [comment]
I think this ticket needs to be revisited. Dev has contributed towards documentation, but I'm going to clear assignees until someone is actively working on this or actively modifying the ticket.

**Comment by ryanfchase** [comment]
Ticket is prioritized and ready to be picked up.

**Comment by ryanfchase** [comment]
@dantor09 this ticket will close when you merge your approved PRs, thanks!
