### ISSUE TITLE
Create neighborhood council selector

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#155]
### Overview
Searchable/filterable checkbox list, dataset can come from a constants file/definition

### Action Items
- [x] Create constants with all neighborhood councils
- [x] Search bar
- [x] Checkboxes
- [x] As characters are typed, filter down the checkbox list
  - [ ] ***BONUS POINTS*** Use a Trie to implement this feature

### 
ETA: 2/11
Availability: Weekdays slack
Blockers: none

### Resources/Instructions
Use [this](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=16%3A4) mock for reference

**Comment by yuenyilam** [comment]
Section looks like this
<img width="591" alt="Screen Shot 2020-01-14 at 8 01 26 PM" src="https://user-images.githubusercontent.com/59905241/72404005-c013a380-3708-11ea-84b9-07e1fb6d998c.png">

**Comment by johnr54321** [comment]
ETA: 2/18.

**Comment by adamkendis** [comment]
Closed by #259
