### ISSUE TITLE
Can Backstop.js can help with our frontend development process?

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1550]
### Overview
Need a volunteer to take a look at backstop.js to see whether it can somehow improve our frontend development workflow

https://github.com/garris/BackstopJS

I've seen other projects use its scrubber feature to see how frontend changes appear visually between iterations of code. 

![BackstopJS_scrubber_mode-xHWeJIfqUC8--00_00_06_to_00_00_10](https://github.com/hackforla/311-data/assets/1448719/7190e15c-8bd6-494e-9421-f263ba7d5652)

It might be useful to see how something looks visually compared to a previous version before committing changes to our codebase and backstop.js could help with this.  

### Action Items

- [ ] Get backstop.js to work with our current NRD stack on localhost
- [ ] Explore its features
- [ ] Summarize the setup process and compile a list of useful features in a write-up/documentation to share with other volunteers
- [ ] Team to review documentation and perform independent setup/review of features
- [ ] Discuss among team to see how and if it can be useful for our development workflow

### Resources/Instructions
https://github.com/garris/BackstopJS

**Comment by dreabd** [comment]
Thus far been running into an issue where when BackstopJs is trying to capture a screenshot it produces a blank page. This occurs in all versions but it was able to pass the smoke test (built in test for BackstopJs). A little lost on how to approach this problem.

**Comment by bberhane** [comment]
@ryanfchase Not sure if this is still in progress

**Comment by ryanfchase** [comment]
This ticket is being closed as won't do. Thanks @edwinjue and @dreabd for putting the time to look into this 🙏
