### ISSUE TITLE
2023-08-16 - 311 Data PM Weekly Meeting

### ISSUE THREAD

**Issue by MBasil03** [hackforla/311-data#1551]
## YYYY-MM-DD - 311 Data Weekly Meeting
_[Back to Top](#)_

### AGENDA
_Timezones listed as Pacific Time._

- [ ] 7:00PM _5 min_ - Check-in
- [ ] 7:05 _20 min_ - Team announcements + updates
1. We need to get the v2 site working again (updates on this)
2. Decide if we want to continue building upon v2
3. Who should be the target audience for v2 (maybe engage with activists instead of NC members?)
- [ ] 7:25 _20 min_ - TBD
- [ ] 7:45 _15 min_ - Breakout Rooms
- [ ] 8:00 fin

### Resources/Instructions

---
#### Content/Marketing/Copywriting
- [ ] TBD

#### UNASSIGNED
- [x] nobody

**Comment by ryanfchase** [comment]
Closing this issue since it should live on the 311 Data Weekly Meeting Agenda issue (https://github.com/hackforla/311-data/issues/1545#issuecomment-1681383682)
