### ISSUE TITLE
Request type selectors

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#156]
### Overview
This component will show all the possible request types to filter on. Upon (de)selecting, data represented will change.

### Action Items
- [x] Create constant definitions for all request types
  - [x] Maybe include a mapping for abbreviations? (See mock)
- [x] Need callback/event on any item (de)selected

### Resources/Instructions
See [this](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=16%3A4) mock

### Resume credit
- Created function component tied to Redux Data Layer.

**Comment by yuenyilam** [comment]
This is what the request type section looks like
<img width="559" alt="Screen Shot 2020-01-14 at 7 57 06 PM" src="https://user-images.githubusercontent.com/59905241/72403788-1a603480-3708-11ea-8f22-80b57d1507b2.png">

**Comment by adamkendis** [comment]
@sellnat77 @brodly @itsjoycelee 
Are we including 'Report Water Waste' in request types? If so, we're missing it in the mockup. It appears to be a valid request type on the city's end, at least as of the end of last year.

<img width="500" alt="Screen Shot 2020-02-14 at 1 48 24 PM" src="https://user-images.githubusercontent.com/40484278/74570107-cf1c8a00-4f30-11ea-9daa-05499e360034.png">

**Comment by itsjoycelee** [comment]
@adamkendis , I believe we were originally requested by the neighborhood council for the 11 request types shown in our original screenshot. @johnr54321 - can you advise whether we should add it?

**Comment by sellnat77** [comment]
Does the water waste request exist in previous years? Or just 2019+?

**Comment by brodly** [comment]
This list was a quick one put together during prototyping. we should spend some time looking at all request types and update our constants file to reflect whatever we can query through socrata
