### ISSUE TITLE
Site Map: Outline Current Information Architecture

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1565]
### Overview
We need a current version of what the site map is looking like in order to better understand and organize the IA for V2 + V3 future iterations.

### Action Items
- [x] Look through most updated wireframes page on Figma
- [x] Create a new page in the Figma titled Site Map
- [x] Create a new site map based on the existing wireframes or using https://edwinjue.github.io/311-data-v2-gh-pages/#/map
- [x] Add a legend for the site map

### Resources/Instructions
Please use a new page in Figma or Figjam to add the site map.

**Comment by ryanfchase** [comment]
closing as done
