### ISSUE TITLE
Dashboard (Overview Screen) Redesign

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1567]
### Overview
Redesign the Overview Dashboard for V2 for improved usability + data visualization

### Action Items
- [x] Gather insights from team meeting (8/28) regarding data visualizations + current designs
- [x] Workshop to update charts (with Ryan) + identify possible constraints
- [x] Mockup charts for usability + accessibility, following best practices
- [x] Iterate & finalize designs based on feedback

### Resources/Instructions
Figma: https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=3266%3A14&mode=design&t=T9dBZ9jiP2UrsYmO-1

**Comment by edwinjue** [comment]
Hi @annaseulgi @ryanfchase how are you? Hope you're having a wonderful weekend!

Just noticed this issue and would like to know whether it relates to #1505? Just thought I'd ask before I let anyone on engineering proceed with any sort of implementation.

Thanks

**Comment by edwinjue** [comment]
Hi @annaseulgi @ryanfchase how are you? Hope you're having a wonderful weekend!

Just noticed this issue and would like to know whether it relates to #1505? I thought I'd ask before I let anyone on engineering proceed with any implementation.

Thanks

**Comment by annaseulgi** [comment]
Hi @edwinjue  @ryanfchase 
I'm working on the redesign right now which might take a couple of days. Not sure if it would be best for engineering to proceed since we're also still working on redesigning the charts for the dashboard as well.

Let me know if that clarifies anything! Will update once it's ready to be developed.
Thanks for checking

**Comment by annaseulgi** [comment]
@ryanfchase Dashboard redesigns are complete. Please view designs in the Figma under the page title: ⭐ Version 1.2 Launch 10/2023-TBD

**Comment by edwinjue** [comment]
Hi @annaseulgi, can you paste a link to the figma? Thanks!

**Comment by ryanfchase** [comment]
Completed Figma: https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=3266%3A14&mode=design&t=T9dBZ9jiP2UrsYmO-1

**Comment by ryanfchase** [comment]
Closing as done
