### ISSUE TITLE
Do background research on these personas (we have started looking through minutes of NC meetings to create NC member personas, for example)

### ISSUE THREAD

**Issue by hworthen** [hackforla/311-data#1570]
We (the research and design teams) have two research tasks planned:

**Task 1 (whole team task):**
We are going to analyze the amount and type of 311 service request from January 1st to Sept 1st, 2023 for each of these 12 neighborhoods that represent a diverse handful of the NCs in LA.  The goal is to get information about what types of service requests are more common in which neighborhoods, which we will then  use to create personas from a handful of these neighborhoods. Neighborhood councils are divided up like this: 

1.  Bel Air-Beverly Crest–HOLLY
2. Boyle Heights– GRAEM
3.  CANNDU–ANNA
4. Echo Park–ALLISON
5. Empowerment Congress Central–ANGELA
6. Lincoln Heights–LUAN
7. Mid-City West–EMILY
8. Panorama City–PAUL
9.  Porter Ranch–ONWUBU
10.  Reseda--ANGELA
11. West Adams--ANGELA
12.  Wilshire Center-Koreatown–PETER

The data for of all the service requests for the time period mentioned can be found in sheet 1 of this excel spreadsheet.  
[MyLA311_Service_Request_Data_2023.xls](https://github.com/hackforla/311-data/files/12508911/MyLA311_Service_Request_Data_2023.xls)

You will need to filter for your NC (see sheet two as an example), and then analyze the amount and type of service requests for your NC (see sheet 3 as an example and for links to helpful YouTube tutorials on how to use excel features).   

Upload your completed analysis (please put the name of the NC in the spreadsheet title) to this google drive folder before the team meeting on September 13: https://drive.google.com/drive/folders/1w9ShLx_CcvMWOWxFcrlRwWRDpii3GPMu?usp=sharing

**Task 2 (Peter, Allison, and Holly):**
Peter and Allison are going to a real live NC meeting! And will try to talk with an NC council member! Here is the research guide for this task: https://docs.google.com/document/d/1m3xfKWgFJL2qS2T1m_gmMFjYqJZKyljWLgJCGslutjY/edit?usp=sharing. 

Peter, Allison, and Holly will do a zoom session to strategize how to do the interviews.

**Comment by annaseulgi** [comment]
Excel shortcut to filter by NC: select Data, select autofilter, select all (to deselect), select your neighborhood district
