### ISSUE TITLE
Design template for personas

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1579]
The Research and Design teams want to create a persona for NC members to better understand the user's needs, pain points, and background.

- [ ] Create a template using brand colors + type settings for personas in Figma by next week's meeting 9/20/2023

Note: The template does not need to include actual content. 

Resources: Figma file

**Comment by Joy-Truex** [comment]
https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=3266-2&mode=design
