### ISSUE TITLE
Create consistent styling

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#158]
### Overview
In order to keep all frontend work consistent, we will adopt the stylguide in figma to a constant stylesheet

### Action Items
- [x] Establish fonts
  - [ ] Heading
  - [ ] Sub-Heading
  - [ ] Body
- [x] Establish color scheming
  - [ ] Fonts
  - [ ] Background
  - [ ] Brand Primary
  - [ ] Brand Secondary
  - [ ] Brand Main
  - [ ] Form Stroke
- [x] Check boxes
  - [ ] Coloration
  - [ ] Drop shadows
  - Might want to separate this into its own component ticket
- [x] Calendar Selector
  - [ ] Colors
  - [ ] Boxes etc
  - Might want to separate this into its own component ticket

When complete, make sure to nitify all front end devs so we can all adopt the correct naming schemes to use consistent styling

### Resources/Instructions
See [this](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=16%3A4) mock for reference and values

**Comment by ExperimentsInHonesty** [comment]
@KChorseraddish  please update with:
1. Progress
2. Blocks
3. Availability
4. ETA
