### ISSUE TITLE
FAQ Page: Design to Engineering Handoff

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1583]
### Overview
- @Graemo27 has finished design work for 311 Data (V2)'s FAQ page and would like to hand it off to engineering

### Action Items
Design
- [x] all Figma pages are accessible to engineering
- [x] confirm scope of the requested changes / additions
- [x] provide before/after (in the future this will be useful for client meetings)

Engineering
- [x] confirm all components and styles are technically feasible
- [x] confirm state changes and behaviors are technically feasible

Final Action
- [ ] create github issues for engineering to make requested changes

**Comment by Graemo27** [comment]
https://www.figma.com/file/SXUc2MnxTptcRdiB3PAd7b/FAQ?type=design&node-id=64%3A2757&mode=design&t=0zsa7u9TngsVj7y0-1

**Comment by ryanfchase** [comment]
moving this to closed and will create new Engineering tickets soon
