### ISSUE TITLE
New feature to allow end users to export 311 requests data to CSV using Map filters directly from the Map page

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1586]
### Overview
Allow end users to generate extracts of 311 requests data directly from the Map page. An end user should be able to apply any combination of filters on the map and be able to download this subset of data in CSV format. This feature would allow the end user to generate extracts similar to the one requested in #1566.

### Action Items
- [x] Create a temporary button on the Map page. (This button can be placed anywhere on the Map page for the time being. Volunteer will collaborate with UI/UX team to determine the finalize placement of button/link later. For now, volunteer will focus primarily on the export functionality). 
- [x] When this button gets clicked, it should trigger a custom DuckDb SQL query to return a subset of the request data in CSV format according to the filters selected in the `Filter` menu (on the left-hand side of the map)
- [ ] Successful execution of this query will initiate a file download whereas an error condition will display an error  [toast](https://fkhadra.github.io/react-toastify/introduction/) on the bottom right-hand side of the Map

### Resources/Instructions
[Example request](https://github.com/hackforla/311-data/issues/1566)
[Example DuckDb queries used in 1566](https://gist.github.com/edwinjue/35bf6b91cad008fcdb41afa203e866d3)
[How to export data in DuckDb](https://duckdb.org/docs/sql/statements/copy#copy-to)
[What is a toast?](https://fkhadra.github.io/react-toastify/introduction/)

**Comment by sophia-bui** [comment]
Update for 9/27 meeting:
Created temporary export button. 
Currently working on functionality.
