### ISSUE TITLE
Create map body

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#159]
### Overview
Create the bare map body for the visualization. 

### Action Items
- [x] Explore different map providers
- [x] Support heat map functionality
- [x] Support pin functionality
- [x] Support pin detail functionality
- [x] Support pin detail detail functionality
For all of the above ^^ Create dummy json files to mock the backend

- [x] Update map as user click & drags around

### Resources/Instructions
See [this](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=42%3A787) mock for reference

**Comment by yuenyilam** [comment]
<img width="430" alt="Screen Shot 2020-01-21 at 8 32 36 PM" src="https://user-images.githubusercontent.com/59905241/72865563-2e1e1480-3c8d-11ea-9eee-826471357643.png">

**Comment by adamkendis** [comment]
**Status:** Looking into react-leaflet overlays for heatmap/clustering. Trying to find plugins that are actively maintained and compatible with react-leaflet v2.
**Blockers:** None.
**Availability:** Available via Slack/github discussion. 
**ETA:** Difficult to estimate at the moment. Picked up the ticket today, 2/20/2020. Ticket may be split into smaller issues after map options are researched.

**Some resources:**
https://github.com/PaulLeCam/react-leaflet/blob/master/docs/plugins.md
https://github.com/OpenGov/react-leaflet-cluster-layer - does not appear to be actively maintained, may not be compatible with v2
https://github.com/OpenGov/react-leaflet-heatmap-layer#readme - compatible with v2

**Comment by johnr54321** [comment]
Adam will have this split into smaller issues by this coming Tuesday 2/25.

**Comment by adamkendis** [comment]
**Status:** Been extremely blocked by life stuff the past week - no opportunity to put much work into this ticket. Josh pushed some fixes in PR 309, so the base map might be done. Two packages that will handle the layers we need are below. Will put time into it this weekend.
**Availability:** Slack/github.
**ETA:** 3/5 for map complete.

https://www.npmjs.com/package/react-leaflet-heatmap-layer
https://www.npmjs.com/package/react-leaflet-markercluster
