### ISSUE TITLE
Semantic Versioning: Spike + Guide

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1591]
### Overview
We need to implement Semantic Versioning into our 311-Data product launches.

### Action Items
- [x] basic research on semantic versioning
- [x] determine 311-Data's official version number (for our upcoming release)
- [ ] create a Wiki page that outlines how 311-Data should version future releases (create a guide)

**Comment by annaseulgi** [comment]
Basic research: I found a good rule of thumb is to follow Semantic Versioning https://semver.org/.

Here’s an example: version 1.9.0.1
1: Major revision (new UI, new features, conceptual change, etc)
9: Minor revision (change to an existing feature, adding 1 new feature, collection of bug fixes)
0: Bug fix release
1: Build number (if applicable — usually not used)

**Comment by ryanfchase** [comment]
Moving ticket to Prioritized Backlog until a PM is ready to carry out the subsequent action items.

**Comment by ryanfchase** [comment]
Update: based on Product Planning meeting, PMs and Leads decided on calling the upcoming launch "311-Data v1.2", which will includes the features Map, and FAQ page. We will consider the product at MVP once we have the Map, FAQ page, and Dashboard. We estimate we can get the Dashboard incorporated in a 311-Data v1.3 release.

We hope to incorporate this versioning system into our milestones (see progress on #1582)
