### ISSUE TITLE
Implement new v2 FAQ

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1593]
### Overview
We will need volunteers to help update our FAQ page from our current design to the new v2 design

For the new v2 design specifications refer to: [FAQ v2 Figma Design](https://www.figma.com/file/SXUc2MnxTptcRdiB3PAd7b/FAQ?node-id=64%3A2757&mode=dev) 

### Action Items
- [ ] Create a new local branch in development called `1593-FAQv2-[your github id]`
- [ ] Familiarize yourself with code in [/components/main/Faqs.jsx](https://github.com/hackforla/311-data/blob/main/components/main/Faqs.jsx)
- [ ] Trace the code to see how the [ThemeProvider](https://github.com/hackforla/311-data/blob/main/index.js) works. Click here to learn more about [MUI ThemeProvider](https://mui.com/material-ui/customization/theming/)
- [ ] Trace the code in [Routes.jsx](https://github.com/hackforla/311-data/blob/main/Routes.jsx) and take note that our codebase utilizes one theme for the Map ([darkTheme](https://github.com/hackforla/311-data/blob/8c2281d6d5b2b286751140aae36f1735aa6d3bad/theme/theme.js#L44)) and another theme for content pages like FAQ, Privacy, etc... ([lightTheme](https://github.com/hackforla/311-data/blob/8c2281d6d5b2b286751140aae36f1735aa6d3bad/theme/theme.js#L25))
- [ ] Consider all changes needed to our [theme.js](https://github.com/hackforla/311-data/blob/main/theme/theme.js) to reflect the changes in [FAQ v2 Figma Design](https://www.figma.com/file/SXUc2MnxTptcRdiB3PAd7b/FAQ?node-id=64%3A2757&mode=dev) regarding:
  - [ ] colors 
  - [ ] fonts
  - [ ] gaps
  - [ ] layout
  - [ ] styles
  - [ ] typography
- [ ] Please use the developer inspect tool in Figma to obtain the values for each element of the FAQ page:
![image](https://github.com/hackforla/311-data/assets/1448719/fa3ca18a-061a-4de8-9696-6130de843b7a)
- [ ] Update each file accordingly https://github.com/hackforla/311-data/tree/main/theme
  - [ ] colors.js
  - [ ] fonts.js
  - [ ] gaps.js
  - [ ] layout.js
  - [ ] styles.js
  - [ ] typography.js
- [ ] Add any new icons/images to [assets](https://github.com/hackforla/311-data/tree/main/assets)
- [ ] Update the code in [/components/main/Faqs.jsx](https://github.com/hackforla/311-data/blob/main/components/main/Faqs.jsx) to display new icons/images

### Resources/Instructions
- [ ] [FAQ v2 Figma Design](https://www.figma.com/file/SXUc2MnxTptcRdiB3PAd7b/FAQ?node-id=64%3A2757&mode=dev) 
- [ ] #1583
- [ ] https://mui.com/material-ui/customization/theming/

**Comment by ryanfchase** [comment]
I think we need to kick this back to Icebox since the FAQ design is in flux at the moment. Reason: FAQ designs are in flux and are not ready for hand-off. Engineering requirements subject to change

@aramattamara sorry for delaying your work on this! Let me know if I can un-assign you and move this to Icebox. Will check back on  1/31 meeting

**Comment by ryanfchase** [comment]
Going to close this ticket as Wont Do, closing the PR as the code and designs are out of date.
