### ISSUE TITLE
Loading screen low-fi iterations

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1594]
### Background
- Problem: stakeholders need for there to be clear information that the map is from a volunteer organization separate from the city due to users being confused (if there are technical difficulties, they go to the city)
- Solution: have a modal w/ overlay on the map for users to see while the map is loading in the background
- Deliverable: Mock up a low fidelity screen with a possible solution & document your design decisions
- Objective: Ideate ways to make it clear for users the interactive map is from Hack for LA, not LA city government

### Deliverable Guidelines: 
- [x] Designers need to create an individual figma page in the file labeled with their first and last name
- [x] Analyze the current designs (either loading modal in github or the about me page). What looks good? What doesn’t? What would you change?
- [x] Mock up a low fidelity screen with a possible solution & document your design decisions

Due Date: 10/18/2023 (next week)

### Resources
Figma: https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=8440%3A7466&mode=design&t=dFKggzL4lq6E2Pmq-1

**Comment by ryanfchase** [comment]
Seeing that design lead moved this issue to done. I'm going to close this issue as completed.
