### ISSUE TITLE
Internal Bug testing of V 1.2

### ISSUE THREAD

**Issue by hworthen** [hackforla/311-data#1596]
### Overview
We need to test the map for bugs or weirdness. We will do this internally with our team before we launch V 1.2!

Map page: https://hackforla.github.io/311-data

### Action Items

- [x] Create a research plan and link to research roadmap
- [x] Create a usability test script
- [x] Find team members who want to participate and schedule the test
- [x] Run tests
- [x] Analyze results
- [x] Present results to team

### Resources/Instructions

- [Presentation on the results](https://docs.google.com/presentation/d/1NBMnS8_znCnYNDNNQrN2Jh5GQZhZmX56rtHME-EewBY/edit?usp=sharing)
- [action steps spreadsheet](https://docs.google.com/spreadsheets/d/1y_8xUCxEU83adN2GjEIOt3F-wILJ1_c2KdgISFRN5cU/edit?usp=sharing)

**Comment by annaseulgi** [comment]
Hi all, the script looks amazing! The design team really values research to help us make research-informed design choices so thank you all for doing this. I added a few comments to the document as well as an additional task/idea if it would be okay to incorporate. Please let me know what you think! 

(Disclaimer: I've only conducted a handful of moderated usability tests so I am definitely not an experienced researcher - please take any of my comments or feedback with that in mind 👍 )

https://docs.google.com/document/d/1wgf7Jcxz5mqRDqAZkxc2Cz87wyD_aeVJ_YvO4g2OVPU/edit
