### ISSUE TITLE
Identify all organizations that 311-Data may want to partner with

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1597]
### Overview
We want to get a list of Civic Tech Orgs to invite to 2023 H4LA Holiday party. We're looking for other organizations that are volunteer-based, and are focused on civic issues. Need to be able to "split up work" with them. Can consider orgs that combine tech and protected classes.

### Deadline
Tentative by 10/19 so Bonnie can start doing outreach

### Action Items
1. collect URLs of Civic Tech Orgs that do work that we may be interested in working with
2. add comment [here](https://github.com/hackforla/governance/issues/88) with list of Tech Orgs

**Comment by ryanfchase** [comment]
I reached out to a contact I have in the LA civic tech engagement space. I will be reporting any useful info that they can pass along.

**Comment by bberhane** [comment]
Since doc is view only, posting Google Doc until I can transfer to the org doc: https://docs.google.com/document/d/1BncbDONW6yzgPd-snrsJOUhJUa2DileGQx919AHGfRE/edit?usp=sharing
