### ISSUE TITLE
Pin/Heat map toggle

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#160]
### Overview
This component will toggle the map component from heat map to pin map

### Action Items
- [ ] Create toggle ui
- [ ] Add loading feedback
  - This will be one of the sources of long wait times
- [ ] Ensure the backing map does not re-render, just the overlay of pins/heat

### Resources/Instructions
See [this](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=42%3A787) mock for reference

**Comment by ExperimentsInHonesty** [comment]
Replaced by larger issue #180
