### ISSUE TITLE
Map Redesign Updates for V1.2

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1601]
### Overview
Fix accessibility issues regarding the map for V1.2 launch

### Action Items
- Reference previous design team's designs that are located in Figma but were never implemented

### Resources/Instructions
Figma

**Comment by ryanfchase** [comment]
@annaseulgi is the work on this ticket done? If so, engineering will begin making tickets to implement the designs referenced in the epic: https://github.com/hackforla/311-data/issues/1618

**Comment by annaseulgi** [comment]
@ryanfchase yes at the moment I believe the lighter map referenced in the epic is ready for development if it is feasible for engineering to create a lighter version of the map in mapbox

**Comment by ryanfchase** [comment]
Thank you @annaseulgi, please close this ticket when you're ready!

**Comment by ryanfchase** [comment]
Closing since design lead moved this ticket to Done
