### ISSUE TITLE
Remove Privacy Text Link from Navigation

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1607]
We will remove the Privacy text link from the nav bar due to it already being a link in the footer. 

When the component is up to date, design will communicate with engineering that the navigation is ready to be updated/developed.

Resource: Figma (page - "Star 1.2 Design System")

**Comment by annaseulgi** [comment]
@Joy-Truex Hey Joy, looks like we'll need to remove the Reports text link to the Navigation bar in addition to the Privacy link. Would you be able to update the component with those changes as well as the design in the Hand-Off page?

**Comment by ryanfchase** [comment]
Closing this since @annaseulgi has moved the ticket to Done
