### ISSUE TITLE
Loading Screen 2nd Iterations

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1609]
Handing off loading screen designs for 1.2 launch

- [x] Meet with Luan and Peter to discuss design documentation & user flows for hand-off
- [x] Approve finalized designs
- [x] Schedule design/engineering hand-off

Resource: Figma (Page - "⭐⭐⭐ V1.2 HAND-OFF")

**Comment by annaseulgi** [comment]
Hi @ryanfchase @edwinjue the design team is ready to hand off designs for the loading screen. Let us know what the document/process is for design to engineering hand offs and we will try to follow the guidelines as closely as possible. 

So far, we have finalized designs in a designated page in the Figma file with a user flow to indicate the flow of the designs.

**Comment by annaseulgi** [comment]
@tonguyen50 @pogwon 
Hi all, so the dev team let me know that it may not be feasible to have a loading bar with percentages. As we discussed, it's best practice for design but it's technically not feasible since the system doesn't actually know when it's reached 100% loaded. 
With that being said, would you both mind ideating on the circular buffering icon and explore those designs more? We'll probably have to go with that for the final version.

**Comment by annaseulgi** [comment]
Examples to reference for different progress bar components that are feasible:
https://mui.com/material-ui/react-progress/

**Comment by annaseulgi** [comment]
Moving to hand-off #1620

**Comment by ryanfchase** [comment]
Seeing that design lead moved this issue to done. I'm going to close this issue as completed.
