### ISSUE TITLE
Create mock for pin/heat map toggle loading feedback

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#161]
### Overview
The pin/heat toggle on the map will most likely take some time so itd be a good idea to mock up some loading indicators

### Action Items
- [ ] I dont know how to describe tickets for loading feedback
- [ ] uhhhh make it cool?

### Resources/Instructions
Uhhmmm you will be creating the resources?

**Comment by brodly** [comment]
Repeated ticket
