### ISSUE TITLE
FAQ Header Design Updates

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1611]
### Overview
We need to make changes to the header in order to create consistency across all the site pages.

### Actions
- [ ] add a blue frame that matches the consistency of the headers on the other existing pages.
- [ ] update all designs in the FAQ portion of the Figma.
- [ ] When finished, make a hand-off ticket.

### Resources
- [Figma, page name]

**Comment by annaseulgi** [comment]
Based on conversations related to content pages on 11/2 evening PM/Leads meeting, I will wait to update the FAQ designs after PMs discuss with Bonnie at following meeting

**Comment by ryanfchase** [comment]
I think we briefly mentioned in the issue workshop that this ticket was a candidate for Close as Unplanned, since the FAQ page is not a pre-launch issue. Happy to re-open a newer and more relevant ticket as we approach the FAQ milestone.

**Comment by annaseulgi** [comment]
@ryanfchase that sounds good, definitely agree that it's not a priority at the moment. Thanks!
