### ISSUE TITLE
Updated Navigation Bar Hand-off

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1615]
The navigation bar has been updated to exclude the Privacy text link. 
Designs are in the Figma and are ready for hand-off.

Resource: Figma (Page - ⭐⭐⭐ V1.2 HAND-OFF)

**Comment by ryanfchase** [comment]
I'm pretty sure this is done since epic the related epic is completed: https://github.com/hackforla/311-data/issues/1624
