### ISSUE TITLE
Create loading feedback for submit button 

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#162]
### Overview
Submitting new filters and changing filters(in the future) will be a source of load times, itll be a good idea to have a loading indicator for this data fetch events
Highly related to #161 

### Action Items
- [ ] Determine if a loading idicator should be a global thing (IE gray out entire ui) or a granular thing (Only gray out the item loading)
- [ ] Tie filter loading into map/graph loading indicators

### Resources/Instructions
N/A

**Comment by ExperimentsInHonesty** [comment]
Closing and adding all content here to #163
