### ISSUE TITLE
Design System Updates: Header Redesigns

### ISSUE THREAD

**Issue by annaseulgi** [hackforla/311-data#1628]
We would like to ideate different iterations of the header designs for the content pages. Current designs are quite out-dated and take up a large amount of space on each page.
This is not an urgent matter and does not need to be implemented into V1.2. However, it should be incorporated in later iterations of the site.

-  Review the existing header designs
-  Ideate and go through different rounds of iterations (if necessary)
-  Wait for design team review, feedback, and/or approval

Resource: Figma

------------------
[Click here to check the hand-off in Figma. The original photo is included in it.](https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=13585-6480&m=dev)

### Design Iterations

**Please move ticket between `In Progress` and `In Review` to assist PM team**

<details><summary>Iteration 1</summary>
<p>

![image](https://github.com/user-attachments/assets/1316fd44-4efa-4214-8c17-dfd9bc447afc)
</p>
</details> 

---

### Hand Off Materials

<details><summary>Before Screenshot</summary>
<p>

**Old Backdrop Without Top Nav & Title**

![image](https://github.com/user-attachments/assets/a2fb5eed-3a2f-4fbb-9357-7a6d611b5996)

**Old Backdrop With Top Nav & Title**

![image](https://github.com/user-attachments/assets/84b93edb-b6c2-4c9f-b4fe-2c3015e68172)

**Old Overall Header Design:**

![image](https://github.com/user-attachments/assets/c7646111-ec57-47fc-a4d7-58eea6c6c00b)

</p>
</details> 

<details><summary>After Screenshot (Finalized)</summary>
<p>

**Backdrop (Combination of background photo & 80% opacity cover)**

![image](https://github.com/user-attachments/assets/b9b6311c-72f0-4623-8cc5-1ac2c979448f)

**Here's the final design of the header with title & top navigation bar**

![image](https://github.com/user-attachments/assets/0241a0a2-ed08-443a-9726-83d64aec189d)

**The title text in Jumbo/Roboto/Medium/Bold, color white and shadowed, which passed contrast test.** 

**New Overall Header Design**

![image](https://github.com/user-attachments/assets/f0f4d1fe-36a4-4f08-aeaa-af90df2d4adc)

![image](https://github.com/user-attachments/assets/c26baaf4-0655-4bdc-b863-436c0a756ebb)

</p>
</details> 
</p>
</details> 

<details><summary>Other Resources</summary>
<p>

Headers background photo by 
[Luo](https://unsplash.com/@luolei?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash) Lei on [Unsplash](https://unsplash.com/photos/birds-eye-view-photography-of-city-scape-yW82CjIrif8?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash), Free of Copyright

Thanks to @Joy-Truex for recommending this site—it’s been helpful!

![image](https://github.com/user-attachments/assets/25f8a8b3-627a-401d-93fb-5efd4f50f812)

**NOTE: This is NOT the original resolution**

</p>
</details> 

### Designer Resources

<details><summary>Iteration Dropdown Copy/Paste</summary>
<p>

```
<details><summary>Iteration X</summary>
<p>

Link to notes: `REPLACE WITH COMMENT URL`

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details> 
```

</p>
</details>

**Comment by Joy-Truex** [comment]
Hi Shu,

Please leave a comment with the following items:

- updated ETA
progress from last week
- Any blockers this week?
- availability for communications during the week

Thanks!

**Comment by kiranofans** [comment]
> Hi Shu,
> 
> Please leave a comment with the following items:
> 
> * updated ETA
> * progress from last week
> * Any blockers this week?
> * availability for communications during the week
> 
> Thanks!

Hey Joy,
 I guess this one is still to be determined (?), and I might give up on it because I can hardly come up with ideas. Sorry again.

**Comment by ryanfchase** [comment]
@kiranofans no worries if you need more information. Please move this from `in progress` to `Questions`, if you'd like to discuss it further during our meetings.

Or if @Joy-Truex and @allisonjeon believe this ticket needs more information in order to proceed, then we can move it to `New Issue Approval` and we can add the label `Discussion` and `Needs more information`

**Comment by Joy-Truex** [comment]
[License | Unsplash](https://unsplash.com/license)
All images published on Unsplash can be used for free. You can use them for commercial and noncommercial purposes. You do not need to ask permission from or provide credit to the photographer or Unsplash, although it is appreciated when possible.

**Comment by kiranofans** [comment]
@ryanfchase I have updated the main comment, feel free to check & edit.

**Comment by bberhane** [comment]
PMs approved. G2G for DEV

**Comment by ryanfchase** [comment]
@Joy-Truex @allisonjeon @kiranofans Dev ticket has been created. We are good to close #1628 when ready!
- new dev ticket: https://github.com/hackforla/311-data/issues/1846
