### ISSUE TITLE
Create loading feedback for graphs/visualizations

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#163]
### Overview
Submitting new filters and changing filters(in the future) will be a source of load times, itll be a good idea to have a loading indicator for this data fetch events
Highly related to #161 

### Action Items
- [ ] Determine if a loading indicator should be a global thing (IE gray out entire ui) or a granular thing (Only gray out the item loading)
- [ ] Tie filter loading into map/graph loading indicators

### Resources/Instructions
This will be used in map and the data visualizations

**Comment by itsjoycelee** [comment]
See wireframes page - local components frame for UI mockup

**Comment by itsjoycelee** [comment]
![image](https://user-images.githubusercontent.com/59002767/72404327-c2c2c880-3709-11ea-9bb2-eb7acba233fc.png)

For use when loading data
