### ISSUE TITLE
Update all instances of the old Twitter logo to the rebranded `X`

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1642]
### Overview

The footer contains an outdated Twitter logo and should be replaced with one for the rebranded 'X'
![image](https://github.com/hackforla/311-data/assets/1448719/4243cef4-54f2-4d28-8aa3-7025b8530935)

### Action Items
- [ ] Collaborate with UI/UX @annaseulgi to obtain the new logo to use for Twitter
- [ ] Add the asset to our /assets folder and make the necessary references to it from within our codebase

### Resources/Instructions
- Similar to how this was done: https://github.com/hackforla/311-data/pull/1640

**Comment by annaseulgi** [comment]
@edwinjue thanks for pointing this out! To follow the procedure that @ryanfchase made for handing-off designs & assets, I'll add the new Twitter logo (X) and create an issue to hand-off the finalized version with updated logo.

**Comment by ryanfchase** [comment]
@annaseulgi @edwinjue let’s review this ticket at the next meeting. I’d like to move this through new issue approval and assign a milestone before creating handoff tickets.

**Comment by annaseulgi** [comment]
@kiranofans here is the issue that you can refer to. Thanks for working on this!

**Comment by kiranofans** [comment]
@annaseulgi Thanks Anna.

The X logo is ready in SVG format. Who should I contact to?

**Comment by ryanfchase** [comment]
@kiranofans thanks for working on this ticket! In the future, please assign yourself and move the ticket to `In Progress` on the Project Board before making your changes.

If your work on this ticket is complete, please move this to `In Review` on the Project Board and add the `ready for design lead` label.

PMs are working on making this clearer in the future, thanks again 😃

**Comment by annaseulgi** [comment]
@ryanfchase @Skydodle @kiranofans confirming if this issue should be closed or still in progress

**Comment by ryanfchase** [comment]
This is closed, thanks!
