### ISSUE TITLE
Update Huggingface URL to point to 311-data instead of edwinjue's personal

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1643]
### Overview
Currently our code is pointing to my personal huggingface repo. We need to update the link in our codebase to point to the one created by hack4la for 311-data

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ryanfchase** [comment]
@edwinjue we are closing this ticket because currently the `updateHfDataset.py` script is pointing at the 311-Data Huggingface repo. I don't think we need to wait on #1644 to resolve this ticket.
