### ISSUE TITLE
Fix nightly batch script to pull data for 2024

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1644]
### Overview
Fix nightly batch script to pull data for 2024 so our website can pull in data nightly for the new year. 

### Action Items
- [x] Update the following variables in [scripts/updateHfDataset.py](https://github.com/hackforla/311-data/blob/main/scripts/updateHfDataset.py) with the specified values
  - [x] url (obtained from Dependency):  
    ```
    https://data.lacity.org/api/views/b7dx-7gc3/rows.csv?accessType=DOWNLOAD
    ```
  - [x] outfile: 
     ```
     2024.csv
     ```
  - [x] infile:
    ```
    2024.csv
    ```
  - [x] fixed_filename:
     ```
     2024-fixed.csv
     ```
  - [x] clean_filename:
    ```  
    2024-clean.parquet
    ```
  - [x] local_filename: 
    ```
    2024-clean.parquet
    ```
  - [x] dest_filename:
    ```
    2024.parquet
    ```
  - [x] repo_name:
    ```
    2024
    ```
- [ ] Update the value of [datasets.parquet.hfYtd](https://github.com/hackforla/311-data/blob/773c95034403b97e687abd6be33c487bc2c0b42e/components/db/DbProvider.jsx#L12) to point to the new 2024 parquet file. The link will appear at the top of the 2024 Huggingface repo after the script runs for the first time.

  <details>
    <summary>Here is where the link is located in the Huggingface 2023 repo</summary>
  
    ![image](https://github.com/hackforla/311-data/assets/1448719/817bf707-0b74-4083-97c4-2431047a6b90)

  Simply copy and paste this link from the 2024 repo and set it equal to  [datasets.parquet.hfYtd](https://github.com/hackforla/311-data/blob/773c95034403b97e687abd6be33c487bc2c0b42e/components/db/DbProvider.jsx#L12)
  </details>

  Updating this URL will also fix #1643 (so please close this ticket out upon updating)

### Resources/Instructions
- [Existing URL 2023](https://github.com/hackforla/311-data/blob/a829d9179d2637ff25a8ef0c745e6c706fa21491/scripts/updateHfDataset.py#L15)
- [View solution on Edwin Jue's personal repo](https://github.com/edwinjue/311-data-v2-gh-pages/blob/main/scripts/updateHfDataset.py)
- https://huggingface.co/311-data

**Comment by ExperimentsInHonesty** [comment]
@edwinjue will revise format

**Comment by ryanfchase** [comment]
@traycn tagging you here!

**Comment by edwinjue** [comment]
@tracyn sorry i provided the wrong url variable. I've updated the issue with the correct 2024 url, which should be
```
https://data.lacity.org/api/views/b7dx-7gc3/rows.csv?accessType=DOWNLOAD
```

Please update  https://github.com/hackforla/311-data/blob/4d5b9821be291737dcce571b9bd37cfbf3c879f0/scripts/updateHfDataset.py#L15 to the value above and I will approve thanks

**Comment by ryanfchase** [comment]
@traycn Please reference this note for your next PR!

https://github.com/hackforla/311-data/pull/1656#issuecomment-1910853861

**Comment by traycn** [comment]
Created another PR to update the url and added the ticket # for tracking. Thanks for the reference note @ryanfchase !

**Comment by traycn** [comment]
Second part of 1644 not completed yet. 

> Update the value of [datasets.parquet.hfYtd](https://github.com/hackforla/311-data/blob/773c95034403b97e687abd6be33c487bc2c0b42e/components/db/DbProvider.jsx#L12) to point to the new 2024 parquet file. The link will appear at the top of the 2024 Huggingface repo after the script runs for the first time.

My availability to complete this issue:
1/28  6AM - 9AM PT

**Comment by ryanfchase** [comment]
Moved the ticket to review and left some feedback for your PR!
