### ISSUE TITLE
PM Team Weekly Meeting Re-Setup

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1645]
### Overview
PM Team meetings are not scheduled for 2024. We need a PM to go into the Zoom Setup sheet and set this meeting up.

### Action Items
- [x] claim the Thursday 7pm PST spot on the zoom setup sheet
- [x] log into zoom via Hack For LA's 1Password account
- [x] set up a weekly meeting (see 2023's Weekly PM Meeting zoom meeting for reference)
- [x] set up weekly Google Calendar reminder

### Resources/Instructions
[Link to zoom setup sheet](https://docs.google.com/spreadsheets/d/15P3MYyNQ7Xn0pqdrTynDDipjrLl5LCN9xHVLhk9SWa8/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
Bethlihem sees the calendar invite, but ryan dosent.  This might not needt to be done.  Sort it out before prioritizing the issue.  Feel free to close as unplanned if it turns out to be a quick fix/

**Comment by bberhane** [comment]
Looks like it wasn't set up on 311-Data's Gmail account, but it was still appearing on my personal calendar.

**Comment by bberhane** [comment]
Issue resolved
