### ISSUE TITLE
Remove "Get Shareable Link" button from Filters Menu

### ISSUE THREAD

**Issue by edwinjue** [hackforla/311-data#1647]
### Overview
Remove the `Get Shareable Link" button from Filters Menu because it is not currently being used.

### Action Items
- [x] Remove the `Get Shareable Link" button from Filters Menu

### Resources/Instructions
<details><summary>Screenshot of button location</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/1448719/1841b3a8-b489-4083-9fc1-a888655f0f97)

</p>
</details> 

- [Action Steps post bug and usability testing January 2024](https://docs.google.com/spreadsheets/d/1y_8xUCxEU83adN2GjEIOt3F-wILJ1_c2KdgISFRN5cU/edit#gid=0&range=C18)

**Comment by Skydodle** [comment]
@edwinjue @ryanfchase For simple issue like this one, we don't need to go through New Issue Approval right? I went ahead and picked up the issue, set to 'In progress' on project board, and added to 'Bug Bash' in Milestone. Please let me know if any of the above needs to be corrected. Thank you.

**Comment by edwinjue** [comment]
@Skydodle Thank you for responding so quickly and taking ownership of this! I'm not the best person to ask regarding our current process but I see no problem with this but I think there is some review/approval process before assigning issues if I'm not mistaken. @ryanfchase can shed some light into the best way to handle quick simple fixes like this? Thanks

**Comment by ryanfchase** [comment]
Ticket looks good, I just removed `Milestone: Missing` label since it was added correctly. I also added `P-feature: Map`. Thanks for pinging me, @Skydodle you're good to continue here. We are doing a ticket workshop soon so we'll go over the formal process then.

**Comment by Skydodle** [comment]
Availability: Weds 01/17 to Friday 01/19 6pm to 9pm
Completion ETA: Friday 01/19 before 9pm
