### ISSUE TITLE
Modal Neighborhood Districts

### ISSUE THREAD

**Issue by Joy-Truex** [hackforla/311-data#1650]
### Overview
Design what ND filter would look like if the name is long and takes up two rows. We need to do this because names that are too long break sizing rules

### Resources/Instructions
Example:
EMP CON: Empowerment Congress (don’t abbreviate)
“Arts District Little Tokyo”, “Bel Air-Beverly Crest”, etc

View the [research deck](https://docs.google.com/presentation/d/1NBMnS8_znCnYNDNNQrN2Jh5GQZhZmX56rtHME-EewBY/edit#slide=id.p1) for details

### Design Iterations

**Please move ticket between `In Progress` and `In Review` to assist PM team**

<details><summary>Iteration 1</summary>
<p>

Link to notes: `REPLACE WITH COMMENT URL`

![Screenshot 2024-03-27 at 4 45 41 PM](https://github.com/hackforla/311-data/assets/113402205/94714875-18c6-4c88-aa97-8b893eb2a770)

</p>
</details> 

---

### Hand Off Materials

Figma Section Name: [Modal Neighborhood Districts #1650](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=11199%3A1918&mode=design&t=RHndOwro8JHmmYoe-1)

<details><summary>Before Screenshot</summary>
<p>

<img width="799" alt="Screenshot 2024-03-27 at 4 58 25 PM" src="https://github.com/hackforla/311-data/assets/113402205/9e692e2d-e739-48fb-815b-7626867ca167">

</p>
</details> 

<details><summary>After Screenshot (Finalized)</summary>
<p>

![Screenshot 2024-03-27 at 4 59 05 PM](https://github.com/hackforla/311-data/assets/113402205/5564e9fa-ec27-458d-a184-89a78ce68aac)

</p>
</details> 

### Designer Resources

<details><summary>Iteration Dropdown Copy/Paste</summary>
<p>

```
<details><summary>Iteration X</summary>
<p>


</p>
</details> 
```

</p>
</details> 

<details><summary>Instructions for Engineering Hand Off</summary>
<p>

To Start Engineering Hand Off...
1. Ensure all Hand Off Materials are filled in
3. Add the "ready for dev lead" label
4. Leave a comment saying "This ticket is ready for engineering hand off." 

</p>
</details>

**Comment by ryanfchase** [comment]
Hi @Joy-Truex -- thank you for making this ticket. You've done a good job of adding role, size, milestone, and project board. During our ticket workshop, we created the label `draft` to indicate that this ticket is still being created (e.g. more details are being added to the description, etc). I'll give a brief overview of what this ticket needs next to continue:

1. When you feel like the ticket description is adequate, you will unassign yourself and add the `ready for design lead` label, and @annaseulgi will give the ticket a look-over. (ticket remains in New Issue Approval)
2.  When design lead is happy with the ticket, we can remove `ready for design lead` and add `ready for prioritization` (ticket remains in New Issue Approval)
3. Product team will add this ticket to the Prioritized Backlog you (or any other design team member) can assign themselves and move the ticket to In Progress.

I know that's a lot! PM team is working to create a process doc, as well as communicate all this to the teams as best as possible.

**Comment by ryanfchase** [comment]
I'm also going to add my notes on the ticket description now since it looks ready for feedback.

1. Before the first line (`Design what ND filter would look like...`), please add a line of markdown text: `### Overview` so we know exactly what this ticket entails
2. Add one more sentence to your overview description that explains why this ticket exists. This helps with ticket prioritization (e.g. `... if the name is took long and takes up two rows. We need to do this because names that are too long break sizing rules`)
3. Before the line that says `Example:`, add a line of markdown text: `### Resources/Instructions` so we know that everything below is information useful to the designer
4. Replace `View the research deck for details` with `View the [research deck](https://docs.google.com/presentation/d/1NBMnS8_znCnYNDNNQrN2Jh5GQZhZmX56rtHME-EewBY/edit#slide=id.p1) for details`

**Comment by Joy-Truex** [comment]
wow i really botched this! thank you so much @ryanfchase , having the steps written out is so helpful for me to reference vs just trying to do it from memory!!

**Comment by ryanfchase** [comment]
You're good @Joy-Truex thank you for making those changes! This ticket is looking good now.

@annaseulgi I think this is ready for prioritization and assignment. If you're happy with it, remove the `draft` label and add the `ready for prioritization` label.

**Comment by Joy-Truex** [comment]
@ryanfchase this is ready for handoff - https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=11199%3A1918&mode=design&t=4a78S5jUavJL8FJM-1

**Comment by Joy-Truex** [comment]
This ticket is ready for engineering hand off.

**Comment by ryanfchase** [comment]
FYI @bphan002 and I going to review this, and then create a dev ticket as long as we have everything we need. Most likely this will close since the work is done, thanks @Joy-Truex !

**Comment by bberhane** [comment]
@ryanfchase Is this good to close?

**Comment by ryanfchase** [comment]
> @ryanfchase Is this good to close?

I say yes!

**Comment by bberhane** [comment]
Closing issue
