### ISSUE TITLE
Transcribe ticket-making workshop

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1651]
### Overview
We need to transcribe the workshop recording so we can have a reference document that all team members can use when making tickets, if needed.

### Action Items
- [x] Watch Zoom video to extract most important information and condense to create a process doc

### Resources/Instructions
- Zoom recording link: https://drive.google.com/drive/folders/1WntRsUF8buzlG4cnvZ95pwk4nbt4ooD-?usp=drive_link 
- Google doc to jot down our notes while reviewing Ticket Workshop: https://docs.google.com/document/d/1hjpc9laZMtcs2BiH4j21wHcsayI-VlQllAU6oQ67QcQ/edit

**Comment by ryanfchase** [comment]
@bberhane I've uploaded the zoom recording, chat, and transcript onto our drive!

https://drive.google.com/drive/folders/1WntRsUF8buzlG4cnvZ95pwk4nbt4ooD-?usp=drive_link

**Comment by bberhane** [comment]
Then this is readyto be assigned

**Comment by ryanfchase** [comment]
Created a google doc for us all to jot down any notes we want to share while reviewing the ticket workshop! Updated the issue to include this in Resources

- https://docs.google.com/document/d/1hjpc9laZMtcs2BiH4j21wHcsayI-VlQllAU6oQ67QcQ/edit

**Comment by cottonchristopher** [comment]
reviewed recording of ticket workshop on 1/26/24 from 3 to 5:27 PM. Notes placed in https://docs.google.com/document/d/1hjpc9laZMtcs2BiH4j21wHcsayI-VlQllAU6oQ67QcQ/edit

**Comment by bberhane** [comment]
Reviewed up to 50:19 of recording, before delving into emergent requests; once complete will need to include instructive screenshots

**Comment by bberhane** [comment]
Here's the most-recent version:
[Ticket workshop transcription doc](https://docs.google.com/document/d/1hjpc9laZMtcs2BiH4j21wHcsayI-VlQllAU6oQ67QcQ/edit) 
Unassigning myself and moving to In Review column for PM review

**Comment by bberhane** [comment]
Cotton and I reviewed and determined this ticket is complete. We will continue to assist team members in real time and will make it known that this document exists.
