### ISSUE TITLE
Compile neighborhood council list for Dev

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1652]
### Overview
We need to make a spreadsheet of neighborhood councils so that Dev can make updates to the search bar on the map page.

### Action Items
- [x] Creat Google Sheet
- [x] Paste neighborhood council names 
- [x] Request list of acronyms from Dev [will get clarification on exact nomenclature] 
- [x] Assign appropriate acronym to NC [will clarify]
 
### Resources/Instructions
- Link to 311 Data NC list (new): https://docs.google.com/spreadsheets/d/1yM3rH1Iv4zYiANzeI4R-P5JZD-SBOL2yguhRrz-RRwQ/edit?usp=sharing
- Link to neighborhood councils list from EmpowerLA: https://empowerla.org/councils/ 
- [link to the js file on our codebase that has all the nc data](https://github.com/hackforla/311-data/blob/main/data/councils.js)
- [Spreadsheet Format for the info from the js file](https://docs.google.com/spreadsheets/d/1yM3rH1Iv4zYiANzeI4R-P5JZD-SBOL2yguhRrz-RRwQ/edit#gid=1860278360)

### Dependency
- [x] need Dev to explain where the abbreviated names are being obtained, and how we can get them (so they can go into the spreadsheet)

**Comment by ryanfchase** [comment]
Summary from prev PM meeting:
- we checked the empowerla NC list and the data.lacity.org public api for NC names and only found un-abbreviated names
- we're not a little confused how eng is obtaining abbreviated names

Takeaway
- we're going to ask about how eng is obtaining and using abbreviated names in the next general meeting
- we'll still create the NC names spreadsheet since it will still be useful moving forward

**Comment by bberhane** [comment]
NC names spreadsheet: https://docs.google.com/spreadsheets/d/1yM3rH1Iv4zYiANzeI4R-P5JZD-SBOL2yguhRrz-RRwQ/edit?usp=sharing

**Comment by ryanfchase** [comment]
Moving out of icebox -- in the engineering breakout room, @edwinjue demonstrated how the code is abbreviating the NC names. I will use this info to generate a list of all NC names that are being abbreviated and provide them on the relevant dev ticket.

- https://github.com/hackforla/311-data/issues/1648

**Comment by bberhane** [comment]
PM meeting note from 2/1: Convert NC list in array and run a script

**Comment by ryanfchase** [comment]
ETA: 2/11
Availability: weekdays, 2/11

**Comment by bberhane** [comment]
@ryanfchase Are we good to close this ticket? All initial tasks are complete

**Comment by bberhane** [comment]
Closing this ticket as all items are completed

**Comment by ryanfchase** [comment]
Yes thank you! Every time I opened this ticket I felt compelled to do a big aesthetic update to that spreadsheet -- but for our purposes, this ticket is complete.
