### ISSUE TITLE
Update Loading Modals after Feedback from Bonnie

### ISSUE THREAD

**Issue by pogwon** [hackforla/311-data#1655]
### Overview
We need to change the loading modal to buy more time while data points load. Bonnie suggested that including the link to My311 on the first modal might be better and considering the initial fun facts about LA could be a way to buy more time.

### Action Items
- [x] Discuss best plan to create a modal that includes link to My311 and buys more time while data points load.
- [x] Gather feedback and finalize designs for handoff.

### Resources/Instructions
- [Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=3266%3A1&mode=design&t=ydC2zfitRXoqElLz-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- https://github.com/hackforla/311-data/issues/1609

**Comment by cottonchristopher** [comment]
Notes for the ticket: needs screenshots of the issue, need a link to where the issue is, need figma link

**Comment by pogwon** [comment]
Link to Figma file: https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=9976%3A4824&mode=design&t=oszLfQ2mS8mbJtIx-1

**Comment by pogwon** [comment]
@ryanfchase Ready for handoff. 

Link to Figma file:

https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=9976%3A4824&mode=design&t=oszLfQ2mS8mbJtIx-1

**Comment by annaseulgi** [comment]
@ryanfchase @pogwon just checking in on this - has this issue already been handed off to devs? if yes then great! just saw that it was closed and moved to done(without merge) so wanted to double check
