### ISSUE TITLE
Fix Contact Form layout on Contact Us page

### ISSUE THREAD

**Issue by Skydodle** [hackforla/311-data#1659]
### Overview
On the Contact Us page, the current contact form's styling does not match our Figma design. We need to update the form's styling and layout to match the Figma design in preparation for pre-launch.

### Action Items
- [x] Inspect the screenshots of 'current layout' & 'expected layout' below in Resources/Instructions to compare the visual difference on the forms
- [x] Review the Figma design file in Figma Resources below to inspect the CSS layout requirements such as properties for each input field on the contact form
- [x] Review the `ContactForm.jsx` component in codebase
- [x] If needed, familiarize yourself with [MUI Components](https://mui.com/components/) documentation specifically on Grids and Forms
- [x] Make changes to the codebase so that our contact form match with the Figma design
- [x] Test the changes to confirm it's bug free prior to pushing and making a pull request

### Resources/Instructions

<details><summary>Screenshot of current layout</summary>
<p>

![Screenshot 2024-01-27 at 12 18 45 AM](https://github.com/hackforla/311-data/assets/69279538/d8c217a5-5b4c-452f-b689-8da82a6df752)

</p>
</details> 

<details><summary>Screenshot of expected layout (from Figma)</summary>
<p>

![Screenshot 2024-01-27 at 12 28 17 AM](https://github.com/hackforla/311-data/assets/69279538/10829a45-9622-44d4-a72b-715d1df61e93)
</p>
<br>
<p>
Note: just work on the form for this issue, ignore the other design differences on the page for now

![Screenshot 2024-01-27 at 12 25 03 AM](https://github.com/hackforla/311-data/assets/69279538/ea98ce6f-e8bb-4685-a6ce-e2520b23e32e)

</p>
</details> 

#### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: Contact Us

**Comment by ryanfchase** [comment]
@Skydodle this looks like sufficient detail for a dev to get started. I'm going to take off the `ready for dev` and `draft` label and put this in `Prioritized Backlog` so it can be assigned.

Also - the `Pre-Launch` label is a good idea, but PMs were reluctant to implement this and instead preferred to go with tracking via the Epic of Epics. I'll leave the label here in case we decide we want to add `Pre-Launch` to all other tickets later 😄

**Comment by bphan002** [comment]
ETA: Monday, February 5
Availability: Saturday, February 3
