### ISSUE TITLE
[Revised] Default and Custom Date Filters (Sidebar Filter)

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#166]
### Overview
Date filters have been designed to show defaulted date filters and custom date filters.

### Action Items

- [x] Create UI for drop down menu that contains 

- Last week

- Last month

- Last 6 months

- Last 12 months

- Year to date

- Custom range

- [x] Create UI for pop-up form for custom range date filter selection

### Resources/Instructions
![image](https://user-images.githubusercontent.com/59002767/72403898-7d51cb80-3708-11ea-95b0-599eba916e3f.png)
^Wireframes 2 (Drop down)

![image](https://user-images.githubusercontent.com/59002767/72403878-73c86380-3708-11ea-827a-34dcb871ddfa.png)
^Wireframes 2 (Clicked drop down)

![image](https://user-images.githubusercontent.com/59002767/72403919-89d62400-3708-11ea-90d0-c5f1da47370f.png)
^ In components - Wireframes (Selected custom data range - popup form)

Click [here ](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=100%3A0)for mockup

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 @itsjoycelee will update this issue to add instructions for the front end team.

**Comment by johnr54321** [comment]
There is a duplicate ticket here: https://github.com/hackforla/311-data/issues/154.  Closed the other ticket.  Leaving this one since it has the mockups.

**Comment by adamkendis** [comment]
@itsjoycelee In the date filter dropdown, should the user be able to click the entire option row or do they need to click the checkbox to make a selection? See image below. Note that the dropdown has not yet been styled to match the mockup - finishing dropdown functionality.

![image](https://user-images.githubusercontent.com/40484278/73599356-6e845a80-44f7-11ea-894a-30181710f31f.png)

**Comment by adamkendis** [comment]
**Status:** Working on date filter dropdown - awaiting minor clarification from UI team. Still need to implement custom range datepicker. Will most likely use an outside package for the datepicker. 
**Blockers:** None at the moment.
**Availability:** Generally available in the evenings this week. Can handle issues/discussion async via Slack/github comments.
**ETA:** Hoping to have this feature pushed to `dev` by Thursday, 2/6.

**Comment by itsjoycelee** [comment]
@adamkendis good point. let's do the entire row than the checkbox option- thanks!

**Comment by johnr54321** [comment]
Spoke with Adam. New ETA is 2/11. He needs to look through the library.

**Comment by adamkendis** [comment]
**Status:** Still on track for 2/11 ETA. Dropdown is complete. Working on custom range datepicker and date filter header section. 
**Blockers:** None.
**Availability:** Available for discussion via Slack/github comments.
**ETA:** Still 2/11.

Note for later: When hooking these components up to the Redux store, some implementation details will depend on server-side decisions. Will the client need to provide start/end dates to plug into a SQL query on every request, or will the predetermined time blocks (Last week/month/6 months, etc.) be precached on the back end and have their own endpoint(s)?

**Comment by ryanmswan** [comment]
@adamkendis At this point I think we'll assume that there will be novel SQL queries for update. We're looking into precaching but the time periods are flexible enough that they might be difficult to cache. At this point we're looking at ways to precache the default views as well as maybe the full year view for each year (2015, 2016, ..., 2020)
