### ISSUE TITLE
Change Map background style and boundary color

### ISSUE THREAD

**Issue by Skydodle** [hackforla/311-data#1661]
### Overview
We need to change the design/color of the map background  & the boundary color to more easily see pins/differentiation.

### Description of Requested Change

1. Change the map background style from 'street' to 'light'
2. Change the boundary color to the shade of blue specified in Figma design file

### Action Items

- [ ] Compare the screenshots of 'current map' and 'proposed changes' below
- [ ] Gather change requirements from the Figma file below

#### Change Background
- [ ] Check out the MapBox API documentation on map styles [here](https://docs.mapbox.com/api/maps/styles/)
- [ ] Navigate to `constants.js` in your local repo, in the `MAP_STYLES` object, update the 'light' style URL with the latest URL provided on the MapBox documentation page
- [ ] Trace down where `MAP_STYLES` is being used in `Map.jsx`
- [ ] Change the `mapStyle` state from 'street' to 'light'

#### Change Boundary Color
- [ ] Navigate to `BoundaryLayer.js`
- [ ] Update the color in `getBoundaryColor` to the color code specified in Figma design file
- [ ] Test the changes to make sure it's visually correct and there are no merge conflicts prior to pushing your code for pull request

### Resources/Instructions
<details><summary>Screenshot of current map</summary>
<p>

![Screenshot 2024-01-28 at 10 35 41 AM](https://github.com/hackforla/311-data/assets/69279538/fb246d44-b838-4fa4-b2c6-e600bec9bacc)

</p>
</details> 
<details><summary>Screenshot of proposed changes</summary>
<p>

![Screenshot 2024-01-28 at 10 37 15 AM](https://github.com/hackforla/311-data/assets/69279538/2043fcb7-b0d2-4c52-b5cc-d9ecaa26fed9)

</p>
</details> 

- https://github.com/hackforla/311-data/issues/1618
- Debugging tips: make sure you are not viewing or making changes in the `archive/aws/` directory when pulling up files like `Map.jsx`, `constants.js`, and `BoundaryLayer.js`

### Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ V1.2 HAND-OFF
- Section Name: Map: Light Version

**Comment by ryanfchase** [comment]
Signing off on this ticket, thank you @Skydodle

**Comment by Skydodle** [comment]
@funbunch Thank you so much for a great job working on this issue. The only minor gentle reminder is that as soon as you picked up an issue, remember to move the issue from 'prioritized backlog' to 'in progress' in the Project Board on right side tool bar.

**Comment by funbunch** [comment]
@Skydodle Noted! And thanks so much for the very detailed steps of what needed to be done for this one. It was really helpful.
