### ISSUE TITLE
Add warning for when user tries to load data prior to 2024

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1664]
### Overview
We need to limit the Datepicker on our map controls to only display years that our app has loaded because we don't want to confuse users when no data appears on the map

### More Info
The 2023 data is stored in the 2023 Hugging Face Repo, it is not automatically included in the 2024 parquet file that gets downloaded when the page loads. While we are hoping to address this in [this ticket](https://github.com/hackforla/311-data/issues/1666), we should generally block users from asking for data prior to the earliest available data (I think its 2015).

We should give the user a way to find out that certain dates are not available via an info button near the date picker.

### Action Items
- [x] limit the datepicker to only allow 2024 (until we allow loading multiple years, see ticket in More Info)
- [x] add an info icon to the datepicker that matches the info button on the Request Types section
- [ ] on hover for this icon, we should display the Datepicker Info text

### Resources/Instructions

Datepicker Info text:

```
311-Data is currently only able to load 311 service request data in 2024 and onwards. For updates on the release of available 311 Data, please follow our LinkedIn page at https://www.linkedin.com/company/hack-for-la/.
```

<details><summary>Screenshot of "Request Types" Info Icon</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/eb7ef307-61bb-4d36-90d4-ae5706f0ea83)

</p>
</details> 

Huggingface URL
- https://huggingface.co/datasets/311-data/2024

**Comment by ryanfchase** [comment]
Based on conversation in PM meeting, I'll be updating this ticket with more specific instructions from Bonnie. Moving to draft.

**Comment by Skydodle** [comment]
Availability: M-F 6pm to 10pm
Completion ETA: 2/14 Wedenesday EOD

**Comment by Skydodle** [comment]
Pushing to next week to work on this, a little occupied this week.
Availability: M-F 6pm to 10pm
Completion ETA: 2/21 Wednesday EOD

**Comment by annaseulgi** [comment]
unless anyone objects, assigning this to ux design role as well since some of the tasks look to be similar

**Comment by cottonchristopher** [comment]
@annaseulgi, we created a design ticket here https://github.com/hackforla/311-data/issues/1677 
We will also link the design to Engineering handoff Epic to the design issue.
