### ISSUE TITLE
Add back button to close Cookie Notice. 

### ISSUE THREAD

**Issue by funbunch** [hackforla/311-data#1668]
### Overview
We need the "Got It" button on the Cookies and Privacy Policy modal to be visible for users to interact with it.

### More Info
Style changes might have taken away our ability to see and close the Cookie Notice. We need to refer back to design and update.

### Action Items
- [ ] adjust styles for the "Got it" button to match the desired look (see pictures in Resources)

### Resources/Instructions
<details><summary>Current screenshot of transparent "Got it" button</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/ae4b9366-04da-467c-a62e-fdfd1507c919)

</p>
</details> 

<details><summary>Screenshot of how "Got it" should look</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/2d5af290-3082-4215-a24e-1a6e5a5da40c)

</p>
</details>

**Comment by bberhane** [comment]
@funbunch Please update the overview portion of the ticket using the format "We need to do X for Y reason"

**Comment by funbunch** [comment]
@bberhane Added the edit.
