### ISSUE TITLE
Identifying Neighborhood Council Names on Map

### ISSUE THREAD

**Issue by pkimmm** [hackforla/311-data#1669]
### Overview
Create a pop-up for users when they hover issues that display the details of issue requests they are able obtain that information quickly and efficiently. 

### Details

Details from the pop-up would include information such as the type of issue, address, neighborhood council, service request #, source, agency, and reported/closed dates. 

### Action Items
Sample Image of how difficult users may have finding specific details such as Neighborhood Councils.
<details>
<summary>Click Me</summary>

![unnamed](https://github.com/hackforla/311-data/assets/139014411/d318fcbd-db97-48f3-84fb-5fe0a5142dbe)
</details>

Here are some potential mock ups that may solve the problem 

<details>
<summary>Click Me</summary>

![pop up](https://github.com/hackforla/311-data/assets/139014411/afd9cfe8-bee5-4bd5-a3e3-8a38c28fc77f)

</details>

### Resources/Instructions

The mock ups can be found in the 311 Data UXUI Figma File in the page named "Paul K"

**Comment by pkimmm** [comment]
Working to finish up the final touches. Will aim to have it done this week.

**Comment by ryanfchase** [comment]
@bberhane @cottonchristopher can we follow up with this ticket at the next meeting? We would like to open it up so that dev can get started, unsure if it needs review or if its ready for hand off.

**Comment by bberhane** [comment]
Will make a note to add it to Wednesday's agenda

**Comment by bberhane** [comment]
Should this be in the review lane, or has this been completed, @pkimmm?

**Comment by pkimmm** [comment]
@bberhane It has been completed!

**Comment by bberhane** [comment]
Thanks, @pkimmm! I'll go ahead and close it, but in the future feel free to close with comment once you're all done :)

**Comment by Joy-Truex** [comment]
Going to update based on Design Team discussion and discussion with @ryanfchase:

### Action Items

- [ ] address the red text color to pass color contrast accessibility requirements
- [ ] remove underline so as not to suggest that it is a hyperlink

<details>
<summary>Screenshot</summary>
<img width="772" alt="Screenshot 2024-08-21 at 8 54 21 PM" src="https://github.com/user-attachments/assets/b5de85e6-b573-45db-a3b9-d6dc3cbda45e">
