### ISSUE TITLE
[Added] Box and Whiskers Data Visualization (Time to Close)

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#167]
### Overview
Box and Whiskers Data Visualization was created to view time-to-close
### Action Items

- [x] UI components

- [ ] Back-end 

- [x] Front-end 

### Resources/Instructions
See time to close frame on [Wireframes 2 page ](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=100%3A0)

**Comment by itsjoycelee** [comment]
![image](https://user-images.githubusercontent.com/59002767/72404415-2220d880-370a-11ea-8507-834f73d25bf8.png)

**Comment by ExperimentsInHonesty** [comment]
@johnr54321  @itsjoycelee will update this issue to add instructions for the front end team.

**Comment by itsjoycelee** [comment]
Front-end to provide comments whether box and whiskers chart is in component library and/or requires additional requirements.

**Comment by jmensch1** [comment]
there's a Chart.js plugin for boxplots:

https://github.com/datavisyn/chartjs-chart-box-and-violin-plot

I'll try to put something together.

**Comment by johnr54321** [comment]
Josh is reviewing.   Should be merged before Tuesday.

**Comment by johnr54321** [comment]
This is waiting on ticket #413 for backend work.

**Comment by jmensch1** [comment]
I'm working on the backend part of this now, will submit a PR by tomorrow.
