### ISSUE TITLE
Spike: Fix 'Learn More' link on Cookies Notice modal

### ISSUE THREAD

**Issue by Skydodle** [hackforla/311-data#1673]
### Overview
We need to decide if the`'Learn more'` link on the Cookie Notice modal should be removed for pre-launch OR if we should have a valid redirection page for it, so that when users click on the link it would not lead to a blank page as the way it is right now.

See the screenshot below in Resources/Instructions for the location of said link

### More Info
Originally, the `'Learn more'` link on the Cookies and Privacy Policy modal leads to the Privacy page. However, we recently decided to temporarily archive the Privacy page in preparation for pre-launch, therefore the link now redirects to an empty page.

A simple fix would be to comment out the link for now (so that it stays in the code but not display to users), then we can reactivate it after launch when we have the Privacy page ready. But I'm not sure if this would be best practice for launch regarding privacy notification standards, and would like to hand over to PM, UX, & Research for discussion.

### Action Items
- [x] Discuss & decide whether to omit the link for now OR keep it
- [x] If keeping it where should the link redirect to?
- [ ] If omitting it, is there anything you would like to add? (additional text etc.)
- [ ] Add more action items here if applicable
- [ ] Create tickets or update this issue according to the outcome of discussion

 **Update:**  The following dev ticket has been created to address this issue:
 - #1681 

### Resources
<details><summary>Screenshot of the 'Learn more' link </summary>
<p>

![Screenshot 2024-02-08 at 1 06 03 PM](https://github.com/hackforla/311-data/assets/69279538/bfcb10c8-92f1-4ab1-a6d0-b16fbeb7f853)

</p>
</details>

**Comment by Skydodle** [comment]
The 'Privacy Policy' link in the footer of the app also applies to this issue.

**Comment by ryanfchase** [comment]
Thanks @Skydodle -- we can add this to the PM agenda for tonight to determine pre-launch actions

**Comment by ryanfchase** [comment]
@Skydodle PMs suggest we remove the link. We are also finding that the footer has a link to the privacy policy page (which was removed)

<details><summary>Image of link in Footer</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/504a2f2e-4d84-4ba0-80b0-687de1a05787)


</p>
</details>

**Comment by Skydodle** [comment]
Per discussion with @ryanfchase, PM team has decided to keep the link active and bring the Privacy page back as we need the page to show our privacy policies. I'll be creating a dev ticket and will link the ticket to this issue soon.

**Comment by Skydodle** [comment]
Dev ticket created to address this issue, closing this ticket as discussion has been done
