### ISSUE TITLE
Prelaunch story point estimation 

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1674]
### Overview
We need to make a spreadsheet to track when pre-launch issues will be done.

### Action Items
- [x] Create spread sheet 
- [x] List all pre-launch issues
- [ ] calculate order of issues (in parallel vs in serial) 
- [ ] Calculate date when all issues will be done 

### Resources/Instructions
-[ PreLaunch Issue Point Sheet](https://docs.google.com/spreadsheets/d/1JZSf7QZGew265jnDk3wiwiiurU5uu3lduOshm5UaKl4/edit#gid=0):

**Comment by bberhane** [comment]
Creating a new doc with updated issues

**Comment by ryanfchase** [comment]
@bberhane shall we consider this ticket closed? It feels a bit like we've achieved all of the action items! I noted once that we could alternatively create a live-forever ticket for managing story point estimations. Perhaps we can review this again at the upcoming PM meeting.

Notes from June 6 product planning meeting, linked [here](https://github.com/hackforla/311-data/issues/1528#issuecomment-2151308505)

> Brainstorm/create remaining pre-launch tickets
> - Add "ETA" column to story points spreadsheet
> - RC: I think we could take the pre-launch spreadsheet ticket and turn it into a live-forever ticket where we post comments with the new pre-launch ticket that is created so we know to update the spreadsheet
> - (just an idea) if we move forward with bot automations (like internship team?) we can automate this so we don't have to manually do it. But in the meantime we'd have to maintain this ourselves

**Comment by bberhane** [comment]
Let's close this and make a new forever ticket; we'll implement the automation when time permits
