### ISSUE TITLE
Update color differentiation for NC Boundaries de-selection "x"

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1675]
### Overview
We need to update the color/differentiation of the "x" in the Boundary field because it is really hard to see 

### Action Items
- [ ] Update the color differentiation of the "X" in the Boundaries (ND) selection, so that when users want to clear/exit/deselect a selection (making the map zoom out), it is more visible 
 

### Resources/Instructions
<details><summary>Screenshot of issue </Summary>
<p>

![image](https://github.com/hackforla/311-data/assets/142280921/2422d6ad-516f-4f06-8bb6-e7986e1e8ed5)

</p>
</details>

**Comment by cottonchristopher** [comment]
Ryan and I reviewed the Map and noticed that it was really hard to see the "x" for the Boundary filter. @ryanfchase    
Can design take a look at this and see if we can make it more visible?   @annaseulgi

**Comment by annaseulgi** [comment]
@ryanfchase @cottonchristopher 
Yes, let's make the icon the same color as the text #0F181F

This is what we already have in the design file from a year ago:

For example:

<details><summary>Screenshot </Summary>
<p>

![Screen Shot 2024-02-13 at 1 45 47 PM](https://github.com/hackforla/311-data/assets/140572118/53159ddc-e1f8-412b-a72d-5da629bb5e31)

</p>
</details>
