### ISSUE TITLE
Update Loading Modals (Dev) 

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1676]
### Overview

We need to implement a loading modal that clarifies who our organization is while also cueing the user that data is still being loaded because the current implementation is ambiguous.

### Action Items

- [x] Modify the FactModal to make use of a click-trap (no clicking out)
- [x] Adjust the modal backdrop to match the new Figma design
- [x] Add another div to the FactModal component that will contains the 311 logo, loading gif, about-us blurb, and modal-footer
- [x] Add a new state, prop, and callback for when the data is loaded in, e.g. `onDataLoaded`, ensure that the modal changes according to the design flow
- [x] Add a div that renders when the data is loaded which contains the header, 311 blurb, and OK button
- [x] Ensure that the modal remains open until the data has loaded, only closing when they click "OK"
- [x] (optional) Rename FactModal to LoadingModal, or some other name that indicates that more than fun facts are being communicated on the modal 

### Resources/Instructions
- Loading Gif is provided in a few frames by design team, you may need to compile this into a gif, perhaps ask Design for assistance
- MUI Modal component [docs](https://mui.com/material-ui/react-modal/)
- https://github.com/hackforla/311-data/issues/1655
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=9976%3A4824&mode=design&t=oszLfQ2mS8mbJtIx-1)

<details><summary>Screenshot of Figma Section</summary>
<p>

<img width="948" alt="Loading Modal for Handoff 02 28 2024" src="https://github.com/hackforla/311-data/assets/129242704/6ff602d1-f982-422f-b0c5-12f4d31a4f8b">

</p>
</details>

**Comment by cottonchristopher** [comment]
After reviewing/estimating prelaunch tickets and time to launch PM's saw the need for an additional ticket related to another issue.  https://github.com/hackforla/311-data/issues/1655 
Now we need Dev team to complete the above ticket that has been started. adding/correcting information on the ticket and indicating "size".

**Comment by Skydodle** [comment]
Availability: M-F after 7pm PST
Completion ETA: Before 3/20 EOD
