### ISSUE TITLE
Add warning for when user tries to load data prior to 2024

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1677]
### Overview
We need to limit the Datepicker on our map controls to only display years that our app has loaded because we don't want to confuse users when no data appears on the map

### Details/Additional information

We should give the user a way to find out that certain dates are not available via an info button near the date picker.

### Action Items
- [ ] Handoff when ready (will be done in the epic #1680)

*Anna*
- [x] Evaluate/redesign existing popover component
- [x] Gather feedback on popover/iterations
- [x] Document user interaction
- [x] Add designs to Handoff page in Figma

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

Original Issue: https://github.com/hackforla/311-data/issues/1664
Datepicker Info text:

```
311-Data is currently only able to load 311 service request data in 2024 and onwards. For updates on the release of available 311 Data, please follow our LinkedIn page at https://www.linkedin.com/company/hack-for-la/.
```

<details><summary>Screenshot of "Request Types" Info Icon</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/eb7ef307-61bb-4d36-90d4-ae5706f0ea83)

</p>
</details>

**Comment by cottonchristopher** [comment]
After reviewing prelaunch tickets and estimating time to launch PM's saw the need for an additional ticket related to another issue.  https://github.com/hackforla/311-data/issues/1664
Now we need UI/UX team to complete the above ticket that has been started. adding/correcting information on the ticket and indicating "size".

**Comment by ahmedsalah0130** [comment]
Hey @allisonjeon, can you please use this ticket to track your progress. When you've completed your work on Figma can you add the section name and a screen shot of your section on to a comment here, thanks.

**Comment by annaseulgi** [comment]
@allisonjeon hey! i added a couple action items (and a new one from the epic) to help outline some of the requirements

**Comment by annaseulgi** [comment]
@allisonjeon removing your action items due to our conversation today regarding the calendar range (still TBD). will proceed with handing off the popover now!

**Comment by ryanfchase** [comment]
@annaseulgi @allisonjeon We are still modifying our hand off process. If this ticket is ready for hand off, please provide the Figma section name and a Before/After screenshot.

I'm not sure if you guys have a good "Before" image so I'll drop one here

<details><summary>example screenshot of "Before"</summary>
<p>
Feel free to use this in your comment!

![image](https://github.com/hackforla/311-data/assets/6414668/ee01f2d4-c63a-4113-bda9-a11719fdd029)


</p>
</details>

**Comment by allisonjeon** [comment]
This ticket is ready for devs!

[Figma file](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=11228-3674&mode=design&t=yN5G3ifHKOhVuSZD-0) - Information Popover #1677 

<details><summary>Before</summary>
<p>
<img width="367" alt="Screenshot 2024-03-06 at 9 52 25 PM" src="https://github.com/hackforla/311-data/assets/140572176/a728c9c1-c84b-4759-8e63-e701eb9f5e9a">
</p>
</details> 

<details><summary>After</summary>
<p>
<img width="414" alt="Screenshot 2024-03-06 at 9 47 44 PM" src="https://github.com/hackforla/311-data/assets/140572176/a33745eb-a876-4fe3-a2fc-5e3c9f67e29a">

</p>
</details>

**Comment by Skydodle** [comment]
@cottonchristopher @ryanfchase  I've created the new dev ticket (#1696) for this issue and also added the dev ticket to the epic (#1680). So I believe we can now close this design ticket since the rest of the work is for dev. Closing this issue.
