### ISSUE TITLE
(Follow up) Spike: Fix contact form (Dev)

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1678]
### Overview
We need to do X for Y reason.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
- Previous issue/ticket: 
     https://github.com/hackforla/311-data/issues/1536
  - [Fix Contact Form layout on Contact Us page ](https://github.com/hackforla/311-data/issues/1659)[#1659](https://github.com/hackforla/311-data/issues/1659)

**Comment by cottonchristopher** [comment]
After reviewing prelaunch tickets and estimating time to launch PM's saw the need for an additional ticket related to another issue. https://github.com/hackforla/311-data/issues/1536
Can we get Dev team to complete the above ticket that has been initiated to add to/correct information on the ticket and indicating "size".

**Comment by ryanfchase** [comment]
Going to close as Wont Do, this ticket duplicates this ticket: https://github.com/hackforla/311-data/issues/1682
