### ISSUE TITLE
(Follow up) Spike: Fix 'Learn More' link on Cookies (Dev)

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1679]
### Overview
We need to do X for Y reason.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

- linked issue: https://github.com/hackforla/311-data/issues/1673

**Comment by cottonchristopher** [comment]
After reviewing prelaunch tickets and estimating time to launch PM's saw the need for an additional ticket related to another issue. 
Can we get Dev/Front End team to complete the above ticket that has been started, adding/correcting information on the ticket and indicating "size".

**Comment by Skydodle** [comment]
@cottonchristopher ahh sorry I didn't see this ticket until I've already created a dev ticket. here it is:
- #1681 

I'll now close this one that you created.
