### ISSUE TITLE
Add the Privacy route back to reactivate Privacy page

### ISSUE THREAD

**Issue by Skydodle** [hackforla/311-data#1681]
### Overview
We need to reactive the Privacy page route so that when users click on the 'Learn more link' on the cookie notice or the 'Privacy Policy' link in the footer, it will direct them to the privacy page.  PM team has decided it's important to have our privacy policy available for pre-launch.

### More Info
This issue is a follow-up to fix
  - #1673 
  
The dev working on this ticket just needs to add the 'Privacy' route back 
### Action Items
- [ ] Review #1673 and reproduce the problem ('learn more' and 'privacy policy' links directs to empty page)
- [ ] Go to `Routes.jsx`, this is where all our page routes are defined.
- [ ] Import the `Privacy` component from `component/main/Privacy`
- [ ] Add the Privacy route back. Hint: follow the pattern of other routes like About, Contact, etc.
- [ ]  Test to see if the Privacy page works and the links now direct to the Privacy page correctly

### Resources/Instructions
If your console is showing error for missing Contenful credential, reach out to @ryanfchase or myself @Skydodle for the credentials on Slack, but without the credentials if there's a big 'Privacy' text banner on top then that means you've brought the page back correctly.

**Comment by ryanfchase** [comment]
This ticket has been prioritized, thanks @Skydodle
