### ISSUE TITLE
Create data dictionary documentation

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#169]
### Overview
Create a spreadsheet document cataloguing data fields in the 311-data 

### Action Items
- [x] Create Google Doc and link from Wiki
- [x] Look over all Socrata data stores and document these fields' data type, value range, and consistency

### Resources/Instructions
https://www.bridging-the-gap.com/data-dictionary/
https://medium.com/@leapingllamas/data-dictionary-a-how-to-and-best-practices-a09a685dcd61

### Future Directions
- [x] Collaborate with front-end developers and data cleaning team to identify which new fields are being created for analysis and document their location and characteristics similarly to the Socrata data

**Comment by ryanmswan** [comment]
Work in progress document available at: [LINK](https://docs.google.com/spreadsheets/d/1lZG_PvyUTYahdpVEjS4pTm21BRNKbnHAOPDqgWTllYw/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@ryanmswan can you provide an update
1. Progress - I see the link, but unclear what percentage done, etc.
2. Blocks - are there any
3. Availability to work on this
4. ETA to completiong

**Comment by ryanmswan** [comment]
1. Currently about 50% done. This is dependent on #213 and #230 
2. Next step is updating with cleaned data information (additional columns). Final update will be with front-end-facing data structures.
3. Can update periodically as we continue updating data structures.
4. Dependent on other issues, but should be resolved by end of February.

**Comment by ryanmswan** [comment]
Link to Google Docs Repository: https://drive.google.com/drive/u/0/folders/10_KYe3pbZqiq6reeLA8zDDeIlz-4PxWM
