### ISSUE TITLE
Update the Twitter logo to 'X'

### ISSUE THREAD

**Issue by Skydodle** [hackforla/311-data#1691]
### Overview
We need to update the Twitter logo on the footer because the new Twitter logo is now 'X'.

### Action Items
- [x] Check out in Resources below for all the design to engineering handoff materials you need
- [x] Use the light-grey 'X' logo from the Figma design file, becuase its more visible on our dark background footer in comparison to using the dark 'X' logo, but feel free to play around with both and chose at your own judgement
- [x] Replace the Twitter logo on our footer
- [ ] Show before/after screenshots on your pull request
### Resources/Instructions
- Design to Engineering hand off ticket : #1642
- [New logo SVG code](https://github.com/hackforla/311-data/issues/1642#issuecomment-1958673900)
- [Figma design file](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=10563-11837&mode=design)

**Comment by ryanfchase** [comment]
This ticket is ready to be picked up, please note your ETA and Availability when moving this to In Progress

**Comment by drakenguyen4000** [comment]
ETA: Before 3/6/2024

**Comment by ryanfchase** [comment]
@drakenguyen4000 ty for your work on this ticket, please move it to `In Review` while you are awaiting PR reviews.
