### ISSUE TITLE
Recruit Users for External Usability Testing 

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1694]
### Dependency 
- https://github.com/hackforla/311-data/issues/1728

### Overview
We need to recruit external users for unmoderated usability testing to ensure the website is legible to those unfamiliar with the project. 

### Action Items
- [x] Determine platform/medium to conduct testing  
- [x] Reach out to HfLA general Slack channel

**Comment by bberhane** [comment]
Bonnie's comments about testing from PM meeting:

- Conduct moderated testing
 
- Dog-food testing, bug-hunt within Hack for LA (only work on grotesque things) ~20 people (eng vs data science vs pm vs design, multiple CoPs)

- We should test with users right after launch, depending on who we think our users: John Ritchey, former NC members (see lucky parking project @ Seymore -- ask who this person thinks we should ask), maybe ask in #general

- Test the testing, do the moderated usabiilty tests with some outside people first, ~10
 
- Moderated usability tests: reach out to Women in Data, introduce ourselves and see if their members can weigh in (and see if they'd like to partner on our continuing development on it)

**Comment by bberhane** [comment]
Hi @brianmonroetherapy,

Please leave a comment with the following items:

- ETA
- progress from the last week (if applicable)
- availability for communications during the week

**Comment by bberhane** [comment]
@brianmonroetherapy let me know whether this issue is good to close

**Comment by brianmonroetherapy** [comment]
This is completed.  The issue can be closed.

**Comment by bberhane** [comment]
Thanks, @brianmonroetherapy! This is closed
