### ISSUE TITLE
Update styling on date picker warning tooltip

### ISSUE THREAD

**Issue by Skydodle** [hackforla/311-data#1696]
### Overview
We need to update the styling on the date picker's warning tooltip to follow the design from UX team, so that it's more intuitive for users.

### More Info
The dev team previously implemented and deployed a basic warning tooltip while we were waiting for UX team to complete the styling design. Now that UX team has completed the design, the dev team will update the styling following UX design.

### Action Items
- [x] Check out the Figma design file in Resources section below
- [x] Tooltip box shape should be chat dialogue style with one pointed corner pointing towards the info icon
- [x] Tooltip background should change to the white color in Figma file, and text font-color should change as well
- [x] First sentence should be Bold
- [x] Change the sentence wordings
- [x] LinkedIn URL should be hyperlink
- [x] Show before and after screenshots in your pull request

### Resources/Instructions
- [Figma Design file](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=11228-3674&mode=design&t=yN5G3ifHKOhVuSZD-0)
- Previous dev ticket #1664 
- Design ticket #1677 
- Epic ticket that's tracking everything #1680
<details><summary>Visual before proposed changes</summary>
<p>

<img width="412" alt="Screenshot 2024-03-07 at 4 45 16 PM" src="https://github.com/hackforla/311-data/assets/69279538/747b4b63-6aa4-44f7-ba90-f3909ab072b4">

</p>
</details> 

<details><summary>Visual after proposed changes</summary>
<p>
<img width="414" alt="Screenshot 2024-03-06 at 9 47 44 PM" src="https://github.com/hackforla/311-data/assets/140572176/a33745eb-a876-4fe3-a2fc-5e3c9f67e29a">
</p>
</details>

**Comment by ryanfchase** [comment]
@Skydodle I'm removing this line from Action Items. If there are mismatch in designs, we will catch in while ticket is `In Review` and send it back to the dev. I want to remove any possible ambiguity around making changes beyond scope of the ticket.

> - [ ] Take note of any other differences between the current design and the new Figma design, and make changes accordingly

**Comment by Skydodle** [comment]
This ticket is ready to be picked up, please note your ETA and Availability when moving this to In Progress

**Comment by bphan002** [comment]
ETA: Tuesday March 19th
Availability: Thursday 2 hours  & Saturday 4 hours
