### ISSUE TITLE
Clear District Council search box field on deselect

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1699]
### Overview
We need to clear the District Council searchbox field when the user de-selects the council on the UI in order to clarify to the user that the search is no longer active

### Action Items
- [ ] when a council is removed from the search filters term, also clear the CouncilList searchbox

### Resources/Instructions

Relevant Components/Methods
- SearchBar.jsx
- CouncilsList.jsx
- CouncilSelector.jsx::handleDelete()

<details><summary>Demo Video of Problem</summary>
<p>

https://github.com/hackforla/311-data/assets/6414668/936e99ad-33de-40d9-8db8-5053f71bc483

</p>
</details>

**Comment by drakenguyen4000** [comment]
ETA: 3/19/24
