### ISSUE TITLE
Create document cataloguing data sets that can be used in 311 analyses

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#170]
### Overview
Create a document making note of datasets that can be used to perform additional analyses by data science team members

### Action Items

- [x] Create markdown document in documentation folder
- [x] Catalogue data sets that represent information specific to Los Angeles that can be used for supplemental analysis when combined with 311 data
- [x] Catalogue data sets currently in use by team members for combined analysis with 311 data

### Resources/Instructions
See similar examples of documents:
https://github.com/awesomedata/awesome-public-datasets
https://github.com/apiad/datasets-list
https://github.com/tensorflow/datasets

**Comment by ExperimentsInHonesty** [comment]
@JRHutson says the markdown file will be in the repo by 2/4/2020.

**Comment by JRHutson** [comment]
Created Markdown file. Opened merge request #230
