### ISSUE TITLE
Create list of ten fun facts for loading modal

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1701]
### Overview
We need to compile a list of ten fun facts for the loading modal that concern Hack for LA/311 Data so that users understand the website is not affiliated with the City of LA.

### Action Items
- [x] Research Hack for LA
- [x] Create list of most interest-piquing facts
- [x] Paste link as comment and add document to the 311 Data Google Drive
- [x] Apply feedback from research and paraphrase facts pulled verbatim from sources 

### Resources/Instructions
[Fun Facts](https://docs.google.com/document/d/1ew6BaXb_H_WAbe1l2PFnP7wxLNzM92pVwnjegske32I/edit)

**Comment by bberhane** [comment]
Available 3/16 after 4pm

**Comment by bberhane** [comment]
ETA: 3/22, afternoon

**Comment by bberhane** [comment]
Apologies for the delay! [Fun Facts](https://docs.google.com/document/d/1ew6BaXb_H_WAbe1l2PFnP7wxLNzM92pVwnjegske32I/edit?usp=drive_link)

**Comment by bberhane** [comment]
Unassigning myself and moving to In Review for team feedback. Please note that many of these are copied and pasted and will require rewriting

**Comment by bberhane** [comment]
Received feedback from UI/UX research teams and will move forward with rewriting and editing. Holly suggested adding a few active or completed Hack for LA projects with a short description. Design says tidbits should be no longer than two lines. Updating action items, assigning myself, and moving to "in progress."

**Comment by bberhane** [comment]
Link to fun facts below for dev to upload, unassigning myself, adding ready for dev lead label but keeping issue open.

[Fun Facts Final](https://docs.google.com/document/d/1ew6BaXb_H_WAbe1l2PFnP7wxLNzM92pVwnjegske32I/edit)

**Comment by ryanfchase** [comment]
Thank you @bberhane!  I've opened up a new dev ticket so we can mark this ticket as done.

Dev ticket: https://github.com/hackforla/311-data/issues/1727
