### ISSUE TITLE
Make headers across pages consistent (TEST, NO ACTION REQUIRED)

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1702]
### Overview
We need to make the headers the same size for visual continuity.

### Action Items

- [x] Address the problem overview with possible design solution(s) in a comment
- [x] Complete Design Iterations section below
- [ ] Document user interaction in Figma

---

### Design Iterations

**Please move ticket between `In Progress` and `In Review` to assist PM team**

<details><summary>Iteration 1</summary>
<p>

Link to notes: 
- Change the font to HELVETICA
- Change the margin to .05 px
- Change the background color to purple 

<img width="1000" alt="Screen Shot 2024-03-20 at 8 10 07 PM" src="https://github.com/hackforla/311-data/assets/143574036/fa39d9cc-4273-4d6c-84e5-43f0282ff545">

</p>
</details> 

---

### Hand Off Materials

Figma Section Name: `REPLACE WITH SECTION NAME`

<details><summary>Before Screenshot</summary>
<p>

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details> 

<details><summary>After Screenshot (Finalized)</summary>
<p>

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details> 

### Designer Resources

<details><summary>Iteration Dropdown Copy/Paste</summary>
<p>

```
<details><summary>Iteration X</summary>
<p>

Link to notes: `REPLACE WITH COMMENT URL`

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details> 
```

</p>
</details> 

<details><summary>Instructions for Engineering Hand Off</summary>
<p>

To Start Engineering Hand Off...
1. Ensure all Hand Off Materials are filled in
3. Add the "ready for dev lead" label
4. Leave a comment saying "This ticket is ready for engineering hand off." 

</p>
</details>

**Comment by bberhane** [comment]
This comment covers first listed action step. Ex. The header size differs across pages and so does the text. I suggest width of X and height of Y and a serif font.

**Comment by bberhane** [comment]
Alt to changing the ticket contents:
ITERATION 1
- Change the font to HELVETICA
- Change the margin to .05 px
- Change the background color to HEX #00000

<img width="1000" alt="Screen Shot 2024-03-20 at 8 10 07 PM" src="https://github.com/hackforla/311-data/assets/143574036/befe51eb-d362-46e5-9288-b9c23d4884bd">

**Comment by bberhane** [comment]
<details><summary>Iteration 2</summary>
<p>

Link to notes:
- Make the font BIGGER
- Make the margins smaller
- Make the background HEX `#FFFFFF`

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details>

**Comment by ryanfchase** [comment]
I vote to close this issue as Wont Do :)

**Comment by bberhane** [comment]
Then we shall
