### ISSUE TITLE
Integrate socrata seeder into backend api

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#171]
### Overview
@ryanmswan Has created the socrata connector when run directly via python script
This task will integrate is work into the backend api

### Dependency
#210 

### Action Items
- [ ] Modify `POST /ingest` endpoint to use the new functionality 
- [ ] Enable a new dev to run the `onboard.sh` then hit localhost/ingest and bring in N datasets based on params

**Comment by ExperimentsInHonesty** [comment]
@GeorgeSu Please provide update on:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by sellnat77** [comment]
This is complete minus the onboard.sh changes but that merits a new ticket for a rewrite when the architecture is more mature
