### ISSUE TITLE
Search and Filters modal needs to remove abbreviation of NC names

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1710]
### Overview
We need to stop abbreviating the searchable NC names in the Search and Filters modal because it is forcing users to type in the exact abbreviation, making it difficult to find those NCs

### Action Items
- [x] Remove abbreviation of NC names when rendering them in the Search and Filters modal
- [x] allow those NCs to be searchable by their full names
- [x] if searched NC names are too long for one line in the Search and Filter modal, apply new styles for multi-line NC names
- [x] if selected NC names are too long for one line in the Search and Filter modal, apply new styles for multi-line selected NC name

### Resources/Instructions
- See new styles for multi-line NC names and selected multi-line NC names: https://github.com/hackforla/311-data/issues/1650
- please IGNORE changes to styles for the Search and Filters modal container

**Comment by Skydodle** [comment]
@bphan002 Thanks for picking up this ticket! Just a friendly reminder to put the ticket into 'In Progress' on the Project Board after pick up =) have fun

**Comment by ryanfchase** [comment]
@bphan002 

Regarding " - please IGNORE changes to styles for the Search and Filters modal container"...

As you can see by the [related design ticket](https://github.com/hackforla/311-data/issues/1650), the entire Search and Filters modal has received new styles. These designs have not been approved for engineering yet -- there was a hiccup with the design system that leaked someone else's work into the hand-off designs for multi-line NC names.

As best you can, please keep the styles of the current implementation of the Search and Filters modal.

<details><summary>Screenshot of desired multi-line NC name styles</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/17b4eab8-6dd9-4a0e-bfae-c1c04029f31d)

</p>
</details> 

<details><summary>current implementation Search and Filters modal styles</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/3d9cbbb3-0e54-4a26-bab7-702d5d125136)


</p>
</details>
