### ISSUE TITLE
Create research issue template

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1715]
### Overview
We need to create an issue template for research so that we have research issues that are HfLA compliant. 

### Action Items
- [x] Find research issue templates from Internship – Research repository
- [x] Review ticket template (below)
- [x] Modify Internship template so that it makes sense for 311 Data
- [x] Discuss template with PM team
- [x] Finalize template

### Notes:
- Future task for when we have more than three research plans (this is a table of contents): [Wiki Research Output Overview Page](https://github.com/hackforla/internship/wiki/Research-Output-Overview)
- This will be relevant when the above is accomplished, i.e., more fleshed out Wiki: Edit placeholders in Overview of this issue with the relevant information in square brackets. (personalizes the issue to make it easier to read). Any place you see [replace...] replace both the text and the brackets with what it is asking for (including in the front matter above but not where it says name, but not where it says title.
-     - [ ] Go to the Research Output Overview Page (link in Resources)
       - [ ] find the relevant overview type wiki page. 
       - [ ] change `[Wiki [TYPE] Research Overview Page]` in the Resources below with the correct wiki page of the research overview by type.
     - [ ] Go to the Research Output Overview Page again
        - [ ] find the relevant wiki page for this specific research plan. 
        - [ ] change the `[RP__ Wiki Page]` in the Resources below with this RP's specific wiki page.
     - [ ] Find and link the folder you are going to put your research plan in  (e.g., Research by Type>2. Intern>RP6 - Intern Intake Interviews)
- For "Update this issue with the relevant Resources," confirm with Holly the Google Drive naming convention/navigation
- Ask Holly where the 311 Data research plan template is to add link to resources section for this template

### Resources/Instructions
INTERNSHIP TEMPLATE TO MODIFIED BELOW

```
### Dependencies
- [ ] [Replace this with Roadmap issue #]
- [ ] A research setup structure has been created and approved.

### Overview
We need to create a Research Plan for [NAME OF RESEARCH PLAN] so that [RESEARCH GOAL(S)].

### Action Items
- [ ] Update this issue to make sure it's properly categorized and easy to manage
     - [ ] Under "Projects," add to the Project Management Board (helps with Project Management overview)
     - [ ] Add the milestone: [07 - Research Plan Creation V1.2](https://github.com/hackforla/311-data/milestone/35) (helps with prioritization)
     - [ ] Add label of the correct research plan number associated with this research plan (e.g., Research: RPV1.2 - Moderated Test) (helps you find related issues in the same workflow)
     - [ ] Edit title of issue with the correct research plan number (same as prior)    
- [ ] Update this issue with the relevant Resources: 
        - [ ] Go to the Google Drive's Research by Type Folder (link in Resources)
        - [ ] Go into the relevant Type Folder 
        - [ ] once inside, right-click on the relevant destination folder and copy the link. 
         - [ ] Add the Google Drive link in the Resources below with the link you just copied and revise the display text to include the Research Plan name
- [ ] Create the Research Plan Document.
     - [ ] Make a new document using the 311 Data Research Plan template (link in Resources). Follow the instructions in the How To Write a Research Plan guide (link in Resources) and mark your progress in this issue.
     - [ ] Move your document from "My Drive" to the shared drive 311 Data folder of this specific RP.
     - [ ] Name your document to be called "311 Data: RP___ : [TITLE OF RESEARCH] Research Plan".
     - [ ] Update the document with the relevant information in accordance with the research roadmap document 
     - [ ] Update the Table of contents (page 2) when you are finished with the document.
- [ ] Once research lead has signed off, add it to the PM/Research lead agenda
- [ ] Sign-off by PM 
- [ ] Does this issue have any dependency checkboxes in the action items here?
   - [ ] If yes, remove dependencies that are listed below (issues that are waiting on this issue to be completed.  Sometimes they have already been made and sometimes they yet to be made).
       - [ ] Close this issue
   - [ ] If no, check to see if the follow-up issues have already been made.  If new issues have not been made, then apply label `ready for research lead` and define what needs to be done in a comment below.
      - [ ] Close the issue
      - [ ] Move to `Question/Review` Column


### Resources
- [Google Drive RP__ Folder]
- [TWE: How to Write a Research Plan](https://docs.google.com/document/d/1Cwc0w4ZPUI8989w3jU8BW2LzLK_Tl5gHdI0VxN5ej0o/edit)
```

**Comment by bberhane** [comment]
@ryanfchase @cottonchristopher @rsschacht Input requested!
Here's what I have so far for the research plan template; we'll need one for usability testings as well
NOTE FOR ACTION ITEMS: Let's create a research plan label

### Dependencies
- [ ] Include any contingent issues 

### Overview
We need to create a Research Plan for [NAME OF RESEARCH PLAN] so that [RESEARCH GOAL(S)].


### Action Items
- [ ] Update this issue to make sure it's properly categorized and easy to manage
     - [ ] Under "Projects," add to the Project Management Board (helps with Project Management overview)
     - [ ] Add the milestone: [Research Plan Creation](WE NEED TO CREATE A MILESTONE FOR THIS)(helps with prioritization)
     - [ ] Add label of the correct research plan number associated with this research plan (e.g., Research: RP001) (helps you find related issues in the same workflow)
     - [ ] Edit title of issue with the correct research plan number (same as prior)
     - [ ] Edit placeholders in Overview of this issue with the relevant information in square brackets. (personalizes the issue to make it easier to read). Any place you see [replace...] replace both the text and the brackets with what it is asking for (including in the front matter above but not where it says name, but not where it says title)
- [ ] Update this issue with the relevant Resources: 
     - [ ] Find and link the folder you are going to put your research plan in  
         - [ ] Add the Google Drive link in the Resources below with the link you just copied and revise the display text to include the Research Plan number (e.g., `Google Drive RP__ Folder` to `Google Drive RP2 Folder`)
- [ ] Create the Research Plan Document.
     - [ ] Make a new document using the Research Plan template (link in Resources). Follow the instructions in the How To Write a Research Plan guide (link in Resources) and mark your progress in this issue.
     - [ ] Move your document from "My Drive" to the shared drive 311 Data folder of this specific RP.
     - [ ] Name your document to be called "311 Data: RP___ : [TITLE OF RESEARCH] Research Plan."
     - [ ] Update the Table of contents (page 2) when you are finished with the document.
- [ ] Meet and sign off research plan document with UX Research lead (by adding it to meeting agenda).
- [ ] Once research lead has signed off, add it to the PM/leads agenda
- [ ] PM to sign off
- [ ] Does this issue have any dependency checkboxes in the action items here?
   - [ ] if yes, remove dependencies that are listed below (issues that are waiting on this issue to be completed. Sometimes they have already been made, and sometimes they yet to be made).
       - [ ] Close this issue
   - [ ] If no, check to see if the follow-up issues have already been made. If new issues have not been made, then apply label `ready for research lead` and define what needs to be done in a comment below
      - [ ] Close the issue
      - [ ] Move to `Question/Review` Column


### Resources
- [Google Drive 311 Data RP__ Folder]
- [TWE: Research Plan Template](https://docs.google.com/document/d/1SDW6n086PnSrrVSmPgQZWhlkz5_yC70vDvp7Lx7u0Wo/template/preview)
- [TWE: How to Write a Research Plan](https://docs.google.com/document/d/1Cwc0w4ZPUI8989w3jU8BW2LzLK_Tl5gHdI0VxN5ej0o/edit)

**Comment by bberhane** [comment]
Unassigned myself and moved to review/demo lane for PM discussion. Thanks!

**Comment by ryanfchase** [comment]
This is ready to be closed!

**Comment by bberhane** [comment]
It sure is!
