### ISSUE TITLE
Search and Filter modal: Update Address Searchbar Text

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1717]
### Overview
We need to update the current "Search and Filter" modal's searchbar text to something that is indicates more directly and clearly what information to type

#### Text Replacements

- Address search bar: Replace "Search" with "Enter an address or locations"  
- Neighborhood council search bar: Replace "Enter district" with "Enter council name"
- Neighborhood council dropdown: Replace "Neighborhood Districts" with "Neighborhood Councils"

### Action Items

- [x] Add screenshot of before, indicating area to change
- [ ] Update address search bar text
- [ ] Update neighborhood council search bar text
- [ ] Update neighborhood council dropdown text
- [ ] Add screenshot of "After" indicating changes/updates completed

---

### Images

<details><summary>Before Screenshots</summary>
<p>

### Address search bar text
<img src="https://github.com/hackforla/311-data/assets/142280921/3286ab6c-056d-488f-94c1-e6a6d6cefe1c" width="60%" height="60%">

### Neighborhood Council search bar text

![image](https://github.com/hackforla/311-data/assets/6414668/75fe05b9-fd0c-4de5-86bd-84fd1646edae)

### Neighborhood Council dropdown text

![image](https://github.com/hackforla/311-data/assets/6414668/7df78600-757e-4989-bf7d-b8b8e583d5e4)

</p>
</details> 

<details><summary>After Screenshot (Finalized)</summary>
<p>

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details> 

### Resources

Research Team's requested changes for research plans: [Google Drive Link](https://docs.google.com/presentation/d/1dsDHbDFjh0gxZTID-CjVG9fLgO7PcbnW/edit?usp=drive_link&ouid=108496399662207959580&rtpof=true&sd=true)

**Comment by ryanfchase** [comment]
@cottonchristopher I made a few modifications but this is good, I can get this prioritized and ready for pickup:

My changes:
- added a little more to the issue's title
- in the Overview, stated we need to change the searchbar's text
- I removed `- [ ] Confirm consistency of design including font, layout, size, shape design, etc.` since there isn't a specific change requested. Removing this will make it very clear that only 1 item is requested for change

**Comment by ryanfchase** [comment]
This ticket was updated to include 2 more text update regions

**Comment by ryanfchase** [comment]
Hi @funbunch, please try to update this to In-Progress if you are still working on this. Otherwise we can get it assigned to another member if you are unavailable.

**Comment by funbunch** [comment]
@ryanfchase Just updated and looking over now!
