### ISSUE TITLE
Update: Search and Filter modal "Request Status" Info Button

### ISSUE THREAD

**Issue by cottonchristopher** [hackforla/311-data#1718]
### Dependency
- [x] get clarification on ": Closed does not mean resolved"

### Overview
We need to add an info button to the Search and Filter modal "Request Status" field to provide clarity to the options (All, Open, Closed) that the user may select.

### Desired Info Popover Text:
There are multiple definitions of closed, including the following: The issue may have already been reported (duplicate request), the issue could have been resolved, or a service technician visited the site of the reported issue and put in an internal request to resolve it.

### Action Items

- [x] Add screenshot before changes/what needs to be changed below in "Image/Screenshot" section below
- [x] Add information symbol just to the right of the Request Type (see reference below)
- [x] In the information symbol pop-up, add the text (see Desired Info Popover Text)
- [ ] Add screenshot of "After" indicating changes/updates completed, in the image screenshot section. 

---

### Images/Screenshots

<details><summary>Before Screenshot</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/142280921/2f9968e7-757f-49f7-9f9a-165e1338b444)

</p>
</details> 

<details><summary>Screenshots of (i) icon, use as reference</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/da27e9f2-8970-463e-9556-2287759990a3)

</p>
</details> 

<details><summary>After Screenshot (Finalized)</summary>
<p>

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details> 

### Resources

Research Team's requested changes for research plans: [Google Drive Link](https://docs.google.com/presentation/d/1dsDHbDFjh0gxZTID-CjVG9fLgO7PcbnW/edit?usp=drive_link&ouid=108496399662207959580&rtpof=true&sd=true)

**Comment by cottonchristopher** [comment]
@ryanfchase @bberhane @rsschacht if you would like to review

**Comment by ryanfchase** [comment]
@cottonchristopher thank you for this ticket. I've made a few updates similar to https://github.com/hackforla/311-data/issues/1717

My changes:
- updated the title to highlight "info button"
- Added Dependency, for obtaining the information regarding "Status: Closed", Moved this ticket to Icebox
- removed Action Steps that say to wait for information from PM team, also removed Action Step saying "make sure style is consistent" -- see my reasoning in 1717

**Comment by ryanfchase** [comment]
This ticket is ready to be picked up!

**Comment by ryanfchase** [comment]
I've done the work related to this ticket. I've paired it with the work needed for this ticket: https://github.com/hackforla/311-data/issues/1724

Moving this ticket to in-review. PR: https://github.com/hackforla/311-data/pull/1725

**Comment by ryanfchase** [comment]
Marking as done with the merge of this PR: https://github.com/hackforla/311-data/pull/1725
