### ISSUE TITLE
Add Console logs to display when all Pins have loaded

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1719]
### Overview
We need to add logging into our site to show when all Service Requeset Pins have rendered

### Action Items
- [ ] add log for "pin rendering time"

### References / More Info
- See `performance.now()` on how to collect time info (e.g. checking database loading time): https://github.com/Skydodle/311-data/blob/e0859fed99ebbdf09b07bf72ed74a19f117203f7/components/Map/index.js#L80
- look into mapbox `map.on('load', ...)
- MapboxGL: https://docs.mapbox.com/mapbox-gl-js/api/map/

**Comment by Skydodle** [comment]
Added time tracking logs for table creation, data loaded, and map loaded which were completed and merged in PR #1711.

@ryanfchase  Moving this ticket back to Prioritized Backlog so someone can finish adding time tracker for pin rendering.
