### ISSUE TITLE
Blank Research Plan Template

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1721]
### Dependencies
- [ ] [Replace this with Roadmap issue #]
- [ ] A research setup structure has been created and approved.

### Overview
We need to create a Research Plan for [NAME OF RESEARCH PLAN] so that [RESEARCH GOAL(S)].

### Action Items
- [ ] Update this issue to make sure it's properly categorized and easy to manage
     - [ ] Under "Projects," add to the Project Management Board (helps with Project Management overview)
     - [ ] Add the milestone: [07 - Research Plan Creation V1.2](https://github.com/hackforla/311-data/milestone/35) (helps with prioritization)
     - [ ] Add label of the correct research plan number associated with this research plan (e.g., Research: RPV1.2 - Moderated Test) (helps you find related issues in the same workflow)
     - [ ] Edit title of issue with the correct research plan number (same as prior)    
- [ ] Update this issue with the relevant Resources: 
        - [ ] Go to the Google Drive's Research by Type Folder (link in Resources)
        - [ ] Go into the relevant Type Folder 
        - [ ] once inside, right-click on the relevant destination folder and copy the link. 
         - [ ] Add the Google Drive link in the Resources below with the link you just copied and revise the display text to include the Research Plan name
- [ ] Create the Research Plan Document.
     - [ ] Make a new document using the 311 Data Research Plan template (link in Resources). Follow the instructions in the How To Write a Research Plan guide (link in Resources) and mark your progress in this issue.
     - [ ] Move your document from "My Drive" to the shared drive 311 Data folder of this specific RP.
     - [ ] Name your document to be called "311 Data: RP___ : [TITLE OF RESEARCH] Research Plan".
     - [ ] Update the document with the relevant information in accordance with the research roadmap document 
     - [ ] Update the Table of contents (page 2) when you are finished with the document.
- [ ] Once research lead has signed off, add it to the PM/Research lead agenda
- [ ] Sign-off by PM 
- [ ] Does this issue have any dependency checkboxes in the action items here?
   - [ ] If yes, remove dependencies that are listed below (issues that are waiting on this issue to be completed.  Sometimes they have already been made and sometimes they yet to be made).
       - [ ] Close this issue
   - [ ] If no, check to see if the follow-up issues have already been made.  If new issues have not been made, then apply label `ready for research lead` and define what needs to be done in a comment below.
      - [ ] Close the issue
      - [ ] Move to `Question/Review` Column

### Resources
- Google Drive RP__ [Folder](https://drive.google.com/drive/u/0/folders/19oXFkecEclzt4HQvL3tMOY4L0N8pqpRa)
- [TWE: How to Write a Research Plan](https://docs.google.com/document/d/1Cwc0w4ZPUI8989w3jU8BW2LzLK_Tl5gHdI0VxN5ej0o/edit)

**Comment by ryanfchase** [comment]
I think this was made in error @bberhane 

Closing this since our template was made correctly in Issue Templates!

**Comment by bberhane** [comment]
Indeed it was! I thought I closed it thoughSent from my iPhoneOn May 9, 2024, at 9:35 PM, Ryan Chase ***@***.***> wrote:﻿
I think this was made in error @bberhane
Closing this since our template was made correctly in Issue Templates!
