### ISSUE TITLE
Modify Fun Fact List to Approved Fact List

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1727]
### Overview
We need to update the fun fact list to use the list of facts provided by PMs and approved by Bonnie

### Action Items
- [x] Replace list of strings in `data/fact.js` to match the facts provided in the document below

### Resources/Instructions
[Fun Facts List Document](https://docs.google.com/document/d/1ew6BaXb_H_WAbe1l2PFnP7wxLNzM92pVwnjegske32I/edit)

**Comment by drakenguyen4000** [comment]
ETA 5/31/24
