### ISSUE TITLE
Pre-release 2nd Round Moderated Usability Study 

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1733]
### Dependencies
- [ ] A research setup structure has been created and approved.

### Overview
We need to create a Research Plan for [Moderated Usability Study RPV1.2] so that [we can get member feedback on the latest version of the 311 Data website to prepare for our public launch].

### Action Items
- [x] Update this issue to make sure it's properly categorized and easy to manage
     - [x] Under "Projects," add to the Project Management Board (helps with Project Management overview)
     - [x] Add the milestone: [07 - Research Plan Creation V1.2](https://github.com/hackforla/311-data/milestone/35) (helps with prioritization)
     - [x] Add label of the correct research plan number associated with this research plan (e.g., Research: RPV1.2 - Moderated Test) (helps you find related issues in the same workflow)
     - [x] Edit title of issue with the correct research plan number (same as prior)    
- [x] Update this issue with the relevant Resources: 
  - [x] Go to the Google Drive's Research by Type Folder (link in Resources)
  - [x] Go into the relevant Type Folder 
  - [x] once inside, right-click on the relevant destination folder and copy the link. 
  - [x] Add the Google Drive link in the Resources below with the link you just copied and revise the display text to include the Research Plan name
- [x] Create the Research Plan Document.
     - [x] Make a new document using the 311 Data Research Plan template (link in Resources). Follow the instructions in the How To Write a Research Plan guide (link in Resources) and mark your progress in this issue.
     - [x] Move your document from "My Drive" to the shared drive 311 Data folder of this specific RP.
     - [x] Name your document to be called "311 Data: RP___ : [TITLE OF RESEARCH] Research Plan".
     - [x] Update the document with the relevant information in accordance with the research roadmap document 
     - [x] Update the Table of contents (page 2) when you are finished with the document.
- [x] Once research lead has signed off, add it to the PM/Research lead agenda
- [x] Sign-off by PM 
- [ ] Does this issue have any dependency checkboxes in the action items here?
   - [ ] If yes, remove dependencies that are listed below (issues that are waiting on this issue to be completed.  Sometimes they have already been made and sometimes they yet to be made).
       - [ ] Close this issue
   - [ ] If no, check to see if the follow-up issues have already been made.  If new issues have not been made, then apply label `ready for research lead` and define what needs to be done in a comment below.
      - [ ] Close the issue
      - [ ] Move to `Question/Review` Column

### Resources
- Google Drive RP__ [Folder](https://drive.google.com/drive/u/0/folders/19oXFkecEclzt4HQvL3tMOY4L0N8pqpRa)
- [TWE: How to Write a Research Plan](https://docs.google.com/document/d/1Cwc0w4ZPUI8989w3jU8BW2LzLK_Tl5gHdI0VxN5ej0o/edit)
- [Moderated Usability Testing Research Plan](https://docs.google.com/document/d/1Djp2o4FFm6jSkXIQT4H8EfM5SBXM09lWVgPNI0BEcCM/edit)

**Comment by bberhane** [comment]
@hworthen ready for your seal approval

**Comment by bberhane** [comment]
Hi @hworthen,

Please leave a comment with the following items:

- updated ETA
- progress from the last week (if applicable)
- availability for communications during the week

**Comment by rrhea22** [comment]
Here is the Figma file for brainstorming: https://www.figma.com/board/5U3zkZnDKOcqGgdbcur2lp/311-Data-Research?node-id=0-1&t=kQCbGFemmMhQVuD2-1

**Comment by bberhane** [comment]
Hi @rrhea22 and/or @brianmonroetherapy,

Please leave a comment with the following items:

- updated ETA
- progress from the last week (if applicable)
- availability for communications during the week

**Comment by rrhea22** [comment]
Here is the update:
- The presentation that summarises the key findings will be ready to share with the team by next Wednesday, 8/28
- We plan to work on the presentation together this week

**Comment by bberhane** [comment]
@rrhea22 Thanks so much! Let us know if you're still on track to present tomorrow so we can add the presentation to the agenda.

**Comment by rrhea22** [comment]
Yes, we would love to present tonight if the schedule allows :)

**Comment by cottonchristopher** [comment]
Next step/future movements
closing remarks and ideas: 
-review NC interviews and Data scientist feedback and analyze and decide what would be useful. 
-User Persona creation: which are the targeted personas? review what the target audience is telling us? 
@brianmonroetherapy and @rrhea22 
Thank you
