### ISSUE TITLE
Update messaging on 311-data.org to state that we are not the City of LA

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1737]
### Overview
We need to update the 311-data.org website to explicitly state that the 311 Data project has no affiliation with the City of LA so people who visit the site do not assume they will be receiving official communications from the City when they subscribe for updates on the 311 Data project. 

### Action Items
- [x] On the landing page, replace the current messaging with the approved messaging (see resources below)

### Resources/Instructions
Current messaging on 311-data.org: 
```
The 311 Data Site is temporarily down while we rebuild. Provide your email below to get updates on the new release. If you are looking to place a 311 ticket, please visit https://myla311.lacity.org/
```

Approved messaging on GitHub pages site: 

```
311-data.org is 100% powered by volunteers from Hack for LA and is not affiliated with the city of Los Angeles. For official information about 311 services in Los Angeles, please visit [MyLA311](https://lacity.gov/myla311).
```

### Links
- [311-data.org](https://311-data.org/)
- [311-data.org landing-page github repo](https://github.com/hackforla/311-landingpage)

**Comment by ryanfchase** [comment]
I made a few minor adjustments, but otherwise this is ready to be prioritized:

My changes
- added link for [311-data landing-page github repo](https://github.com/hackforla/311-landingpage) since it is technically different than our main [311-data github repo](https://github.com/hackforla/311-data)
- updated Action Item to reference the updated language in the Resources section

**Comment by ryanfchase** [comment]
@bberhane ACTUALLY -- turns out this site is managed by our Mailchimp account. This is a PM task, and since I'm logged in, I should be able to work on this ticket. Moving it out of draft, moving it to `role: product management`, and assigning myself

**Comment by ryanfchase** [comment]
@bberhane I actually think we should keep the current messaging to clarify that the site is still down. I've opted to append the approved messaging. I've updated the site and it is available for review:

See [here](https://mailchi.mp/0a55d32db98e/zqb0z3jn23) or [here](https://311-data.org/) for latest version.

**Comment by bberhane** [comment]
Ah, yes, my instructions were unclear! Thank you for finessing! @ryanfchase I reviewed the updated site, and I have some cosmetic qualms, particularly, the text size/order. 

Can we make this text larger?: `The 311 Data Site is temporarily down while we rebuild. Provide your email below to get updates on the new release.`

Can we make this text smaller?: `311-data.org is 100% powered by volunteers from Hack for LA and is not affiliated with the city of Los Angeles. For official information about 311 services in Los Angeles, please visit[ MyLA311](https://lacity.gov/myla311).`

If text is the same size, then can we move `311-data.org is 100% powered by volunteers from Hack for LA and is not affiliated with the city of Los Angeles. For official information about 311 services in Los Angeles, please visit[ MyLA311](https://lacity.gov/myla311).` to below `If you are looking to place a 311 ticket, please visit https://myla311.lacity.org/`

If any of these are feasible, perhaps we just discuss in our next PM meeting before making any updates

**Comment by ryanfchase** [comment]
Assigning back to myself while I work on this

**Comment by ryanfchase** [comment]
Just for next time, here's how I'm able to edit this:

1. login on 1password and access 311-data vault
2. grab 311-data@hackforla.org password and login 
3. grab mailchimp username/password/security questions and prepare to send security code to email address
4. punch in code and login to mailchimp
5. On the left-hand sidebar, click Campaigns
6. On "311-Data landing page", select the dropdown and click "edit"
7. Scroll down to Design and click "edit design" on the right hand side
8. You should now be able to edit!

**Comment by ryanfchase** [comment]
@bberhane I think this should be good now! Have a look: https://311-data.org/

**Comment by cottonchristopher** [comment]
Reviewed by PM team, Approved.
