### ISSUE TITLE
Set up contact form on website 

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1739]
### Overview
We need to set up the contact form so users can submit inquiries or suggestions, which we can then receive and respond to. 

### Action Items
- [ ] Review links below to understand how HfLA Website team handles forms/submissions
- [ ] Replace contact form with embedded Google Form, then do Google Apps Script

### Resources/Instructions
- PMs to decide what our CRM page/dashboard would look like for comment submissions 
- Contact Form: See HfLA Website team's Wins AppScripts
- Consider GithubSecrets
- Use a google App Script to open a GitHub issue with label `new-contact-submission`
- Perhaps add a dashboard to see if there are any unanswered emails
- Related ticket: https://github.com/hackforla/311-data/issues/1682 

### Links to review
[Wins page on HfLA website](https://docs.google.com/forms/d/e/1FAIpQLSeTiFjtxKbYgrJHAdFUovXlE55BdwwUQ9NePOXRY2q-h-w1tg/viewform
)
[Website team's submissions tickets](https://github.com/hackforla/website/issues?q=is%3Aissue+label%3Anew-win-submission+is%3Aclosed) 
[How the Wins page works](https://github.com/hackforla/website/wiki/Wins-page)

**Comment by ryanfchase** [comment]
Assigning myself while I review this ticket

**Comment by ryanfchase** [comment]
I think we can move forward with closing this ticket as wont do, since this ticket now has all the relevant info we need to proceed: https://github.com/hackforla/311-data/issues/1682
