### ISSUE TITLE
Adjust docker images to use github packages as a registry

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#174]
### Overview
Use github packages...or whatever its called to act as a container registry. This will allow devs to point here for image layer caches and avoid long image build times

### Action Items
- [ ] Front end docker images built and pushed to github packages
- [ ] Back end docker images built and pushed to github packages
- [ ] Prove that we can utilize github's registry for cached layers

### Resources/Instructions
https://help.github.com/en/github/managing-packages-with-github-packages/configuring-docker-for-use-with-github-packages

**Comment by sellnat77** [comment]
Haven't started
Blocked by life
Eta unknown, someone can grab this if interested

**Comment by ExperimentsInHonesty** [comment]
@sellnat77 Thanks for the update.  This will go back into the prioritized backlog.  If you get time to work on anything, just grab it again, if it's at the top of the priority list.

**Comment by sellnat77** [comment]
See https://github.com/hackforla/311-data/packages for reference
