### ISSUE TITLE
 Ensure the loading modal only appears on the map page

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1740]
### Overview
We need to remove the loading modal from all website pages except the map page because those pages don't house data, and users may be confused when they see it on, for example, the About page. 

### Action Items
- [ ] Reproduce the issue
- [ ] Prevent the data loading modal from appearing on all non-map pages

### Resources/Instructions
This issue doesn't occur on all operating systems. Please reproduce the issue and test out on different systems/machines. 

e.g., https://hackforla.github.io/311-data/#/about

<details><summary>Screenshot of modal outside of map</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/c5b4c785-58ab-4faf-bb12-549bfb574a6d)

</p>
</details>

**Comment by ryanfchase** [comment]
I've just added a little extra clarification to the 2nd action item:
 `Remove from all non-map pages` --> `Prevent the data loading modal from appearing on all non-map pages`

I am approving this issue and moving it to Prioritized Backlog @bberhane

**Comment by ryanfchase** [comment]
This ticket is ready for pickup

**Comment by bphan002** [comment]
ETA: Saturday June 1st
