### ISSUE TITLE
SR CSV download functionality needs an Address and Count export 

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1746]
### Overview
We need to be able to export, for a given SR, Address and Number of SRs at that address so that NCs can act on areas of priority in their neighborhood.

### Note for Dev
- we are getting started on the "backend/data" portion of this feature before the design is ready for implementation
- document your assumptions in the implementation (e.g. only 1 SR is selected in the UI) or implement limitations (e.g. fail out if > 1 SR is selected)

### Action Items
In `components/main/Desktop/ExportButton.jsx`
- [x] create the query string, `groupedAddressQuery`, that will yield the correct result(see pseudo-code)
- [x] use `await conn.query(groupedAddressQuery)` to query duckdb (assign as variable, `groupedAddressesToExport`
- [x] use `ddbh.getTableData(groupedAddressesToExport)` to get an exportable js object
- [x] convert the object to CSV
- [x] additionally include this CSV into the zipped file contents
- [x] TEMPORARY: uncomment the export button to test your implementation, see [Export Button Implementation](https://github.com/hackforla/311-data/pull/1612/files) for list of all areas to uncomment

### Resources/Instructions
- Info on Duckdb WASM: https://duckdb.org/2021/10/29/duckdb-wasm.html
- Duckdb SQL intro: https://duckdb.org/docs/sql/introduction.html
- Export Button Implementation (very useful): https://github.com/hackforla/311-data/pull/1612/files

General query body pseudo-code for Duckdb:

```sql
SELECT
  Address, 
  COUNT(*) AS NumberOfRequests
FROM requests
WHERE 
  CreatedDate >= (start_date) AND
  CreatedDate < (end_date) AND
  Status = 'Open' AND
  NC = (council_id) AND
  RequestType = (request_type)
GROUP BY
  Address;
```

**Comment by bberhane** [comment]
This one looks good to go—moved to prio backlog and updated labels

**Comment by ryanfchase** [comment]
@kdow thank you for your work on this! I'm requesting a few items before we can move forward with review. Please check the boxes when you've completed them:

### Action Items

- [ ] Make sure your questions have the correct visibility and labels
  - [ ] move your questions onto a comment on this issue (#1746)
  - [ ] add the `Question` and `ready for dev lead` labels
- [ ] Please check all the action items in this issue as you've completed them. Specify in a comment if you've taken a different approach, or if the action items were too granular (this is good feedback for dev leads)

Thanks @kdow -- otherwise looking forward to completing your review once the above is done and we've addressed your questions!

**Comment by kdow** [comment]
Questions:

- I had to change the table name from `requests` to `requests_2024` for the queries to work. Should this be left as `requests` or `requests_2024` for now?
- The way I've currently implemented a solution will only generate the SR count CSV if it meets the following conditions: exactly one SR type is selected, a NC is selected, and status is Open. Should any of those requirements be changed?

**Comment by ryanfchase** [comment]
Adding a review / addressing comments later this afternoon, thanks!

**Comment by ryanfchase** [comment]
> The way I've currently implemented a solution will only generate the SR count CSV if it meets the following conditions: exactly one SR type is selected, a NC is selected, and status is Open. Should any of those requirements be changed?

Can you just add a comment to an upcoming commit that says: 
```
// Note: this logic will only generate the SR count CSV if it meets the following conditions: exactly one SR type is selected, a NC is selected, and status is Open. 
```

I think that will be sufficient for now! I will paste this on the PR, moving back to `In Review`, thanks @kdow !

**Comment by kdow** [comment]
ETA for submitting revised PR: 6/14

**Comment by ryanfchase** [comment]
Linking old PR to preserve comments/discussion: https://github.com/hackforla/311-data/pull/1752
