### ISSUE TITLE
Create Hoverover Info Box

### ISSUE THREAD

**Issue by brodly** [hackforla/311-data#175]
### Overview
General component to display hover over information when a user hovers over the info icon on the UI

### Action Items
- [x] Research Bulma ability to display hover over elements
- [x] Create reusable functional component that can take in title and text as props

Image for guidance:
<img width="387" alt="Screen Shot 2020-01-14 at 8 00 57 PM" src="https://user-images.githubusercontent.com/29147758/72403946-9b1f3080-3708-11ea-8df1-0786e19c3f51.png">

**Comment by adamkendis** [comment]
Dropping links to a decent looking Bulma tooltip extension for whoever picks up this ticket.
[bulma-tooltip docs](https://wikiki.github.io/elements/tooltip/)
[npm](https://www.npmjs.com/package/bulma-tooltip)

**Comment by jmensch1** [comment]
Hi guys, I'm new here. Anyone mind if I take a shot at this ticket? 

Looking forward to meeting you on Tuesday.

**Comment by brodly** [comment]
Go for it! Thanks for hopping aboard

**Comment by jmensch1** [comment]
Morning guys, thanks for setting me up with the permissions. 

I checked out bulma-tooltip, but it only accepts a string for the tooltip content, so you can't distinguish between a title and text within the tooltip. (And it won't parse an HTML string if you try to hack it that way).

So I ended up using react-tooltip, which lets you put arbitrary content in the tooltip.

**Comment by adamkendis** [comment]
Merged #282
