### ISSUE TITLE
Restore missing H4LA logo from the footer

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1750]
### Overview

We need to fix a regression where the H4LA logo was removed from the 311-Data site footer 

### Action Items

- [x] Add the H4LA logo to the footer, referencing screenshots or figma page
- [x] Note: the H4LA logo already exist in the `assets` folder as `hack_for_la_logo.png`

### Resources/Instructions
Figma Resources
- [Link to Figma File](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?type=design&node-id=4081%3A9245&mode=design&t=PTDbT1wUuq0S7f2W-1)
- Page Name:⭐⭐⭐ HAND-OFF
- Section Name: (use any section within HAND-OFF page)

Other resources:
- [Link to related bug-hunt post](https://github.com/hackforla/311-data/issues/1726#issuecomment-2113969710)

<details><summary>Current footer missing HFLA logo</summary>
<p>

<img width="492" alt="Screenshot 2024-05-15 at 8 38 36 PM" src="https://github.com/hackforla/311-data/assets/69279538/ce924df0-1d2e-40da-aa3e-e66d9c84b044">

</p>
</details> 

<details><summary>Proposed footer with HFLA logo</summary>
<p>

![Screenshot 2024-05-15 at 8 42 00 PM](https://github.com/hackforla/311-data/assets/69279538/bcb20e67-ab5b-4941-a3bd-399a552f9dd6)

</p>
</details>

**Comment by aqandrew** [comment]
ETA: Tuesday 6/11
availability: 8am-12pm, 1-5pm

**Comment by ryanfchase** [comment]
@aqandrew I think we forgot to move this to `In Progress` and later to `In Review` -- can you update this for us?

BTW I've had a look at your PR, I'm almost ready to approve but I'd like to just make sure I'm understanding the CSS rules that are being utilized before officially signing off.

I'm also shooting for 2 approvals before merge, I'll give this PR a shoutout tonight at our meeting.

**Comment by aqandrew** [comment]
@ryanfchase Status updated! I'll remember to move it when appropriate next time.
