### ISSUE TITLE
Record Oral History of 311 Data

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1757]
### Overview
We need to interview Bonnie about the story of 311 Data so we can add it to our About page and appease/regain stakeholders we lost at initial website launch.

### Action Items
- [x] Obtain Bonnie's scheduling page
  - posted in our group chat
  - do not post this on an issue -- not for publishing to the repo
- [x] use the Bonnie scheduling sheet to pick a time
- [x] pick one PM to conduct the interview
- [x] Figure out transcription issue on Zoom
  - for Zoom Business accounts only
- [x] Compile questions
- [x] Record video
  - [x] Interview confirmed for:  6/24 at 3:30 PM PST

**Comment by ryanfchase** [comment]
Regarding this action item..

> - [ ] Figure out transcription issue on Zoom

Reporting what @bberhane mentioned in our slack channel!

> Zoom transcription feature only for business accounts

**Comment by ryanfchase** [comment]
I've reviewed this ticket, and we're good to get started on it!

**Comment by ryanfchase** [comment]
I've asked admin team to provide us with Bonnie's scheduling page -- this will help us agree upon a time and schedule it in her calendar

**Comment by bberhane** [comment]
ETA: 6/24 at 3:30 PM PST

**Comment by bberhane** [comment]
This is complete.
