### ISSUE TITLE
Restrict Future Date Selections on Date Picker 

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1759]
### Overview
We need an error message or UI feedback to indicate that a user cannot select a date in the future so that we can prevent future date selections on the date picker.

### Background
Currently, when selecting an end date in the date picker calendar, the data load as though data are available for the whole timespan. Additionally, when selecting start and end dates in the future, the loading modal briefly appears. 

### Action Items
- [x] Determine how to limit date picker
- [x] Possibly create error message with either of the following text: "You cannot select a future date. Please choose a date on or before today's date," OR "Error: Date cannot be in the future."

### Resources/Instructions
<details><summary>Loading modal with future end date selected</summary>
<p>
<img width="1381" alt="Screen Shot 2024-06-10 at 1 30 57 PM" src="https://github.com/hackforla/311-data/assets/143574036/33a01c13-a41a-4d2c-8232-17dd15210877">

**Comment by ryanfchase** [comment]
@bberhane this ticket is looking good, ready for prioritization!

**Comment by ryanfchase** [comment]
This ticket is ready to be picked up

**Comment by bphan002** [comment]
ETA June 19
