### ISSUE TITLE
Add Q&A About Overlapping Boundaries to FAQ Page

### ISSUE THREAD

**Issue by bberhane** [hackforla/311-data#1760]
### Overview
We need to add a Q&A about overlapping boundaries on the map to limit confusion when users interact with the map.

### Action Items

- [x] PM to review the text below
     - [x] Sign off on text
- [x] Log into Contentful using 1Password
- [x] Navigate to 311 Data near hamburger menu in the top left
- [x] Select "FAQ" in the "Content Type" in left side pane under "Views"
- [x] Select "Add Entry," top right 
- [x] Add approved copy
- [x] Hit "Publish"

### Resources/Instructions
Question: `Why do some Neighborhood Council boundaries overlap?`

Answer: `In some cases, the boundaries of two or more Certified Neighborhood Councils may overlap if the proposed area is designed for public use, such as a park, school, library, police or fire station, or major thoroughfare; or houses a historical landmark or facility. For more information on neighborhood boundaries, see [EmpowerLA's Plan for a Citywide System of Neighborhood Councils](https://empowerla.org/wp-content/uploads/2012/12/Plan-for-a-citywide-system-of-neighborhood-councils.pdf).`

[Link to Contentful](https://app.contentful.com/spaces/dw507zz82496/home)

**Comment by cottonchristopher** [comment]
@bberhane   are those the only instances for overlap? or should we say etc, in the description if there are more instances or reasons? Or is it not that significant to add that? 
"the boundaries of two or more Certified Neighborhood Councils may overlap if,,, etc"

**Comment by bberhane** [comment]
I think it covers all the instances listed in the document I found: public use, thoroughfare, historical landmark. Perhaps we can provide the link to the source and add something like `For more information on neighborhood boundaries, see [Empower LA's Plan for a Citywide System of Neighborhood Councils](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://empowerla.org/wp-content/uploads/2012/12/Plan-for-a-citywide-system-of-neighborhood-councils.pdf).`

**Comment by ryanfchase** [comment]
@bberhane I updated your Answer text to include the "For more information..." text that you provided in [your comment](https://github.com/hackforla/311-data/issues/1760#issuecomment-2161938624).

I also modified the URL in the hyperlink -- looks like a chrome extension is modifying your links, FYI! 

Otherwise, I think we can move forward with this ticket and get it prioritized! Sounds like we've all reviewed the text at this point, but we can still assign the ticket to get the FAQ updated.

**Comment by bberhane** [comment]
Thanks, @cottonchristopher + @ryanfchase! Labels updated and ticket moved to prio backlog

**Comment by bberhane** [comment]
ETA: 6/17 or 18 by 5pm

**Comment by bberhane** [comment]
Completed

**Comment by ryanfchase** [comment]
I went through and resolved all the comments on the original migration ticket. Good job @bberhane, thank you!
