### ISSUE TITLE
Bugfix: Remove invalid CSS property in AcknowledgeModal

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1762]
### Overview

We can remove an invalid CSS property in the AcknowledgeModal that is currently neither hurting nor helping the component, removing it will help clear confusion around this property

### More Info (optional)

- See @aqandrew's post in the live forever bug hunt ticket: https://github.com/hackforla/311-data/issues/1726#issuecomment-2163764526

### Action Items

- [x] Remove the invalid `fontWieght` property from the `<Typography>` component in `AcknowledgeModal.jsx`

### Resources/Instructions

Notes from the bug hunt ticket, credit @aqandrew 

> 400 is the default font weight in our typography settings. The screenshot below shows that font-weight: 400 has been set for this element already, despite the misspelled CSS property added by sx. Therefore the fontWieght entry can be safely removed from the object passed to the sx prop.

**Comment by DrAcula27** [comment]
- **ETA**: 17 June 2024
- **Availability**: weekdays, 5pm–8pm Pacific time

**Comment by DrAcula27** [comment]
@ryanfchase I have made the changes in my branch to remove the offending CSS. However, when I used `git status` before starting my commit, I saw that there are 2 other files, _that I didn't touch_, have changes not staged for commit. See attached image for reference. What should I do? Go ahead and add-commit, or just ignore them?
- I did make sure my fork of the repo is up-to-date with the upstream fork

![image](https://github.com/hackforla/311-data/assets/62191468/7d97e03a-2b4f-449d-86ee-3365b42b7295)

**Comment by aqandrew** [comment]
@DrAcula27 You can just add AcknowledgeModal.jsx to your commit and ignore the other files. 👍🏽

Those 3 other files listed are the ones I modified in #1761, so I suspect it has something to do with when you checked out my branch for that PR for review. Please feel free to DM me on Slack to get those sorted out!

**Comment by DrAcula27** [comment]
PR has been opened for this issue at #1775

**Comment by ryanfchase** [comment]
Leaving review with one small adjustment, thanks @DrAcula27!

https://github.com/hackforla/311-data/pull/1775/files#r1646610706
