### ISSUE TITLE
Create designs for email template

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1763]
### Overview
We need to create a design for a 311-Data email template in order to ensure that emails sent through our app are compliant and on-brand with the 311-Data design system

### Note For Designer

The end result should be applicable to any email that 311 needs to send, it should not be specific to just our Contact Form subject/body.

### Action Items

- [x] Come up with designs for overall styles and layout of our email template
  - [x] fonts types and sizes
  - [x] footer info
  - [x] logo placement
- [x] Complete Design Iterations section below
- [x] Document user interaction in Figma

---

### Design Iterations

**Please move ticket between `In Progress` and `In Review` to assist PM team**

<details><summary>Iteration 1</summary>
<p>

Link to notes: https://github.com/hackforla/311-data/issues/1763#issuecomment-2320195305

![image](https://github.com/user-attachments/assets/8f9fedeb-a364-41ae-98b4-489be6369b0f)

</p>
</details> 

---
#### 

<details><summary>Example Email Contents </summary>
<p>

Subject

```
Thank you for your input!
```

Message Body

```
{{to_name}},

We appreciate you taking the time to leave a suggestion for our 311 Data service request map. Your feedback is important to us, and we are always looking for ways to improve our data visualization tool. Please follow our [LinkedIn](https://www.linkedin.com/company/hack-for-la/) for updates on this civic tech project and others within the Hack for LA organization.

Sincerely,

311 Data Volunteers at Hack for LA
```

</p>
</details> 

### Hand Off Materials

Figma Section Name: `Email Templates: 1763`

<details><summary>Before Screenshot</summary>
<p>

n/a

</p>
</details> 

<details><summary>After Screenshot (Finalized)</summary>
<p>

![image](https://github.com/user-attachments/assets/1679e125-5fda-4e9c-aa87-9bb8b64fce2a)

</p>
</details> 

### Designer Resources

<details><summary>Iteration Dropdown Copy/Paste</summary>
<p>

```
<details><summary>Iteration X</summary>
<p>

Link to notes: `REPLACE WITH COMMENT URL`

`REPLACE WITH SCREENSHOT UPLOAD`

</p>
</details> 
```

</p>
</details> 

<details><summary>Instructions for Engineering Hand Off</summary>
<p>

To Start Engineering Hand Off...
1. Ensure all Hand Off Materials are filled in
3. Add the "ready for dev lead" label
4. Leave a comment saying "This ticket is ready for engineering hand off." 

</p>
</details>

**Comment by ryanfchase** [comment]
Just realized I referenced an older version of the contact page message body. Though, it was not very important for the designer to complete their work. But let it be known that it is correct now.

@annaseulgi for next time: when you're done reviewing, unassign and remove `ready for design lead`, thanks!

Also, if you are going to move the ticket into the backlog, you'll need to make sure it is ordered properly by Milestone. Moving it into Prioritized Backlog will simply move it to the bottom, and we'll need to drag it to it's correct place. I prioritized this just now, so no action is required. FYI you can also just add the `ready for prioritization` label when you've signed off and PMs will move it for you.

**Comment by annaseulgi** [comment]
@ryanfchase Gotcha thanks for letting me know! Will try my best to do that moving forward

**Comment by ryanfchase** [comment]
> @ryanfchase Gotcha thanks for letting me know! Will try my best to do that moving forward

We're trying to improve the way we communicate these! Thanks for being open and flexible.

Last ask if you're the designer to work on this. Please jot down...
- An ETA of when you'd like to complete this
- Your availability for being contacted about this ticket -- we obviously trust you as design lead, but we ask this to be consistent 😉

**Comment by annaseulgi** [comment]
ETA will be about 2 weeks!
Availability is flexible and I get notified by email when something comes up :) (not sure if that's what you were referring to @ryanfchase )

**Comment by annaseulgi** [comment]
finishing up mockups - waiting to finalize after getting team feedback after the July break!

**Comment by bberhane** [comment]
Adding @Joy-Truex since I believe Anna discussed handing off her issues to new leads

**Comment by ryanfchase** [comment]
Hi @Joy-Truex,

Please leave a comment with the following items:

- updated ETA
- progress from the last week (if applicable)
- availability for communications during the week

---

I know this is technically in the process of being handed off. If we can get an update on this by tonight (for my information), that would be appreciated. Thanks!

**Comment by Joy-Truex** [comment]
Hi! After getting feedback from the team, I have moved this to the [handoff page](https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=13452-6294&t=EanmSPB9TZU10CIM-1). 

We've decided to go with the second of 3 options that anna designed.
<img width="700" alt="Screenshot 2024-08-29 at 11 21 33 PM" src="https://github.com/user-attachments/assets/2e328033-fad5-4742-aed3-c4a61e329d67">

**Comment by ryanfchase** [comment]
> Hi @ryanfchase ! After getting feedback from the team, I have moved this to the [handoff page](https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=13452-6294&t=EanmSPB9TZU10CIM-1).
> 
> We've decided to go with the second of 3 options that anna designed. We chose this because of the contrast provided from the blue rectangle at the top, and overall scan-ability of the message template. <img alt="Screenshot 2024-08-29 at 11 21 33 PM" width="700" src="https://private-user-images.githubusercontent.com/113402205/363063228-2e328033-fad5-4742-aed3-c4a61e329d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMjQ5MzcsIm5iZiI6MTcyNTIyNDYzNywicGF0aCI6Ii8xMTM0MDIyMDUvMzYzMDYzMjI4LTJlMzI4MDMzLWZhZDUtNDc0Mi1hZWQzLWM0YTYxZTMyOWQ2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQyMTAzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWJmMzBmNTY2NTg3MGUwOWQzOGFhMzhkNmY4Mzg0MDQ0NzhmNGRjMDhjZDI4MmM5ZDA3MDNhYzJhYzQxMDZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LVVdaoqqYvvunDfoBoDwABWGvMU7oq5JcRVo9UwI5Ok">

@Joy-Truex, I will have a look and make sure we have everything we need to make a dev ticket. I will help close this ticket once at that point, feel free to unassign yourself in the meantime. Thanks!

**Comment by ryanfchase** [comment]
Assigning myself so I can make a dev ticket.

- ETA: tonight
- availability: tonight

**Comment by ryanfchase** [comment]
ETA: tonight
availability: weekdays

**Comment by Joy-Truex** [comment]
Due to discussion in [Implement designs for email template #1828](https://github.com/hackforla/311-data/issues/1828) stating that we cannot use web fonts in our emails, the font has been updated from Roboto to Sans Serif (Arial) to utilize a font that is from the list that the Gmail text editor allows.

<details><summary>Font Comparison
</summary>
<p>

![Image](https://github.com/user-attachments/assets/72e73093-b105-4d75-ae13-e5a04bb37f4c)

</p>
</details>
