### ISSUE TITLE
311Data: Open Role for: Full Stack Developer

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1771]
<img src="https://www.hackforla.org/assets/images/projects/311_data.png"/>

**Project Name**: 311 Data

**Name of Role**: Full Stack Developer

**Volunteer Opportunity**: We're looking for volunteers who have an intermediate level background in frontend development. Our tech stack is frontend only.

**Duration**: On-going

**Meeting Times**: Wednesdays 7-8pm PT

**Who to communicate your interest to**
- Slack channel link: [#311-data](https://hackforla.slack.com/archives/CJY4R382X)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/311-data)

**Comment by ExperimentsInHonesty** [comment]
@ryanfchase This got marked as filled, but if its filled it also needs to be closed.   Are you still looking?

**Comment by ryanfchase** [comment]
@ExperimentsInHonesty I'm not sure why it got moved to filled. I'm going to move it back to Currently Recruiting

**Comment by ryanfchase** [comment]
This role has been filled by @Brandoncyu, @DorianDeptuch
