### ISSUE TITLE
311Data: Open Role for: Team Tech Lead

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1772]
<img src="https://www.hackforla.org/assets/images/projects/311_data.png"/>

**Project Name**: 311 Data

**Name of Role**: Team Tech Lead

**Volunteer Opportunity**: We're looking for a volunteer to lead our developer team as well as work closely with the product team. React fluency required, tech lead experience preferred. Our tech stack is frontend only.

**Duration**: On-going

**Meeting Times**: 

311 Data General Meeting
- Wednesdays 7-8pm PT

Product Planning Meeting
- 1st Wednesday of month
- Wednesday 7-8pm PT

Optional: PM Meeting
- Thursdays 7-8pm PT

Dev Meeting
- Saturdays 10am PT

**Who to communicate your interest to**
- Slack channel link: [#311-data](https://hackforla.slack.com/archives/CJY4R382X)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/311-data)

**Comment by traycn** [comment]
Hey @ryanfchase . Excited to be supporting the project in this role. Alongside attending the meetings listed, here are the responsibilities I'll be prioritizing for the position.

- Updated Project Documentation
- Dev tickets definition
- Reviewing PRs
- Accountability Checks

**Comment by ryanfchase** [comment]
This role has been filled by @traycn.

She will be focusing on responsibilities as outlined above.
