### ISSUE TITLE
311Data: Open Role for: Product Manager

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1773]
<img src="https://www.hackforla.org/assets/images/projects/311_data.png"/>

**Project Name**: 311 Data

**Name of Role**: Product Manager

**Volunteer Opportunity**: We're currently looking for a product manager to manage agendas, status updates on issues, as well as contribute towards PM deliverables

**Duration**: On-going

**Meeting Times**:

311 Data General Mtg
- Wednesdays 7-8pm PT

Product Planning Meeting
- 1st Wednesday of month
- Wednesday 7-8pm PT

PM Meeting
- Thursdays 7-8pm PT

Product Management CoP
- Friday 12pm-1pm PT

**Who to communicate your interest to**
- Slack channel link: [#311-data](https://hackforla.slack.com/archives/CJY4R382X)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/311-data)

**Comment by Varun710** [comment]
Hi,

I’m interested in the Product Manager role for 311 Data. I currently work as a Software Engineer aiming to transitioning into Product Management, and I believe this opportunity would provide invaluable experience in managing deliverables, agendas, and updates, which are key skills I’m looking to develop.

I’m available for the required meetings and excited to contribute to the project. Please let me know the next steps!

Best,
Varun Raghu

**Comment by ryanfchase** [comment]
Closing this ticket:
- Status: position filled
- New Member: @londondkim
