### ISSUE TITLE
311Data: Open Role for: Data Analyst

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/311-data#1774]
<img src="https://www.hackforla.org/assets/images/projects/311_data.png"/>

**Project Name**: 311 Data

**Name of Role**: Data Analyst

**Volunteer Opportunity**: We are looking for committed Data Analysts with a focus on data visualization to help us grow our project to the next level. We are hoping to work on improving data visualization. 

**Duration**: On-going

**Meeting Times**: Wednesdays 7-8pm Pacific

**Who to communicate your interest to**
- Slack channel link: [#311-data](https://hackforla.slack.com/archives/CJY4R382X)
- Slack name of person to contact in the channel: see who this issue is assigned to and @ message them in the channel above

[Read more about the project](https://www.hackforla.org/projects/311-data)

**Comment by ryanfchase** [comment]
This role has been filled by @meghana101
