### ISSUE TITLE
Set up Research team with new Figma Board

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1777]
### Overview
We need to give UXR team edit access to the Figma so they can create a FigJam board to collaborate on usability test insights

### Action Items
- [x] Give UXR access to a FigJam board
  - [x] Do we have access to this via our Figma board? or is this a separate platform (and do we need access / need to create one)
- [x] Add UXR emails
  - [x] hworthen@gmail.com
  - [x] carolren0202@gmail.com
  - [x] brianmonroetherapy@gmail.com

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by bberhane** [comment]
Closing
