### ISSUE TITLE
Startup verification for backend

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#178]
### Overview
On backend startup, run a verification step to make sure settings.cfg has all the same keys as settings.example.cfg

**Comment by ExperimentsInHonesty** [comment]
@Jeimmi Please update with:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by johnr54321** [comment]
Need backend person with DevOps skills in order to do this.

**Comment by sellnat77** [comment]
This is still in progress, and should stay open till that ^ PR is resolved

**Comment by jmensch1** [comment]
Implemented -- there's a warning in the console whenever a key is missing.
