### ISSUE TITLE
Header should still be clickable while the loading modal is active

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1783]
### Overview

We need to make the Header clickable when the loading modal is active so that users can access other tabs while data is loading.

### Action Items

- [x] Contain the loading modal to the Map component
  - the loading modal's container should not extend into the Header or Footer
  - the Header and Footer should not be dimmed while the loading modal is rendered
- [x] Ensure that we can click a navlink while the loading modal is present
- [x] Returning from a different page (via navlink) does not interrupt the data loading process
  - if the data is still loading, continue to show the loading modal
  - if the data is loaded, show the acknowledgement modal
- [x] fill in screenshot of implemented changes in **Resources/Instructions** below

### Resources/Instructions

<details><summary>Screenshot of Desired Area to Change</summary>
<p>

Loading Modal Disables Header/Footer
![image](https://github.com/hackforla/311-data/assets/6414668/c51605ab-5622-46b1-af77-b92fc70eb4d9)

Acknowledge Modal Disables Header/Footer
![image](https://github.com/hackforla/311-data/assets/6414668/503860c1-94b8-4845-bdb2-641ec8e66d28)

</p>
</details>

<details><summary>Screenshot of implemented changes</summary>
<p>

Loading Modal Visible Header/Footer
![onload](https://github.com/user-attachments/assets/cfb8805b-3445-43ff-9308-6ced73104d64)

Acknowledge Modal Visible Header/Footer
![modal](https://github.com/user-attachments/assets/6a96f4e5-1906-4f60-a314-2c2ee36ad8f8)

</p>
</details>

**Comment by bberhane** [comment]
@Skydodle PM has signed off, so OK to move to prio backlog upon your approval.

**Comment by Skydodle** [comment]
Looks good to me. This ticket is ready to be picked up.

**Comment by ryanfchase** [comment]
Hi @traycn,

Please leave a comment with the following items:

- ETA
- Any blockers this week?
- availability for communications during the week

**Comment by traycn** [comment]
Hi @ryanfchase 

ETA: Friday 8/16
Blockers: None
Availability: Tues-Fri after 5pm

**Comment by traycn** [comment]
Updated ETA: Tuesday 8/20
Blockers: None
Availability: Tues - Fri after 5pm
