### ISSUE TITLE
Update README with latest information

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1784]
### Overview

We need our README.md to be updated with new tech stack information so that members can understand what technologies we use

### Action Items
Change Title
- [x]  Change text from `311-Data v2` to `311-Data v1.2`

Screenshot
- [x]  update the screenshot of the app via the latest version of our [hosted site](https://hackforla.github.io/311-data/#/map)

Data Analysis
- [x]  remove Matplotlib, Polars, Numpy
- [x]  remove Google Colab
- [x]  remove Observable

UIUX
- [x] remove Adobe CC
- [x] remove Miro

**Comment by ryanfchase** [comment]
Moving this directly to prioritized backlog since it's simple. Ready for pickup.

**Comment by DrAcula27** [comment]
#### ETA
3 July 2024

#### Availability for Collaboration
5pm - 8pm weekdays

**Comment by DrAcula27** [comment]
@ryanfchase
I have completed everything in the issue, but have not created the PR yet. Please let me know when you look into a better link than the [Open Roles Board](https://github.com/orgs/hackforla/projects/67), and I will make the PR.

**Comment by ryanfchase** [comment]
> @ryanfchase I have completed everything in the issue, but have not created the PR yet. Please let me know when you look into a better link than the [Open Roles Board](https://github.com/orgs/hackforla/projects/67), and I will make the PR.

ETA Thursday 1:30pm
