### ISSUE TITLE
Implement Latest Export Button UI

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1785]
### Overview

We need to implement UI elements that allow users to export selected data on to their devices since we do not officially have a way of utilizing our data export feature.

### Note

Handoff documents will contain a version of the Search and Filters modal that DO NOT MATCH what we have implemented. We are to implement only the UI elements relevant to this feature
- [x] I understand

### Action Items

- [x] Add export button at bottom of Search and Filters Modal
- [x] Error modal is displayed on Export Button click when criteria is not met
  - [x] More than 1 request type is selected 
  - [x] No request types selected
  - [x] No NC is selected
- [x] NC selected + 1 request type selected begins data export on Export Button click
  - [x] data downloading modal appears
  - [x] data download success modal appears if data download succeeds
  - [x] data download failed modal appears if download failed

### Resources/Instructions

- [Link To Figma](https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=4081-9245)
- Page Name: ⭐ ⭐ ⭐ Handoff 
- Section Name: `Export Link Button And Hand Off Process`
- Related previous ticket: https://github.com/hackforla/311-data/issues/1695
  - [x] review: Before Screenshot
  - [x] review: After Screenshot (Finalized)
  - [x] review: Video Upload of "Export Button" demo 

<details><summary>Screenshot of Figma Overview</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/358c7505-f27b-4421-bae6-0be342d70951)

</p>
</details> 
<details><summary>Screenshot after implemented changes</summary>
<p>

![image](https://github.com/user-attachments/assets/f5bf4c35-a9e9-4def-8fce-69fd28733b0f)

![image](https://github.com/user-attachments/assets/6599c33b-7606-44dd-a587-1c72e3dcabd7)

![image](https://github.com/user-attachments/assets/73d52360-cb1b-4c24-9585-8b5a2bbebaa9)

![image](https://github.com/user-attachments/assets/da38fd11-a42d-429a-8842-d45ac06a316b)

![image](https://github.com/user-attachments/assets/791bbae3-c363-4588-af3b-587b8fa6b853)

![image](https://github.com/user-attachments/assets/0474a849-73bd-492f-b024-2e0369eb687a)

![image](https://github.com/user-attachments/assets/7d67aa04-0a5a-4584-be09-ddd504efa5ec)
</p>
</details>

**Comment by Skydodle** [comment]
Ticket is ready to picked up.

**Comment by kdow** [comment]
ETA: 8/23
Availability: Mon-Fri 1pm-6pm

**Comment by kdow** [comment]
Are the needed icons available somewhere as assets or names in a font/icon library? I found some that look similar in Material UI's library (https://mui.com/material-ui/material-icons/?query=error&selected=Warning, https://mui.com/material-ui/material-icons/?query=check&selected=CheckCircle), but I haven't found exact matches for some of the others (export icon, info tooltip in notice message, document download icon in confirmation dialog).

**Comment by ryanfchase** [comment]
> Are the needed icons available somewhere as assets or names in a font/icon library? I found some that look similar in Material UI's library (https://mui.com/material-ui/material-icons/?query=error&selected=Warning, https://mui.com/material-ui/material-icons/?query=check&selected=CheckCircle), but I haven't found exact matches for some of the others (export icon, info tooltip in notice message, document download icon in confirmation dialog).

Actually I think you can download all the relevant assets directly off the team Figma. I believe you can go to the `Export Link and Download Process` section, find the "Assets" section, and download those assets directly via Figma.

@Joy-Truex @kiranofans please let me know if there is a better way to approach this. Downloading directly off Figma seems to be our process at the moment.

<details><summary>Screenshot of assets</summary>
<p>

![image](https://github.com/user-attachments/assets/4a7e0aef-a714-4ccf-bc4e-a49e216acec4)


</p>
</details>

**Comment by kiranofans** [comment]
> Are the needed icons available somewhere as assets or names in a font/icon library? I found some that look similar in Material UI's library (https://mui.com/material-ui/material-icons/?query=error&selected=Warning, https://mui.com/material-ui/material-icons/?query=check&selected=CheckCircle), but I haven't found exact matches for some of the others (export icon, info tooltip in notice message, document download icon in confirmation dialog).

Yes you can directly download frame/image from Figma in various format: 
-> Open Figma -> find the icons or widgets -> single click on the icons or the icons on Widgets -> on your right hand you will see a panel -> at the bottom of the panel, there's a Export section -> click on Preview to expand the icon/image/widget download preview -> Click the "+" button beside Export to add one Export setting including image format and resolution/size as shown in the screenshot below:

<img width="588" alt="image" src="https://github.com/user-attachments/assets/a65c544e-e595-4fb7-a3b2-c4164badf9a4">
Download Preview: 

<img width="260" alt="image" src="https://github.com/user-attachments/assets/998e42e0-b791-4f2f-8dac-cb7e4225b728">

Click on the image forma drop down to select an appropriate one, then click on Export Frame/default to download it.

You can also click on a widget frame, then right-click and select Copy/Paste as. From there, choose Copy as SVG, Copy as PNG, or Copy as Code (CSS, iOS, Android). You can then paste the SVG/PNG directly, or paste the code wherever it applies.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/4e67aa08-e811-4e54-ae07-c5ce922dc496">

<img width="718" alt="image" src="https://github.com/user-attachments/assets/6f881f41-df4e-4703-ac89-40c1af425a23">

**Comment by ryanfchase** [comment]
@kiranofans this is a very good guide, thank you. I'm going to make a note in our agenda about adding this to our wiki

**Comment by ryanfchase** [comment]
@kdow if your question has been answered, please move back to `in progress`. I will review this in breakout rooms to confirm.

**Comment by kiranofans** [comment]
I just remembered that while it's easy to export static images in Figma, I don't know how to export GIFs or animations. But we can use other tools:
Quote: 

```
Use another tool: After creating or inserting the GIF in Figma, you can use tools like Adobe After Effects or an online GIF converter to handle the export.

Or

Export as video: You can export the prototype or frame as a video in tools like ScreenFlow, then convert the video into a GIF using software like Photoshop.
```

**Comment by kiranofans** [comment]
I'm sorry I was trying to delete the comment (which I haven't sent yet) but I didn't notice why I closed this ticket. I have already changed it back to In Progress.

**Comment by ryanfchase** [comment]
@kiranofans @kdow I'm move this back to `In Progress`, since that seems to be the latest desired state

**Comment by ryanfchase** [comment]
Adding my review today ETA 3~4pm
