### ISSUE TITLE
Prep project boards for Migration

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/311-data#1797]
### Overview
We need to prepare the Project Boards for the forced migration that GitHub is doing in August, so that it is already working well for the team by then.

### Action Items
Repeat first 3 steps for each card
- [ ]  copy this template to a comment below
   ````
   ### Text from project board card, [Add name of board here], [Add name of column here]
   ```
   [PASTE CARD CONTENT HERE]
   ```
   - [ ] Determine where this item goes on the wiki (page and section)
   - [ ] copy item to wiki
   - [ ] hide this comment when completed.
   ````
- [ ] copy the content of the card (by clicking the 3 dots and selecting Edit Note, and then CRTL+C) and paste it into your new comment where it says `[PASTE CARD CONTENT HERE]
- [x] delete card from project board
- [x] add project board URL(s) in resources below
- [x] add the `project board migration` label to this issue
- [x] add issue to project board
- [x] move issue to Prioritized Backlog

#### Classic Project board URL(s):
- Open:
  - [20200414 - NC Workshop Board](https://github.com/hackforla/311-data/projects/6)

- Closed:
  - [311: project board](https://github.com/hackforla/311-data/projects/10)
  - [Vision Board](https://github.com/hackforla/311-data/projects/8)
  - [Data Analysis Projects](https://github.com/hackforla/311-data/projects/7)
  - [311 MVP](https://github.com/hackforla/311-data/projects/4)
  - [MVP](https://github.com/hackforla/311-data/projects/3)
  - [Project Management](https://github.com/hackforla/311-data/projects/2)

#### New Project board URL(s):
- [311: Project Board](https://github.com/orgs/hackforla/projects/63)

#### Card Content Spreadsheets

- [Project Board Cards: 311-data: 20200414 - NC Workshop Board](https://docs.google.com/spreadsheets/d/1xtNLwofLwpsQn-ZsWwbNQxsQYcGF-z_PiO5x3EQmsbM/edit)

**Comment by ryanfchase** [comment]
This is ready to be picked up by the PM team

**Comment by ExperimentsInHonesty** [comment]
Everything has been moved to wiki or appropriate issue
