### ISSUE TITLE
Create General Reusable Components

### ISSUE THREAD

**Issue by brodly** [hackforla/311-data#180]
### Overview
Create generic, reusable components for re-use across the application. This includes:

- Buttons
- Dropdowns
- Checkboxes
- Toggles

### Resources/Instructions
Make sure these components use and comply to the Bulma framework guidelines - www.bulma.io

**Comment by ExperimentsInHonesty** [comment]
ETA Tuesday 1/28

**Comment by adamkendis** [comment]
Merged into dev in PR #220
