### ISSUE TITLE
Bugfix: SR RequesetDetail loading spinner not appearing on subsequent mouse-over popups

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1805]
### Overview

We need to fix a bug where the loading spinner on the Service Request inspect modal does not appear on subsequent mouse-overs.

### Action Items

In `Map.jsx`
- [x] Review usage of `<RequestDetail/>`
- [x] Review usage of `this.requesetDetail`
- [x] Correct loading behavior of RequestDetail
- [x] Provide SCREEN CAPTURE of the correct behavior

### Resources/Instructions

Abbreviations
- Service Request = SR
- Neighborhood Council = NC

Useful Files & Components
- RequestDetail: `components/Map/Map/RequestDetail.jsx`
- Map: `components/Map/Map.jsx`

Mapbox Docs:
- API Reference: https://docs.mapbox.com/mapbox-gl-js/api/
- Popup Example: https://docs.mapbox.com/mapbox-gl-js/example/popup/

Reproducing the Bug
1. load the [311 Data site](https://hackforla.github.io/311-data/#/map)
2. select an NC (e.g. Koreatown)
3. Mouse-over to one SR
  3.1. observe the loading spinner that appears immediately on hover
  3.2. take note of the SR Type.
4. Move-over to a new SR
  4.1. Observe that there is no loading spinner, instead the SR modal is unchanged from step 3
  4.2. Observe that the SR modal will quickly re-render with the correct SR information

<details><summary>Click to see finished result</summary>
<p>

[TODO: VIDEO GOES HERE]

</p>
</details>

**Comment by ryanfchase** [comment]
@bphan002 thanks for picking this up. When you can, please leave as a comment:
- ETA
- availability for comment/discussion

**Comment by bphan002** [comment]
ETA: Thursday 10/5 3 PM

Availability: Any time before 2 PM

**Comment by ryanfchase** [comment]
> ETA: Thursday 10/5 3 PM
> 
> Availability: Any time before 2 PM

@bphan002 did you mean 9/5? 🤣 

We can always accommodate if you need more time ofc... 😁

**Comment by bphan002** [comment]
I did lol sorry

**Comment by ryanfchase** [comment]
@bphan002 moving this ticket to In Review since your PR is available

**Comment by ryanfchase** [comment]
Adding my review, eta this evening

**Comment by ryanfchase** [comment]
@bphan002 I've left you a review on your PR. Please provide an ETA for addressing the review, thanks!

**Comment by bphan002** [comment]
ETA: Thursday Sept 12

**Comment by ryanfchase** [comment]
Thank you @bphan002, merge when ready
