### ISSUE TITLE
Add NC name pill to Search and Filters modal on address selection

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1813]
### Overview

We need to render the relevant neighborhood council's name as a pill when the user selects an address so that users know what neighborhood council that address is in.

### Action Items

- [ ] Ensure that address search also selects the NC as a pill (StyledChip)
  - [ ] Capture councilId param value when Address is searched
  - [ ] Display NC in a StyledChip with a `x` close action
- [ ] Ensure that clicking `x` on the pill will deselect the selected address and reset the zoom level to see all boundaries (e.g. the default zoom level)
  - [ ] Do this by using the `this.reset` function in the resetMap prop  

### Resources/Instructions

Useful Files and Components
- Map: `components/Map/Map.jsx`
  - see: `onGeocoderResult`
  - see: resetMap prop in `<FilterMenu/>`

v1.2 Moderated Usability Test Slideshow:
- [link](https://docs.google.com/presentation/d/1w1YpzC-sM7X1OOQ70f5Ey8h6Q0yOoTlC/edit)
- [Slide for Insight (1)](https://docs.google.com/presentation/d/1w1YpzC-sM7X1OOQ70f5Ey8h6Q0yOoTlC/edit#slide=id.p9)

<details><summary>Screenshot before proposed changes</summary>
<p>

![image](https://github.com/user-attachments/assets/ec297a87-651e-454e-8cc6-549b82a2adc3)

</p>
</details>

<details><summary>Screenshot after proposed changes</summary>
<p>
![image](https://github.com/user-attachments/assets/0ede2cea-6533-40d4-bcb1-c9388b8c93ef)
</p>
</details>

**Comment by ryanfchase** [comment]
This ticket is ready for dev lead review -- I'm unsure if this is a `Good First Issue`. If so, I can add more instruction to support the new dev in completing the ticket.

**Comment by traycn** [comment]
Reviewed and ready for priotization.

**Comment by ryanfchase** [comment]
This ticket has been prioritized and is ready to be picked up 👍

**Comment by Brandoncyu** [comment]
Taking this on. Hoping to get it done by Saturday, September 14

**Comment by Brandoncyu** [comment]
PR is opened: https://github.com/hackforla/311-data/pull/1825

Sending to @ryanfchase and @traycn for review

**Comment by ryanfchase** [comment]
Adding my review soon, eta late afternoon. Checking out the branch, the behavior is looking good:

<details><summary>Selecting an address also selects the NC</summary>
<p>

![image](https://github.com/user-attachments/assets/033671de-40b8-46dc-b1a9-27a4a76054c0)

</p>
</details> 

@Brandoncyu for future reference, modify the PR contents so that "issue number here" gets populated. This is the only real requirement for PR issue-formatting for our team at the moment. It becomes a dynamic link and makes it easy to navigate. Thanks.

<details><summary>"Issue number here" location</summary>
<p>

![image](https://github.com/user-attachments/assets/f1a0ac50-8912-420b-a6b3-6a0b1ac13f3a)

</p>
</details>

**Comment by ryanfchase** [comment]
Just adding one request for change in my review. Please make the adjustment, or state an alternative approach. Thanks.
