### ISSUE TITLE
Make font types in search and filters modal consistent

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1815]
### Overview

We need to make fonts on the search and filters modal consistent so users don't get confused about how the modal works

### Action Items

- [x] Grab the color, font size, and font weight for "Request Types" in the Search and Filters Modal
  - loc: `/components/main/Desktop/TypeSelector/index.js` , line: 22, 83

- [x] Apply that color, font size, and font weight to "Boundaries"
  - loc: `/components/main/Desktop/CouncilSelector/index.js` 
  - [x] 1. Add class style from collapsible section - __ADD: Header class style for "Boudaries"__
  - [x] 2. Update class `classes.label` to `classes.header` for "Boundaries" title
  - [x] 3. Cleanup, Delete class style from collapsible section - __DELETE: Label class style for "Boundaries"__

- [x] Apply that color, font size, and font weight to "Date Range"
  - loc: `componenets/DataSelector/DataSelector.jsx`
  - [x] 1.  Add useStyle & class style from collapsible section - __ADD: useStyle const for "Date Range"__
  - [x] 2. Delete `import useStyle from ...`
  - [x] 3. Add `import makeStyles from '@mui/styles/makeStyles';`
  - [x] 4. Update `span` to `div` for the title value ` Date Range&nbsp;` 
  - [x] 5. Update `className={label}` to `className={classes.header}`

### Collapsible Sections

<details>
  <summary>ADD: Header class style for "Boudaries"</summary>
  
```
  header: {
    fontSize: '12.47px',
    fontWeight: theme.typography.fontWeightMedium,
    marginBottom: '8px',
  },
```

</details>

<details>
  <summary>DELETE: Label class style for "Boundaries"</summary>
  
```
  label: {
    display: 'inline-block',
    font: theme.typography.b2,
    marginBottom: '10px',
    color: theme.palette.secondary.light,
  },
```

</details>

<details>
  <summary>ADD: useStyle const for "Date Range"</summary>
  
```
const useStyles = makeStyles(theme => ({
  header: {
    fontSize: '12.47px',
    fontWeight: theme.typography.fontWeightMedium,
    marginBottom: '8px',
  },
}));
```

</details>

### Resources/Instructions

- Figma design file [link](https://www.figma.com/files/team/1039983981189012111/311-data?fuid=604439038560392673)

<details><summary>Screenshot before proposed changes</summary>
<p>

![image](https://github.com/user-attachments/assets/592ff5bf-a5bc-454a-a61f-fa831a436c5e)

</p>
</details>

<details><summary>Screenshot after proposed changes</summary>
<p>
![image](https://github.com/user-attachments/assets/85c9c00a-d0ca-45b7-9266-619fe71fa326)
</p>
</details>

**Comment by ryanfchase** [comment]
Ready for dev lead. I think it's a "Good First Issue". Happy to add more in-depth instruction if required.

**Comment by traycn** [comment]
Reviewing as dev lead:
ETA - 9/8
Time -  12pm PT

**Comment by traycn** [comment]
Updated Action Items with file loc, line, and implementation for "Boundaries" and "Date Range" titles in the search/filter map modal. 

### Comment on my findings:
Style implementation for each title is inconsistent across the 3 Titles in the modal. To introduce consistency, I've proposed a solution to use the `useStyle` for each file to be consistent with how the style title "Request Types" is implemented. 

### IMPORTANT NOTE:
Use style has been deprecated since 2021 and is now Legacy. It is not recommended for use. 
[Link to useStyle docs here.](https://mui.com/system/styles/basics/)

**Comment by traycn** [comment]
Updated the description a second-time. Issue previously did not update with the detailed action items points.

**Comment by ryanfchase** [comment]
This ticket has been prioritized and is ready to be picked up 👍

**Comment by Brandoncyu** [comment]
Updates have been made: 
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/971b3f07-0ab4-4565-89fb-5348b6cdb97f">

**Comment by Brandoncyu** [comment]
PR has been made: https://github.com/hackforla/311-data/pull/1821
