### ISSUE TITLE
Implement designs for email template

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1828]
### Overview

Design team has created an email template design and now we need to implement it for our Contact Page emails.

### Action Items

- [x] In the 311-Data repo, create a new directory: `311-data/templates`
- [x] Create a new file: `311-data/templates/contact-us.html`
- [x] Implement the referenced design
  - [x] contain the work within `contact-us.html`, do not use external style sheets (see R1)
- [x] Send a test email with using the Send HTML In Gmail plugin (see R2)
- [x] Upload a screenshot into the `Screenshot after proposed changes` section of this post

### Resources/Instructions

- R1: How to send html emails in Gmail [blog post](https://htmlemail.io/blog/how-to-send-html-emails-in-gmail)
- R2: Chrome Plugin for embedding HTML in emails: [link to chrome web store](https://chromewebstore.google.com/detail/send-html-in-gmail/ipaogmomajeofkdpcmmjgilnblolomhb)

##### Figma Info

- [Figma design file link](https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=13452-6294&t=EanmSPB9TZU10CIM-1)
- Related design ticket: https://github.com/hackforla/311-data/issues/1763

<details><summary>Screenshot before proposed changes</summary>
<p>

n/a

</p>
</details>

<details><summary>Screenshot after proposed changes</summary>
<p>
![image](https://github.com/user-attachments/assets/80f83227-d892-40bc-980f-f05f48b2edab)

</p>
</details>

**Comment by ryanfchase** [comment]
Ready to be picked up

**Comment by Brandoncyu** [comment]
Pull request has been opened: https://github.com/hackforla/311-data/pull/1832

**Comment by ryanfchase** [comment]
@Brandoncyu I've provided a review with request for a small change to the asset URLs.

Also, notes on ticket management:
1. When beginning work on the ticket, please move from `Prioritized Backlog` to `In Progress`.
2. After completing your work, while you're waiting for review, move the ticket to `In Review`.

Thanks Brandon!

**Comment by ryanfchase** [comment]
@Joy-Truex @allisonjeon can we get a review on the dev's implementation? A screenshot is available here: 

<details><summary>Details</summary>
<p>

![image](https://github.com/user-attachments/assets/50d29ef1-fd67-4b4e-a160-08c2223b18da)

</p>
</details> 

I'm wondering if its worth coming up with a system for design leads to review dev's implementations before it gets merged. Perhaps we can talk about this tonight. Maybe a process for dropping screenshots into the Figma so design lead can quickly inspect and compare it to the original designs.

**Comment by ryanfchase** [comment]
Moving to In Review while waiting for design lead to have a look.

**Comment by Joy-Truex** [comment]
Here are my notes:

- Please ensure the text has these specifications:

<details><summary>Screenshot</summary>
<p>

<img width="293" alt="Screenshot 2024-09-29 at 10 32 02 PM" src="https://github.com/user-attachments/assets/a63a0fe6-0c74-4313-bcd5-04f1220fa17b">

</p>
</details> 

- please ensure the linkedin is hyperlinked to: https://www.linkedin.com/company/hack-for-la/
- perhaps i can't tell from the screenshot but please if possible confirm the three dots above the logo are vector images with the following specifications 

<details><summary>Screenshot</summary>
<p>

<img width="1061" alt="Screenshot 2024-09-29 at 10 35 42 PM" src="https://github.com/user-attachments/assets/a2950d54-53e2-461a-9a09-d000f33460be">

</p>
</details>


TY!

**Comment by Brandoncyu** [comment]
@Joy-Truex wanted to ask what a "hug" is? And if you have any instruction for inserting this into HTML?

**Comment by Joy-Truex** [comment]
@Brandoncyu basically it means the object should resize on a larger/smaller device size not just stay static.

**Comment by Brandoncyu** [comment]
I have added the new dots:

![image](https://github.com/user-attachments/assets/12b30a07-c34b-4b5d-88fc-e9033a453d25)

**Comment by Joy-Truex** [comment]
Great! are you able to update the font to the specifications here?
<img width="293" alt="371957866-a63a0fe6-0c74-4313-bcd5-04f1220fa17b" src="https://github.com/user-attachments/assets/48312298-8f3b-4949-a23f-d7d59a3c9d66">

**Comment by ryanfchase** [comment]
Thanks all. I've approved the PR, I believe it satisfies requests made during QA.

**Comment by Joy-Truex** [comment]
Can you ensure the font is Roboto? It looks like it may be times new roman?

**Comment by Brandoncyu** [comment]
It is Roboto:
![image](https://github.com/user-attachments/assets/a1af58d1-3168-4339-ba0c-7df0db51ba6f)

**Comment by Joy-Truex** [comment]
Will it show up differently in the email than it does in this screenshot? Roboto is a sans serif font and the font in the screenshot is serif.
Sorry if I'm missing something, ty!

**Comment by Brandoncyu** [comment]
@ryanfchase can you confirm?

**Comment by ryanfchase** [comment]
Good catch @Joy-Truex, and indeed @Brandoncyu is specifying it correctly in the code. However, it seems that we **cannot** use web fonts in our emails. At least, according to [the guide](https://htmlemail.io/blog/how-to-send-html-emails-in-gmail) I attached. I think we'll need to pick from the list that the Gmail text editor allows.

<details><summary>List of available fonts</summary>
<p>

- Sans Serif (Arial)
- Serif (Times New Roman)
- Fixed Width (monospace)
- Wide (Arial Black)
- Narrow (Arial Narrow)
- Comic Sans MS
- Garamond
- Tahoma
- Trebuchet MS
- Verdana


</p>
</details> 

<details><summary>Screenshot of "No Web Fonts"</summary>
<p>


![image](https://github.com/user-attachments/assets/c9caf9e8-33da-49e4-9413-b86175b042c1)


</p>
</details>

**Comment by Brandoncyu** [comment]
Changed has been made.

**Comment by Brandoncyu** [comment]
![image](https://github.com/user-attachments/assets/030f64d3-7652-486f-9767-97d39aa0cbdc)
