### ISSUE TITLE
Fix Filter modal's date range buttons style not being applied

### ISSUE THREAD

**Issue by traycn** [hackforla/311-data#1835]
### Overview

We need to apply styling on the pre-defined date range buttons in the Filters modal, to have the `Last Week`, `Last Month`, `Last 3 Months` buttons styled.

### Action Items

- [ ] Refer to error popup at: `components/DateSelector/DateSelector.jsx` , line - 14.
  - [ ] Fix import error to apply the styles defined in `iconStyle` obj: 
  `components/DateSelector/DateSelector.jsx` , line - 26.

### Resources/Instructions

[Replace this text - Provide these resources here if exist. Provide screenshot only if the issue has visual
changes on the site, do not post screenshots of codebase]

- Figma design file link: https://www.figma.com/design/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=4081-9245&t=dREizYCRxn9JzUaR-1
- Related previous ticket: n/a

<details><summary>Screenshot before proposed changes</summary>
<p>

![Screen Shot 2024-09-25 at 7 33 44 PM](https://github.com/user-attachments/assets/b96e01bd-d7f0-4e39-b089-c8cf165b15aa)

</p>
</details>

<details><summary>Screenshot after proposed changes</summary>
<p>

![image](https://github.com/user-attachments/assets/744f7417-e66b-490a-a508-6ee81d3b059d)

</p>
</details>

**Comment by ryanfchase** [comment]
@traycn this is looking good. When you're ready, remove `draft` and add `ready for prioritization`.

**Comment by ryanfchase** [comment]
My edits to the page: added link to the Figma page. Also adding Milestone.

**Comment by ryanfchase** [comment]
Prioritized and ready to be picked up!

**Comment by Brandoncyu** [comment]
PR has been made: https://github.com/hackforla/311-data/pull/1838

**Comment by ryanfchase** [comment]
@traycn I'm going to OK this to get approved. This is a new idea, but I feel like 1pt Size and under probably can just use 1 review. This should alleviate both of us needing to watch every single PR moving through.

**Comment by Brandoncyu** [comment]
I will wait til @traycn gives the ok before merging.

**Comment by traycn** [comment]
Approved! Moving the styles to the seperate file was a great change. Taking note that we are referencing styles for the DateSelector dropdown at: `components/DateSelector/useStyles.js`


Feel free to merge @Brandoncyu
