### ISSUE TITLE
Bugfix: Closing the datepicker should cancel the ongoing selection

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1836]
### Overview

We need to provide a way to cancel and reset the date selection so that users aren't stuck in an unspecified UX flow.

### Action Items

- [ ] Add state to track the selected dates of the datepicker that exist prior to the user selecting a new Start Date
  - e.g. initialStartDate, initialEndDate
- [ ] Provide an event handler that restores the initial dates when the user clicks out of the datepicker dropdown, essentially canceling the datepicker flow
  - the map should not load data for the new dates, this cancellation action should be [idempotent](https://developer.mozilla.org/en-US/docs/Glossary/Idempotent)

### Dev Resources

Useful Files and Components
- Map.jsx
- FilterMenu.jsx
- DateSelector.jsx

### Resources/Instructions

- [Bug Report: (see Steps to Reproduce)](https://github.com/hackforla/311-data/issues/1726#issuecomment-2359698327)

**Comment by traycn** [comment]
Heads up for future dev work. The state being modified in this ticket is the same state that will be worked on for this ticket: https://github.com/hackforla/311-data/issues/1818 (currently in design review).

**Comment by ryanfchase** [comment]
This ticket is ready to be picked up 👍

**Comment by DorianDeptuch** [comment]
Availability: Weekday Afternoons/Evenings
ETA: 10/13 End of Day

**Comment by DorianDeptuch** [comment]
Updated ETA: 10/20 End of day
