### ISSUE TITLE
Research geodatabase implementation and tradeoffs over relational database

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#184]
### Overview
Investigate implementations of geodatabases and evaluate level of value provided over existing Postgres/MySQL implementation

### Action Items
- [ ] Create document for tracking information 
- [ ] Find existing implementations of geodatabases and evaluate cost and utility

**Comment by JRHutson** [comment]
@ryanmswan Do we have any minimum specs or requirements for a server? I discovered there is a way to enable spatial queries on the AWS Dynamo server that is in the free tier. It’s No-SQL though.
