### ISSUE TITLE
Bugfix: Searching an address outside of an NC boundary silently fails

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1840]
### Overview

We need to fix a regression so that users can still look up addresses outside of NC boundaries.

### Action Items

- [ ] Modify behavior of the else block on L663 of Map.jsx
  - if `ncIdOfAddressSearch` is empty, still attempt to set the address state so that a geocoder pin is placed

### Dev Resources

Useful Files and Components
- MapSearch.jsx (see props)
- Map.jsx (see L534, `onGeocoderResult(result)`

Mapbox Docs
- https://docs.mapbox.com/api/search/geocoding/

### Resources/Instructions

- Bug Hunt report: https://github.com/hackforla/311-data/issues/1726#issuecomment-2390344364

<details><summary>Screen recording after proposed changes</summary>
<p>
[insert screenshot here]
</p>
</details>

**Comment by ryanfchase** [comment]
I'm opening this up as ready to work on. Smaller than 1pt, skipping dev lead review.

**Comment by bphan002** [comment]
ETA Oct Oct 17 Thursday

**Comment by bphan002** [comment]
@ryanfchase 
I need a bit of clarification.

I was able to have the marker placed, but did we want it to zoom in on the location?  
If we want that to still occur I'll have to look into it deeper since I believe the zoom is based on the neighborhood council.

**Comment by ryanfchase** [comment]
Adding this as a point of discussion for today's agenda. I'll add a response soon:
- https://github.com/hackforla/311-data/issues/1545#issuecomment-2415319731

**Comment by ryanfchase** [comment]
Design team to discuss in breakouts this evening. Follow up coming after meeting is over.

**Comment by ryanfchase** [comment]
@bphan002 for now, when an address is provided outside of an NC, can we fly to that address with a zoom level of 9? Design will be working on a ticket to decide how to message to the user that the search did not fall within an NC.

**Comment by bphan002** [comment]
New ETA Friday Oct 25th EOD
