### ISSUE TITLE
PM Spike: Learn and report on website team's usage of DRs

### ISSUE THREAD

**Issue by ryanfchase** [hackforla/311-data#1842]
### Overview
We need to learn about the website team's Decision Records and document our findings so that we may implement a similar systems in our Wiki and Issues

### Action Items

- [x] Create a Google Document within the folder "03 - Product Management" in the shared drive (e.g. Report: Website DR)
- [x] List the types of pages needed to establish a DR Wiki System
  - most likely we'll just need Wiki pages similar to R1.01, R2.01, R3.01, and then pages for each actual DR. Please confirm this is the case.
- [x] For each page determine a requirement for our DR Wiki System:
  - List in the report the general structure of that page (we will be generating a markdown template from these notes)
- [x] Walk through listings in 4.01 and 4.02, note which issues begin with `DR:`, `Decision Record:`, or `Decision Record For`
  - Simply listing them in the report is OK, we will review these as a team
- [ ] ~Add new comment to 311 Data PM agenda: "For upcoming agenda's topic requests: Review website DR report: `#1842`" (see Resource 5.02)~
  - ~After you've done this, you can move this ticket to `In Review`, and your work will be complete until feedback is provided~

### Resources (R)

1. Wiki: DR Index (All)
  1.01 [index page](https://github.com/hackforla/website/wiki/Decision-Records)
2. Wiki: DR Adopted
  2.01 [Sub-Index & Template page](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted)
  2.02 [example page](https://github.com/hackforla/website/wiki/DR:-How-to-pass-off-an-issue-that-needs-follow-up-by-a-lead)
3. Wiki: DR Not Implemented
  3.01. [Sub-Index & Template ](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented)
  3.02. [example page](https://github.com/hackforla/website/wiki/DR:-Capitalization-of-menu-items-in-nav-bar-and-header)
4. DRs Appearing in Website Team Issues
  4.01. [Search listing in website repository for "Decision Record"](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22Decision+Record%22&type=issues)
  4.02. [Search listing in website repository for "DR"](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22DR%22&type=issues)
5. General Info
  5.01 [What is a spike](https://www.agile-academy.com/en/agile-dictionary/spike/#:~:text=Definition%20of%20a%20Spike%3A,than%20producing%20a%20shippable%20product.)
  5.02 [PM Weekly Meeting Agenda](https://github.com/hackforla/311-data/issues/1546)
  5.03 [What is a Decision Record?](https://github.com/joelparkerhenderson/decision-record) ⚠️ Not an internal document! (Just for reference)

### Hand Off Material
- Link to report requested by Action Items: https://docs.google.com/document/d/1lpbYUZ_p4JEfZCm2UGbEHizqOR8DpuQClzgKb2FjjzI/edit?usp=sharing
- New DR Wiki Pages
  - Index: https://github.com/hackforla/311-data/wiki/Decision-Records
  - Solutions Adopted: https://github.com/hackforla/311-data/wiki/Decision-Records-on-Solutions-Adopted
  - Solutions Not Implemented: https://github.com/hackforla/311-data/wiki/Decision-Records-on-Solutions-Not-Implemented

**Comment by ryanfchase** [comment]
Prioritizing this and getting ready for pickup.

**Comment by londondkim** [comment]
ETA: next Friday (10/18).

**Comment by ryanfchase** [comment]
I wanted to know if other projects were utilizing Decision Records in their wikis. To find this information, I did the following:

1. Went to the Hack for LA main github page: https://github.com/hackforla
2. Typed in the search bar "decision record" (see dropdown below) and clicked the first result: "search in this organization"
3. In the left sidebar, I clicked "More", then Wikis
4. The page then lists all search results in the organization where a wiki page contains the word "decision record"

<details><summary>Screenshot of Search Bar</summary>
<p>

![image](https://github.com/user-attachments/assets/9e6d2a40-a556-417a-8e07-288141acad87)


</p>
</details> 

<details><summary>Screenshot of Sidebar</summary>
<p>

More
<img src="https://github.com/user-attachments/assets/d9e4d881-2002-4dd4-ac80-6bf2cc4c6b41"  width=200 />

Search Results In Wikis
<img src="https://github.com/user-attachments/assets/ea544adf-4fcc-43c2-ae9e-6c58ff350179"  width=200 />


</p>
</details>

**Comment by londondkim** [comment]
https://docs.google.com/document/d/1lpbYUZ_p4JEfZCm2UGbEHizqOR8DpuQClzgKb2FjjzI/edit?usp=sharing

Link to the report made for this ticket
Finished

**Comment by londondkim** [comment]
Reviewed with Ryan Chase + ticket is done
