### ISSUE TITLE
Comparison Feature - Data Visualization

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#185]
### Overview
Regarding #183 - UI is complete and up for review/next steps on development

### Action Items

- [ ] Requires front-end team to provide feedback

- [ ] Data team to confirm whether this shows what we want to show

- [ ] Project Manager to confirm this fits requirements

### Resources/Instructions
See Wireframe 3 page [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=176%3A0)
Screenshot for frames below:
![image](https://user-images.githubusercontent.com/59002767/72576801-8f0cad80-3885-11ea-96a9-acfdb548718a.png)
^Basic comparison form when "comparison button" is clicked
![image](https://user-images.githubusercontent.com/59002767/72576840-aa77b880-3885-11ea-822a-a6c14b5dcae1.png)
^ Options for frequency chart, time to close chart, and total request chart (not for how people contact 311 and not for type of request chart)

![image](https://user-images.githubusercontent.com/59002767/72576933-e579ec00-3885-11ea-9e05-6370ae7b454d.png)
^Frequency Chart

![image](https://user-images.githubusercontent.com/59002767/72576995-0f331300-3886-11ea-8dbe-5faeeab6357f.png)
^Time to close

![image](https://user-images.githubusercontent.com/59002767/72577009-1bb76b80-3886-11ea-9070-9686137f31d7.png)
^Total request

![image](https://user-images.githubusercontent.com/59002767/72577033-2bcf4b00-3886-11ea-93a8-2081bdf31843.png)
^How people contact 311

![image](https://user-images.githubusercontent.com/59002767/72577050-3be72a80-3886-11ea-896e-93c0e3bb3882.png)
^Total Request

**Comment by ExperimentsInHonesty** [comment]
@itsjoycelee please talk to @johnr54321 about if this issue is ready to be handed off to front end and together revise text to indication next steps.

**Comment by adamkendis** [comment]
### Updated mockups:
https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=2178%3A83958

@itsjoycelee For the comparison tool, do you think we should remove the Request Type legend and include selected request types under Criteria? See last two screenshots below. It seems the legend will be used for color-coded neighborhoods/districts.

![Screen Shot 2020-03-06 at 1 25 36 PM](https://user-images.githubusercontent.com/40484278/76123817-497b7f80-5fae-11ea-8eee-49f8d1e8fe24.png)


![Screen Shot 2020-03-06 at 1 25 51 PM](https://user-images.githubusercontent.com/40484278/76123828-51d3ba80-5fae-11ea-9ab8-f88c2c9a65ea.png)


![Screen Shot 2020-03-06 at 1 29 48 PM](https://user-images.githubusercontent.com/40484278/76123974-9cedcd80-5fae-11ea-8460-25970c62b8e9.png)


![Screen Shot 2020-03-06 at 1 32 57 PM](https://user-images.githubusercontent.com/40484278/76124200-07067280-5faf-11ea-98f5-6ca6cb712523.png)

**Comment by adamkendis** [comment]
Moved ticket back into Requirements Review. See #385

**Comment by johnr54321** [comment]
Current Status: 50%
Currently missing backend route, etc.

**Comment by adamkendis** [comment]
Status: Comparison tool is nearly complete. Charts and most filter selectors are done. Need to complete one selector, submit button, and style cleanup. Likely will be completed by this weekend.
