### ISSUE TITLE
Switch db dialect to mysql

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#197]
### Overview
In order to utilize free resources we are switching from postgres to mysql. This task should replace the dialect of sqlalchemy to mysql. 
This change will include updates to the docker-compose file to support all other collaborators

### Action Items
- [x] Update dialect to mysql in settings.cfg in `/server/src/settings.cfg`
  - Test changes to make sure they work
- [x] Update dialect to mysql in settings.example.cfg in `/server/src/settings.example.cfg`
  - This will be the file that is tracked in github so it needs to be updated too
- [ ] Update docker-compose.yml in `/Orchestration/docker-compose.yml`
  - [ ] Start a mysql docker container
- [ ] Update docker-compose.example.yml in `/Orchestration/docker-compose.example.yml`
  - This will be the file that is tracked in github so it needs to be updated too
- [ ] Validate from a fresh copy of the repo that a new dev can seed the database
  - To clean the repo as if it were fresh you can run ```git clean -dfx```
  - You will need to run onboard.sh again to get the correct files copied over (ie. docker-compose.yml and settings.cfg)

Updating the dialect in sqlalchemy is _supposed_ to be painless, especially since we are going between relational databases. But if there are bugs that arise that are fairly complex, feel free to create a bug ticket to track work done.

### Resources/Instructions
Docs of sqlalchemy dialects -> https://docs.sqlalchemy.org/en/13/dialects/

**Comment by ExperimentsInHonesty** [comment]
@rgao please update with
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by rgao** [comment]
Changed connection string to mysql dialect on local machine

Currently testing ingestion on local; running into authentication issues.

ETA: 1/29

**Comment by ExperimentsInHonesty** [comment]
@rgao it looks like your eta has passed.  please update with
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by johnr54321** [comment]
rgao updated dialects to mysql last week. Goal is to update docker-compose.yml by 2/11.

**Comment by sellnat77** [comment]
We decided on postgres...but thanks to the effort on this ticket, our system is robust enough to migrate to other dialects with ease :+1:
