### ISSUE TITLE
Fill Out Wiki Outline

### ISSUE THREAD

**Issue by stewcat** [hackforla/311-data#198]
### Overview
Convert outline into a rough draft complete with links in html/css format.

### Action Items
file:///C:/Users/Dream%20Machine/Desktop/Programs/311-Data/GitHub-Wiki_Draft_01-20-2020.html

Interview early founders, developers and volunteers to get clear origin stories, development of project, challenges from the past, organization of labor and overall goals.

### Resources/Instructions
Ru

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 Planning to review this weekend (1/-25-26/20) and discuss during next Tuesday meeting.

**Comment by johnr54321** [comment]
Ru is out.  Moving to backlog so someone else can take it.
