### ISSUE TITLE
I don't want to to edit it

### ISSUE THREAD

**Issue by moneymett** [hackforla/311-data#2]

**Comment by croor005** [comment]
2. Extract environment variables from cypress code
I noticed a couple of magic strings in your code that would ideally be put into the environment. These are the ones I'm talking about (and I may have missed some):

CYPRESS_RECORD_KEY -- this can easily be put into a Github secret

MAILOSAUR_API_KEY -- I see this is in the config.js file. Not sure if there's a way cypress can read from the environment (like a .env file or Github secret) to get this value. Possibly also the projectId although I'm not sure it's necessary.

The serverId and testEmail in cypress/integration/email.spec.js

the stuff in cypress_api.spec.js

    Cypress.env({
      host: 'veronica.dev.local',
      api_server: 'http://localhost:8888/v1/',
    })
