### ISSUE TITLE
Discuss having github post to slack.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/311-data#20]
### Overview
Github can post activity to the slack channel (or even a separate but related slack channel). There are several ways to implement this, discuss pros and cons of each and decide what our setup will be.

### Action Items
Review Resources

### Resources/Instructions
Example of general project channel where github posts directly: [Heart's slack channel](https://hackforla.slack.com/messages/CDWKEBYBB), scroll back till you see a post or go directly to a [post](https://hackforla.slack.com/archives/CDWKEBYBB/p1562654223172500)

Shared housing has two slack channels:
[#shared-housing-lafh](https://hackforla.slack.com/messages/CJK3UAX0D)
[#shared-housing-dev](https://hackforla.slack.com/messages/CLRQ8DRHA)
They have decided to segregate the dev traffic from all other slack traffic on their project.  The github messages are only setup to go to the dev channel.

**Comment by sellnat77** [comment]
Closed and reopened due to cleaning issue backlog

**Comment by sellnat77** [comment]
Slack is connected
