### ISSUE TITLE
Draft Email to NC List asking for Report & 311 Feedback

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#201]
- [x] Draft Email
- [x] #205

**Comment by ExperimentsInHonesty** [comment]
John says waiting for to review clickable prototype with Bonnie Issue #205 

@johnr54321 please add draft to comments and then put in icebox.

**Comment by johnr54321** [comment]
Here is the latest draft. Obviously we still have some material to include before sending.  https://docs.google.com/document/d/190fl2ctPRjZXuqtJCbqMBnEy6GfJeERw1ukw66gjogI/edit

**Comment by johnr54321** [comment]
Youtube videos won't be done in time for this ticket.  I took out the references in the email.

**Comment by johnr54321** [comment]
@ExperimentsInHonesty Please include Dan Kegal on the email and add him to wherever you keep this group of interested folks that we reach out to. Thanks!

**Comment by johnr54321** [comment]
Email sent.
