### ISSUE TITLE
Add update functionality to sqlIngest script

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#202]
### Overview
Allow updating SQL data store of raw data without fully reseeding database. 

### Action Items
- [x] Add method for in-place updating of values
- [x] Allow Socrata querying by most recently updated
- [x] Verify data consistency and ability to run update from Sanic

**Comment by ExperimentsInHonesty** [comment]
@ryanmswan Please provide update on:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ryanmswan** [comment]
Just sent this in as a merge request awaiting review from @sellnat77 and @gennaer. Functionality should be ready to go. Documentation of the changes will be up on dev branch once it gets the okay.
