### ISSUE TITLE
Clean up the permissions on github and remove all collaborators

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#203]
### Overview
Contributors must be on the Teams, not added as collaborators.  

###Action Items

- [x] Make sure that everyone is added as a team member
   - [ ] Ryan Swan - ryanmswan
   - [ ] Genna - gennaer
   - [ ] Jeimmi  - Jeimmi
   - [ ] Ryan - rgao
   - [ ] John - johnr54321
   - [ ] Ru - stewcat
   - [ ] Kevin Chrzanowski - KChorseraddish
   - [ ] henry wang - henrywang7
   - [ ] Matthew C. - MCC-542
   - [ ] joyce lee - itsjoycelee
   - [ ] Regan - JRHutson
- [x] Remove them as collaborators
- [ ] Turn off the ability for anyone to add collaborators to the teams

### Resources
[Current Team Roster ](https://docs.google.com/spreadsheets/d/1c4pYPX8YgSzkZ4iE8fOG98py56n4umUmlq5FQ40yniI/edit#gid=0)

**Comment by ExperimentsInHonesty** [comment]
@johnr54321  and @sellnat77  - I have removed all the collaborators (listed above in this issue). They will have to accept the invites in their email before they work on the project again.  I will post something about it in the channel.  But only in the main 311 channel.

**Comment by ExperimentsInHonesty** [comment]
I have posed the following in slack:

Bonnie  3:17 PM
In an effort to cleanup the permissions on the github repo, we have sent the following people an invite to join the hackforla github (via email) and have removed you as collaborators:
@Ryan Swan, @Genna @Jeimmi Gomez, @Ryan Gao, @John Ritchey @Ru Est, @Kevin Chrzanowski, @Henry Wang @Matthew Calima, @Joyce Lee, @jrhutson
If you find there is something you cannot do that you could do before.
check to see if you accepted invite
Let me know by sending me an @Bonnie as a thread on this issue.

3:20pm
@Russell Tan I changed some other permissions as well.  I think we had been fiddling with it while creating the second repo.  You are back down to maintainer.  Let me know if there is anything you need to do that you can’t do anymore.
