### ISSUE TITLE
Create clickable prototype for 311 data website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/311-data#205]
### Overview
We need a clickable prototype for the NCs to review and comment on, so we don't get too off track with Dev, building something they don't like.

### Action Items
Convert existing Figma to clickable version

### Resources/Instructions
[Current 311 Figma](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=0%3A1)
Example: [TDM calc project](https://www.figma.com/file/qNgPc5lttpf0SWSwkbbWyT/TDM-Calculator?node-id=0%3A1)

Example: Triage Tracker
Clickable demonstration prototype App.
Please note: the prototype walks users through a typical MCI scenario to demonstrate the app's key features; not every button/link in the prototype is clickable. To see what's is clickable on any screen, simply click anywhere on that screen and clickable areas will be highlighted in blue.
View the following prototypes in your computer's web browser
[Demonstration EMS Prototype](https://www.figma.com/proto/zKSd9S5UYszO4R6yhsr9NN/EMS-Triage-App---Hi-Fi?node-id=15%3A1422&scaling=scale-down) (shows mobile phone use): 
[Demonstration IC Prototype](https://www.figma.com/proto/zKSd9S5UYszO4R6yhsr9NN/EMS-Triage-App-Hi-Fi?node-id=524%3A7254&scaling=scale-down) (shows tablet use):

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 can you define what features from this doc ([October 29th NC Meeting Notes](https://docs.google.com/document/d/1VNL3i_B634gjcroa0CAV76BUCxe0tu1sWXmayLX_ck4/edit#)), need to be in the clickable prototype?

**Comment by Ambmoney** [comment]
https://www.figma.com/proto/x52imPqvpXlTW99qGgwId2/Untitled?scaling=contain&node-id=1%3A517

**Comment by ExperimentsInHonesty** [comment]
Duplicate of #217 217
