### ISSUE TITLE
Update Project Profile: 311 Data

### ISSUE THREAD

**Issue by harishlingam** [hackforla/311-data#207]
### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
Provide in the comments below:
- [x] updated wording if necessary on the project card (see [hackforla.org](https://www.hackforla.org/))
- [x] information on which Tools your team is using for the project (Ex: figma, Balsamiq, photoshop, etc.) . This is different than programming languages
- [x] updates for "Looking For" Section
- [x] any updated links that are not currently displayed on the site (do you have a demo site?)
- [x] Hero image to be displayed on Project Home Page at 1500 x 700 px
- [x] any resources for a Getting Started link (either a link to a wiki or readme)

### Resources/Instructions
See the hero image on the [hackforla.org](https://www.hackforla.org/) homepage

**Comment by harishlingam** [comment]
@johnr54321 Please provide an update as follows:

1. Progress:
2. Blocks:
3. Availability:
4. ETA:

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 This has to be done by 3/3/20 6:45 pm
sent via slack:
This has to be done by tomorrow night 6:45pm.  I need this for the launch of the project specific homepages tomorrow.  Because right now, this is what your project page looks like:
https://www.hackforla.org/projects/311-data.html

Just send the request for the hero image to joyce, and post something in the channel about tools people use on the project (not coding languages).

**Comment by johnr54321** [comment]
Hi Bonnie,

Re: Website

Openings / Looking for: 
Frontend Developers
Backend Developers
Backend Lead
DevOps

Contributors:
Add: johnr54321, Ambmoney, yuenyilam, itsjoycelee

Hero Image: Still working on this.

Join us link: https://github.com/hackforla/311-data/wiki/Joining-the-311-Team

Tools: Figma, Google suite, docker, AWS, etc.

Best,

John

**Comment by johnr54321** [comment]
Our Hero Image: 
![two screen 311](https://user-images.githubusercontent.com/20999589/75868629-2c338f00-5dbd-11ea-8eba-6fb15234b818.jpg)

**Comment by ExperimentsInHonesty** [comment]
@Ambmoney The image is beautiful.  and I love the idea of the image, but it reads as a little to well off, for much of the population we will be serving.  What would be great, would be an image where we are looking over the shoulder of a person of color, and we see them looking at the product on their laptop in a public environment, like cafe.  Please feel free to reach out to me via slack and we can talk some more about it if you like.

In the meantime we are going to use this image:
 ![Final 311data MVP](https://user-images.githubusercontent.com/37763229/76170695-993e8000-6141-11ea-9761-cd7550c88539.png)
