### ISSUE TITLE
convert ingest table to clean data table

### ISSUE THREAD

**Issue by gennaer** [hackforla/311-data#210]
### Overview
Read from sql_ingest_table and write to new clean_data table.

### Action Items
- [x]  copy table
- [x] add time to complete column
- [ ] other cleaning operations

### Resources/Instructions
See https://github.com/ryanmswan/311-data/blob/dev/Documentation/sqlIngest_documentation.ipynb for documentation about the sql ingest script

**Comment by ryanmswan** [comment]
Created DataCleaner object methods for creating new clean_data table in PR #227

**Comment by ExperimentsInHonesty** [comment]
@ryanmswan can you provide a few more details...
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ryanmswan** [comment]
1. We have a data cleaning object that can pull data from the database and write it back. I'd say we're probably at about 20% here.

2. Next steps are to add cleaning functionality to create new columns and decide for which tasks it's better to do operations in the database per #213 and which require operations to be done after pulling the data from the database.

3. This is my primary issue to work on for the next week. @gennaer is actively on this issue as well.

4. Best guess ETA based on prior progress is March 1.

**Comment by ExperimentsInHonesty** [comment]
When this issue is done, please move #171 from icebox to prioritized backlog

**Comment by ExperimentsInHonesty** [comment]
@ryanmswan 
1. Progress Attacking from the ground up, figuring out which rule got binned.
2. Blocks - none, just a large issue
3. Availability: 8-10
4. ETA 3/2

Recommendation to break into several issue

**Comment by ryanmswan** [comment]
Updated to break location binning into new issue #239

**Comment by johnr54321** [comment]
@ryanmswan will have a basic version of this done by 2/18 if Genna hasn't contributed before then.

**Comment by johnr54321** [comment]
ETA 3/10.

**Comment by johnr54321** [comment]
We had backend issues.  Ryan and Russell are chatting about how to do this given the 10M row limit. Goal will be to do this adaptively using sql injest or on it´s own.

**ETA**: Tuesday 3/31.

**Comment by johnr54321** [comment]
New ETA based on potential issues with Pandas. ETA 4/7

**Comment by jmensch1** [comment]
We're now cleaning data in a separate table and copying it to the requests table. So closing this one.
