### ISSUE TITLE
Send SQL Data pulled from Socrata to be Cleaned and Store in Another SQL Table

### ISSUE THREAD

**Issue by GeorgeSu** [hackforla/311-data#212]
### Overview
Data team are writing helper functions to clean the raw SQL data being retrieved from Socrata. We need to send this raw data to the clean_data functionality they write, and store this cleaned data in another SQL table.

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ryanmswan** [comment]
Added a couple of edits to reflect that the database operations should be dialect agnostic. We're switching over to MySQL, but sqlAlchemy should be fairly robust to database implementation.

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 please clean up issue and text ryan for the 4 updates in the issue

**Comment by johnr54321** [comment]
@ryanmswan @GeorgeSu Please update ticket by:
1.) Cleaning up description.  (remove default text)
2.) Add: ETA or blockers, etc.
Thanks!

**Comment by johnr54321** [comment]
Sent email on 2/1 to Sevak. Waiting for email reply.

**Comment by johnr54321** [comment]
This issue is dependent on data cleaner.  Moving back to backlog.

**Comment by jmensch1** [comment]
We're currently cleaning the data in a separate table, and then copying it into the requests table. So this ticket is basically done.
