### ISSUE TITLE
New Map Components Review

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#218]
### Overview
New Map components were designed for user usability issues - needs review to see if it is priority for MVP

### Action Items

- Map Key/Legend Component Creation
- Map   Scale Component Creation
- Zoomed-out   view in Satellite
- Legend/scale   for heat map colors
- Updated   colors for pins (for better visibility in Satellite mode)
- Border   over hovered thumbnail in pin info window

### Resources/Instructions
@henrywang7 @yuenyilam to provide design components when available

**Comment by johnr54321** [comment]
Spoke with Henry.  He's hoping to have prototyping done this week. So ETA is 2/11.
