### ISSUE TITLE
Send Request to 311 re Picture Data

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#228]
### Overview
We would like the pictures that go with the 311 app submissions.  We plan to use the pictures for displaying on our map with the pins, Machine Learning projects, as well as having before and after photos in measuring progress.

### Action Items

- [x] Contact 311
- [ ] Get the photos
- [ ] Keep the 311 team leadership abreast of progress

### Resources/Instructions
It is important that when we get the photos that they come with the request's Unique ID so we can link it to the other data.  Right now, we only need images for the request types that we have access to:

- Bulky Items
- Dead Animal Removal
- Electronic Waste
- Feedback
- Graffiti Removal
- Homeless Encampment
- Illegal Dumping
- Metal / Household Appliances
- Multiple Streetlight
- Single Streetlight
- Other

**Comment by ExperimentsInHonesty** [comment]
Sent email request to city Jeanne Holm, Deputy CIO, City of LA on 2/1/2020.

**Comment by johnr54321** [comment]
We may have a way to get this information via open source street view photos.... but it would need to be labeled.

**Comment by ExperimentsInHonesty** [comment]
This is not feasible because the city will not release the images

**Comment by johnr54321** [comment]
For the record… city of SF 311 has their images available online.  Not sure if it works for this, but thought I should add that.
