### ISSUE TITLE
Research precached data stores

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#232]
### Overview
Work with frontend developers and backend developers to identify data that can be precomputed and stored in a database table to avoid delays in serving data to frontend.

### Action Items
- [x] Create data subset for two weeks of most recent data for visualizations on frontend as a default
- [ ] Precompute timeline histogram for number of events for each neighborhood council (each row should be one day)
- [ ] Identify any additional data that can be precomputed

**Comment by johnr54321** [comment]
@ryanmswan @rgao should speak with @sellnat77 ; @GeorgeSu @adamkendis on 2/18 to determine what needs to be pre-cached for prototype.  ETA on completion TBD after discussion.

**Comment by rgao** [comment]
So far, I've wrote a method that successfully queries recent data based on current time and a variable X number of days, flexible for all councils/requests types or a specific one. Working on precompiling histograms (bar graphs?)

**Comment by rgao** [comment]
I've compiled datasets of created dates for recent requests for each request type and each council.
What is the best to store/cache the data, and for the eventual histograms?

**Comment by johnr54321** [comment]
@ryanmswan to discuss status with @rgao to determine what is left.  Decision to be made on precaching on Tuesday.

**Comment by sellnat77** [comment]
This is still an active topic, @jmensch1 has done some work with precalculating values during ingestion which will save a lot of time
And the work @rgao has done could also prove useful during the ingestion cycle instead of a per-request basis

**Comment by jmensch1** [comment]
This has been implemented by storing data in pickled pandas files. See `/server/api/src/pb`
