### ISSUE TITLE
Investigate Automation from Review to Done

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#238]
Currently, once issues are merged, they are not being closed.  John will discuss with team and decide on exact automation and implement.

**Comment by johnr54321** [comment]
ETA 2/18

**Comment by sellnat77** [comment]
This is a conflict with default branch vs current development style
Once the `dev` branch is merged to master, automation should work but the repo is setup to treat master as the default branch instead of dev

**Comment by sellnat77** [comment]
We can change the default branch, but im nervous about the implications
could be no issue at all...or throw a lot of things outta whack
80% no issue...20% unsure

**Comment by adamkendis** [comment]
@johnr54321 

Closing stale issue. This is now working properly as long as the pull request properly references the issue with `Fixes #<issue_number>`.
