### ISSUE TITLE
Recruiting needs for 2/11

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/311-data#240]
### Overview
We need to add some team members

### Action Items
Identify what kind of experience sets we need.
Front End - React (2) mentor/implementer
Back End - Node or Flask/Sanic for Microsever
Database - someone experienced in postgress and/or mysql implementation
Dev Opps - Russsel augmenter

**Comment by johnr54321** [comment]
2/11 recruiting needs is in our PPT.
