### ISSUE TITLE
Connect redux action to axios api request to backend

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#242]
### Overview
Connect a redux action to a backend api request to ensure frontend can request data from the backend. This will setup the precedent for future FE->BE communication 

### Prerequisites
  - backend running on localhost
    - via docker or python app.py
    - In the future this will be a deployed address like 311-data.herokuapp.com
  - **BONUS POINTS** Persistence layer via docker
  - Frontend running on localhost
    - via docker or python app.py

### Action Items
  - [ ] Create redux action to communicate with backend
    - [ ] Basic communication (hit healthcheck and print to console)
    - [ ] Retrieve data and print to frontend console (hit /timetoclose with appropriate params and use the response)
    - [ ] **BONUS POINTS** Trigger backend action, initiate an ingest into persistence of a specific year

**Comment by johnr54321** [comment]
ETA: 2/21.

**Comment by sellnat77** [comment]
This has been completed/proven on 2/25 
Backend + persistence running in aws was able to serve data to a frontend
