### ISSUE TITLE
Draw.IO Diagram of Tech Stack

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#253]
### Overview
We need a clear decision record and diagram so people who are onboarding can understand why we made the decisions we did in terms of our tech stack.

### Action Items
Draw.IO Diagram of Tech Stack as per the attached photo of our whiteboard drawing.

### Resume Builder
After completing this ticket, can add making tech stack architectural diagrams to their resume.

**Comment by sellnat77** [comment]
@johnr54321 Heres the diagram, not sure where we want to store it
![311-data-architecture](https://user-images.githubusercontent.com/3691245/74812869-1a27fb80-52a9-11ea-871a-61de4c69f22f.png)

**Comment by johnr54321** [comment]
@sellnat77 Let's put this diagram here: https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md

**Comment by johnr54321** [comment]
After this is done, feel free to close.  Thanks!
