### ISSUE TITLE
Create visualization for neighborhood council report

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#258]
### Overview
Create visualization to accompany report to neighborhood councils summarizing number of 

### Action Items
- [ ] Decide on appropriate visualization for task
- [ ] Create visualization as python object
- [ ] Incorporate visualization into neighborhood council report document

### Resume items
- Create visualizations using Seaborn/matplotlib/etc for reports to neighborhood council representatives

**Comment by johnr54321** [comment]
See here for the sample CSV: https://hackforla.github.io/311-report/

**Comment by joshuayhwu** [comment]
Completed with plotly dashboard #1378
