### ISSUE TITLE
Implement AWS lambda for database ingestion

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#269]
### Overview
Migrate from using local Python calls for database ingestion to AWS lambda triggers

### Action Items
- [ ] Replace Sanic endpoints for sqlIngest.py with lambda triggers

### Resources/Instructions
[AWS Lambda Documentation](https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html)
[Building Lambda Functions With Python](https://docs.aws.amazon.com/lambda/latest/dg/python-programming-model.html)

### Resume Items
Used AWS Lambda to connect AWS computing services using Python.

**Comment by sellnat77** [comment]
I think this ticket is basically done...The lambda will just be the entirety of sqlIngest.py
I still want to keep that in the /server project for local development anyways but the migration for ingestion _should_ just be a copypasta up to aws

**Comment by jmensch1** [comment]
Ingestion is now done with a single command, instead of an api call.
```
docker-compose run api python bin/db_seed.py 
```
