### ISSUE TITLE
Serve /pins with different params

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#279]
### Overview
We should still serve `GET /pins` with no params and just return defaults
We should also serve `POST /pins` with no body params

### Action Items
Allow `GET` methods on `/pins`
Allow `POST` method on `/pins` with an empty body

For both instances, return the defaults set by the `.get()` statements in the route

**Comment by GeorgeSu** [comment]
#322

**Comment by sellnat77** [comment]
I think this is safe to close, all communication to the backend is controlled through the front end and we want to keep our routes secure to respond to what is expected
The use of a set list of filters means that all backend routes can expect the same traffic
