### ISSUE TITLE
Create/maintain 311-data terraform resources

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#280]
### Overview
A terraform file has already been created but eventually it will need to be added to or managed so we should create the terraform files of our resources in anticipation of that

### Action Items
- [ ] Get EC2 instance tf file
- [ ] Create PostgreSQL instance free tier tf file
- [ ] Work with @sellnat77 to lock in extra setup steps of necessary packages for EC2 instance
- [ ] Replace the "clone 311-data GitHub repository to EC2 instance" with a docker pull
- [ ] DB Connection string should be controlled via terraform one way or another
  - and environment variable could be exposed and the startup script would overwrite settings.cfg with the correct environment variable

### Resources/Instructions
[Terraform Documentation](https://www.terraform.io/docs/index.html)
[Joel Parker Henderson's Terraform Demo](https://github.com/joelparkerhenderson/demo_terraform_aws)

### Resume Items
Worked with AWS cloud computing services and Terraform to provision database and compute resources.

**Comment by sellnat77** [comment]
@raymonddeng99

**Comment by raymonddeng99** [comment]
Sounds interesting, could I be assigned this issue?
