### ISSUE TITLE
Create Mobile Friendly Mockups

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#291]
### Overview
There will be a need to create a mobile access friendly version of the 311 data tool.

### Action Items

- [ ] Map mockup

- [ ] Data visualization mockup

- [ ] Comparison tool mockup

### Resources/Instructions

See mobile wireframes [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=1922%3A0).

**Comment by johnr54321** [comment]
This is a longer term project.  We'll check back in on Tuesday.  Henry is taking lead on this.

**Comment by henrywang7** [comment]
First iteration of prototype was finished and critiqued last week, currently working on second iteration based off feedback. Planning on completing it by this weekend

**Comment by ExperimentsInHonesty** [comment]
@itsjoycelee can you post a general update on this issue?  Thanks!

**Comment by itsjoycelee** [comment]
Henry has finished his second iteration for the mobile friendly web version. It still requires some iterations to make consistent with the computer web version, in addition to making it accessible. After accessibility discussion for our MVP (ad it is our top focus), I’ll try to see Henry’s availability and sit with him to review and develop a more refined mockup in addition to considering accessibility as well.

@henrywang7 can we set some time next week to discuss? Will you have bandwidth?

I’m also creating a side project for a mobile app for the 311 data project as well.

**Comment by johnr54321** [comment]
@kevindperez Did a great job with the Mockups for Mobile.  I just need to review it.

**Comment by danarchen** [comment]
V2 mobile version is also ready on Figma.
