### ISSUE TITLE
Prototype Testing Feedback Result Mapping

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#292]
### Overview
Testing will provide valuable insight to the usability of the 311data tool. We will need to gather all the insights and prioritize the changes to design/dev.

### Action Items

- [x] Record user flow question and answers during testing 

- [x] Tabulate insights into digital stickies

- [x] Categorize insights

- [x] Prioritize insight recommendations

### Resources/Instructions
Digital stickies [here](https://miro.com/welcomeonboard/rvUUt064hkzcfju8LjvTJMfvbhAaBIsveCjY9LNHd8Ej4jcgk9w5s8pl9cyWUJLn).

**Comment by itsjoycelee** [comment]
Ensure to document UX process

**Comment by itsjoycelee** [comment]
@johnr54321 to provide notes for both testing sessions.
Team to go through sound recording Tuesday 3/9

**Comment by johnr54321** [comment]
Here is the link to the notes from our interviews thus far: https://github.com/hackforla/311-data/wiki/March-2020---311-MVP-Alpha-UX-Interview-Notes

**Comment by itsjoycelee** [comment]
I will work on completing this over the weekend.

**Comment by johnr54321** [comment]
Moving to backlog, since current priority is accessibility.
