### ISSUE TITLE
Update time to close module to interface with the data service abstraction

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#296]
### Overview
The time to close module directly interacts with the database, this ticket will separate that logic out to the data service

This will improve the modularity of our application

### Action Items
  - Replace database calls to the data service abstraction layer
  - Improve any queries/calculations to utilize SQL language as much as possible
  - Reduce complexity of time to close module
  - Create testing infrastructure for primary path

**Comment by jmensch1** [comment]
This got done along the way.
