### ISSUE TITLE
Update deploy workflow to pull and run latest backend docker container

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#302]
### Overview
When a merge is made to master with changes to the backend, run remote ssh commands to update the ec2 server with the latest docker image

### Action Items
  - Determine if a backend change was made
  - Get the specific tag for the latest built backend container
    - DO NOT use :latest
  - remote-ssh apply a [rolling update](https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/) to the latest backend container

**Comment by jmensch1** [comment]
done
