### ISSUE TITLE
Create environment variable for server connection

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#305]
### Overview
Create an environment variable to reference the backend service address

### **_Be sure not to commit any secrets to .example.env_**
see [here](https://github.com/hackforla/311-data/blob/dev/GETTING_STARTED.md#api-secrets) for the reason why

### Action Items
  - Create env variable in `.env`
    - Post in #311-data-backend to connect with someone who can give you the correct server address to use
  - Create same environment variable with a redacted value in .example.env
  - Notify #311-data-dev of the environment var name so it can be updated in the build pipeline

**Comment by brodly** [comment]
can this close as well?
