### ISSUE TITLE
Update Figma Model from Internal UX Feedback

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#312]
### Overview
The UI/UX team interviewed a number of people at hack for LA on 2/18 to get feedback on the figma model.  The suggestions needed here prior to interview are not feature specific.

### Action Items

- [x] Add Boundary lines for Neighborhood Councils and City Council Districts
- [x] Make boxes clickable all at once when multiple are selected
- [x] Fix Heat Maps to look more typical
- [x] Remove pictures from pins on map

### Due Date
Need this done by 3/3/2020

**Comment by johnr54321** [comment]
Created this issue to track the work currently taking place in prep for Tuesday.

**Comment by yuenyilam** [comment]
Boundaries are completed 3/1.
