### ISSUE TITLE
Only trigger workflows on changed files

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#320]
# Description
Within each front/backend workflow we only need to trigger the job steps if code within actually changed.
For example, if no code changed in the backend...auto pass the workflow in the backend since there are no tests to check

## Action Items
  - [ ] Determine if code changed in `/server` for backend
    - [ ] If no code changed, auto-pass backend build
  - [ ] Determine if code changed in any file/folder except `/server` for frontend
    - [ ] If no code changed, auto-pass frontend build
  - [ ] Apply all ^ to all the `/.github/workflow/*.yml` files

**Comment by jmensch1** [comment]
Looks like this can be done using the `paths` field in the workflows:

https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths

**Comment by jmensch1** [comment]
done
