### ISSUE TITLE
Individual pin to request request info on click

### ISSUE THREAD

**Issue by brodly** [hackforla/311-data#332]
### Overview
For PinMap, backend is reducing size of data by serving up an array of data points containing only: Long/Lat and SR Number. We want to grab specific SR information when the user clicks on a pin.

### Action Items
- Pin should make a query to grab specific data of itself by `srnumber`
- Pin should display a loading state while waiting for data from BE
- Pin should display error state

**Comment by johnr54321** [comment]
FE 3/10 by Adam.  Will create backend issue for Russell to distribution.  Adam to handle integration.

**Comment by adamkendis** [comment]
Looks like the endpoint has already been implemented on the server.

/servicerequest/<srnumber>

**Comment by adamkendis** [comment]
**Status**: Rolling #412 and this ticket into a single PR - Russell updated `/pins` endpoint on 3/11 to return requesttype in response. Currently working on color-coding pins by request type and creating legend. 
**ETA** for both issues: 3/15/2020.

**Comment by johnr54321** [comment]
Thanks Adam!
