### ISSUE TITLE
Mapbox token is exposed via GET param

### ISSUE THREAD

**Issue by brodly** [hackforla/311-data#337]
**Describe the bug**
The Mapbox API token is visible in the params of the GET req. We should put this in a POST req. Look into Leaflet TileLayer rendering to use POST requests

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamkendis** [comment]
Can we just add URL restrictions to the Mapbox API key we use?

https://docs.mapbox.com/help/how-mapbox-works/access-tokens/#url-restrictions

**Comment by brodly** [comment]
Not 100% on if it's actually exposed, this was more of a research ticket. But if it is and we can't hide it this seems like a good solution.
