### ISSUE TITLE
Create node_env dependent var for http/https connections to the backend server

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#364]
#Description
Local development aka NODE_ENV == development can use http traffic
production traffic aka NODE_ENV == production should be targetting https traffic

## Action Items
  - [ ] Update db_url prefix accordingly depending on NODE_ENV

**Comment by jmensch1** [comment]
what if we just include the prefix in the definition of `DB_URL`? 

On the production server the `DB_URL` variable would be `https://amazon.whatever`. But in our local `.env` files (which are .gitignored) we could just put `http://amazon.whatever`. Then we wouldn't have to mess with switching between environments.

**Comment by sellnat77** [comment]
Yeah that's prob better, easier too
Also the backed is prob going to head over to heroku to deal with all the https garbage

**Comment by brodly** [comment]
Can we close this?
