### ISSUE TITLE
Hero Photo for 311 Website Page

### ISSUE THREAD

**Issue by Ambmoney** [hackforla/311-data#365]
#Description
Photo needed for the 311 website page. This should be size 1500x 700

## Action Items

- [ ] Decide with team on best photo.

- [ ] Schedule Photo Shoot

- [ ] Send photo to John

**Comment by itsjoycelee** [comment]
![Digital Mockup 311data HFLA](https://user-images.githubusercontent.com/59002767/76918615-f34aee00-6883-11ea-9fa4-c16763c75930.png)
Final
