### ISSUE TITLE
Use a better SSL Cert for the backend 

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#366]
#Description
LetsEncrypt is a free service that can provide a trusted cert

## Action Items
  - [ ] Add better cert so the backend can serve trusted content over https

## Resources
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

**Comment by jmensch1** [comment]
we're using a AWS load balancer now that encrypts everything with a cert
