### ISSUE TITLE
[Service] Request Frequency

### ISSUE THREAD

**Issue by jmensch1** [hackforla/311-data#376]
# Description
Provide data to support the Frequency and TotalRequests charts. 

The data for these charts is the same. The TotalRequests chart requires a total, but that can be calculated on the front end.

## Endpoint
Check or uncheck the supported methods
Accepted methods
  - [ ] GET
  - [x] POST

Path: ```server:port/{requestfrequency}```

## Inputs
```json
{
	"startDate":"2015-01-01",
	"endDate":"2015-01-31",
	"ncList": ["SUNLAND-TUJUNGA NC", "ANOTHER-COUNCIL"],
	"requestTypes":["Homeless Encampment", "Bulky Items"]
}
```
## Outputs
The response should include a sequence of date buckets that span the period between `startDate` and `endDate`. The buckets should be of equal duration, and there should probably be 10 to 12 of them. For example, if the difference between `startDate` and `endDate` is one year, the buckets could be one month each. If the difference is 30 days, the buckets could be three-day period.

For each bucket, we need the total number of requests made in the given councils for each of the `requestTypes`.

Here's an example response using the inputs above. The request period is 30 days long, so the response uses 10 three-day date buckets
```json
{
	"lastPulled": "NOW",
	"data": [{
		"bucketStartDates": ["2015-01-01", "2015-01-04", "2015-01-07", "2015-01-10", "2015-01-13", "2015-01-16", "2015-01-19", "2015-01-22", "2015-01-25", "2015-01-28"],
		"requestTypes": [{
			"type": "Homeless Encampment",
			"numRequests": [200, 250, 12, 143, 200, 250, 12, 143, 200, 250]
		}, {
			"type": "Bulky Items",
			"numRequests": [2, 25, 682, 333, 444, 666, 11, 1002, 2, 15]
		}]
	}]
}
```
This response means that there were a total of 200 "Homeless Encampment" requests made in the given NCs between 2015-01-1 and 2015-01-03 (inclusive); 250 requests made between 2015-01-04 and 2015-01-06; etc.

**Comment by sellnat77** [comment]
See 
https://github.com/hackforla/311-data/blob/dev/server/src/services/pinService.py
https://github.com/hackforla/311-data/blob/dev/server/src/services/requestCountsService.py
https://github.com/hackforla/311-data/blob/dev/server/src/services/requestDetailService.py
for data service connection reference

**Comment by rgao** [comment]
Finished updating the frequency module functionalities so that it returns the data in the desired format.

Known issue: bucket start dates are displaying backwards, starting from most recent bucket
