### ISSUE TITLE
Create sketches and Mockups for: About 311, Contact Us, Splash Page

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#378]
#Description
Just as our working prototype has links to "About 311 Data" and "Contact Us" we will need to design the interface to provide valuable information to our users. We have a splash page that another UX designer created [here](https://www.figma.com/file/e2Fpfla61ZsNL3SW1bBUaT/311-Data?node-id=0%3A1). We can work off of that for a splash page if we do decide on using it.

## Action Items

- [ ] Sketches to review first and approve with the team 

- [ ] High-fidelity Mockups and review with team

- [ ] Working prototype (which links to our current prototype)

## Resources
Wireframes go [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=2288%3A96003)

**Comment by johnr54321** [comment]
@yuenyilam Thanks for taking the lead on this. I'll get you our 311-Data email address group that can be put on our site for contact information.

**Comment by johnr54321** [comment]
ETA is Tuesday 3/17?

**Comment by johnr54321** [comment]
@yuenyilam Here is the email you should put for contact us: 311data@hackforla.org

**Comment by yuenyilam** [comment]
ETA Thursday, if not, latest Sunday.

**Comment by itsjoycelee** [comment]
FInal mockups [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=2288%3A96003). 

![image](https://user-images.githubusercontent.com/59002767/77217888-3f479e00-6ae3-11ea-9c5e-85e6cb6f8ae7.png)


John to review content/verbiage 3/21.

**Comment by itsjoycelee** [comment]
Changed splash picture as per Bonnie's recommendation.

Click link [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=2288%3A96003).
