### ISSUE TITLE
Migrate backend to heroku

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#380]
#Description
In order to alleviate the ssl mumbo jumbo, the backed will be moved to heroku and the database will remain on aws
This is the first iteration, in the future this will become a part of the GitHub action workflow

## Action Items
  - [ ] deploy backed docker image to a heroku account
  - [ ] swap in correct environment variables

**Comment by brodly** [comment]
Is this necessary? Does AWS Cert manager not work? This seems like the nuclear solution to something that could be solved easier (at least in the short term)

**Comment by sellnat77** [comment]
:skull_and_crossbones: idk...it's the route that I'm more familiar with and has a concrete implementation
But if someone has more experience/expertise, I'm open to alternatives
