### ISSUE TITLE
DateSelector - error handling

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#381]
#Description

Add better error handling/display to DateRangerPicker component. Remove the alert for when start/end date hasn't been selected.

## Action Items

- [ ] Remove alert('Provide valid start and end dates.')
- [ ] Add error handling for when user clicks submit without valid start and/or end dates.
- [ ] Change corresponding date input color on error. (bulma danger classname)

**Comment by adamkendis** [comment]
I'll do this after I finish #332

**Comment by brodly** [comment]
Ticket #426 creates an error handling modal when a data request errors out. Might be able to use this modal to populate general UI errors as well. Should discuss this approach
