### ISSUE TITLE
Map zoom functionality interferes with sidebar toggle

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#383]
**Description**
when the sidebar is collapsed, the zoom features on the map are partially blocked...at least on mobile(desktop version)

**To Reproduce**
1. Go to hackforla.github.io/311-data
2. Click on sidebar toggle to minimize it
3. See zoom functionality blocked in top left corner

**Expected behavior**
Should still be able to zoom in/out while sidebar is both collapsed and expanded

**Screenshots**
![Screenshot_20200306-130540](https://user-images.githubusercontent.com/3691245/76122783-c822ed80-5fab-11ea-983d-afffcb0ba55c.png)

**Desktop:**
 NA

**Smartphone:**
 - Device: Google pixel
 - OS: android
 - Browser stock browser

**Additional context**
Not sure if this applies to desktop too but I was using desktop version on my phone

**Comment by adamkendis** [comment]
Map zoom controls were moved to the top right in #373. Merged to dev but not pushed to master/deployed to gh-pages yet.

**Comment by sellnat77** [comment]
Confirmed fixed in latest build :+1:
