### ISSUE TITLE
Revise Request Type Colors with Accessibility

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#386]
##Description
During our testing, a user was not able to differentiate request types due to accessibility issues. As color blindness affects approximately 1 in 12 men (8%) and 1 in 200 women in the world. Therefore we will need to incorporate patterns to differentiate colors for those who may not be able to discriminate against colors (mainly green/red and in rare cases, blue/yellow and total color blindness)

## Action Items

- [ ] Revise color on all UI with patterns to discriminate one request from another

## Resources
In figma model [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=0%3A1).

**Comment by itsjoycelee** [comment]
Reds and greens have been changed 3/6. Other accessibility colors will be evaluated after more testing.

**Comment by johnr54321** [comment]
Re-scoping accessibility.  Will create another set of tickets for this.
