### ISSUE TITLE
Prototype 4 Fixes

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#387]
##Description
For a more intuitive flow based on user testing, a few minor UI and prototype flow changes have been implemented

## Action Items

- [x] Pin Map appears first after filter selection

- [x] For graphs that do not have request type associated colors, put them into the selection criteria as words

- [x] Change tab to remain as "comparison tool" rather than changing it back and forth from the  "311 data tool"

## Resources
Changes are made [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=2178%3A83958).

**Comment by itsjoycelee** [comment]
This is complete 3/6

**Comment by johnr54321** [comment]
fixes #387
