### ISSUE TITLE
[FEAT] Harness the true power of async

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#390]
### Overview
With offsets + paging on the ingest pipeline we can distribute the workload to multiple workers

### Action Items
  - [ ] For every page/offset combo for socrata requests, spawn a sanic worker
  - [ ] Ensure the db table replace v append works correctly
    - Worker 1 should start and init the table
    - Concurrent worker 2 should be appending to the table and not initing the tabl

**Comment by jmensch1** [comment]
We now have a script that updates the database, so the speed of ingestion isn't critical any more. We only need to run the ingest once the first time we're setting up an environment.
