### ISSUE TITLE
Heatmap fixes

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#397]
# Description

- Heatmap layer looks inconsistent when map is zoomed in or out. See screenshots below for the same dataset at different zoom levels.
- NC boundary color is hard to see on satellite tiles.

## Action Items

- [x] Improve consistency of heatmap layer when map is zoomed in/out. This might just be changing the `HeatmapLayer`'s radius and blur props to be dynamic based on current map zoom.

- [x] Swap out current satellite tiles for satellite with streetnames tiles.

- [x] Change NC boundary color when satellite is selected.

## Resources

![Screen Shot 2020-03-08 at 7 47 49 PM](https://user-images.githubusercontent.com/40484278/76178815-e63c4980-6175-11ea-9594-26cdfd22f01e.png)
![Screen Shot 2020-03-08 at 7 47 58 PM](https://user-images.githubusercontent.com/40484278/76178818-e8060d00-6175-11ea-8340-86f96df56528.png)
![Screen Shot 2020-03-08 at 7 48 06 PM](https://user-images.githubusercontent.com/40484278/76178820-ea686700-6175-11ea-863f-9d396b960cfe.png)
![Screen Shot 2020-03-08 at 7 48 24 PM](https://user-images.githubusercontent.com/40484278/76178824-ec322a80-6175-11ea-80e5-fd056492c1c7.png)

**Comment by brodly** [comment]
The solution to heatmap spreading out properly is to set these props on the HeatmapLayer

```
max=1
intensityExtractor={() => 1}
``

**Comment by johnr54321** [comment]
closing since this was done Mar 25.
