### ISSUE TITLE
[FEAT] Show github sha on frontend

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#399]
### Overview
For the purpose of identifying builds, we should put a frontend component that shows what github hash is currently being served from the frontend and from the backend

More often than not, the frontend version will match the backend but i _think_ it is possible for the two versions to drift apart so we want to be able to retrieve both versions from the ui

### Action Items
  - [ ] UI Design
    - To be linked after complete
  - [ ] Frontend retrieve github sha from ???
  - [ ] Frontend to retrieve backend github sha from `GET https://${DB_URL}/healthcheck`
    - See #359 for response format

**Comment by itsjoycelee** [comment]
See screenshot of hover design below.

![image](https://user-images.githubusercontent.com/59002767/76444035-97aecb00-6380-11ea-842c-43d4b0098464.png)

Front end would be the top 7 numbers, while back end will be the bottom 7 numbers.

Component is [here](https://www.figma.com/file/9RJJyaGAdT5hcRuv9PUMOY/311-Wireframe-v1.0?node-id=122%3A216).
