### ISSUE TITLE
Convert UNICODE text to ASCII before ingest

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#416]
# Description

Postgres dislikes ascii special characters. These start appearing in the 2019 data after the data refresh on Socrata took place. Need to filter the ingested data to correct format in order to avoid ingest errors.

## Action Items
- [x] Convert text to ASCII during import
- [x] Add error condition describing text conversion error

**Comment by johnr54321** [comment]
This is to fix issues after refresh. Done.
