### ISSUE TITLE
Investigate column changes after Socrata refresh

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#417]
# Description

Column createdbyuserorganization dropped from all tables after Socrata refresh. Need to check table consistency after update and make sure no columns have been renamed and are being lost at import.

## Action Items

- [x] Check existing table structure relative to prior table schema. Add new rows or delete missing rows from schema.

## Resources
See [databaseOrm.py](https://github.com/hackforla/311-data/blob/dev/server/src/services/databaseOrm.py)

**Comment by johnr54321** [comment]
ETA: Tuesday 3/31.

**Comment by johnr54321** [comment]
please update.

**Comment by ryanmswan** [comment]
Updated table specification and data dictionary to reflect new Socrata output.
