### ISSUE TITLE
Heroku paid by H4LA

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#418]
# Description
This will let us put all data on Heroku.
## Action Items

- [x] Answer questions for Code for America:
    Project name and a short description
        Who is your target user?
        When do you hope to release your project? (This can be a very rough estimate.)
    The contact information for the lead developer on the project
    What is the estimated monthly cost for hosting your project?
- [x] Draft Email for Bonnie to send

- [ ] Get Bonnieś CC on Heroku

**Comment by johnr54321** [comment]
Leaving in Ice Box in case we can't get AWS working.

**Comment by sellnat77** [comment]
- Project name and a short description
  - Who is your target user?
  - When do you hope to release your project? (This can be a very rough estimate.)
    - March 31
  - The contact information for the lead developer on the project
    - Russell Tan
    - Sellnat77@gmail.com
  - What is the estimated monthly cost for hosting your project?
## Dynos
  - Desired 100% uptime + more workers ~**$7/mo**
  - Satifactory Sleeps after 30m of inactivity + limited number of workers **Free**
## Database
  - Hard requirement for near term requirements 10M row upper limit ~**$9/mo**

## Total estimated monthly cost
~**$15/mo**

**Comment by johnr54321** [comment]
**Name**: 311 Data
**Description**: We empower citizens to make decisions at the local level based on publicly available data.
**Target User**: Citizen or Neighborhood Council member that wants to solve problems related to 311 data.

**Comment by johnr54321** [comment]
Assigning this to Bonnie to get the funds from Code for America.

**Comment by johnr54321** [comment]
**Name**: 311 Data
**Description**: We empower citizens to make decisions at the local level based on publicly available data.
**Target User**: Citizen or Neighborhood Council member that wants to solve problems related to 311 data.
**When do you hope to release your project?** (This can be a very rough estimate.)   
March 31
**The contact information for the lead developer on the project**
        Russell Tan
        Sellnat77@gmail.com
**What is the estimated monthly cost for hosting your project?**
Dynos
    Desired 100% uptime + more workers ~$7/mo
    Satifactory Sleeps after 30m of inactivity + limited number of workers Free
Database
    Hard requirement for near term requirements 10M row upper limit ~$9/mo
Total estimated monthly cost
~$16/mo

**Comment by johnr54321** [comment]
Bonnie sent email Tuesday.

**Comment by sellnat77** [comment]
This is complete

**Comment by ExperimentsInHonesty** [comment]
This is the email I ended up sending
```yaml
Hi.   

Hack for LA has a project team called 311 data.  This project has been active for a year, and we are about to go live with our MVP.  Our partner is Department of Neighborhood Empowerment, LA City.   Here is the project's homepage:  
https://www.hackforla.org/projects/311-data

Name: 
311 Data

Description: 
We empower citizens to make decisions at the local level based on publicly available data.

Target User: 
Citizen or Neighborhood Council member that wants to solve problems related to 311 data.

When do you hope to release your project? (This can be a very rough estimate.)
March 31

The contact information for the lead developer on the project: 
Russell Tan, Sellnat77@gmail.com

What is the estimated monthly cost for hosting your project?:
Dynos
Desired 100% uptime + more workers ~$7/mo
Satisfactory Sleeps after 30m of inactivity + limited number of workers Free
Database
Hard requirement for near term requirements 10M row upper limit ~$9/mo
Total estimated monthly cost
~$16/mo
```

**Comment by ExperimentsInHonesty** [comment]
This was the reply
```yaml
Hi Bonnie and team,

We're happy to hear from you, and that your project looks to be off to a good start! We'd love to support your project's ongoing development by paying for Heroku at the expected cost of $20/month. Since you mentioned you’re hoping the project release will be by 3/31/2020, I’ll make a note to reach out about 3 months after that date to do a quick check-in to make sure the project is still ongoing.

As for the logistics. In order for us to pay for Heroku, we will need to be the "owner" of the app on Heroku -- so we'll need to transfer this project to CfA. This will put us on the hook for all app-related expenses.

Here is roughly what that process looks like to move an existing app:
Change the app's name to something that includes your city or brigade. (e.g. “openoakland-courtbot” for a project called “courtbot” in the “openoakland” brigade.)
Add infra@codeforamerica.org to the app as a Collaborator.
I will need to accept the collaboration request at this point, so reply here when you've completed that step.
Finally, you'll follow the instructions on this page to transfer the app to the infra@codeforamerica.org account.
If you do not already have an existing app, send me the name of the project that you would like as well as the list of collaborators on the app.

With that, I think we'll be good to go. Feel free to reach out if you have any additional questions. Good luck with your project!

Best,
Tom

```
