### ISSUE TITLE
Get 311 Data Email Working

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#424]
# Description
We need a group contact that will receive emails from our website and that we can use to send to people outside our organization.

## Action Items

- [ ] Bonnie to fix 311-data@hackforla.org

**Comment by sellnat77** [comment]
Can i use this to setup all outside-github accounts?
aka aws login

**Comment by sellnat77** [comment]
@johnr54321 We can close this right?

**Comment by johnr54321** [comment]
Yep!

**Comment by johnr54321** [comment]
Works!  Now gets forwarded to Bonnie and I.
