### ISSUE TITLE
UI/UX Onboarding Documentation

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#435]
## Description
As the UI/UX team grows, it would be helpful to have a repository of information, a design pattern library, how to get started, and list of links that will give background to the project and design. 

## Action Items

- [x] Onboarding document

- [x] Pattern Library Creation

- [x] Helpful Links

- [x] Team Org Chart

## Resources
See team [wiki](https://github.com/hackforla/311-data/wiki) to start.

**Comment by ExperimentsInHonesty** [comment]
Helpful Links
Project board filtered by UI/UX issues: https://github.com/hackforla/311-data/projects/4?card_filter_query=label%3Aui%2Fux
