### ISSUE TITLE
Build out endpoint for database initiation method

### ISSUE THREAD

**Issue by ryanmswan** [hackforla/311-data#444]
# Description

Create Sanic endpoint to run database initiator (drop previous sql ingest table and instantiate new table)

## Action Items
- [ ] Build Sanic endpoint for triggering database initiation prior to ingest
- [ ] Change pipeline to call endpoint before spawning workers

## Resources
Depends on #436

**Comment by jmensch1** [comment]
The database now be reset with a single command (run from the `/server` directory)
```
docker-compose run api python bin/db_reset.py
```
Gonna stay away from using endpoints for DB manipulation since they would require settings up some sort of authentication system.
