### ISSUE TITLE
Database connections are not being closed

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#445]
**Describe the bug**
back end service is not closing connections and after time will overwhelm the db and start throwing 500 errors

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jmensch1** [comment]
This Sanic starter app shows one possible solution. https://github.com/seanpar203/sanic-starter

Basically what they did was configure and create the DB engine in a single module, and then passed the engine around wherever its needed. They also use scoped sessions with the sqlalchemy ORM to make sure connections don't remain open forever.
