### ISSUE TITLE
Contact 311 chart visual issues 

### ISSUE THREAD

**Issue by jmensch1** [hackforla/311-data#460]
## Description
There are a few issues with the Contact 311 chart: 
- the labels overlap in cases where the individual sections are small
- the longer labels sometimes run off the edge of the screen (like "Mobile App" below). It would take a lot of padding to avoid that for the longest labels ("Driver Self Report").

<img width="479" alt="pie-chart" src="https://user-images.githubusercontent.com/9143823/77477611-d8273380-6dd9-11ea-86b0-1b4c94550abd.png">

In addition to these visual issues, there are a bunch of request sources that are not identified in the wireframes, and so they don't have colors assigned. Here's a full list of the requests sources that are in the DB from 2019-2020.

<img width="285" alt="request sources" src="https://user-images.githubusercontent.com/9143823/77478071-a19de880-6dda-11ea-86ba-0ddca5bc24f7.png">

I'm not sure whether we want to display all of these request sources, or just stick with the ones in the wireframes. But obviously if we do display all of them there would be more potential for overlap between the labels.

## Potential fix 

It might help to use a legend specifically for this chart. I'll see what our chart package can do about adding a legend.

**Comment by jmensch1** [comment]
Hey guys, after I wrote this ticket I thought of a simple way to do this. It wouldn't involve any change to the layout or adding a legend.

Basically we'd group together all the requests that have very small numbers (like less than 1%) and put them in a catchall category called "Other" instead of displaying them individually. So the chart would look like this:

![new-pie](https://user-images.githubusercontent.com/9143823/77561911-9602fe00-6e7c-11ea-9955-18d995caeea8.png)

That would make it unlikely that there would be overlap between the labels. 

And as for the labels running off on the side, I could make abbreviations for the longer ones, like DSR for Driver Self Report, MA for Mobile App. And then inside the hoverover tooltip I could put the full name.

Does that sound okay? thanks

**Comment by itsjoycelee** [comment]
That works, Jake.
For overlapped text, would it be possible to use lines that help the text not be in the vicinity of each slice (see below image example)?
![image](https://user-images.githubusercontent.com/59002767/77583071-ad061800-6e9d-11ea-9ff2-9efd1d2fd4ca.png)

@yuenyilam is also designing alternative views for the pie chart for the next iterations as well.

**Comment by jmensch1** [comment]
Hi Joyce, 

I looked at the docs for our chart package, and unfortunately they don't offer any way to add lines like that, or move labels out of the way of each other. But they do have an option to hide a label if it overlaps another label. And it's also possible to control how far away the label is from the edge of the pie.

**Comment by yuenyilam** [comment]
<img width="402" alt="Screen Shot 2020-03-26 at 3 31 18 PM" src="https://user-images.githubusercontent.com/59905241/77621171-e494c300-6f76-11ea-9666-0fd56a73e7d6.png">
