### ISSUE TITLE
[Service] Nuclear

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#487]
# Description
In experimenting we will likely have extra data here and there in the db. This task will create an endpoint that will wipe the database for a fresh start
This will also be useful for local development to clear your docker postgres db

## Endpoint
Accepted methods
  - [x] DELETE

Path: ```server:port/nuclear/:AdminSecret```

## Inputs
There will be a url parameter of `AdminSecret`
This will come from config and the example.cfg value will be REDACTED
In production this will be set to a specific value so that we can protect who has access to this endpoint

## Outputs
```json
{
  "IsItDone": "The deed is done"
}
```

**Comment by jmensch1** [comment]
We can now reset the DB with a single command (run from `/server`):
```
docker-compose run api python bin/db_reset.py
```
This is pretty simple, and doesn't require setting up an auth system.
