### ISSUE TITLE
Create github account with 311data email for issue creation

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#489]
# Description
We need an access token generated by a shared account for the contact us page

## Action Items
  - [x] Create hackforla email
  - [ ] Create github acount with :arrow_double_up: 
  - [ ] Create an access token with these permissions `public_repo, read:org, read:packages`
  - [ ] Replace github secret with token generated from :arrow_double_up:

**Comment by jmensch1** [comment]
done
