### ISSUE TITLE
surprising closed dates in the city's data

### ISSUE THREAD

**Issue by jmensch1** [hackforla/311-data#507]
## Description
In 2019, there were 321,423 graffiti removal requests where a `closeddate` is indicated in the city's data. 

In 145,157 of those cases, the request was closed within 10 minutes of being created.

Related to #456

## Resources

```
# count grafitti removal requests in 2019 with closed dates
SELECT COUNT(*) FROM ingest_staging_table 
WHERE requesttype = 'Graffiti Removal' AND closeddate IS NOT NULL AND EXTRACT(YEAR FROM createddate) = '2019' 

	  
# count graffiti removal requests in 2019 that were closed within 10 minutes
SELECT COUNT(*) FROM (
	SELECT 
		requesttype, 
		createddate, 
		closeddate, 
		EXTRACT(EPOCH FROM (closeddate::timestamp - createddate::timestamp)) as secondstoclose 
	FROM ingest_staging_table
	WHERE requesttype = 'Graffiti Removal' AND closeddate IS NOT NULL AND EXTRACT(YEAR FROM createddate) = '2019'
) as seconds
WHERE secondstoclose < 600
```

**Comment by jmensch1** [comment]
yeah that makes sense. if the user doesn't know that though the time-to-close chart could be a little misleading

**Comment by joshuayhwu** [comment]
- It seems like the time-to-close issue is not specific to the graffiti removal issue, but rather an issue relevant to all types of requests. Based on discussions and feedback from DS community of practice, I propose two solutions:

1) Feature Engineering Perspective: Flag the records of requests that have absurd time-to-close (e.g. 10 minutes, 1 day, 3 days ...etc). Display such data on plotly dashboard as part of data summary to empahsize the severity of the problem
2) Data Quality Perspective: Remove the rows immediately if these requests are lower than our threshold time-to-close as mentioned above

The first point is implemented as an indicator visual on the plotly dashboard MVP as "Ignored Request" (See below). Would be open to any other suggestions.
![IgnoredRequests](https://user-images.githubusercontent.com/77765986/169425229-c1824174-bf06-44d1-92f1-9eb4ab7da465.PNG)

**Comment by joshuayhwu** [comment]
Basically issues were closed because of driver self-report (service request > create request > close request)
