### ISSUE TITLE
Terms & Conditions / Privacy Policy Write Up

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#508]
## Description
In order to stay covered for privacy or legal issues, we will need to have text to go onto our product.
We will need to review the need and importance of having it available on the product site.

## Action Items

- [ ] Terms & Conditions

- [ ] Privacy Policy

## Resources
Unknown at this time. There was a note to not utilize a template and not place one from CFA...

**Comment by johnr54321** [comment]
done.
