### ISSUE TITLE
Email Input Validation & Email Integration

### ISSUE THREAD

**Issue by rgao** [hackforla/311-data#517]
Currently the form input for contacts page checks if the required fields are filled before the Submit button becomes active. It doesn't however check for the syntax of the inputs. (i.e. the email field can simply be 'abc' and the form would validate). 

-  [x]  Proper email validation (in 'abc@def.com') format

Additionally, not for MVP, implement email integration. We may want to receive messages that are not technical problems via email rather than via github issue creation. 

-  [x]  Send an email from one email address to another via a back-end module
-  [ ]  Authentication access for 311data@hackforla.org
-  [ ]  Front-end integration and UI

**Comment by rgao** [comment]
I wrote a module for it and was able to send and receive emails programmatically using my own emails. There is likely going to be issues with authentication using another email to send.

**Comment by adamkendis** [comment]
Hey @rgao. I added email validation to the contact form.
