### ISSUE TITLE
Performance experiments with /pins

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#552]
# Description
`/pins` is our heaviest route when given sufficient data/filters. This task is to investigate ways to improve the performance

## Action Items
  - [ ] Investigate the serialization bottleneck
    - When a large result comes back from the database, sqlalchemy has a hard time deserializing to the model
  - [ ] See what happens if we have thresholds for # of filters
  - [ ] See what happens if we have thresholds for # of years

## Resources
For the case of thresholding something, lets see what happens if we break the request into several internal requests.
Example:
  - Threshold of 1 year
  If a user requests for 1 year of data, handle the request like normal
  If a user requests for > threshold, break the request into 1 year chunks first and handle all of those concurrently

The same principle can be applied to filters for nc's or filters for requesttypes

**Comment by jmensch1** [comment]
closing since /pins is gone
