### ISSUE TITLE
Header - Hamburger menu on browser zoom

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#558]
# Description
Header links (Comparison Tool, About 311 Data, Contact) are currently disappearing when browser zoom hits a certain level.

https://bulma.io/documentation/components/navbar/

## Action Items

- [x]  Add hamburger menu to right side of header at breakpoint where links disappear, or for smaller screen widths.

## Resources

<img width="570" alt="Screen Shot 2020-04-23 at 4 20 16 PM" src="https://user-images.githubusercontent.com/40484278/80158901-92978b00-857e-11ea-925e-4048edb1c098.png">

<img width="569" alt="Screen Shot 2020-04-23 at 4 20 37 PM" src="https://user-images.githubusercontent.com/40484278/80158918-9fb47a00-857e-11ea-9f88-1edd86a0d376.png">

<img width="570" alt="Screen Shot 2020-04-23 at 4 20 43 PM" src="https://user-images.githubusercontent.com/40484278/80158921-a3480100-857e-11ea-86ec-36566571af3a.png">

**Comment by johnr54321** [comment]
@justin1j @adamkendis if nothing by eod, let's reassign.  Thx.
