### ISSUE TITLE
UI Design - Heat Map Legend: Scale

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#568]
## Description
The heat map is currently confusing when zoomed in and out when viewing request types as the scale legend do not change to show the different in density containing min, max, mid.

## Action Items

- [ ] Meeting with front end to confirm scaling issue on heat map view

- [ ]  Create digital mockup of heat map legend scale

## Resources
[https://github.com/hackforla/311-data/projects/6#card-36314389](url)
[https://github.com/hackforla/311-data/projects/6#card-35752612](url)

**Comment by danarchen** [comment]
Status: UX team is currently in the middle of design studio. The team will come together on 5/8 to discuss ideas and then have the idea/prototype ready by 5/12.

**Comment by danarchen** [comment]
design:
https://xd.adobe.com/view/150e346e-ce58-47f7-5c87-dca9f696b893-633f/

@adamkendis let me know if you have any questions or anything regarding this issue.
