### ISSUE TITLE
UX: Stakeholder Maps

### ISSUE THREAD

**Issue by thomisfrank** [hackforla/311-data#571]
### Description
Understand who the stakeholders involved are and how they are related to one another. 

**(Can we add more context regarding why we're doing this?)** 

### Action Items
- [x] List the stakeholders (direct & indirect ex: Hack for LA & Users)
- [ ] Show how they're related to each other and the project
- [ ] Prioritize their importance
- [ ] Visualize stakeholders on a map

### Resources
- [Figma Relationship Map](https://www.figma.com/file/Pv4Gj5wOM42knLVfh9UOjR/HfLA-relationship-map)
- [Stakeholder Registry](https://docs.google.com/spreadsheets/d/1UDabNBE1kUPDGNtNdySXbL15qZOm64RJQ9eq8K28VXc/edit#gid=0)

**Comment by captain-nimo** [comment]
[311 Data User Journey & Key Features Mapping](https://docs.google.com/document/d/1DU6tN1xrBimskMpmKaCGntfJA6UxVwVaq0wa2lniqB0/edit)

**Comment by captain-nimo** [comment]
@dhwanirparekh 
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by dhwanirparekh** [comment]
Above doc [311 Data User Journey & Key Features Mapping](https://docs.google.com/document/d/1DU6tN1xrBimskMpmKaCGntfJA6UxVwVaq0wa2lniqB0/edit) captures the stakeholders and features very well. We would be discussing the relationship between stakeholders in the next meeting.

**Comment by ExperimentsInHonesty** [comment]
New miro board.  ask to be added https://miro.com/app/board/o9J_l1AapbU=/

**Comment by ExperimentsInHonesty** [comment]
Snow from the open community survey project and I met with Lissa who is helping us work on this.

**Comment by ExperimentsInHonesty** [comment]
still meeting with Snow and Lissa every week on thursday on this.  Just added Bernard from the Open Community Survey project to help us move it to figma

**Comment by ExperimentsInHonesty** [comment]
Lissa could not meet with us for the last few weeks and Snow is going to reach out to her to find out if we need to postpone till jan

**Comment by ExperimentsInHonesty** [comment]
Lissa and Snow did not show up to the meeting today and she has been veeeeerry unavailable, and I don't see that changing, I will update again next week after talking to Snow.

**Comment by ExperimentsInHonesty** [comment]
We will give an update on this next week.

**Comment by ExperimentsInHonesty** [comment]
Currently being worked on, with Bernard from Open Community Survey.  He is adding all the NC logos and we need to add to the figma the names of the NCS we have had relationships with and link a document with details to the figma

**Comment by EchoProject** [comment]
Bonnie found the [spreadsheet](https://docs.google.com/spreadsheets/d/1UDabNBE1kUPDGNtNdySXbL15qZOm64RJQ9eq8K28VXc/edit#gid=0) and sent it to Lissa.
