### ISSUE TITLE
UI: Create a legend for the map

### ISSUE THREAD

**Issue by thomisfrank** [hackforla/311-data#572]
## Description
Create a legend that sticks on the map and how it looks when exported.

## Action Items

- [ ] create sketches

- [x] create mockups

- [x] create clickable prototype

## Resources

- [ ] [figma link]

**Comment by danarchen** [comment]
Status: UX team is currently in the middle of design studio. The team will come together on 5/8 to discuss ideas and then have the idea/prototype ready by 5/12. (Tackling both issues at the same time)

**Comment by danarchen** [comment]
here's the XD link: 
https://xd.adobe.com/view/d064e8b7-83bd-400e-67d9-e5468093b939-a655/
