### ISSUE TITLE
[FEAT] Static streetview thumbnail

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#588]
### Dependency 
This issue is dependent on user testing and surveying if a thumbnail view is a priority feature for our target customers.

### Overview
When requesting info on a specific pin it would be cool to show a street view thumbnail

### Action Items
  - Setup google credentials
  - Retrieve streetview thumbnail from backend or frontend but backend will be more secure in how it handles env variables
  - Design pin details with street view window
  - Implement front end for ^ 

### Resources/Instructions
Street view static api docs https://developers.google.com/maps/documentation/streetview/intro

**Comment by danarchen** [comment]
Has not come up in any user research feedback

**Comment by EchoProject** [comment]
Adding this Issue to items for review for the product roadmap.
