### ISSUE TITLE
UI: Beta Notice

### ISSUE THREAD

**Issue by danarchen** [hackforla/311-data#593]
## Description
Creating a splash page or message to let user know the product is in beta stage
## Action Items

- [ ] Create content

- [x] Research / Sketch idea

- [x] Mock up / Prototype

## Resources

- TBD

**Comment by danarchen** [comment]
Link to mockup:
https://drive.google.com/open?id=1n0tarAIX6ZbEb062wvzJyIWdYr43opT9

**Comment by johnr54321** [comment]
fixed#593
