### ISSUE TITLE
Setup Social Media Accounts for 311-Data Project

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#597]
# Description
We need to have a social media presence when we go live. The goal of this project is to decide which accounts are most relevant and set them up.
## Action Items

- [ ] Decide which accounts are most relevant

- [ ] Set the accounts up

## Resources
311-data@hackforla.org

**Comment by danarchen** [comment]
I would think facebook, instagram and twitter would be the basics.
But we can definitely discuss about other options and more when jump on a meeting.

**Comment by danarchen** [comment]
Social media was created: Facebook and twitter
