### ISSUE TITLE
Map features for beta release

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#610]
# Description
Placeholder ticket for beta-necessary map features so I don't forget. Pending final UI mockups.

## Action Items
- [x] Map scale bar
- [x] Export legend
- [x] Heatmap/legend changes
     - Bugfix (heatmap overlapping on browser zoom)
     - Legend numbers (low, high) NOT FOR BETA
     - Heatmap display. Play with dynamic blur/radius to obtain consistency across zoom levels. PROBABLY NOT FOR BETA
-[ ] Investigate blurry pins on some displays (shadow?)

## Resources
https://xd.adobe.com/view/d064e8b7-83bd-400e-67d9-e5468093b939-a655/
https://xd.adobe.com/view/150e346e-ce58-47f7-5c87-dca9f696b893-633f/

**Comment by johnr54321** [comment]
2 hrs legend & scalebar
5 hrs w/ export legend
