### ISSUE TITLE
Draft Privacy Policy and Cookie Notice

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#612]
# Description

## Action Items
- [x] draft cookie notice (johnr)
- [x] draft privacy policy (johnr)
- [x] mockup location

Frontend Action Items
- [x] Implement cookie notice - link to privacy policy
- [x] Privacy policy page
- [x] Add Beta label to 311Data logo in header.

## Resources
![cookiesnprivacy](https://user-images.githubusercontent.com/40484278/83182895-e6e0de00-a0db-11ea-8c14-40d51b07149d.png)

![beta1](https://user-images.githubusercontent.com/40484278/83182937-f5c79080-a0db-11ea-8112-a3548195a356.png)

**Comment by johnr54321** [comment]
Cookie notice: "This website uses cookies and similar technologies to measure the effectiveness of our website and outreach efforts. By continuing to use the site, you consent to this website storing cookies on your machine."

**Comment by johnr54321** [comment]
Here is the 311-data privacy policy: https://docs.google.com/document/d/1688az36WXvDfm57qCHJMofSihrwU4OExgsqjKGLyfwk/edit?usp=sharing

**Comment by danarchen** [comment]
Link to mockup:
https://drive.google.com/open?id=1Nnq4VX2H0sPad4Kwlvg24tloA5nyo7MD

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 i just read privacy policy draft.  Let’s talk about changing the contact info from code for America to HackforLA.

**Comment by johnr54321** [comment]
Done.
