### ISSUE TITLE
Consolidate github secrets

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#622]
# Description
There are a lot of github secrets with bad naming conventions 😅 Some of which are not being used anymore. This task will address correct naming and remove unused keys

## Action Items
  - [ ] Identify keys used by node application
  - [ ] Identify keys used by python application
  - [ ] Identify if there are keys used for the docker-compose portion
  - [ ] Identify keys used during github actions workflows
  - [ ] Identify keys used on heroku
  - [ ] Verify unused keys
  - [ ] Remove unused keys
  - [ ] Consolidate naming conventions for different aspects of the application
    - Suggestion: Similar to Branch naming ->`{FRONT/BACK/DEVOP}_{TKN/URL/PAS/SEC}_{What is it}`  
    -  `FRONT_TKN_MAPBOX`
    - `FRONT_URL_BACKEND`
    - `BACK_TKN_GH_ISSUES`
    - `BACK_TKN_SOCRATA`

**Comment by jmensch1** [comment]
this is done
