### ISSUE TITLE
Research Reason for Overlapping Neighborhoods

### ISSUE THREAD

**Issue by JRHutson** [hackforla/311-data#628]
The Neighborhood Council polygons from the city have areas that overlap and areas that are not covered by any neighborhood. 

Research reasons for this. Some areas may be intentional (ex. Parks, Jail...) while others may be data errors.

<img width="384" alt="Screen Shot 2020-05-19 at 6 43 21 PM" src="https://user-images.githubusercontent.com/10876900/82399748-aa8ded80-9a0a-11ea-8ccd-d05ddb984b98.png">

**Comment by JRHutson** [comment]
Sent message to dataset owner through the city open data portal.

**Comment by adamkendis** [comment]
Example: Encino NC and Lake Balboa have significant overlap in a large park/golf course area. All reports (of the scattered dozen or two that I clicked) in the overlap appear to be assigned to Lake Balboa NC.
<img width="871" alt="Screen Shot 2020-05-19 at 9 29 56 PM" src="https://user-images.githubusercontent.com/40484278/82405194-f85d2280-9a17-11ea-98aa-196ed96e82de.png">
<img width="591" alt="Screen Shot 2020-05-19 at 9 30 51 PM" src="https://user-images.githubusercontent.com/40484278/82405217-07dc6b80-9a18-11ea-9cc6-7c48e1e3005a.png">

**Comment by adamkendis** [comment]
Related #791
