### ISSUE TITLE
Front - Footer tooltip for "Data updated through"

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#630]
# Description
The footer displays the date/time of last ingestion, however, this might be confusing for the user without explanation. A tooltip or popup should be displayed with a brief explanation of what the date represents.

Also, the terms&conditions and privacy policy footer links redirect to / at the moment. Update or remove links by beta launch. 

## Action Items
- [ ] Write brief explanation of what the "Data Updated Through" date/time in the footer represent.
- [ ] Add a tooltip or popup with the explanation text that appears when the user hovers or clicks the date in the footer.

- [ ] Update or remove footer links.

## Resources

![Screen Shot 2020-05-19 at 8 12 16 PM](https://user-images.githubusercontent.com/40484278/82400817-11aca180-9a0d-11ea-8b2a-f261321e02af.png)

**Comment by johnr54321** [comment]
I really love that we have this feature that tells the user when the data is current through.

**Comment by EchoProject** [comment]
- This issue is being closed as it pertains to v1 launch. A new issue has been created for v2 #1160
