### ISSUE TITLE
Cookie notice, Beta banner. Privacy Policy should show up on 1st page load.

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#632]
# Description
We added our privacy policy and cookie notice to our footer that shows up in most views.  Unfortunately, these things do not show up on the about us page that we start people loading on.

## Action Items
Pending UI mockups for:

- [ ]Make cookie notice with link to privacy policy visible on about us page and 1st page load.

**Comment by johnr54321** [comment]
@adamkendis If you want UX to mock up how this would look first, please assign to UX and add the label and message them here & in slack so they know.  Thanks.

**Comment by adamkendis** [comment]
@johnr54321 
I believe this is resolved. The cookie notice is appearing on all pages on first page load. After clicking the "Got it!" button, the notice won't appear again in the same browser tab even if the page is manually refreshed. The notice re-appears if the site is visited in another tab/browser. Let me know if there's still an issue or if this can be closed.
