### ISSUE TITLE
Setup 311Data Mapbox account

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#634]
# Description
Both map tilesets (streets, satellite) are being fetched from Mapbox API with a team member's personal token.

## Action Items
- [ ] Create Mapbox account with 311-data email address.
- [ ] Generate token.
- [ ] Apply restrictions referenced in #595 
- [ ] Update mapbox token env variable.

**Comment by EchoProject** [comment]
See if the issue is still true.

**Comment by ExperimentsInHonesty** [comment]
@adamkendis whose token are we using?  And also we are using a mapbox key that CfA got us, will we need to change that out as well?

**Comment by EchoProject** [comment]
@nichhk Are we using mapbox API? Have there been any issues with generating tokens? Not sure if this Issue needs to be addressed or if it's no factor.

**Comment by nichhk** [comment]
Yeah, we are using Mapbox. The token we are using has worked fine, but it would be a good idea to follow the Action Items. I can work on this.

**Comment by mc759** [comment]
Hey @edwinjue, do you have an update for us on this issue?

Please update:

- Progress:
- Blockers:
- Availability:
- ETA:

Thanks!

**Comment by edwinjue** [comment]
Hi @mc759, thank you for bringing this to my attention. However, do you or @EchoProject know who in H4LA is in charge or creating new accounts under H4LA since it seems this is what is required and I have no ability to do so.
