### ISSUE TITLE
Splash (Prior About) Redesign

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#653]
## Description
The 311 Data about page will be re-designed to become the  landing splash page.

## Action Items

- [x] Low fidelity mockup

- [x] Dev discussion

- [x] High fidelity mockup

## Dev Action Items

- [ ] Update hero image. Disregard hero image in Figma mockup. Use new hero image from comment thread in #786 .
- [ ] Remove "About 311 Data" hero image overlay text. 
- [ ] Remove bouncing arrow "scroll down" button.
- [ ] Append "Contact Us" form to the bottom of the new home page.
- [ ] Add "Back to Top" button to the Contact portion of the homepage. 

## Resources
Lo-Fi designs are in XD and will be completed in figma or XD.

https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A2

**Comment by danarchen** [comment]
@adamkendis Hi Adam! the new landing page has been added to our new figma file. Please let me know if you have any questions or if there's anything I can modify or do.

**Comment by adamkendis** [comment]
@danarchen Thanks Dana! The mockup looks great. I'm going to reassign this ticket to frontend.

**Comment by adamkendis** [comment]
Hey @tan-nate, was this closed in error?

**Comment by tan-nate** [comment]
I just figured 786 supersedes this

**Comment by adamkendis** [comment]
Got it, makes sense! Best to leave a closing comment if there's no linked PR. 

Ticket replaced by #786
