### ISSUE TITLE
[Re-design] Compressing and expanding sticky criteria legend

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#654]
## Description
In order to create a sticky criteria legend, a compressing and expanding is needed so that it doesn't take too much space in the map/data visualization pages.

## Action Items

- [ ] Lo-fi mockup

- [ ] Dev discussion

- [x] Hi-fi prototype

- [ ] Dev deployment

## Resources
Figma/XD image or link to be placed.

**Comment by danarchen** [comment]
check out the design here:
https://xd.adobe.com/view/2a0939f4-c4b7-4653-65be-83b2d8035d25-5c38/

**Comment by danarchen** [comment]
new iteration of sticky legend
https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A2

will review at tomorrow's meeting (7/14)

**Comment by danarchen** [comment]
prototype: https://xd.adobe.com/view/2503c1cd-0a4a-463d-86af-b395515e4fd6-7050/
