### ISSUE TITLE
[FEAT] Show Source Information on File Exports

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#675]
### Overview
Currently, when someone exports an image, csv, or PDF, the source information isn't there. We should be including a reference to our site, to the data source, and information regarding the query like the date it was generated, NC, request type, etc.

### Action Items

- [ ] PNG Export (contains all these items visible at the bottom
- [ ] CSV Export (contains info towards the top of the CSV
- [ ] PDF export (ideally in the footer)

**Comment by EchoProject** [comment]
Circle back to @chelseybeck on downloading reports/ maps.

**Comment by EchoProject** [comment]
Hi @chelseybeck please provide a link to the new ticket here.
