### ISSUE TITLE
[FEAT] Give Mayor's Office Credit for Open Data Initiative

### ISSUE THREAD

**Issue by johnr54321** [hackforla/311-data#676]
### Overview
Adding Mayor's office logo and link to about us page

### Action Items

- [x] Adjust text to add link to open data project

- [ ] Add Mayor's Office Logo

**Comment by adamkendis** [comment]
Text updated on live site. Image not included - authorization needed from mayor's office to use logo.

**Comment by adamkendis** [comment]
Closed by #679
