### ISSUE TITLE
Add legend/criteria to chart exports

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#699]
# Description
Legend/criteria are currently not included in individual chart exports. This makes the chart exports near-useless unless the user also screenshots the legend/criteria.

## Action Items
- [ ] Work with UI/UX re updated legend/criteria components.
- [ ] Add legend/criteria to all charts exports. 

## Resources
- https://github.com/hackforla/311-data/issues/1378

**Comment by EchoProject** [comment]
Will be handled in Plotly Dash. Find requirements for the reports.

**Comment by ExperimentsInHonesty** [comment]
@chelseybeck are you able to estimate size on this?

**Comment by chelseybeck** [comment]
I've researched and haven't found a way to do this within the plotly dash framework.

**Comment by ExperimentsInHonesty** [comment]
@to be discussed with Adam and entire team.  We may need to get off plotly.

**Comment by EchoProject** [comment]
@nichhk and @joshuayhwu 
This Issue addresses including a legend and search criteria when exporting. According to the above, Plotly may not support this feature. Can one of you guys, or a new volunteer, explore this and other options? This shouldn't be needed for the Map, but exported reports should clearly show labels.

**Comment by nichhk** [comment]
I'll share this with our new engineers and see if anyone is interested in working on it.

**Comment by joshuayhwu** [comment]
Updtaed version of plotly dash exports automatically include legends. Criteria filter is shown using title of charts. Will close this issue.
