### ISSUE TITLE
311 Data Educational Content Pages

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#704]
## Description
The NC has noted the need for additional help for users to understand and interpret the data. We will initially need the design and content for the FAQ and glossary pages.

## Action Items

- [x]  FAQ page UI

- [ ]  FAQ page content

- [ ]  Glossary page UI

- [ ]  Glossary page content

## Resources
Mockups will be in the 311-Data Figma.

**Comment by johnr54321** [comment]
@pras4u wanna take a first crack at content?  I can get you some as well.
