### ISSUE TITLE
Identify Success Metrics

### ISSUE THREAD

**Issue by pras4u** [hackforla/311-data#710]
### Overview
We need to be able to measure the success of our application with users, so that we know if when we make improvements it is serving our customers.

### Action Items
- [ ] Define the metrics
- [ ] Define the applications we are using
- [ ] Find or create write up for accessing 
- [ ] Establish baseline
- [ ] Determine frequency of evaluation
- [ ] Provide instructions for evaluation including logins

### Resources
- #1407 

#### Metrics first draft
- Growth in number of unique visitors per month [% of LA City NC Members / Sub members/ Volunteers (~20 per NC - 20@100 councils - 2000) ]
- Growth in number of unique visitors per month [% of LA City Households(~500k) ]
- Growth in number of signups
- Growth in repeat visitors
- Growth in shares

**Comment by alexulven** [comment]
I've been looking through documents in the drive for additional context and work that has already been done. I found a requirements document that may be an example from another company: https://docs.google.com/document/d/1vVyRVfe9PIkDMPREp_3IFONZWrpgtl5NeqGpm3ldTOY/edit#heading=h.hd4768e1vmu8

I plan to define metrics per feature that are listed in this product requirements sheet: https://docs.google.com/spreadsheets/d/1KWPIoo0skY4I_Xi7bFTPbyjQ6QiyVq4RML_t3IViAqs/edit#gid=0

**Comment by alexulven** [comment]
I added some ideas for metrics by feature in the requirements [document](https://docs.google.com/spreadsheets/d/1KWPIoo0skY4I_Xi7bFTPbyjQ6QiyVq4RML_t3IViAqs/edit#gid=0). I think it would be worthwhile to update this sheet and the google doc [here](https://docs.google.com/spreadsheets/d/1KWPIoo0skY4I_Xi7bFTPbyjQ6QiyVq4RML_t3IViAqs/edit#gid=0).

These success metrics rely on the ability to gather website usage data. Is it possible to enable google analytics so we can track traffic? Are we collecting data in the website now?

**Comment by alexulven** [comment]
No update this week. I still need look at the google analytics data and see what data we've collected so far.

**Comment by EchoProject** [comment]
Hi @alexulven! Please update: 
1. Progress:
2. Blockers: 
3. Availability:
4. ETA:
