### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by pras4u** [hackforla/311-data#711]
A favicon, also known as a shortcut icon, website icon, tab icon, URL icon, or bookmark icon, is a file containing one or more small icons, associated with a particular website or web page.

**Comment by danarchen** [comment]
![311-favicon](https://user-images.githubusercontent.com/62914516/86061954-8c110e00-ba1c-11ea-952c-b66b78eaf908.png)

@adamkendis let me know if this icon will do or if its blurry! ty
