### ISSUE TITLE
Rotating Single question survey for sticky users

### ISSUE THREAD

**Issue by 311-data** [hackforla/311-data#714]
# Description
We don’t have much of any way to interact with users.  We need to collect additional data from them as a part of the site journey.  If someone has been on the site for 5 minutes, we should be able to ask them a question like... What do you think could make this site better?
## Action Items
- Mock up look for modal / pop up
- build it so that it only appears for users that are sticky. (> 5mins)

**Comment by kevindperez** [comment]
The Nielsen Norman Group has some great suggestions on what to do and not to do with pop-ups and modals (https://www.nngroup.com/articles/popups/). The ones that seem most applicable to keep in mind for this is issue: 

1) **Never** show a popup before users can glean value from your website
2) **Never** interrupt a user's task
3) Ask for feedback **after** critical tasks are completed or provide a static, nonintrusive, means of which to give feedback anytime a user wants.
