### ISSUE TITLE
[Ideate] Using multi-select Chips to enhance usability

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#722]
## Description
The request type selection can be enhanced to ensure better usability, updated aesthetic, and modern-feel.

## Action Items

- High fidelity Mockups

## Resources
Will be in [figma](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A5).

**Comment by danarchen** [comment]
Duplicated issue
