### ISSUE TITLE
[User Interviews] Understanding what are the important things to put into informational content pages

### ISSUE THREAD

**Issue by itsjoycelee** [hackforla/311-data#726]
## Description
In order to understand what the users will want to know, need to understand, and may have confusion with, user interviews will need to be conducted to formulate the content to place into the FAQ, Glossary, and coming blog pages to educate users on data to enhance their ability to use the tool and be more data-savvy in general.

## Action Items

- [ ] Set up times with NC to interview

- [ ] Create interview questions 

- [ ] Transcribe interview

- [ ] Create insights from interview

- [ ] Create content for educational content pages

## Resources
TBD.

**Comment by danarchen** [comment]
Done
