### ISSUE TITLE
Update map attribution

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#738]
# Description
We are using two different Mapbox tilesets for the map: streets and satellite. Maps using Mapbox map designs or data must display the Mapbox wordmark and text attribution. While our map currently does have text attribution for Mapbox, it doesn't meet the Mapbox attribution requirements and the required wordmark is absent. 

The text attribution is set via the `attribution` props in the PinMap TileLayers.

Current attribution:
<img width="235" alt="Screen Shot 2020-07-14 at 6 57 41 PM" src="https://user-images.githubusercontent.com/40484278/87494931-0b9a0200-c605-11ea-859b-2fcce167cc21.png">

Mapbox attribution requirements:
https://docs.mapbox.com/help/how-mapbox-works/attribution/

## Action Items
- [x] Update text attribution on map.
- [x] Add Mapbox wordmark to map.

**Comment by tan-nate** [comment]
Updated the text attribution and added a wordmark
<img width="370" alt="Screen Shot 2020-07-20 at 9 54 08 AM" src="https://user-images.githubusercontent.com/47701264/87964405-06a6d980-ca6f-11ea-80a9-df9365a923ed.png">
