### ISSUE TITLE
Update navbar links, styling to improve flow

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#741]
# Description

Tweaking navbar to make user flow more intuitive. To discuss with @danarchen @pras4u on 7/16.

## Action Items

- [x] Add link for 311-data tool to navbar.
- [x] Update styling to make current selection more apparent.
- [x] Discuss re-wording navbar link text / adding tooltip or info icon to links.
- [ ] Discuss changes to about or splash page.

## Resources
[UX Update.pdf](https://github.com/hackforla/311-data/files/4922828/UX.Update.pdf)

**Comment by johnr54321** [comment]
Logo should point to about 311
New link should be called: ...   button should be limited to 2-3 words if possible

**Comment by johnr54321** [comment]
Move to dev for review
