### ISSUE TITLE
Create a square 311 logo

### ISSUE THREAD

**Issue by pras4u** [hackforla/311-data#758]
for use in our social media handles - currently twitter handle logo needs improvement ; Also needed for democracy labs site

**Comment by johnr54321** [comment]
here is where we are thinking of putting it: https://twitter.com/data_311

**Comment by danarchen** [comment]
Hi @pras4u, the logo has been created it. You can find the square logo on our figma file under style guide / components : logos or you can save the image here: https://drive.google.com/file/d/1RPx3Bcshe8dTnsmW2QYgFOAIGZPeMEWg/view?usp=sharing
