### ISSUE TITLE
Create and connect control's state with Redux

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#76]
### Overview
The ```control``` state will be the driving state for the individual components. This includes all values represented in the header. On any ```control``` change, all child components will update accordingly.

### Action Items
  1. Centralize state across application with Redux
  2. Plan all/starter control values [startYear, endYear, NC, etc...]
  3. Create a pattern for integrating redux across the componentry and application (i.e duck, rails, etc.)
  4. MVP+ Implement Redux libraries to reduce boilerplate reducer/action code

### Verification Items
  - [ ] Utilize react hooks ```useState()``` where applicable
  - [ ] Ensure functional components used as much as possible
  - [ ] All controls should be connected/accessible from their corresponding child components
    - This could be actually functional or at least ```console.log()``` the new values to prove functionality

### Resources/Instructions
[React hooks with controlled input](https://www.freecodecamp.org/news/how-to-get-started-with-react-hooks-controlled-forms-826c99943b92/)

**Comment by sellnat77** [comment]
@brodly Id say you can either close this or rewrite it for reduxifying?

**Comment by ExperimentsInHonesty** [comment]
@brodly - are you working on this issue or should it go back in the pool for next available person?

**Comment by brodly** [comment]
This has been pushed to dev already
