### ISSUE TITLE
[FEAT] Refactor server object caching 

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#785]
# Description
There is a need to refactor the caching mechanism. There are currently a few different cache configurations: disk (picklecache) and redis. Redis infrastructure is stood up but not currently used. There are some redundant cache calls between getting the clusters and heatmap. The caching is also not threadsafe and could cause an issue if simultaneous writes were tried. Complicating things is multi-threading and the size of cache objects.

## Action Items
* Do some profiling on behavior to see what the user access paths are
* Create some API tests to get baseline on key request performance
* Do some comparison of different caching scenario performance
* Either refactor code or simply remove unused options (e.g. Redis)

## Resources
Maybe use cache library: 
* https://github.com/bbangert/beaker
* https://github.com/tkem/cachetools

**Comment by jmensch1** [comment]
Those libraries both look good. I like how beaker lets you choose between different backends (Redis, file, memory, etc.)

**Comment by mattyweb** [comment]
- API version 2 is now on dev
- It includes Redis-based key-value caching
- The implementation is asynchronous using aiocache and aioredis
- There isn't much cache priming being done but more things can be added to cache as needed.
