### ISSUE TITLE
Redesign hero image on homepage

### ISSUE THREAD

**Issue by danarchen** [hackforla/311-data#786]
## Description
Replace / redesign hero image. 
New image should tell audience what our site does, and not just a view of Los Angeles. (Don't get me wrong, it looks awesome!)
## Action Items

- [x] Create/replace image

- [x] Provide image to frontend

## Resource

- image size: 1920 x 1080 (16:9)

**Comment by adamkendis** [comment]
Hey @danarchen , I neglected to consider the heights of the header and footer in regards to hero image dimensions when we last discussed this. Our combined header+footer height is 114 pixels. Could we try an image with dimensions of 1920 x 966 pixels?

**Comment by danarchen** [comment]
@adamkendis let me know if resizing works.

![heroimage1920x966](https://user-images.githubusercontent.com/62914516/91777932-02112d00-eba6-11ea-9576-9512b04eb49a.png)

**Comment by danarchen** [comment]
![heroimage1920x966](https://user-images.githubusercontent.com/62914516/91778479-70a2ba80-eba7-11ea-9935-16948c20bd27.png)


@adamkendis let me know if this one works better

**Comment by tan-nate** [comment]
another potential design: https://www.figma.com/file/sIeGaO3sMLA0zjIeLmHpmq/home-page?node-id=0%3A1
