### ISSUE TITLE
[FEAT] Enable database migrations

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#788]
### Overview
Currently there isn't a consistent way to manage changes to the database once it's in production. We will want to be able to add tables, columns, etc in a consistent way across environments that is in source control and tied to releases. This might also be useful in creating test fixtures for integration tests against a real database.

### Action Items
Since we're already (lightly) using SQL Alchemy, Alembic is the natural database migration solution. We'd want to reverse engineer the current database and commit that as the initial version. We might need to give some thought to the data generation. Presumably in some cases we're going to want to seed the database. In a test environment we may want to include a seed file since pulling the data from Socrata is time consuming.

### Resources/Instructions
https://alembic.sqlalchemy.org/en/latest/

**Comment by jmensch1** [comment]
Alembic certainly seems promising. Their docs look pretty good.

**Comment by mattyweb** [comment]
- API version 2 is now on dev.
- It includes Alembic (SQL Alchemy) for database migrations.
- Alembic migrations will be run when new code is deployed.
