### ISSUE TITLE
[FEAT] Create integration tests and/or unit tests with data fixtures

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#789]
### Overview
Currently there are a few pytests, some API tests, and some UI tests in the project. These tests are good at ensuring that there are no errors and the major functions return 200 or otherwise don't bomb out, but I don't think there is anything that is validating that function is returning an expected value. We should have some tests to that effect. Perhaps integration tests with a static database. Perhaps unit tests with mocked data. Ideally both.

### Action Items
Build some unit tests with mocked data. Build some integration test with a database seeded from a static file. Need to think about how to make this work. Sanic also has a library for pytest integration. Should investigate the right approach here.

### Resources/Instructions
https://docs.pytest.org/en/stable/
https://sanic.readthedocs.io/en/latest/sanic/testing.html

**Comment by jmensch1** [comment]
Yep you're right, our current backend tests are basically smoke tests. They don't check return values, which would be way better.

Linking #360 which has some additional testing research.
