### ISSUE TITLE
Clicking pin near the top of the map causes a ton requests

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#795]
My GUESS at what is going on is:
* The app currently sends new cluster requests every time the map is moved. 
* Clicking a pin near the top of the map causes the map to move to show the full pin and tooltip
* This moving happens pixel by pixel and thus creates dozens of API calls

Proposed Solution:
* Move map first (maybe center the pin?) before sending the cluster request

**Comment by adamkendis** [comment]
Great catch. I was able to easily reproduce this as well.

**Comment by mattyweb** [comment]
It actually looks like sometimes this behavior is crashing the app.

Now when I'm clicking on a point at the top of the screen I'm seeing some blank screens...

![image](https://user-images.githubusercontent.com/10199792/91789364-5f67a700-ebc3-11ea-9c52-bcf4a04472e9.png)
