### ISSUE TITLE
Expanded pins at lowest level do not show tooltip the first time clicked

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#813]
**Describe the bug**
Little hard to describe but at the lowest level of the map (highest zoom...17?) there still may be a cluster of 2+ pins. Clicking the cluster expands the pins with lines connecting them to a transparent version of the cluster. However when the pins themselves are clicked the first time instead of showing the tooltip for the pin the pins just disappear into the cluster again. If you repeat this process the tooltip will show up on subsequent tries.

**To Reproduce**
- Run any report and drill down until you get to the lowest level and find one of these clusters.
- Click to expand the cluster
- Click one of the pins and verify that it disappears
- Click again to expand the cluster
- Click the pin again and verify that the tooltip appears

**Expected behavior**
Tooltip should show up the first time the pin is clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/10199792/94168357-65f3e200-fe42-11ea-9a22-76181165a5ea.png)

**Comment by adamkendis** [comment]
Clusters/old map markers eliminated.
