### ISSUE TITLE
[FEAT] Enable Users to "watch" service requests or neighborhoods and get notifications

### ISSUE THREAD

**Issue by JRHutson** [hackforla/311-data#816]
### Dependency
Check with user feedback on value after v2 launch and widget integration with NC sites.

### Overview
@mattyweb suggested that users might want to be able to receive text or email alerts when there is a new 311 request near them.

### Action Items

1. Would require addition of PostGIS extension to the database to simplify spatial queries.
2. Would require a method of sending communication to the requestor.
 - Research if all mobile carriers support converting email to text messages.
 - Can we get an email account tied to the 311-data domain or a "311-alerts@hackforla.org" account.
 - Need a workflow to allow people to unsubscribe to an alert they previously setup. (If we don't have user accounts, it could be done through a reply "STOP" to unsubscribe workflow.)

### Resources/Instructions

Verizon FAQ with info on email to text - https://www.verizon.com/support/text-messaging-faqs/
AT&T Info - https://www.att.com/support/article/wireless/KM1061254/

**Comment by JRHutson** [comment]
Using a service like Twilio would prevent having to identify someone's mobile carrier, but would have a cost. https://www.twilio.com

**Comment by JRHutson** [comment]
@ExperimentsInHonesty Is there any relationship with Twilio that could be leveraged, or should we investigate setting something up that could be routed through gmail?

**Comment by ExperimentsInHonesty** [comment]
@aws offer 62,000 sms messages a month on the their I am already paying for.  So I would use that

**Comment by mattyweb** [comment]
Nice!

Would love to get direction from the User team as to how we think people would prefer to get notified (SMS, email, social media) and with what frequency (daily, weekly, etc.).

It's also important to keep in mind we currently only update data nightly...we probably don't want to be sending people texts at 3 AM...

**Comment by JRHutson** [comment]
Great thoughts Matt. I can see interest in text and email, not sure about Social Media. Would be good to get end user feedback though. 

Definitely need to have a delay before sending so that it is at a reasonable hour. 

Should the logic be that users get a daily/weekly summary or that users get a notification when there is anything new?

I had been thinking about it as anything new but users may prefer the other way.

**Comment by mattyweb** [comment]
I'm thinking that giving users the choice of a daily and/or weekly summary either for their NC (or a sub-area if we can figure out how to do that) makes the most sense. Maybe they could also choose which problem types they were interested in getting alerted about.

BTW, the other notification I can see users being interested in would be for service request status updates. That is, the pins could have "Watch this" button and the user would get a notification when the graffiti was cleaned up and the ticket was closed.
