### ISSUE TITLE
[FEAT] Enable user authentication

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#817]
Using this as a discussion topic for us to look at what user authentication would look like in the context of 311 data. The outcome of this work would be the ability to uniquely identify a user coming to the website and offer some kind of a personalized experience.

Some key questions are:
1. What are examples of new features we could enable with user authentication?
2. What are the security implications and risks of enabling it?
3. What different authentication methods would our users want us to support?

What else do we need to think about regarding user authentication?

**Comment by mattyweb** [comment]
I'm gonna respond to my own question by focusing on #2: the security implications.

I would *vastly* prefer a solution where authentication was done externally (e.g. using Facebook login or an equivalent). Bottom line is it would be great to avoid having to store usernames and passwords ourselves and deal with maintenance tasks like password resets.

Our user authentication system could be as simple as storing a user token, email address, and their NC. Then tying that to whatever preferences, notifications, or personalization we decide to offer.

**Comment by mattyweb** [comment]
After thinking about this a bit, using a tool like [Autho](https://auth0.com/) or similar Identity-as-a-Service provider would save us from having to do a bunch of work and save us from the security risk of storing a bunch of person data. I'd recommend something along these lines.

**Comment by mattyweb** [comment]
Just learned about the [FastAPI Users](https://frankie567.github.io/fastapi-users/) project. If keeping costs down takes precedence (as it likely will) this might be a good solution. Downside is more work (obviously) and more responsibility (ie. as opposed to having a 3rd party manage credentials).

**Comment by ExperimentsInHonesty** [comment]
The only use case we are thinking about for authentication is campaign management/data analysis.  And the authentication will be discussed when we do product requirements for that new version of the app.
