### ISSUE TITLE
[FEAT] Introduce pseudo-groups for service requests

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#822]
Was looking at the 311 website a bit and it feels like we might be lacking a bit of helpful fidelity to the 311 service request structure. To wit, if you look at the [create a request page](https://myla311.lacity.org/portal/faces/home/service/service-request) you see that most of the types are grouped by some kind of category or city department.

I was thinking that doing a similar grouping on 311 data would be helpful for users. We don't have all the same categories as the city website, but we could start by grouping the repairs and trash types together.

Something like this:

- Deceased Animal
- Homeless Encampment
- _(Repairs)_ Graffiti
- _(Repairs)_ Multiple Streetlights
- _(Repairs)_ Single Streetlight
- _(Trash)_ Bulky Items
- _(Trash)_ Electronic Waste
- _(Trash)_ Illegal Dumping
- _(Trash)_ Metal/Appliances
- Other Service
- Feedback @ 311

Along these lines, by ordering the types like this it'd probably also be easy to group them by color. That way it'd be easy to visually see all the trash issue together for instance.

**Comment by jmensch1** [comment]
I like the grouping-by-color idea. Maybe the requests in the same group could have different shades of the same color so they'd still be distinguishable.

**Comment by mattyweb** [comment]
Yeah, we could just as easily set our own colors for these such that all trash requests were shades of yellow, all repairs shades of blue, etc.

A combination of names and color palates should make it more obvious which of these items are related to one another.

**Comment by mattyweb** [comment]
We could still do this but since I added city Agency that seems like a fine way to sort things. I'm gonna close this.
