### ISSUE TITLE
Create tri-state toggle switch component

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#829]
# Description

**Comment by EchoProject** [comment]
Adding this Issue to items for review for the product roadmap.

**Comment by ExperimentsInHonesty** [comment]
@adamkendis Do you remember what this issue was about?

Was it in reference to the Request status (see this new design vs the two status toggle on the current dev)

![image](https://user-images.githubusercontent.com/37763229/146846752-5cb1c187-99cc-4ae4-aaed-866eb8cfa294.png)

**Comment by ExperimentsInHonesty** [comment]
If Adam says that is what this issue is about, then product will look to see if this is already covered by another issue, and 
if no, revise this issue
if yes, close this issue

**Comment by EchoProject** [comment]
- The only other related issue I found is [this issue that built the two toggle switch](https://github.com/hackforla/311-data/issues/831).

**Comment by EchoProject** [comment]
The tri-toggle will be addressed in the menu redesign. Closing this issue.
