### ISSUE TITLE
Create reusable two-state toggle switch

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#831]
# Description

A two-state toggle switch will be used to switch between Basic and Advanced menus.

## Action Items
- [ ] Implement a ToggleSwitch component using material-ui (if possible). See link in resources. 

## Resources
![Screen Shot 2020-11-12 at 5 50 07 PM](https://user-images.githubusercontent.com/40484278/99018695-92a5ab00-250f-11eb-8058-ed34febd3ef8.png)

Material-UI (see customized switches):
https://material-ui.com/components/switches/

**Comment by pras4u** [comment]
Obsolete due to redesign
