### ISSUE TITLE
Filter menu - bottom drawer (mobile)

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#833]
# Description

This menu drawer will provide the primary map/visualizations controls for mobile.

See #832 for desktop menu.

## Action Items

Don't implement the actual filter/selector controls under this ticket.

- [ ] Implement sliding bottom drawer menu using material-ui [Drawer](https://material-ui.com/components/drawers/) component.
    - [ ]  Functional component using React Hooks strongly encouraged.
    - [ ]  Styling via one of material-ui's styling options.
    - [ ]  Collapsed by default.
    - [ ] Open via tap or swipe up. (mobile)
    - [ ] Close via tap at the top or swipe down.

## Resources

https://material-ui.com/components/drawers/
https://material-ui.com/styles/advanced/#makestyles

<img width="280" alt="Screen Shot 2020-11-19 at 5 06 34 PM" src="https://user-images.githubusercontent.com/40484278/99743214-16204880-2a8a-11eb-9231-8a1df2e350be.png">
<img width="302" alt="Screen Shot 2020-11-19 at 5 06 43 PM" src="https://user-images.githubusercontent.com/40484278/99743221-191b3900-2a8a-11eb-8c5c-6b1fe68027fd.png">
<img width="234" alt="Screen Shot 2020-11-19 at 5 07 27 PM" src="https://user-images.githubusercontent.com/40484278/99743235-22a4a100-2a8a-11eb-9904-8857b8a0635d.png">

**Comment by captain-nimo** [comment]
@adamkendis 
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by adamkendis** [comment]
Progress: Started a week ago.
Blocks: Have been blocked by work.
Availability: Will be working on it this weekend.
ETA: By next week.

**Comment by adamkendis** [comment]
I have an in progress branch. Will push it up and pull in another dev to complete if I'm not able to in the next week or two.

**Comment by EchoProject** [comment]
@nichhk here's an issue related to the Map Menu for mobile. this may not be relevant with the menu re-design change coming. Please feel free to close if not needed, else we can add to the epic.

**Comment by nichhk** [comment]
Hmm this looks like a pretty useful design for mobile. I'm not sure how compatible it is with the current design though. @melissahermes99, do you think this is helpful?
