### ISSUE TITLE
Request type legend - map - collapsible (desktop/mobile)

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#834]
# Description

A collapsible map legend displaying request type names and colors.

## Action Items

**Standard stuff:**

  - Functional component using React Hooks strongly encouraged.
  - Styling via one of material-ui's styling options.

**Component stuff:**

1. Implement button to show map legend. Use material-ui.
    - [ ] Must be able to tab to the button. (desktop)
    - [ ] When button is focused, activate via mouseclick, space or enter keypresses. (desktop)
    - [ ] Tap to activate (mobile).

2. Implement legend.
    - [ ] When open, the close/X button should be tabbable. (desktop)
    - [ ] Close/X button activated via mouseclick, space or enter keypresses. (desktop)
    - [ ] Close/X button activated via tap (mobile)
    - [ ] Individual items within the legend should not be tabbable (probably - discuss if you think otherwise)
    - [x] Do **not** hardcode the request types/colors into the component jsx. We will ultimately fetch the request types/colors from the backend. Basically, this component should receive and render the list via props. Okay to create a list of request types/colors for frontend use until backend is ready.

## Resources
https://material-ui.com/styles/advanced/#makestyles

Collapsed:
<img width="262" alt="Screen Shot 2020-11-19 at 5 26 06 PM" src="https://user-images.githubusercontent.com/40484278/99747454-65b54300-2a8f-11eb-90b6-2fd0a527619c.png">

Expanded:
<img width="204" alt="Screen Shot 2020-11-19 at 5 26 44 PM" src="https://user-images.githubusercontent.com/40484278/99747463-69e16080-2a8f-11eb-81b6-f40a0cafe661.png">

**Comment by tan-nate** [comment]
Still working on this, took a little while than I thought wrapping my head around Material UI. Got the expanded legend done and now just working on the collapsible feature.

**Comment by adamkendis** [comment]
Moving ticket to prioritized backlog. In progress branch https://github.com/hackforla/311-data/tree/834-collapsible-legend

**Comment by captain-nimo** [comment]
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by KristenDLR** [comment]
Progress: In progress, material-ui button to show map legend. 
Blocks: Need some guidance on functionality, will discuss a scheduled meeting for this upcoming week. 
Availability: Wednesday anytime after 2pm, Friday anytime after 2pm

**Comment by KristenDLR** [comment]
Progress: Issued pull request, collapsable legend. After the meeting and PR received suggested changes. Will be working on it this week, for next week's review.

**Comment by ExperimentsInHonesty** [comment]
@KristenDLR Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@KristenDLR Please provide update
Progress
Blockers
Availability
ETA
