### ISSUE TITLE
[FEAT] Enable Users to create a new Service Request

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#841]
### Dependency 
This issue is dependent on user testing and surveying if SR creation support is a priority feature for our target customers. As of 2021-12-20, we have a link to creating an SR link on the FAQ page. 

### Overview
In the simplest incarnation this could be a link to the My LA 311 page that allows users to make requests:

https://myla311.lacity.org/portal/faces/home/service/service-request

If we were able to get really fancy we could let user point to a spot on the map, pick an issue type, take a picture(?), and create the issue from the 311-data.org site.

**Comment by EchoProject** [comment]
A post was added to the [FAQ page ](https://dev.311-data.org/faqs) for directing users where to go to submit service requests.
