### ISSUE TITLE
Interviews + Usability Testing on V2

### ISSUE THREAD

**Issue by danarchen** [hackforla/311-data#848]
### Dependencies:
Dependency: v2 needs to be completed.

https://github.com/hackforla/311-data/projects/10?card_filter_query=milestone%3A%22initial+v2+launch%22

Conduct interviews and usability testing on new designs, to see if there's any iterations needed.

- [x] Prototype designs
- [x] Create interview script
- [ ] Schedule interviews
- [ ] Perform Interviews
- [ ] Synthesize interviews

Other sources:
Dana provided this link [Script document](https://docs.google.com/spreadsheets/d/1ueibPcAseB8wck_UyXkBn7J61r8MF5J76DObcwtVJdU/edit?usp=sharing)
Dana provided this link [training deck](https://docs.google.com/document/d/1W7_kTiGuoEWQ6IVFI8vDcdzzSqBpqKrr4FwJUj-OiaQ/edit?usp=sharing)
Elizabeth provided this: Found V2 usability [testing script](https://docs.google.com/document/d/1TmNUgahYILzQAuH_0-Ge-JA6NiH-sErC/edit?usp=sharing&ouid=115969779390102088313&rtpof=true&sd=true) in Google Drive UX Research folder. Updating script with current V2 features and saving as a revised version (to not lose original)

**Comment by kevindperez** [comment]
UX Research recruitment request made on the UI-UX Repository

**Comment by danarchen** [comment]
Update: currently creating a training deck to recruit people to help interview w/ @kevindperez

Resource:
[https://docs.google.com/document/d/1W7_kTiGuoEWQ6IVFI8vDcdzzSqBpqKrr4FwJUj-OiaQ/edit?usp=sharing]

**Comment by danarchen** [comment]
Kevin and I are in the process of creating a deck to onbard people that could help us interview users.

**Comment by danarchen** [comment]
The script for the interview itself is ready.

**Comment by captain-nimo** [comment]
Hi @nswiderski, it looks like you're assigned to multiple issues (#962, #966, #848). We generally do 1 issue per person, and leave all extra issues in the backlog. So that new team members can grab issues from there. 

Could you please unassign yourself from 2 issues.

**Comment by elizabeth-ux** [comment]
Found V2 usability [testing script](https://docs.google.com/document/d/1TmNUgahYILzQAuH_0-Ge-JA6NiH-sErC/edit?usp=sharing&ouid=115969779390102088313&rtpof=true&sd=true) in Google Drive UX Research folder. Updating script with current V2 features and saving as a revised version (to not lose original)

**Comment by captain-nimo** [comment]
@elizabeth-ux Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by captain-nimo** [comment]
@elizabeth-ux Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

Also, can you please add the size of the ticket?
https://github.com/hackforla/311-data/labels?q=size

**Comment by ExperimentsInHonesty** [comment]
@elizabeth-ux About 14 days ago, I put the following note

> @elizabeth-ux wants to discuss with @dhwanirparekh
> Estimated ETA for updating the new script: by next week.

 Since we did not hear from you on this issue for two weeks we are assuming you are not working on it.   If you have specific questions please put them in this issue.

**Comment by ExperimentsInHonesty** [comment]
sent you a message on slack
@danarchen @kevindperez  it looks like there are two documents referenced in this issue but I can't access either of them.  Can you both check to see if you have access to either and then make sure they are located in the 311 folder.

Dana provided this link [Script document](https://docs.google.com/spreadsheets/d/1ueibPcAseB8wck_UyXkBn7J61r8MF5J76DObcwtVJdU/edit?usp=sharing)
Dana provided this link [training deck](https://docs.google.com/document/d/1W7_kTiGuoEWQ6IVFI8vDcdzzSqBpqKrr4FwJUj-OiaQ/edit?usp=sharing)

**Comment by elizabeth-ux** [comment]
Came up with a few questions for the [script](https://docs.google.com/document/d/1umm0Jawq6_Ejkrd2DGA7LjsyshAiYg2qF_DaZEQPsik/edit?usp=sharing), but it's a bit difficult since the dev site isn't complete so I can't really test the tasks. This is the general idea. Have the user test the main menu and settings and then move along to the reports to see if they can find certain reports, etc.

**Comment by hworthen** [comment]
This was from a long time and was done already.....we have new issues for what needs to be done regarding testing moving forward.
