### ISSUE TITLE
Add Business Improvement District (BID) Shapefiles to Map Search 

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#849]
### Overview
We need users of the 311 data app to be able to find the data by multiple district types (city, county, neighborhood) to increase the reach of users within Los Angeles.  

### Example
Business Improvement Districts can look up the 311 requests that are in their district boundaries.  BIDs would be treated in the app just like Neighborhood Council Districts and City Council districts.

### Assumptions
1. The city will provide BID geometries in a single GeoJSON file
2. BIDs will have a name and a shape
3. we can use the [document here:](https://data.lacity.org/A-Prosperous-City/Business-Improvement-Districts/733b-ryrk)
4. There are around 40 BIDs in the city

## Action Items 
- [ ] Add GIS extension to Postgres | Backend | Not sure this is strictly necessary to make BIDs work? But we should maybe do it anyway.
- [ ] Add BID table with ids/names (similar to the new councils table) | Backend | Need to modify migration that currently creates the councils table.
- [ ] New migration to batch add points for requests | Backend | Since there are 6mm requests I think we should batch encode what we have (but i really don't know how long encoding is going to take until we try it...)
- [ ] New migration to add geometries for BIDs (and other stuff) | Backend | We currently have long and lat columns and i think need to transform these into points
- [ ] Code requests by BID during ingestion | Backend | Geopandas could do this based on the BID geojson. Yeah, not sure if Geopandas or Postgis is the better approach here. Ideally we'd try both and pick the winner
- [ ] Add metadata endpoint for BIDs (similar to the new councils endpoint) | Backend |  
- [ ] Modify open-requests/counts endpoints to include BID counts | Backend | Not clear yet whether the counts would be included in /open-requests or would come from a separate endpoint
- [ ] Modify /comparison endpoints and underlying services to accept list of BIDs | Backend | Do we need BIDs in the comparison reports? They are not uniform, contiguous, etc.
- [ ] Include BID metadata in data we initially load from server | Frontend | This would be included in the general refactor we've been discussing where we load metadata from the API, and store it in redux, rather than taking it from a constants file
- [ ] Add BID geojson to map as another layer | Frontend |  
- [ ] Modify comparison-tool dropdowns to allow BID selection | Frontend |  

### Resources
- Get District Types API from Data Science community of practice https://github.com/hackforla/data-science/issues/118
- From the city of LA's open data website [Business Improvement Districts Map Interface](https://data.lacity.org/Housing-and-Real-Estate/Business-Improvement-Districts/733b-ryrk)

- A business improvement district is a geographically defined area within the City of Los Angeles in which services, activities, and programs are paid for through a special assessment that is charged to all members within the district. They do this to equitably distribute the benefits received and the costs incurred to provide the agreed-upon services, activities, and programs. The assessment money is collected by the City or by the County through a special contractual arrangement with the city. Because the assessment funds collected in a given district cannot legally be spent outside of that BID, the City creates a trust fund for each BID, with funds periodically released to support operations.

**Comment by EchoProject** [comment]
Reviving this Issue and moving from Icebox to New Issue Approval.
