### ISSUE TITLE
Date range selector (mobile)

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#886]
### Overview
On mobile, the date selector is getting cut off.  We need to be able to select any day in the month.

### Details
Additionally, the way it looks now on the desktop and mobile are different from each other (see images below), and neither of them look like the Figma.  They are all pretty close

## Action Items
- [ ] Review the _Things you might look_ at section below
- [ ] review CSS or SCSS files to figure out where it's being controlled
- [ ] Revise to match Figma and use the material ui library. 
- [ ] Make sure it covers the menu, so there is no awkward color blocking (see current desktop screenshot)
- [ ] Document in WIKI details that help the next developer work on this component

### Things you might look at
- [ ] Implement date range select component. See material-ui Select components (native).
- [ ] Down-caret tapped: open standard date range options (see resources)
- [ ] Calendar icon tapped: open calendar for custom date range selection.

## Resources
[Figma file with design spec](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1597%3A18386)

<details>
<summary>Desired Final Design</summary>

![Screen Shot 2021-01-07 at 3 25 47 PM](https://user-images.githubusercontent.com/40484278/103956126-b85cc400-50fc-11eb-8a6b-9f8dffe698a2.png)

![Screen Shot 2021-01-07 at 3 25 44 PM](https://user-images.githubusercontent.com/40484278/103956131-b98df100-50fc-11eb-8774-823c136cd1a1.png)
![Screen Shot 2021-01-07 at 3 25 40 PM](https://user-images.githubusercontent.com/40484278/103956132-ba268780-50fc-11eb-9034-5c070f5e6f5b.png)
</details>

<details>
<summary>Desktop currently</summary>

![image](https://user-images.githubusercontent.com/37763229/161185348-6d4b939a-3388-4e3c-9a95-ea9c7e14550b.png)
</details>

<details>
<summary>Mobile currently</summary>

![KfNuQLhk](https://user-images.githubusercontent.com/44175476/161186585-2f59f682-210f-4540-9973-81fc35f4e6cb.jpeg)
</details>

**Comment by EchoProject** [comment]
@nichhk putting this on your radar. This issue should be resolved when the menu re-design is built. Once the new ticket gets created, we can close this out. Let me know if there's a reason to keep this one. Thanks!
