### ISSUE TITLE
Request type selector (mobile)

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#887]
# Description

Mobile 311 request type selector.

## Action Items

- [ ] Implement multiselect using material-ui Select component. See native options as they may be better to use for mobile selector.
- [ ] Selected values should be rendered as material-ui Chip components color-coded by request type color.
- [ ] User should be able to deselect by tapping 'x' on the chips.

## Resources

https://material-ui.com/components/selects/
https://material-ui.com/components/chips/

![Screen Shot 2021-01-07 at 4 08 50 PM](https://user-images.githubusercontent.com/40484278/103958878-12608800-5103-11eb-8e65-5695e17685bf.png)
![Screen Shot 2021-01-07 at 4 08 46 PM](https://user-images.githubusercontent.com/40484278/103958881-142a4b80-5103-11eb-963a-c2d3bdaa4f00.png)
![Screen Shot 2021-01-07 at 4 08 38 PM](https://user-images.githubusercontent.com/40484278/103958882-14c2e200-5103-11eb-8bbf-fc2501286373.png)

**Comment by jevonmao** [comment]
@adamkendis I just wondered across this Hack For LA project. Very cool stuff going on! The mobile app seems to be in the designing stage. What platform is the mobile app on? Native iOS/Android or cross platform?

**Comment by EchoProject** [comment]
This needs to be reviewed by design to see how it fits within our schema.
