### ISSUE TITLE
Geocoder search box

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#888]
# Description

Address search box for basic user menu.

## Action Items

- [x] Add mapbox-gl-geocoder control to map for basic user menu
- [x] Map flyTo on successful geocode result.
- [x] Search by address.
- [x] Search by NC.
- [ ] Limit bounds to LA.

## Resources
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/

<img width="340" alt="Screen Shot 2021-02-15 at 3 33 08 PM" src="https://user-images.githubusercontent.com/40484278/108002045-27062a80-6fa3-11eb-9350-e4b5a38c339f.png">
<img width="512" alt="Screen Shot 2021-02-15 at 3 33 00 PM" src="https://user-images.githubusercontent.com/40484278/108002048-29688480-6fa3-11eb-825e-23ffc8ebfbee.png">

**Comment by mattyweb** [comment]
FYI, I created a ticket on the backend to get a lat and long and look up the NC from it. It's issue #957 

I also think it would be great to use the browser location feature so users don't have to type in an address.

**Comment by mattyweb** [comment]
Question: what is the benefit of having the address search box be able to search by council name in addition to address? The neighborhood council names are not exactly easy to determine or remember. I would kind of assume that if someone knew the name of a council they'd know it's location on the map and it would be easier for them to click on it than type it in. do we have any data from v1 that says this is a useful feature? otherwise, it might be easiest for this to be a pure address search.

**Comment by adamkendis** [comment]
I don't know of  v1 data supporting council name search for the v2 basic user. A pure address search would definitely be easier.

**Comment by adamkendis** [comment]
Address search bar redesigned to allow toggling between address and council search. See contemplated redesigns in Figma:
https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=2375%3A0

**Comment by adamkendis** [comment]
**Status:** Geocode address to lat/lng and fetching enclosing council id from API working. Still need to:
- Style
- Handle map flyTo on geocode result
- Push to history on geocode result - `map/nc/:nc_id` or something similar.
- NC localGeocoder
- Switching between address/NC search

**ETA:** This weekend.

**Comment by adamkendis** [comment]
**Status**: Wasn't able to finish up this past week. Address search merged to dev via #1081. Working on localGeocoder for searching by NC name.
**ETA**: By next meeting.
