### ISSUE TITLE
Council Multiselect (advanced/desktop)

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#904]
# Description

NC/District multiselects for desktop/tablet advanced menu.

## Action Items

- [x] Implement reusable multiselect using `SelectorBox` component
- [ ] User should be able to enter search text into the multiselect input.
- [x] User-provided search text will filter matching councils in dropdown.
- [x] Selected values should be rendered as material-ui Chip components.
- [x] Tapping 'x' on a selected Chip will deselect it.

**Redux stuff:**
     Councils and Regions are fetched from the api on initial render. Councils are available at `state.metadata.councils`. Regions are available at `state.metadata.regions`.
- [ ] If both council multiselects are enabled, update `state.comparisonFilters.comparison` on select/deselect.
- [x] If only the first council multiselect is enabled, update `state.filters.councils`

## Resources

![Screen Shot 2021-01-21 at 5 23 59 PM](https://user-images.githubusercontent.com/40484278/105433212-0e0d9200-5c0e-11eb-9f2a-ea5d5836527e.png)
![Screen Shot 2021-01-21 at 5 23 51 PM](https://user-images.githubusercontent.com/40484278/105433215-106fec00-5c0e-11eb-8caa-3930a760cbec.png)
![Screen Shot 2021-01-21 at 5 23 43 PM](https://user-images.githubusercontent.com/40484278/105433216-11088280-5c0e-11eb-9007-e3d72d1bc1a8.png)

**Comment by adamkendis** [comment]
**Status:** Just started on this today - implementation will be very similar to the RequestTypeSelector components.
**ETA:** Should be able to complete this over the weekend 1/24-1/25 subject to feedback from UI/UX re some slight design changes.

UI/UX items:
- Combining searchable input with selected council chips could get messy. Instead, add a sticky standalone search bar at the top of the dropdown?
- Clarification on "Neighborhood District" label in dropdown. Is this another non-interactive subheader to segment NCs from CC districts?

**Comment by kevindperez** [comment]
@adamkendis after talking with @danarchen, we have updated the design of the Council Selector on the Figma page titled "Version 2_Working Updates." I've added a light drop shadow to provide contrast with the dropdown menu and the top portion of the selector. We've also updated the text and incorporated the search bar within the dropdown. Before I push these updates onto the rest of the Figma file, have a look and let us know what you think.  And I believe we decided that the "Neighborhood District" label is a non-interactive subheader.

**Comment by mattyweb** [comment]
@adamkendis I think it'd be a good idea to touch base on reporting again before starting this work. I'm hoping we can come up with a toolset where we don't have to build complicated reporting controls ourselves.

**Comment by adamkendis** [comment]
@mattyweb sure, let's discuss at the meeting this evening.

**Comment by adamkendis** [comment]
Status: Haven't started on the redesigned dropdown. A generic ChipList component has already been created for the selected councils.
ETA: 2/11

**Comment by adamkendis** [comment]
Status: Everything is working except the SearchBar. Filtering is working if a search term is manually coded in, but encountered an issue (?) where no input will accept text. Still trying to figure it out.

![councilselector](https://user-images.githubusercontent.com/40484278/108446702-65a21c00-7213-11eb-8086-87a50efa924e.gif)
