### ISSUE TITLE
Implement resuable Loader

### ISSUE THREAD

**Issue by rufataliy** [hackforla/311-data#907]
# Description
Implement a loader component that will take the `loading `prop and show `spinner` when it is true or the children when it is false. It **shouldn't wrap** children with any additional tags.

`<Loader loading={fetching}>`
      `anything you want to render`
`</Loader`

## Resources
[This could be an example](https://github.com/rufataliy/recippy/blob/master/src/views/ContentLoader.tsx)

**Comment by danarchen** [comment]
There is UIUX label on this issue, does development or product need a mockup for this? And at what point was this determined to be a requirement?

**Comment by adamkendis** [comment]
We're going to use the material-ui [spinner](https://material-ui.com/components/progress/#circular). UI/UX label removed.
