### ISSUE TITLE
Calculate Time to close json payload given filters

### ISSUE THREAD

**Issue by sellnat77** [hackforla/311-data#93]
### Overview
Json payload that defines the average time to service request closure as defined by the control-filters
 
### Action Items
- [ ] Talk with @gennaer or @ryanmswan to get the pandas/sql function used to generate the time to close report that was demoed during the...demo
- [ ] Update the time to close module with the necessary components to pull the data from the postgres instance
- [ ]  Pass required parameters from the get/post body on the api side to the time to close module
- [ ] Return either the dataframe/json/dict to the api side and determine if further conversion is necessary 
- Result should represent a mapping of 
```json
{ 
  "RequestType": "AverageTimeToClose"
} 
```
to start
- [ ] Build out possibility of including more information such as
```json 
{
  "RequestType" : { 
     "averageTimeToClose": "48H", 
     "Max": "78H", 
     "Min": "1H" 
    }
} 
```
or something similar

### Resources/Instructions
Reach out to @gennaer or @ryanmswan for the proper calculation/logic behind *time to close*

**Comment by ExperimentsInHonesty** [comment]
Pull request #195
