### ISSUE TITLE
Create new production release builds

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#936]
We redid the GitHub actions for building the dev environment but need to do the same thing for the production environment.

Builds should run off of /release branches and create and tag the needed Docker images.

**Comment by mattyweb** [comment]
Not quite ready to move forward with this one. Actually, this is a bit of a placeholder issue. I think we might decompose this into separate production deploy tasks for API and Report Server. Also, originally I had conceived of having semver versioned releases, but not sure that makes sense anymore. Let's keep this in backlog for now.

**Comment by EchoProject** [comment]
This may be tied to Adam needing to fix the build pipeline for some PR tickets found [here](https://github.com/hackforla/311-data/pull/1148#issuecomment-996122163).

**Comment by EchoProject** [comment]
@nichhk I think we talked about this some time ago, but I can't remember where we landed. Is this still relevant or will it be addressed in the ops migration or something else?

**Comment by nichhk** [comment]
This still needs to be worked on. We can work on this closer to when we're ready to launch, and I expect it to be pretty straightforward--just changing a couple lines of configuration code.
