### ISSUE TITLE
Map - hook tilesets, boundaries, color schemes to map settings menu

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#948]
# Description

Connect map modes, color schemes, and boundary selections to left drawer.

**Comment by adamkendis** [comment]
Status: This ticket is just about done. Map tileset changes complete, just need to link boundary layers to side drawer.
ETA: Will be pushed Fri 5/14.

**Comment by adamkendis** [comment]
Status: Been slammed the past 2 weeks and wasn't able to touch this since last update. TIme set aside this weekend to complete the boundary layers portion.

**Comment by melissahermes99** [comment]
> Connect map modes, color schemes, and boundary selections to left drawer.

If this is in reference to the different map modes drawer, then yes. We aren't going forward with that option as part of the menu for V2.
