### ISSUE TITLE
Map - heatmap/hotspot layer

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#949]
# Description

**Comment by mattyweb** [comment]
Question: do we still need the heatmap? Now that the map has switched from the clusters to showing the currently open data points this feature seems redundant and could be removed.

**Comment by adamkendis** [comment]
I'm in favor of removing the heatmap layer entirely. It seemed to cause more confusion than value in v1. If we absolutely want to keep a similar feature in v2, we should consider hotspot instead of heatmap.

**Comment by mattyweb** [comment]
we'll remove from v2

(we can always build this again if people miss it)

**Comment by mattyweb** [comment]
Closing this issue as we decided we don't need heatmaps now that we have the new pin approach in v2.
