### ISSUE TITLE
Map - comparison district overlays

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#950]
# Description

When a user is viewing two "comparison" district sets on the map, there should be a clear visual distinction between each set's councils. 

## Action Items

Given the menu is toggled to `Advanced` and the user has selected two sets of councils/districts:

- [ ] The transparent fill for NC/CD boundaries in set1 and set2 should be different colors and visually distinct enough to avoid any user confusion.

**Comment by mattyweb** [comment]
Question: would love to understand the goal of this feature too. Why would someone want to compare neighborhoods? And even more so why would someone want to compare more than 2 neighborhoods? If I were on a Neighborhood council I could see myself wanting to compare my neighborhood with the district average maybe. To see if I was under/over-performing somehow. 

(Or maybe there would be a "similarity score" that could find the most similar neighborhood to compare mine to? You'd want to adjust for population and maybe some kind of economic measure like median home values to be fair. But this feels like more of an accountability feature to me either way...like something a city official would do.)

**Comment by mattyweb** [comment]
- don't need the comparison ("advanced") filters for the map
- we will build the comparison logic into the Plotly dash charts
- will get a comparison report direction sample from product or UX and give to the data team to prototype
- we will iterate on the comparison reports with internal (and potentially external) stakeholders
- @adamkendis and @kevindperez will figure out what parts of the advanced menu need to stay and tweak designs
