### ISSUE TITLE
Map - exporting

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#951]
# Description

As a user of the 311-data.org website, I would want the ability to export an image of the map along with any queried 311 requests, map legend, and any other information necessary to understand what is displayed.

**Comment by mattyweb** [comment]
Question: interested in understanding the purpose of this feature. What needs to be exported? The map? The other reports? I can't imagine that a print out of the map will legible with 30K+ dots. Maybe this feature was useful in v1 when there were clusters used? This feels like it could be obsolete.

**Comment by captain-nimo** [comment]
@pras4u will give us update on this.

**Comment by pras4u** [comment]
In place of the v1 Map export feature (with the requests as dots), we are going to use the Plotly Dash's Choropleth Map in v2.
