### ISSUE TITLE
Info icon with tooltip

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#952]
# Description

**Comment by mattyweb** [comment]
What is this item? I don't understand.

**Comment by adamkendis** [comment]
Here's a screenshot below. This is an info icon/tooltip on hover that provides some useful information or instructions. We have these attached to each selector in the v1 menu. 

![Screen Shot 2021-02-25 at 6 19 50 PM](https://user-images.githubusercontent.com/40484278/109245884-1f5e3700-7796-11eb-8619-140114e27f3d.png)

**Comment by adamkendis** [comment]
Need design for tooltip.

**Comment by mattyweb** [comment]
We would use Material-UI for this, right? So one of these: https://material-ui.com/components/tooltips/

Curious does UI/UX look at the options and pick their preference? (Placement, arrows, etc.) Or design something in codepen? Not sure if you already have a way of working here.

**Comment by captain-nimo** [comment]
@adamkendis and @kevindperez will talk about this later in detail, and make a decision about this.
