### ISSUE TITLE
[PAGE] Help Center

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#961]
### Overview 

We need a redesign of the page to look like the new tool.

## Action Items / Open Questions
- [x] Is this the same content as v1? - NO
- [x] Is this the same design as v1? - NO
- [x] redesign the Help Center page so that it fits with the new look and feel of tool and has less space wasted at the top, while being ADA compliant.

### Special note
When this page is live in the development environment take new screenshots and do another mockup of the drop downs and any questions... this will also be informed by the UX research comments. #848 

### Resources
https://311-data.org/faq

**Comment by danarchen** [comment]
We will update v2 to include contact us in NAV and any other necessary links.

**Comment by captain-nimo** [comment]
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by elizabeth-ux** [comment]
UI/UX team will work together (initially) on designs (suggestion from Kevin). Team will meet at 6:30 p.m. on Wednesdays beginning April 14. Will have mockup for April 15 meeting.

**Comment by elizabeth-ux** [comment]
- UI on Help Center is ongoing for consistency with other pages being redesigned by the UX/UI Team.
- Reviewing content of FAQs for consistency/clarity (e.g. Neighborhood Councils, neighborhood councils, NCs).
- Getting examples to add to certain requests to What do each of the 311 'Request Type' mean? (e.g. E-waste such as computers,  TVs, printers,...)

@ExperimentsInHonesty, @pras4u, @captain-nimo - At the UX/UI team meeting last night, we discussed reaching out to Neighborhood Councils to get a better sense of the project and its users. I volunteered to conduct interviews. Any help in reaching out to councilmembers and stakeholders would be appreciated.

**Comment by elizabeth-ux** [comment]
-  Made some minor design changes to Help Center. 
- Adding "Collapse/Expand All Questions" option so users can see all answers rather than clicking each individual question.
- Adding examples to for "What do each 311 Request Type mean?" question. Will mirror request order on main page.

Shifted focus this week to create a usability test with Maze to test out check box or chips for requests, as well as how request type examples are displayed (one box with all requests or by individual request)

**Comment by elizabeth-ux** [comment]
Completed usability test for menu design and request descriptions. Discussed design changes at UX/UI meeting on 4/29. Design will be similar to V. 1 using new header and footer with default (light) mode.

**Comment by elizabeth-ux** [comment]
Pages have been edited with new header (similar look to Contact Us page). Need to update screen shots and request descriptions.

**Comment by elizabeth-ux** [comment]
No new updates. Figma [file](https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=3461%3A59)

**Comment by elizabeth-ux** [comment]
![image](https://user-images.githubusercontent.com/20293568/121615286-5c80c900-ca15-11eb-95d5-74b40aee4332.png)

**Comment by elizabeth-ux** [comment]
Issue can be closed. Will add new issue to update screenshots for How do I search for 311 requests in my Neighborhood Council? once filter look is finalized.

**Comment by captain-nimo** [comment]
Closing the issue, since this is done and another ticket was created!
