### ISSUE TITLE
[PAGE] Contact Us

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#962]
### Overview

We need to redesign the Contact us page so that it fits with the new look and feel of tool 

## Action Items / Open Questions
- [ ] Is this the same content as v1?
- [ ] Is this the same design as v1?
- [ ]  redesign the Contact us page so that it fits with the new look and feel of tool and has less space wasted at the top, while being ADA compliant.

### Resources
- https://311-data.org/contact

**Comment by adamkendis** [comment]
related ticket #864

**Comment by danarchen** [comment]
We will update v2 to include contact us in NAV and any other necessary links.

**Comment by captain-nimo** [comment]
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by captain-nimo** [comment]
Hi @nswiderski, it looks like you're assigned to multiple issues (#962, #966, #848). We generally do 1 issue per person, and leave all extra issues in the backlog. So that new team members can grab issues from there. 

Could you please unassign yourself from 2 issues.

**Comment by danarchen** [comment]
Danielle will be working on this issue moving forward.

**Comment by daniellerubio** [comment]
**Progress:** on-going
**Blocks:** missing some foundational items in the design system, but will be creating those
**Availability:** will work on this weekend and next week
**ETA:** 4/25

**My actions from UI/UX team meeting on Wed (4/14):** 
- [ ] - Determine break points for desktop, tablet, mobile; share with team
- [ ] - Finalize grid (columns, spacers, grid system for buttons/components); share with team
- [ ] - Update the CTAs - could use more contemporary look
- [ ] - Microinteractions - polish this, could use some
- [ ] - Establish text field inputs, including active, disabled, error states
- [ ] - Flesh out the design system - e.g. documentation for components
- [ ] - Set typography scale and update type styles (8:9 – major second); note which text should be used for content pages vs tool (map)

**Comment by daniellerubio** [comment]
Will be able to do work on this on Friday 4/23

**Comment by daniellerubio** [comment]
For 4/22 Review:

- When I started on this issue (design contact page for v2 version), I discovered some needs for some design system basics, which should probably be turned into their own issues:

1. Determine break points for desktop, tablet, mobile; share with team - **REVIEW TODAY**
2. Finalize grid (columns, spacers, grid system for buttons/components); share with team - **REVIEW TODAY**
3. Update the CTAs - could use more contemporary look
4. Microinteractions - polish this, could use some
5. Establish text field inputs, including active, disabled, error states
6. Audit the design system and identify needs
7. Documentation for components
7. Set typography scale and update type styles (8:9 – major second); document which text should be used for content pages vs tool (map)

**Comment by daniellerubio** [comment]
Work done so far:

Design system:
- Recommended break points
- Recommended grid
- Updated header nav component as per dev site (wordmark, nav list, typography)
- New update to header nav component: changed active page state from background to underline (accessibility)

Contact us page:
- Grid
- Copy/content updated (someone else did this before I got to it)
-

**Comment by daniellerubio** [comment]
Prioritized list based on convo w/ Adam and Elizabeth today:

**v2**

- Determine break points for desktop, tablet, mobile; share with team - DONE

Desktop: 960px and up
Tablet: 600-960px
Mobile: 600px and below

- Finalize grid (columns, spacers, grid system for buttons/components); share with team


**v2.1**
Changes that should be done eventually

- Set typography scale and update type styles (8:9 – major second); document which text should be used for content pages vs tool (map)
- Update the CTAs - could use more contemporary look
- Microinteractions - polish this, could use some
- Establish text field inputs, including active, disabled, error states
- Update pre-exisiting design system components to v2 look
- Audit the design system and identify needs
- Documentation for components

@captain-nimo

**Comment by daniellerubio** [comment]
- Grids - finalized and documented in figma design system
- contact page - ready for review

**Comment by pras4u** [comment]
@elizabeth-ux As discussed work with UX team & reassign this ticket.

**Comment by pras4u** [comment]
mocks ready. lined up for FE
