### ISSUE TITLE
[CMPT] Global footer component

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#964]
### Overview

We need to have the footer display on all pages

## Action Items / Open Questions
- [x] Is it same as v1? - NO
- [x] Do we keep same footer split between map and everything else? - YES
  - [x] Document changes
    - [x] Create one footer that contains all information and trim down words as much as possible.
    - [x] Drop the version number
  
![Screen Shot 2021-03-11 at 7 32 49 PM](https://user-images.githubusercontent.com/37763229/110888239-a6380700-82a0-11eb-91cb-60f34d908870.png)
![Screen Shot 2021-03-11 at 7 32 41 PM](https://user-images.githubusercontent.com/37763229/110888241-a6d09d80-82a0-11eb-8c2b-0fda64b48139.png)

**Comment by danarchen** [comment]
Will update footer design

**Comment by adamkendis** [comment]
Removing frontend label because this ticket (if needed) is not ready for development.

**Comment by kevindperez** [comment]
Finished updating the footer. 
![image](https://user-images.githubusercontent.com/63424114/111664989-930cc600-87cf-11eb-97ca-2ceaab1202ac.png)
[https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1842%3A4684](url)

**Comment by adamkendis** [comment]
@kevindperez Just wanted to confirm if this footer should be fixed and visible at the bottom of the browser viewport even if the user scrolls down (like in v1). Is that correct?
