### ISSUE TITLE
[CMPT] Cookies alert

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#965]
# Description

Need a message when new visitors arrive.

## Action Items / Open Questions

- [x] Is this the same? - VERY SIMILAR
- [x] Does the design change? - YES

**Comment by danarchen** [comment]
We will update the cookies design. It will be similar to what it is now; however, with the new colors.

**Comment by kevindperez** [comment]
Design has been updated. You can find it here: [https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1916%3A171](url) 
![image](https://user-images.githubusercontent.com/63424114/109583504-db7c7200-7ab4-11eb-81e9-393994f9772f.png)

**Comment by adamkendis** [comment]
Ticket ready for development. Moving to Prioritized Backlog.

**Comment by captain-nimo** [comment]
Please provide update:

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by funbunch** [comment]
In progress. 
Need some more styling guidance. 
Available to finish this asap after that.

**Comment by funbunch** [comment]
I have been blocked this week by interviews/prep. Design is done, and hope I can get to completing the functionality by tomorrow or this weekend.
