### ISSUE TITLE
[PAGE] Privacy page

### ISSUE THREAD

**Issue by mattyweb** [hackforla/311-data#966]
### Overview

We need to know how the privacy policy will be displayed on V2 that is different from the current state

### Current State
There is a link to the PP on the footer on all pages except the tool
https://311-data.org/privacy

#### Open Questions for Design
- [x] Is this the same content as v1? - YES
- [x] Is this the same design as v1? - NO
- [x] Document changes
   - [x] new design needed that will work with new tool design but still be ADA compliant

### Resources
https://www.figma.com/file/eF63O8yIGz2soQ4JJFfyoK/311_Data_UXUI?node-id=1%3A5

**Comment by mattyweb** [comment]
BTW, is there a legal/terms of service page?

**Comment by danarchen** [comment]
- we can definitely update the design
- however, who wrote up the content? we're not sure what can be simplified and etc. so I guess we would need more info on this..

**Comment by adamkendis** [comment]
The privacy policy was borrowed from https://www.codeforamerica.org/privacy with some modifications.

**Comment by danarchen** [comment]
Our current privacy content is approved by Code for America. So it should not be changed or modified as it will need to be approved again.

**Comment by ExperimentsInHonesty** [comment]
That the PP footer needs to be visible on every page including the tool.  See issue about the footer for details #964

**Comment by captain-nimo** [comment]
Hi @nswiderski, it looks like you're assigned to multiple issues (#962, #966, #848). We generally do 1 issue per person, and leave all extra issues in the backlog. So that new team members can grab issues from there. 

Could you please unassign yourself from 2 issues.

**Comment by captain-nimo** [comment]
@jeffmorrowuxd, could we have a quick update on this please?

**Comment by jeffmorrowuxd** [comment]
Hey @captain-nimo  - This is completed to a point where @adamkendis said he would put get it live.  There are a few things that need to be discussed with the UX team as a whole, like Line and Paragraph spacing, but the main design is complete and ready for dev.  It can be found in the v2 Design studio.

**Comment by adamkendis** [comment]
Ready for dev.

**Comment by EchoProject** [comment]
Footer displays Privacy Policy link and the link works. Closing this issue, and will create another issue to handle potential design changes to the PP page itself.
