### ISSUE TITLE
Request Type Descriptions

### ISSUE THREAD

**Issue by danarchen** [hackforla/311-data#972]
## Description
Adding descriptions or renaming the request type to cause less confusion for users

## Action Items

- [x] Create an excel sheet of current type request terminology, terminology from the government site, what people prefer 
(will need to conduct user interviews or survey to see how they would prefer it)
- [x] Adjust terminology or design
- [x] Discuss with frontend
- [ ] Frontend development

## Resources
[Government site](https://myla311.lacity.org/portal/faces/home/service/service-request?_adf.ctrl-state=sfyoxk73c_5&_afrLoop=3343250519523305#!)

**Comment by mattyweb** [comment]
I like the idea of adding a description for each type. There might even be some existing language we can use from the different 311 systems. Overall, there is some inconsistency between the current mobile app, online and reporting and I think we can add value by helping users understand more how the 311 system works.

It would also give us a chance to describe any transformations/modifications we make to the data. (I'm trying to keep a list of our data loading rules [here](https://github.com/hackforla/311-data/blob/dev/docs/data_loading.md#notes-about-how-we-handle-the-311-data).)

**Comment by mattyweb** [comment]
FYI, here is the current types file we are loading.
[request_types.csv.zip](https://github.com/hackforla/311-data/files/6050844/request_types.csv.zip)

If we agree on this approach, I would start by adding a description column to this file, loading it and exposing it in the /types endpoint. I think 100 characters is a good guess for length (e.g. "Air conditioners, dryers, refrigerator and more..." which is the metal/appliance description) and would easily fit in a tooltip.

@danarchen you could add the tooltips to the designs and hopefully by then the data would be available in the API for @adamkendis to work with.

**Comment by mattyweb** [comment]
@danarchen and @adamkendis,
I added descriptions and put it on dev. you can see it/use it here: https://dev-api.311-data.org/types
Best approach is probably to figure out where to put the tooltips, do the UI dev work, and attach to this ticket.

**Comment by captain-nimo** [comment]
Assigning this ticket to UI/UX. UI/UX will re-assign to Frontend when they're done.

**Comment by danarchen** [comment]
Meet with Bonnie and will update issue with notes

**Comment by danarchen** [comment]
[govt site](https://www.lacity.org/myla311)

**Comment by dhwanirparekh** [comment]
This [spreadsheet](https://drive.google.com/file/d/18ppFaAaqcJ-tXk71rSXcUpdFaG0coGgp/view?usp=sharing) has the list of request types as per the [gov site ](https://www.lacity.org/myla311). Gov site has 12 main request types and each of that has several sub-categories. And the [311-data ](https://311-data.org/data) website seems to be showing only 11 **sub-categories**, I have following questions:

- Are we pulling data only for specific sub-categories or the gov data has data only for those specific sub-categories?
- Should we design considering all the main/sub-categories?
- Can we check with neighbouring council how do they use this filter, and what do they expect to have here?

**Comment by dhwanirparekh** [comment]
It's still a work in progress - presented one of the ideas in the last meeting, adding request type descriptions to a modal that would pop out when clicked on the info icon next to the "Request Type" label. Another idea is to replace the multi-select dropdown for Request Type with a group of checkboxes as in version 1 and have a service type description be right below each of the service names. The team is going to do user testing for version 2 this week, which would help get some insight on which solution would work best.

**Comment by elizabeth-ux** [comment]
Created user testing for Menu and Request Type descriptions [](https://t.maze.co/35584517) Sent to #admin in Slack for release to users.

**Comment by adamkendis** [comment]
Status: @elizabeth-ux conducted user test for Request Type descriptions preference. Users preferred a single modal displaying all req. type descriptions. @dhwanirparekh to prepare mockup.

**Comment by pras4u** [comment]
@dhwanirparekh please link the final mocks here

**Comment by dhwanirparekh** [comment]
![RequestTypeDescription](https://user-images.githubusercontent.com/38696871/120732588-330eed00-c4ab-11eb-84b9-ed9bdcfb9c0c.png)
![RequestTypeDescription_PopUp](https://user-images.githubusercontent.com/38696871/120732594-3609dd80-c4ab-11eb-88ce-ba950b2d3f2e.png)

**Comment by adamkendis** [comment]
Just picked this ticket up. Adding modal to map page.

**Comment by nichhk** [comment]
This is something that we still need to implement for v2.
