### ISSUE TITLE
Increase resolution of image on hackforla.org project page for 311 Data to 600 x 400 pixels or higher

### ISSUE THREAD

**Issue by shaswa** [hackforla/311-data#987]
### Overview
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400 pixels or higher. 

Current Resolution: 388 x 258 pixels
Current Ratio: 3:2

### Action Items
- [x] Increase resolution of image for 311 Data to 600 x 400 pixels or higher
- [ ] Update Status on hackforla/website#1105

### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)

**Comment by kevindperez** [comment]
![311mockup_600x400](https://user-images.githubusercontent.com/63424114/112030606-ab465300-8af7-11eb-9d39-71da4303f76d.png)
Completed.

**Comment by captain-nimo** [comment]
Hi @shaswa,

Please find the image @kevindperez uploaded in the ticket. We hope this helps.

**Comment by shaswa** [comment]
@captain-nimo @kevindperez Thank you! Though this ticket is for this particular image. Sorry about not being clearer. Could you update this image too?
https://www.hackforla.org/assets/images/projects/311_data.png

**Comment by captain-nimo** [comment]
@shaswa, what resolution do you want this image? 600 x 400?

**Comment by captain-nimo** [comment]
@kevindperez, could you please update the following image too?
https://www.hackforla.org/assets/images/projects/311_data.png

**Comment by kevindperez** [comment]
Done. 
![311mockup_2-02](https://user-images.githubusercontent.com/63424114/112063011-fa06e380-8b1d-11eb-9b54-8fd8a6f32a31.png)

**Comment by captain-nimo** [comment]
Thanks a lot @kevindperez .
@shaswa ,please check out the image that Kevin has attached.

**Comment by shaswa** [comment]
@kevindperez @captain-nimo Thank you! I'll create a new issue in the website to use the new image. This issue can be closed.
