### ISSUE TITLE
[Map] Zoom to - Service request details popup

### ISSUE THREAD

**Issue by adamkendis** [hackforla/311-data#998]
Related to #947 

# Description

Adds a "Zoom to" button on the service request details popup. This centers the selected SR pin and zooms to a fixed level.

## Resources

![108664545-d6516e80-7487-11eb-897c-94d224f0042e](https://user-images.githubusercontent.com/40484278/110026291-52984d00-7ce5-11eb-91fe-1de48cd199cd.png)

**Comment by EchoProject** [comment]
@roz0n 
Please update: 
1. Progress:
2. Blockers: 
3. Availability:
4. ETA:

**Comment by ExperimentsInHonesty** [comment]
@roz0n Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@roz0n Please provide update
Progress
Blockers
Availability
ETA

**Comment by EchoProject** [comment]
@nichhk this issue may no longer be relevant. I'm adding to the Eng Epic for now, but feel free to remove and close if we're past this.

**Comment by nichhk** [comment]
Don't think this is needed since we are already zooming and centering to the NC.
